### PR TITLE
Hhh 10106

### PR DESCRIPTION
**Pull request by vyacheslav-rarata**
https://hibernate.atlassian.net/browse/HHH-10106

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by vyacheslav-rarata** [comment]
Yes, using email cayneir@gmail.com

**Comment by vladmihalcea** [comment]
Great. I changed the message a little bit:

    throw new MappingException(
        String.format("Association [%s] for entity [%s] references unmapped class [%s]",
            propertyName, propertyHolder.getClassName(), assocClass)
    );

We are practiclaly interested in the entity class, the entity property, and the entity property type, right? I don't think that the table/column are too informative in this context since we are dealing with an entity mapping.

**Comment by vyacheslav-rarata** [comment]
Ok, I will do changes.

**Comment by vladmihalcea** [comment]
No need. I fixed it and merged it upstream.

**Pull request closed without merging**
