### PR TITLE
HHH-10427 - ServiceRegistry creates multiple service instances and returns uninitialized services

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-10427

### CODE REVIEW

**Comment by karlvr** [comment]
@dreab8 Would it avoid the always-synchronization to synchronize on the `serviceBinding` only if `service` is null? (then inside the synchronization block check again if the service is registered and only initialize it at that point if it isn't)

**Comment by dreab8** [comment]
@karlvr , you can still return a service that is not null but not fully initialized.

**Comment by gbadner** [comment]
This seems kind of heavy-handed, but I don't see an alternative without changing an SPI. @sebersole, wdyt?

**Comment by gbadner** [comment]
I've incorporated the commits in this pull request into a new pull request:
https://github.com/hibernate/hibernate-orm/pull/1391

The new pull request adds a commit that caches the initialized services in a new field: AbstractServiceRegistryImpl#initializedServiceByRole.

AbstractServiceRegistryImpl#getService only synchroizes on this when the service is not found in initializedServiceByRole.

**Comment by Sanne** [comment]
closing as it's superseded by #1391

**Pull request closed without merging**
