### PR TITLE
HHH-14260: Fix dead and obsolete links in user guide

### PR DESCRIPTION
**Pull request by tscz**
https://hibernate.atlassian.net/browse/HHH-14260

Hi, this change fixes some dead links and removes an unused book reference in the bibliography.

### CODE REVIEW

**Comment by NathanQingyangXu** [comment]
I would suggest retaining the unused book reference. Firstly it is a really good book; secondly I don't think we need to mention it in place other than reference.

**Comment by tscz** [comment]
@NathanQingyangXu: Good point, I took the bibliography a bit too academic. I agree, that it is a good source for further readings. I reverted and restored the entry.

**Review by NathanQingyangXu — APPROVED** [review]

**Comment by dreab8** [comment]
Hi @tscz,

there is another broken link, Configurations.adoc line 687, the correct link is https://infinispan.org/docs/stable/titles/integrating/integrating.html#configuration_properties and not http://infinispan.org/docs/stable/user_guide/user_guide.html#configuration_properties

**Comment by tscz** [comment]
Hi @dreab8, thx! I corrected the link and pushed the change to the merge request branch. Also found an outdated link to the infinispan blog, which didn't forward to  a new one of my browsers. Also added the new link (https://infinispan.org/blog/2015/10/01/hibernate-second-level-cache/) there.

**Comment by NathanQingyangXu** [comment]
Actually we can find such broken dead links by script. I even created a
ticket (https://hibernate.atlassian.net/browse/HHH-14261) to bind the
automatic checking with testing phase, though it might go too far.
Preparing a script and run it before each release might be enough.

**Comment by tscz** [comment]
@dreab8: The broken infinispan links were already fixed and merged to master in the meantime. Synced with master and updated pull request accordingly.

**Comment by dreab8** [comment]
Thanks @tscz , 
applied upstream and to 5.4 branch.

**Pull request closed without merging**
