### PR TITLE
HHH-13367 Add a Hibernate 6 dialect for Spanner Database

### PR DESCRIPTION
**Pull request by dzou**
This is an initial version of the [Spanner](https://cloud.google.com/spanner/) Dialect for Hibernate 6. Spanner is Google's distributed relational database.

We are interested in contributing this to the Hibernate 6 branch. Please let us know if we are missing something with regard to contributing; looking forward to working with you all.

cc/ @chengyuanzhao @meltsufin

### CODE REVIEW

**Comment by sebersole** [comment]
Getting a lot of compile errors with this

**Comment by dzou** [comment]
> Getting a lot of compile errors with this

Ah I see, I'll take a look and get back to you.

**Comment by dzou** [comment]
Ok, should be good now on the compilation side.

**Comment by dzou** [comment]
@sebersole - Hey just wanted to followup on this; wanted to hear your initial thoughts on this dialect and what additional items you guys would like us to complete.

**Comment by sebersole** [comment]
I have been pulled into some other work.  I'll be back to working on 6 by
end of this week at the latest

**Comment by sebersole** [comment]
Thanks guys.  Looks good.  

At some point we should discuss testing.  I also spoke with Mike briefly about wanting to get feedback from y'alls experience implementing this - any suggestions you might have.  The function registration specifically is very much a moving target at this point.

**Comment by sebersole** [comment]
BTW, there is a PR proposing changes to function registration - https://github.com/hibernate/hibernate-orm/pull/2858

**Comment by meltsufin** [comment]
Thanks Steve! Yes, we need to discuss testing, and we'll also take a look at the function registration proposal in that PR.

**Pull request merged**
