### PR TITLE
HHH-17125 use prefixes for jaxb-generated classes

### PR DESCRIPTION
**Pull request by gavinking**

### CODE REVIEW

**Comment by sebersole** [comment]
This is going to cause major conflicts with 7.0.  So feel free to apply it, but expect to handle the conflicts

**Comment by gavinking** [comment]
> This is going to cause major conflicts with 7.0. So feel free to apply it, but expect to handle the conflicts

Because we moved the processor to a new module, you mean?

**Comment by sebersole** [comment]
No.  Because 7.0 reuses the model between hibernate-core and the processor

**Comment by sebersole** [comment]
If you match the naming, then yes.

**Comment by gavinking** [comment]
This has been fixed in H7.

**Pull request closed without merging**
