### PR TITLE
TestCase for HHH-8879 Not more possible to use Embeddable as MapKey

### PR DESCRIPTION
**Pull request by pb00068**
This Pull-request contains the TestCase for reproducing 
HHH-8879 Not more possible to use Embeddable as MapKey

### CODE REVIEW

**Comment by gbadner** [comment]
When I ran all the unit tests, I see that org.hibernate.test.map.MapIndexFormulaTest is failing.

I also noticed that the SQL generated for ManyToOneTest.testMapWithCompositeKey() includes the left outer joins of the many-to-one associations in the map key, but it really shouldn't. It doesn't actually initialize the associations (nor should it).

I am close to a fix without these problems, so I'm closing this pull request.

Thanks for the pull request. The test case and your fix helps a lot.

**Comment by fday** [comment]
Hi @pb00068, did you find solution for maps with embedded keys in 4.3? Seems your pull-request was not merged, I got a problem with the same stack trace as in https://hibernate.atlassian.net/browse/HHH-8879, when I was trying to use MapKey with embeddable class (I'm trying to do migration of Hibernate from 3.6 to 4.3).

**Comment by pb00068** [comment]
Actually this bug should be fixed in version 4.3.9, with which 4.3 version did you test?

**Comment by fday** [comment]
@pb00068 I've tested it on 4.3.12 and it did not work. I did not see any pull-request in the jira except yours, but seems it was not merged.

**Pull request closed without merging**
