### PR TITLE
6.2 backports

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-16962
https://hibernate.atlassian.net/browse/HHH-17047
https://hibernate.atlassian.net/browse/HHH-17168
https://hibernate.atlassian.net/browse/HHH-17015
https://hibernate.atlassian.net/browse/HHH-17082
https://hibernate.atlassian.net/browse/HHH-16666
https://hibernate.atlassian.net/browse/HHH-16403
https://hibernate.atlassian.net/browse/HHH-16706
https://hibernate.atlassian.net/browse/HHH-16945
https://hibernate.atlassian.net/browse/HHH-17100
https://hibernate.atlassian.net/browse/HHH-17087

### CODE REVIEW

**Comment by Sanne** [comment]
250 commits as candidate for backport ?

**Comment by beikov** [comment]
>250 commits as candidate for backport ?

I know it's a lot, but it's mostly just documentation and build related things. The idea of doing this is to ease backporting of future build related changes. Let's see what Steve says about this when he's back. He mentioned that he'd consider re-doing just the build changes to accommodate for the Gradle updates instead of doing full cherry-picks like I did. I don't really care what we do, but when I started this work, I hadn't realized there were this many commits necessary 😅

**Comment by Sanne** [comment]
@beikov yes I've seen that - seems mostly harmful indeed.

Still, I whas hoping for a super-trivial 6.2.9 release to happen quickly with the bare minimal we need to get Quarkus updated first. 

I have a bunch of trivial performance optimisations in the queue as well, and I'd be eaget to have a release with these included as well, but I'm holding off to sending them at this point. We should release more often ;)

**Comment by beikov** [comment]
>yes I've seen that - seems mostly harmful indeed.

Freudian typo? 😆 

>Still, I whas hoping for a super-trivial 6.2.9 release to happen quickly with the bare minimal we need to get Quarkus updated first.

I don't anticipate merging this into before the 6.2.9 release, so don't worry.

>I have a bunch of trivial performance optimisations in the queue as well, and I'd be eaget to have a release with these included as well, but I'm holding off to sending them at this point. We should release more often ;)

Improving release frequency is on the todo list ;)

**Comment by Sanne** [comment]
> > yes I've seen that - seems mostly harmful indeed.
> 
> Freudian typo? 😆

oops yes :) I meant the opposite of course

**Comment by sebersole** [comment]
I understand the hesitation to backport all of this.  In fact we had a long conversation about this.

But given that (a) we need to support 6.2 for 18+ months  and (b) no product includes 6.2 - 

1. keeping up with Gradle versions is highly desirable.
2. keeping up with documentation *clarifications* is also highly desirable.  they usually clarify what is (or not) supported

**Comment by Sanne** [comment]
@sebersole , @beikov sure I have no problem with the changes in se.

But let's also consider how other teams are going to perceive this; remember e.g. product teams want an explanation for each commit to justify their presence and check for tasks QA/docs might need to be aware.

So I'd suggest in such cases to reorganize the commits a little, e.g. squash all "documentation editing and polishing" into a single commit.

**Comment by Sanne** [comment]
BTW don't take my comment as a blocker - if you want this merged quickly merge it.
I only meant my suggestion as something to keep in mind please.

**Comment by Sanne** [comment]
@beikov ok no problem :+1:  I didn't mean to get in the way or create more work, I only meant to let you know to take this aspect into account. I trust you can decide what's best.

**Comment by sebersole** [comment]
> But let's also consider how other teams are going to perceive this; remember e.g. product teams want an explanation for each commit to justify their presence and check for tasks QA/docs might need to be aware.

Come on Sanne :)  6.2 is not in any product still.  And keeping the backing history is far more important I think.

But if you wish to take on that highly difficult squashing task I don't think we'd complain ;)

**Pull request merged**
