### PR TITLE
HHH-16611 : Sybase schema support in NameQualifierSupport

### PR DESCRIPTION
**Pull request by sebersole**
HHH-16611 : Sybase schema support in NameQualifierSupport

### CODE REVIEW

**Comment by beikov** [comment]
It seems the jConnect JDBC driver doesn't support schemas so I figured that we can't say Sybase ASE "supports" `BOTH`. Try running the test suite with the jConnect driver and you will see some tests that fail due to `AbstractMethodError`. We can surely try working around that, though I wanted to share the troubles I had in the past with you.

**Comment by sebersole** [comment]
Beyond annoying they still don't make their driver available.

**Comment by sebersole** [comment]
Well, actually these tests are using jTDS still right?  And its failing there.

What's odd is that their documentation explicitly states they do support schemas and catalogs - though granted nothing specific about the JDBC driver, just what the database supports.

**Comment by beikov** [comment]
Superseded by https://github.com/hibernate/hibernate-orm/pull/7138

**Pull request closed without merging**
