### PR TITLE
Feature/asciidocs

### PR DESCRIPTION
**Pull request by vladmihalcea**
The architecture and the domain model chapters are ready for review. Looking forward to getting your feedback.

### CODE REVIEW

**Comment by sebersole** [comment]
Unfortunately GitHub PR may not be the best option to discuss this set of changes in terms of giving feedback.  The PR is too large; GitHub complains: "Sorry, we could not display the entire diff because too many files (579) changed."

**Comment by sebersole** [comment]
I'll give specific in-line comments as I can.

**Comment by sebersole** [comment]
Since you seem to have these individual commits still hanging around, would it be possible to split this into: (1) migrate to Asciidoc, (2) re-write the individual chapters?  Like for 2 even, I know you said that the PR represents the architecture and mapping chapters as ready for review but the PR shows commits working on many other chapters as well.

**Comment by vladmihalcea** [comment]
I could squash it all in a single commit, which makes reviewing easier. At this point I was wondering if you can use the rendered output and review that one. I think it's best to have all this in a single commit because it's very difficult to judge which commits belong to the migration and which are for new content. Even now, while I review the next chapters, I still find migration issues which need to be corrected.

**Comment by sebersole** [comment]
I actually do render the docs.  In fact I have pulled the branch as of this
PR and rendered them.  The issue is that the changeset is just too big for
GitHub to handle in its UI.  I do not know if squashing the commits helps
with that or if the sheer size of the diff would still be too great.

**Comment by sebersole** [comment]
Given that the message specifically mentions the number of files changed, I doubt squashing the commits would have any effect.

**Comment by vladmihalcea** [comment]
The tests (54) could go into one commit, for instance. Those are located in the hibernate-entitymanager (hibernate-entitymanager/src/test/java/org/hibernate/jpa/guide).

I could remove the css and the images folder under asciidoc (148) files since we only use the default Asciidoctor theme for now.

**Comment by sebersole** [comment]
Yes, I think all the "theme" files should have not been moved yet.  Just leave them in their original place until (if) we actually need them.  No idea about these "tests".

The issue is not the ability to "display all modified files" btw.  The issue is being able to comment on what needs to be changed.  That's what a PR is for, for discussion.  If the GitHub UI cannot render all these files then we cannot discuss via line comments in those files obviously.

**Comment by vladmihalcea** [comment]
From the [Help guide](https://help.github.com/articles/what-are-the-limits-for-viewing-content-and-diffs-in-my-repository/):
> The maximum number of files in a single diff is limited to 300.

I'll have to see how I can split that.

**Comment by vladmihalcea** [comment]
I counted all files under the Userguide and there are 410 and counting. Basically there are two options:
- I commit only the asciidocs and then everything else
- We use regular git diffing and use other medium for exchanging comments

**Comment by sebersole** [comment]
The other option is to simply integrate all this work upstream and start from there as a baseline in terms of "review"

**Comment by sebersole** [comment]
But by and large the "distinction" of all these commits is organic to your workflow, but not so in terms of the overall task.  At the end of the day, the user will not care less that this rewrite was done in 5 commits or in 500; it's completely irrelevant.

IMO we ought to push this work as of some specific commit you chose, and then begin the review/editing from there.  That lets us focus on more atomic edits.

**Comment by vladmihalcea** [comment]
I have done much progress with the review of the remaining chapters, so I got to Chapter 13. HQL. Although I added more TODO sections, I think it's worth if I review all those to make sure the migration was fine and then we can push them in one big commit and continue the review from there. Afterwards there will be less files to be reviewed anyway.

**Comment by sebersole** [comment]
In terms of your initial review, sure.

But I have already found quite a few edits.  Some are pretty large
changes.  The problem for me is how to track these edits I propose.  At the
moment I simply cannot.  I need some known point from which to start.  So
then when you are ready to push, we will push this work upstream and I will
start my review from the start yet again.  I will not review any more until
that point, because its pointless.  I have to start from scratch every time
and its a huge waste of my time right now until we get that known point.

**Comment by vladmihalcea** [comment]
Ok, I'll let you know when the remaining chapters are reviewed and we can push it upstream

**Pull request closed without merging**
