### PR TITLE
HHH-18184 rescue @NamedQuery/@NamedNativeQuery.cacheMode

### PR DESCRIPTION
**Pull request by gavinking**
cc @sebersole 

[Please describe here what your change is about]

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

https://hibernate.atlassian.net/browse/HHH-18184

### CODE REVIEW

**Comment by sebersole** [comment]
Why?

**Comment by gavinking** [comment]
Well, partly because it makes migration a little easier, but also just because our `CacheMode` is still a fully-supported part of our native API, in good standing, and we accept it in every other API where we accept the JPA enums.

**Comment by gavinking** [comment]
Consistency, I guess. 🤷‍♂️

**Comment by sebersole** [comment]
Ok, you effectively changed the type here from CacheModeType to CacheMode.  Which I'm fine with.  But its not "just" restoring them

**Comment by gavinking** [comment]
Yeah yeah it's not a roll back of your change.

**Comment by sebersole** [comment]
Ok, I noted this change on the Jira

**Pull request merged**
