### PR TITLE
HHH-16223 Deprecate all "javax." constants defined in org.hibernate.cfg.AvailableSettings

### PR DESCRIPTION
**Pull request by Sanne**
https://hibernate.atlassian.net/browse/HHH-16223

### CODE REVIEW

**Comment by Sanne** [comment]
@sebersole ok I'll try to get to that but it means it will take some more time - wouldn't you prefer to treat that as a separate step?

**Comment by sebersole** [comment]
I'll make an exception for you ;)

But it is a bad idea generally imo to accept changes to make a setting deprecated without adding the logging for that.

**Comment by Sanne** [comment]
I'm wondering now if I'm not missing something; isn't it implied that all `javax.` properties are deprecated?

I didn't mean to "deprecate them" (now), I simply thought we had forgotten to mark these as being deprecated.

But sure no worries I'll figure out if I can add the logs; I thought this was already done.

**Comment by Sanne** [comment]
I think I've don that now - indeed it was mostly done already :+1:

**Pull request merged**
