### PR TITLE
HHH-8687

### PR DESCRIPTION
**Pull request by Loniks**
https://hibernate.atlassian.net/browse/HHH-8687

I have created working branch from 4.3 branch according to affects version from an issue. Is it correct?

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for your PR.

We are usually working on master when fixing issues, and sometimes they might be backported to older versions.

**Comment by vladmihalcea** [comment]
I have applied your fix upstream on 5.2.

**Comment by Loniks** [comment]
Thank you, next time I will be working on master branch.

**Comment by vladmihalcea** [comment]
Cool!

**Pull request closed without merging**
