### PR TITLE
HHH-13794 Fix ClassCast problem JAXBContext

### PR DESCRIPTION
**Pull request by haster**
- Use the current (XmlParserHelper) class's classloader to create the root JAXB context, so as to avoid a class cast problem with classes loaded on different classloaders due to jaxb defaulting to the current thread's context classloader.
- Add more information to the error message in case of a problem related to reading the persistence.xml (So that a non-parsing error also gets shown instead of "message: null").

### CODE REVIEW

**Comment by bjansen** [comment]
Could someone have a look at this PR please?

**Comment by robertspee-topicus** [comment]
This exactly solves my problem of using jpamodelgen with JDK 11

**Comment by BobbyRollof** [comment]
Is it possible to get this merged?

**Review by BobbyRollof — APPROVED** [review]

**Comment by beikov** [comment]
I was just looking into this, but it seems newer Maven and/or Java versions (11 update 9) are not affected anymore. At least I couldn't reproduce the error. Please continue the discussion on https://hibernate.atlassian.net/browse/HHH-13794

**Comment by daspilker** [comment]
The problem still exists with Hibernate 6.3.1, JDK17, Maven 3.9.4, Maven Compiler Plugin 3.11.0. I created an up-to-date reproducer, see https://hibernate.atlassian.net/browse/HHH-13794?focusedCommentId=112967

**Comment by dreab8** [comment]
Hi @haster ,

thanks for you PR and sorry for the long time to look at it.
It seems this issue has been fixed in 6.4.5 (https://github.com/hibernate/hibernate-orm/commit/6941ddd58c8001365fcd195e98663a9668c36bff ) https://hibernate.atlassian.net/browse/HHH-17579. so I'm going to close this PR

**Pull request closed without merging**
