### PR TITLE
Removing validation that breaks

### PR DESCRIPTION
**Pull request by luanpotter**
In some circumstances this validation seems to break the code.
By the comments I read in the code, it is regarded as unecessary anyways.
Is it ok to remove? Or could we get more insight on how can we fix our code to fix the "error"?

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Can you provide a replicating test case for your use case?

**Comment by vladmihalcea** [comment]
We are interested in such a use case where this exception might be thrown. I'm going to leave this issue open for a while waiting for your response.

**Comment by luanpotter** [comment]
I haven't responded yet because sadly I no longer remember what was the case that I was working on that caused this problem... It's been a while hahaha

But I will take a look in my old projects and see if I can find the culprit

**Comment by vladmihalcea** [comment]
Thanks for looking.

**Comment by vladmihalcea** [comment]
Closing issue since we didn't receive any test case for it.

**Pull request closed without merging**
