### PR TITLE
Try dropping local tables in same connection

### PR DESCRIPTION
**Pull request by beikov**
Test to see if this fixes the testsuite issues.

### CODE REVIEW

**Comment by gavinking** [comment]
@beikov is this a fix for why the postgresql builds hang on my PRs?

**Comment by beikov** [comment]
@gavinking no, this is about the main branch. On wip/6.0 there is a different issue.

**Comment by gavinking** [comment]
Right, OK.

**Comment by beikov** [comment]
I just pushed a fix for wip/6.0 though as well.

**Comment by gavinking** [comment]
Ah, great, excellent.

**Pull request merged**
