### PR TITLE
[urgent] HHH-11083 Fix compilation failures in hibernate-jcache

### PR DESCRIPTION
**Pull request by rvansa**

### CODE REVIEW

**Comment by dreab8** [comment]
Thanks @rvansa 
merged

**Comment by Sanne** [comment]
will this need backporting as well?

**Comment by Sanne** [comment]
@gbadner ^

**Comment by rvansa** [comment]
@Sanne No, hibernate-jcache (where the changes were not applied) is not in 5.1

**Comment by Sanne** [comment]
ok, right. Sorry, hadn't looked at the changes ;)

**Pull request merged**
