### PR TITLE
insert with @DynamicInsert should use generateIdentityInsertString()

### PR DESCRIPTION
**Pull request by gavinking**
See the comment in `generateInsertString()`

This is a very minor change but is conceptually correct.

### CODE REVIEW

**Comment by gavinking** [comment]
Hrm, failing on Sybase, but I have no way to figure out if that's related to my change...

**Comment by dreab8** [comment]
Hi @gavinking , I do not thing the failure is caused by you changes.

**Comment by dreab8** [comment]
Thanks @gavinking !

**Comment by gavinking** [comment]
Thanks for merging!

**Pull request merged**
