### PR TITLE
HHH-5538 - fix sequence query string for multiple identical schema’s

### PR DESCRIPTION
**Pull request by tubbynl**
using pg_table_is_visible to filter sequences to only the sequences within the current schema (applied by search_path or set schema)
https://www.postgresql.org/docs/9.1/static/functions-info.html#FUNCTIONS-INFO-SCHEMA-TABLE

### CODE REVIEW

**Comment by tubbynl** [comment]
the junit test merely verifies the query string, for what it's worth the real (integration) test would be
* have a domain class with a 
`
@Id
@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "TEST")
@SequenceGenerator(name = "TEST", sequenceName = "SEQ_TEST", allocationSize=1)
`
* run schema update on a empty schema within a database
* run schema update on a different empty schema within this same database
* the second schema won't contain a created sequence

**Comment by vladmihalcea** [comment]
I wrote a [test case](https://github.com/hibernate/hibernate-orm/blob/7728d23c9f5b08d263049a61e161e05cf1a0f7e3/hibernate-core/src/test/java/org/hibernate/test/schemaupdate/PostgreSQLMultipleSchemaSequenceTest.java) that proves that this issue does not replicate. 

To run the test on PotgreSQL:

> gradle test -Pdb=pgsql --tests org.hibernate.test.schemaupdate.PostgreSQLMultipleSchemaSequenceTest

**Comment by tubbynl** [comment]
Cool, thank you for this testcase, i'll try to run it and see if i can make it fail replicating our setting

**Comment by tubbynl** [comment]
Ok, i altered the test-case to our situation (perhaps not correct, but it does reflect it not generating  the second create sequence statement. 

- we use a named sequence per entity (as the one used on the Box entity)
- we use schema-based multi-tenancy
- run/build the schema-specific schema-update using MetadataBuilder#applyImplicitSchemaName
- we change change the search_path on the connection (using a MultiTenantConnectionProvider)

perhaps applyImplicitSchemaName requires a different ImplicitNamingStrategy to generate a more specific naming for the Sequences

**Comment by tubbynl** [comment]
i had to rebase the commits from the master to my branch so i could alter your testcase and update this pull request. Is there a better way of doing this and keep the auto-checks happy?

PostgreSQLMultipleSchemaSequenceTest contains the updated test

**Comment by vladmihalcea** [comment]
This PR has more commits than necessary. If you think you can isolate the issue, try providing a new PR containing the `PostgreSQLMultipleSchemaSequenceTest` changes that prove your findings. I'm going to close this one.

**Pull request closed without merging**
