### PR TITLE
HHH-9676 testcase and fix

### PR DESCRIPTION
**Pull request by timove**
Testcase and fix for [HHH-9676](https://hibernate.atlassian.net/browse/HHH-9676).

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @timove ,
thanks for the patch, have you signed the Contributor License Agreement [https://cla.jboss.org/index.seam]
if not can you do it?

**Comment by vladmihalcea** [comment]
This issue cannot be for [HHH-967](https://hibernate.atlassian.net/browse/HHH-967) which is closed for a long time now.

**Comment by vladmihalcea** [comment]
Hi @timove. Can you please sign the [CLA](cla.jboss.org) so that we can integrate your fix.

**Comment by timove** [comment]
Hi! I did sign the CLA on 2015-03-23, username "gctve". Can you confirm?

**Comment by vladmihalcea** [comment]
Thanks. I updated the issue status.

**Comment by vladmihalcea** [comment]
This issue seems to have been fixed, and the `TypeSafeActivator` already contains that change. We can at least add the test cases, to prevent any future regression.

**Comment by vladmihalcea** [comment]
Applied upstream on master and 5.1

**Pull request closed without merging**
