### PR TITLE
HHH-11569 : Return only distinct elements when query is hinted with E…

### PR DESCRIPTION
**Pull request by BOOTMGR**
…ntityGraph
- With test case
- Updated test case for HHH-9457

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by BOOTMGR** [comment]
Hi @vladmihalcea , I have already signed CLA.
"You already are a contributor, or have applied to be a contributor to Hibernate."

**Comment by vladmihalcea** [comment]
Thanks. I'll review your changes today.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
