### PR TITLE
Hhh 10427

### PR DESCRIPTION
**Pull request by Sanne**
Incorporates #1391 and fixes some more corner cases.

### CODE REVIEW

**Comment by gbadner** [comment]
@Sanne I think I missed a case in my pull request that doesn't show up in the diffs. 

When a service is provided via `createServiceBinding(ProvidedService<R> providedService)` it never gets added to `initializedServiceByRole`, so any time that `ProvidedService` is requested via `getService(Class<R> serviceRole)`, the `AbstractServiceRegistryImpl` will be synchronized.

IIUC, `createServiceBinding(ProvidedService<R> providedService)` should immediately add `providedService` to `initializedServiceByRole` or `getService(Class<R> serviceRole)` should add it the first time the `ProvidedService` is requested.

**Comment by Sanne** [comment]
@gbadner also provided services will be retrieved via "getService(Class)"
eventually, and when they do they will be resolved and added to the
_initializedServiceByRole_
cache.

So next access will be allowed without the synchronization.

**Comment by gbadner** [comment]
@Sanne I don't think that's true because serviceBinding.getService() will return the ProvidedService (not null), so it won't get added to initializedServiceByRole.

**Comment by dreab8** [comment]
with https://github.com/hibernate/hibernate-orm/pull/1403 I tried a different approach, not sure it's a good one and in case it is probably it could be applied only to future releases versions due to a change of the spi class ServiceBinding.

**Comment by Sanne** [comment]
@gbadner you're right I didn't think of the provided ones. I'll simply move the "put" operation one line down.

@dreab8 sorry I'm in meetings this week so I won't be able to review an alternative. I'll fix my proposal, as that's trivial, then you can all choose one :) If this isn't urgent I could review alternatives on Friday.

**Comment by Sanne** [comment]
Pushed one more commit to handle the case pointed out by @gbadner .

**Comment by dreab8** [comment]
a bug in the test I have created
the 3 assertions
```
assertTrue( "The service is not initialized", result.isInitialized() );
assertTrue( "The service is not configured", result.isConfigured() );
assertTrue( "The service is not started", result.isStarted() );
```
should be moved inside the `ServiceCallable#call()`
method

**Comment by sebersole** [comment]
Applied upstream to master.

**Pull request closed without merging**
