### PR TITLE
Added test for HHH-11180

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-11180

### CODE REVIEW

**Comment by Naros** [comment]
@beikov @vladmihalcea I'd appreciate if you both could test these changes and make sure they're not introducing any unintended problems.  Thanks!

**Comment by beikov** [comment]
Code looks ok. Unfortunately I currently can't test that version with my production apps because I haven't migrated to 5.2 yet. Will try to get that done so I can give you more feedback.

**Comment by vladmihalcea** [comment]
Sure. I'll test it tomorrow.

**Comment by Naros** [comment]
@beikov @vladmihalcea Thanks guys!

**Comment by vladmihalcea** [comment]
Tested and applied upstream, thanks

**Pull request closed without merging**
