### PR TITLE
HHH-12661 Hibernate types cannot bind value in StoredProcedureQuery

### PR DESCRIPTION
**Pull request by rkurucz9**
https://hibernate.atlassian.net/browse/HHH-12661

### CODE REVIEW

**Comment by Naros** [comment]
How is this different from https://github.com/hibernate/hibernate-orm/pull/2326 exactly?

**Comment by rkurucz9** [comment]
This Pull Request contains only tests, more of it than that.

**Comment by Naros** [comment]
> This Pull Request contains only tests, more of it than that.
But #2326 contains tests as well; hence my confusion so is this meant to also supplement that PR or will this be offering something else which #2326 does not cover?

**Comment by rkurucz9** [comment]
I tried to cover Basic Hibernate Types with tests in my Pull Request. This is the only advantage compare with #2326. My Pull Request does not contain any solution.
In my opinion, it would be better as many tests as possible.

Covered Basic Hibernate Types:
1. StringType
2. MaterializedClobType
3. TextType
4. CharacterType
5. NumericBooleanType
6. YesNoType
7. TrueFalseType
8. BooleanType
9. ByteType
10. ShortType
11. IntegerType
12. LongType
13. FloatType
14. DoubleType
15. BigIntegerType
16. BigDecimalType
17. TimestampType
18. TimestampType
19. TimeType
20. DateType
21. CalendarType
22. CurrencyType
23. LocaleType
24. TimeZoneType
25. UrlType
26. ClassType
27. BlobType
28. ClobType
29. BinaryType
30. CharArrayType
31. UUIDBinaryType

**Comment by vladmihalcea** [comment]
Integrated it into this [PR](https://github.com/hibernate/hibernate-orm/pull/2326).

**Pull request closed without merging**
