### PR TITLE
HHH-13073 - AnyMetaDef.metaType should default to "string"

### PR DESCRIPTION
**Pull request by vladmihalcea**
@johnlinp This PR continues [the original one](https://github.com/hibernate/hibernate-orm/pull/2619) and adds a test for HBM as well.

### CODE REVIEW

**Comment by johnlinp** [comment]
@vladmihalcea Is there any update on this one? Thanks!

**Comment by vladmihalcea** [comment]
@johnlinp Since this is not a critical issue, I'll push it to 6.0 and it can be backported to 5.4 if the branch maintainers want to do that.

**Comment by johnlinp** [comment]
@vladmihalcea Sure, that works for me perfectly too! Thank you.

**Comment by vladmihalcea** [comment]
I tried to integrate it into 6.0, but the tests fail because the annotation parser throws an exception. I'll try it when that's fixed.

**Comment by sebersole** [comment]
Not knowing the nature of the failure its hard to say whether this should work now.  But adding the `6.0?` label as it targets master which is still 5.4

**Comment by gavinking** [comment]
There is no longer any `@AnyMetaDef` annotation. Closing.

**Pull request closed without merging**
