### PR TITLE
HHH-15613 remove 'lateral' from fromRoot rule

### PR DESCRIPTION
**Pull request by gavinking**
This is currently ignored by HQL, is undocumented, and untested, and anyway would be a synonym for `join lateral`.

Also squash some warnings in `SemanticQueryBuilder`.

### CODE REVIEW

**Review by beikov — APPROVED** [review]
LGTM. Might be worth also getting rid of `org.hibernate.query.criteria.JpaSelectCriteria#fromLateral`

**Comment by gavinking** [comment]
Ah, sure, OK, will do!

**Comment by gavinking** [comment]
Oh right, now I see why this seemed to be unused, because of this untypesafe code:

```java
final boolean lateral = ( (TerminalNode) firstChild ).getSymbol().getType() == HqlParser.LATERAL;
```

which mean that nothing broke when I changed the grammar.

We *really* need to move away from doing this sort of stuff in `SemanticQueryBuilder`, it's super-fragile!

**Comment by gavinking** [comment]
This is now https://hibernate.atlassian.net/browse/HHH-15613.

**Pull request merged**
