### PR TITLE
5.3 jdk17 w/ component upgrades

### PR DESCRIPTION
**Pull request by Sanne**
- https://hibernate.atlassian.net/browse/HHH-13821
 - https://hibernate.atlassian.net/browse/HHH-14315
 - https://hibernate.atlassian.net/browse/HHH-14370
 - https://hibernate.atlassian.net/browse/HHH-14371
 - https://hibernate.atlassian.net/browse/HHH-14372
 - https://hibernate.atlassian.net/browse/HHH-14709
 - https://hibernate.atlassian.net/browse/HHH-14731
 - https://hibernate.atlassian.net/browse/HHH-14771
 - https://hibernate.atlassian.net/browse/HHH-14781
 - https://hibernate.atlassian.net/browse/HHH-14782
 - https://hibernate.atlassian.net/browse/HHH-14783
 - https://hibernate.atlassian.net/browse/HHH-14784
 - https://hibernate.atlassian.net/browse/HHH-14785
 - https://hibernate.atlassian.net/browse/HHH-14786

### CODE REVIEW

**Comment by Sanne** [comment]
@gbadner this is what I suggest we merge in 5.3: unless you have objections I'll merge it tomorrow?

N.B. CI jobs aren't enabled to test on JDK17, we'll enable the jobs after it's merged.

**Comment by Sanne** [comment]
Preview CI jobs:
 - https://ci.hibernate.org/job/hibernate-orm-personal-andrea-5.3-jdk17/
 - https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-andrea-5.3-jdk17-javassist/
 - https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-andrea-5.3-jdk18/

**Comment by dreab8** [comment]
@Sanne we have to upgrade Byte Buddy to 1.11.12, I tried it now and it seems fixing the failures for JDK 18

**Comment by Sanne** [comment]
I'm ok to upgrade BB further, but let's remember we need JDK17 to work, not
18 ( yet )

**Comment by dreab8** [comment]
@Sanne sure, in case we decide to not upgrade it we have to remove the _HHH-14771 Upgrade to Byte Buddy 1.11.12_ commit from the PR

**Comment by Sanne** [comment]
superseded by #4155

**Pull request closed without merging**
