### PR TITLE
HHH-13446 - Validate mapped-by values got from annotations in bytecode enhancers

### PR DESCRIPTION
**Pull request by barreiro**

### CODE REVIEW

**Comment by Sanne** [comment]
hey @barreiro , thanks! Could you add a test case?

**Comment by barreiro** [comment]
@Sanne I have tried, but unfortunately isn't straight forward. The behavior is different between javassist and bytebuddy enhancers.

**Comment by Sanne** [comment]
Could you add one just for byte-buddy? Javassist is deprecated and will be removed soon.

**Comment by barreiro** [comment]
I could, but why not fix both when that fix is ready !?

**Comment by Sanne** [comment]
> I could, but why not fix both when that fix is ready !?

Because we prefer having some protection against regressions. You mentioned you tried to create a test, so I assume you have something that could be adjusted fairly easily?

But also, there is no rush in merging as we're not releasing today, so you have a little more time to tweak your tests.

**Pull request closed without merging**
