### PR TITLE
HHH-10657 Make 'none' a valid option for hibernate.hbm2ddl.auto

### PR DESCRIPTION
**Pull request by Sanne**
This looks like simple enough to avoid the error message, although I was looking to update some documentation for this too.

I remember in old docs there was a table describing the options, but I couldn't find the documentation for this property in the news docs ?

 - https://hibernate.atlassian.net/browse/HHH-10657

### CODE REVIEW

**Comment by vladmihalcea** [comment]
I'm going to commit tomorrow the first version of Configs. Meanwhile, you can find them [here](https://github.com/vladmihalcea/hibernate-orm/commit/2796668d1cb855a70053f3721883f7c56e352de2).

**Comment by sebersole** [comment]
Looks good.  Thanks Sanner

**Comment by Sanne** [comment]
Thanks, merged it.

@vladmihalcea I'll leave the docs update to you then, thanks!

**Comment by vladmihalcea** [comment]
I've just added to my branch and I'll integrate it as soon as I'm done with all configs.

**Comment by Sanne** [comment]
great, thanks!

**Pull request closed without merging**
