### PR TITLE
HHH-11712 - PostgreSQL does not support negative initial sequence values for ascending sequences unless MINVALUE is defined as well

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-11712

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@gbadner Would you like to review this PR? It fixes an issue relate to negative sequence values in PostgreSQL.

**Comment by dreab8** [comment]
@vladmihalcea i think we have problems also with positive initial values and negative increment

**Comment by vladmihalcea** [comment]
I'll add one more test for that use case and provide a fix for that too.

**Comment by vladmihalcea** [comment]
@dreab8 I pushed a new version to take into consideration both the ascending and the descending use cases.

**Comment by gbadner** [comment]
I've merged this PR. I also added a commit with some minor changes so names and comments are consistent with what the new test is doing: https://github.com/hibernate/hibernate-orm/commit/1752da008e2f4945d718d9f60a39a2027485d58c

**Pull request merged**
