### PR TITLE
Several optimizations for reference cached entities and query cache

### PR DESCRIPTION
**Pull request by stalep**
removed call to postLoad and afterInitialize for reference cached entities
refactor methods, made some private, some final
try to optimize cached result
refactor out getPersister so it can be inlined

### CODE REVIEW

**Comment by stalep** [comment]
The two biggest gains in this commit is that reference cached entities do not call afterInitialize when they are fetched from cache nor postLoad.
I do not know if the removal of running postLoad on these entities will break any functionality. The afterInitialize call removal should not break any functionality afaik.
Other optimizations;
-  Removal LOG.isTraceEnabled with a static final boolean. This prevents logging from being changed during runtime, but it optimizes away those calls and give a higher chance of methods to be inlined.
- Changed some protected methods to be private
- Refactored logic into private methods so they can more easily be inlined.

**Comment by Sanne** [comment]
Looks good to me, although I'm not sure either of what consequences the removal of postLoad events might have on integrations and listeners.

@sebersole would this warrant a doc change to explain that there might be some additional limitation with the referebce cached entities?

@stalep is there a related JIRA?

**Comment by stalep** [comment]
@Sanne thanks for the review! yes, a doc change is a good suggestion.
no i havent created a jira yet, ill do that asap.

**Comment by stalep** [comment]
I've created; https://hibernate.atlassian.net/browse/HHH-10366 to track this.

**Comment by sebersole** [comment]
Stale, please rebase your commit to change the commit message to refer to
that JIRA.  Thanks.

Sanne, there are some bytecode hooks done in those calls, but iirc they all
relate to "self dirty tracking".  As these are immutable entities, that
should be ok to skip.  Although I would like to verify how these are
skipped exactly before this gets applied.

**Comment by Sanne** [comment]
thanks @sebersole , unless you push it yourself, if you see it's ok let us know we'll push the rebased version (I had it rebased locally already)

**Comment by sebersole** [comment]
Stale, also could you update the codestyle you use when contributing
Hibernate patches?  As these get more non-trivial, it is more difficult to
clean them up.  Specifically I notice a lot of incorrect whitespace
handling.

**Comment by sebersole** [comment]
@barreiro Actually this makes me think... we really ought to automatically disable "self dirty tracking" when an entity is defined as immutable; tracking that is just unnecessary overhead.

**Comment by sebersole** [comment]
@Sanne It looks ok.  I'd appreciate it if you could correct the white space too then.  Thanks

**Comment by Sanne** [comment]
@sebersole cool, I will.

**Comment by Sanne** [comment]
merged in 5.0, re-testing on master now as I had a small conflict.

**Comment by Sanne** [comment]
merged on both. Thanks all!

**Comment by stalep** [comment]
thanks for the merge guys!
@sebersole yes, i should be better at changing the codestyle, ill make sure to do it next time!

**Pull request closed without merging**
