### PR TITLE
Add override annotation

### PR DESCRIPTION
**Pull request by carstenartur**

### CODE REVIEW

**Comment by Sanne** [comment]
ouch, you've been busy :)

I'm not sure I should merged this, as 90% of the team is working on a massive branch for 6.0 and will certainly have conflicts when rebasing?

**Comment by carstenartur** [comment]
That's why I created https://github.com/hibernate/hibernate-orm/pull/2997 that does the same on wip6. I was not aware you still can do a rebase between master and wip6.
But no problem.  If you decide to stay away from this change please just c,lose. I am not sure if you will be so happy with it anyway because of some formatting issues I do not know how to solve.

**Comment by sebersole** [comment]
Thanks @carstenartur!  

We decided to take a different approach to the type system changes in 6 and so the upstream `wip/6.0` branch is atm "stale".  We have been working on those changes on a branch in my personal fork of Hibernate at https://github.com/sebersole/hibernate-core/tree/wip/sqm-jpa-types-sql-ast  We plan to apply this to upstream `wip/6.0` (force push, unfortunately) soon.

As @Sanne mentioned, we do keep these branches up to date with master intermittently.  We are hoping to do one this week as a matter of fact.  So applying these to master will copy the changes over. 

As far as the conflicts, that is a real concern for sure.  Might be better to apply this to both branches individually after the larger merge?

**Comment by carstenartur** [comment]
no problem - then I suggest to close this one and the other one(s) now and look at it at a later point in time.  Within normal working hours I cannot do much however, better at the weekend.

**Comment by sebersole** [comment]
@carstenartur - this already applies over master cleanly.  I'm suggesting we leave this one open, but close the one targeting 6.0.  Then after we finish merging master and 6.0 we can apply this to master and try to apply it to 6.0.  If it does not apply cleanly to 6.0, then we can deal with that at that time.

**Pull request closed without merging**
