### PR TITLE
HHH-14211 Switch to using oid for CLOB in PostgreSQL to avoid losing data after vacuumlo

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-14211

Also see the discussion here:

### CODE REVIEW

**Comment by sebersole** [comment]
Do not merge this.  I want to look through this one.  See discussion at https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/TOAST.20text.20column.20content.20in.20pg_largeobjects.20in.20pgsql

**Comment by gavinking** [comment]
OK, interesting, so it looks like the issue here was actually the precise opposite of what was reported.

That is, the problem was actually that we used the wrong column type (by default) for things that really are CLOBs and belong in `pg_large_objects`, and that we never realized because the broken-ass postgres drivers tolerate this and work fine with it and make it seem totally legit, right up until your DBA runs some command line tool.

And unfortunately users were reporting this issue as the exact opposite problem: that when they use @Lob they wanted things TOASTed, not stored as oids, which just didn't seem to make any sense at all. Because I guess they were abusing @Lob in order to change the SQL column type to `text`.


Thanks for untangling this @beikov.

**Comment by beikov** [comment]
Exactly @gavinking, you pretty much nailed the gist of this :)

**Comment by jannic** [comment]
> And unfortunately users were reporting this issue as the exact opposite problem: that when they use @lob they wanted things TOASTed, not stored as oids, which just didn't seem to make any sense at all. Because I guess they were abusing @lob in order to change the SQL column type to `text`.

I guess this is because of misleading tutorials like https://www.baeldung.com/jpa-annotation-postgresql-text-type

**Comment by jannic** [comment]
Ping to @Baeldung, perhaps you'd like to comment? If the analysis in this ticket is correct (and as far as I know, it is), the mentioned tutorial should be updated.

**Pull request merged**
