### PR TITLE
[6.0] HHH-11452 Extended audit query API to specify the use of scalar functions

### PR DESCRIPTION
**Pull request by ffeisst**
Added methods to specify arbitrary functions in
* projections
* comparison between functions and simple values
* comparison between functions and entity properties
* comparison between entity properties and functions
* comparison between two different functions

[Link to Jira issue](https://hibernate.atlassian.net/browse/HHH-11452)

### CODE REVIEW

**Comment by sebersole** [comment]
@Naros - This is labelled for 6.0, but is still targeting master branch.

**Comment by Naros** [comment]
@dreab8, I assume the target branch for 6.0 is `wip/6.0`, correct?  If so, I'll take a look at rebasing this and seeing what hurdles exist (if any).

**Comment by dreab8** [comment]
@Naros yes I think it should target the `wip/6.0` branch

**Comment by Naros** [comment]
Closed in favor of PR #4470

**Pull request closed without merging**
