### PR TITLE
HHH-14452 Support set operations in JPA Criteria API

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-14452

### CODE REVIEW

**Comment by gavinking** [comment]
Cool!

**Comment by sebersole** [comment]
The vast majority of changes here are actually related to simple changes to add generic types to code blocks and have nothing to do with this work.  Would be really nice to limit such changes and ideally do them in a separate PR or just push them.

**Review by sebersole — COMMENTED** [review]
I give up scrolling through unrelated changes ;)

From what I can tell, the actual work done here related to criteria builder, etc looks fine

**Comment by beikov** [comment]
Sorry for these unrelated changes, I'll try to avoid them in the future.

**Pull request merged**
