### PR TITLE
HHH-18561 Fix for Informix primary key constraint syntax error

### PR DESCRIPTION
**Pull request by VladoKuruc**
Please, backport also to 6.6 branch

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

https://hibernate.atlassian.net/browse/HHH-18561

### CODE REVIEW

**Review by mbladel — APPROVED** [review]
LGTM

**Comment by mbladel** [comment]
Backported to 6.6 via https://github.com/hibernate/hibernate-orm/commit/1830660710ab2c7b8e85f60c72562657d6a4c2b0.

**Comment by mbladel** [comment]
@VladoKuruc had to revert https://github.com/hibernate/hibernate-orm/commit/1830660710ab2c7b8e85f60c72562657d6a4c2b0, the primary key constraint in version `6.6` is exported via the `PrimaryKey#sqlConstraintString`, which is not dialect specific. If you want this change please try to see how we could approach this in the old branch and provide a dedicated PR.

**Comment by VladoKuruc** [comment]
OK

**Pull request merged**
