### PR TITLE
HHH-18296 call set client_min_messages = WARNING before dropping tables on Postgres

### PR DESCRIPTION
**Pull request by gavinking**
https://hibernate.atlassian.net/browse/HHH-18296

### CODE REVIEW

**Review by yrodiere — APPROVED** [review]
LGTM, thanks. I added a test in a separate commit.

**Comment by vlsi** [comment]
Will Hibernate return `client_min_messages` to its previous state?
Otherwise it might cause surprises for the users.

Imagine someone calls `client_min_messages=ERROR`. Then executes Hibernate, and it would reset `client_min_messages=WARNING`.

**Comment by gavinking** [comment]
What is the scope? Per-connection?

**Comment by vlsi** [comment]
The settings are per connection

**Comment by gavinking** [comment]
Yeah, I mean, in principle we should reset it, since we might be sharing a connection pool.

Except it's not actually a big deal since you should never run `SchemaDropper` in a production system against a production database. It's used for testing.

But sure, it would be better I guess to check the current value before setting it, and then reset it back.

**Comment by yrodiere** [comment]
> But sure, it would be better I guess to check the current value before setting it, and then reset it back.

Agreed.

Ideally we'd actually reset _all_ connection settings (including those set by the user) before we return the connection to the pool, but I guess there is no easy way to do that.

**Pull request merged**
