### PR TITLE
HHH-10532 Prevent NullPointerException + Testcase

### PR DESCRIPTION
**Pull request by jfboeuf**
Fix for HHH-10532 .
This includes https://github.com/hibernate/hibernate-orm/pull/1271 .

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by jfboeuf** [comment]
Yes I did on February 2016, 20th. Status is still "Awaiting approval by project lead".

**Comment by vladmihalcea** [comment]
Thanks, I'll ask Steve to aprove it.

**Comment by vladmihalcea** [comment]
Thanks for the PR. Applied it upstream.

**Pull request closed without merging**
