### PR TITLE
wip/6.0 HHH-14091: eliminate bunch of if-else-statement

### PR DESCRIPTION
**Pull request by yangchenwen**

### CODE REVIEW

**Comment by NathanQingyangXu** [comment]
@Sanne , it would be great if you take a look at this for you are the last reviewer of the closed PR and this is a followup.

**Comment by Sanne** [comment]
I might have a look, but this looks like low priority. Could you clarify why are these changes being proposed?

Thanks

**Comment by NathanQingyangXu** [comment]
> I might have a look, but this looks like low priority. Could you clarify why are these changes being proposed?
> 
> Thanks

Nothing special and surely it is of lower priority. Guess the author wanna improve code readability.

**Comment by yangchenwen** [comment]
it seems no need to do this.

**Pull request closed without merging**
