### PR TITLE
Use switch over strings where possible

### PR DESCRIPTION
**Pull request by carstenartur**

### CODE REVIEW

**Comment by Sanne** [comment]
@sebersole this PR targets branch wip/6.0 :) Will you take it? Looks like a good idea in principle. Need help backporting?

Thanks @carstenartur !

**Comment by sebersole** [comment]
Same caveat as before wrt target of 6.0 development.  This does not apply cleanly over that dev branch, but I will pull your branch locally and see why.

**Comment by sebersole** [comment]
For whatever reason, this one I could not get to apply via patch.  

@carstenartur Would you like to re-target this on the working 6.0 branch?  If not I will just pick the changes over manually.

**Comment by carstenartur** [comment]
I need some time to prepare a checkout of your github repository copy. If this will be resolved soon by you pushing your code to the regular repository I would like to wait and then work on the regular repository because then I do not need to waste time setting up an environment that I do not need any longer after the merge. :)

**Comment by sebersole** [comment]
No worries - I can just pull the changes manually if you don't get around to it.

**Pull request closed without merging**
