### PR TITLE
HHH-15500 Cache key is huge since migration to 6

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-15500

### CODE REVIEW

**Comment by Sanne** [comment]
hi @dreab8, sorry but I don't understand the relation between these changes and the issue - and there's no test?

Could you explain what the idea is? And how is Redisson encoding the keys? The example made on JIRA is horrible :)

**Comment by dreab8** [comment]
Hi @Sanne, this change tries to reduce the size of the `CacheKeyValueDescriptor` (that is not anymore the entire `org.hibernate.type.BasicType` ), an being the `CacheKeyValueDescriptor`  a field of `CacheKeyImplementation`  this should reduce the size of the key.

Not sure how to create a proper test, any idea?

**Comment by Sanne** [comment]
But how is the `CacheKeyValueDescriptor` converted into a Redis representation? Serialized?

**Comment by dreab8** [comment]
@Sanne good question but I really don't know :(

**Comment by beikov** [comment]
>But how is the CacheKeyValueDescriptor converted into a Redis representation? Serialized?

Yes, it is serialized. I'm working on something to improve this.

**Comment by Sanne** [comment]
Ok, thanks for the info. But I'm still confused about what this PR is attempting to achieve - I admit I was primarily looking for a test in hope that this would shed some light :)

What's the idea @dreab8 ? And why was `CacheKeyValueDescriptor` introduced - it seems to re-introduce the requirement for each such element to be Serializable, which we removed before AFAIK for good reasons, so it feels like a step back.

**Comment by beikov** [comment]
Superseded by https://github.com/hibernate/hibernate-orm/pull/5324

**Pull request closed without merging**
