### PR TITLE
HHH-12391

### PR DESCRIPTION
**Pull request by dreab8**
@sebersole [this](https://github.com/hibernate/hibernate-orm/pull/2205/commits/98c577b8704a37d2a9848e81f9a108dac1640b40) reverts your last commit, it was causing some test failures.

[here](https://github.com/hibernate/hibernate-orm/pull/2205/commits/76a42beac569c613bf5fd0ea51e4f880039121f6) a test that reproduces the issue.

finally [here](https://github.com/hibernate/hibernate-orm/pull/2205/commits/2e09d27692e4f783faf1307d9d2c4c5ae174886b) a possible solution

### CODE REVIEW

**Comment by sebersole** [comment]
I don't follow.  How was my test causing other test failures?

**Comment by dreab8** [comment]
@sebersole I haven't investigated but seems the changes you made cause
[Failing tests](http://ci.hibernate.org/job/hibernate-orm-master-h2-main/1141/)

If run individually they pass but running the entire test suite they fail

**Comment by sebersole** [comment]
That's so strange - I cannot fathom how that change would cause those failures.  But clearly they do (its the only change in that build) and the test is not needed anyway.

**Comment by scottmarlow** [comment]
I'm not sure if it helps with this failure but should the rollback() + commit() methods be changed to always clear the rollbackOnly flag?  Currently, they look like they are not clearing the rollbackOnly flag.

**Comment by dreab8** [comment]
@scottmarlow the rollback() method sets the rollbackOnly flag to false;
anyway the [commit](https://github.com/hibernate/hibernate-orm/pull/2205/commits/2e09d27692e4f783faf1307d9d2c4c5ae174886b) seems fixing the problem

**Comment by sebersole** [comment]
@scottmarlow have you tested whether the changes here fix your failure?

**Comment by scottmarlow** [comment]
@sebersole I haven't, I should be able to try that.

**Comment by scottmarlow** [comment]
@dreab8 I meant that rollback() may not clear rollbackOnly, if for example we enter the method and don't reach the rollbackOnly=false.  Perhaps the entire method body should be in a try/finally {rollbackOnly=false;}

Commit() does not set rollbackOnly=false, that probably also needs a try {} finally {rollbackOnly=false} around the method body, to ensure that we do not leave rollbackOnly == true.  We might call rollback() or not.

**Comment by dreab8** [comment]
@scottmarlow for the `commit() `method I think there is not need, when `rollbackOnly=true `the `rollback()` method is called.
For `rollback()` you may be right, probably `rollbackOnly=false` should be the first thing the `rollback()` method does.

**Comment by dreab8** [comment]
@scottmarlow forget my last comment on the `rollback()` change, your idea of try/finally for setting the `rollbackOnly=false` is correct.
Running test and then I'll push the changes.

**Comment by dreab8** [comment]
@sebersole thanks, I'm going to merge it.

**Pull request closed without merging**
