### PR TITLE
HHH-13493 - For a native query, the SessionImpl class does not call applyQuerySettingsAndHints

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-13493

### CODE REVIEW

**Comment by Sanne** [comment]
hi @vladmihalcea , could you review your test?

f I isolate and revert the fix, it still passes the test. I guess we need a better way to test for this.

**Comment by vladmihalcea** [comment]
@Sanne 

Without the fix, I get:

```
java.lang.AssertionError: Should have thrown lock timeout exception!

	at org.junit.Assert.fail(Assert.java:88)
	at org.hibernate.jpa.test.lock.NativeSQLQueryTimeoutTest.lambda$test$0(NativeSQLQueryTimeoutTest.java:47)
	at org.hibernate.testing.transaction.TransactionUtil.doInJPA(TransactionUtil.java:210)
	at org.hibernate.testing.transaction.TransactionUtil.doInJPA(TransactionUtil.java:251)
	at org.hibernate.jpa.test.lock.NativeSQLQueryTimeoutTest.test(NativeSQLQueryTimeoutTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.hibernate.testing.junit4.ExtendedFrameworkMethod.invokeExplosively(ExtendedFrameworkMethod.java:45)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:748)
```

I haven't rebased it, so I simply retest the PR branch. I could only run it with IDEA 2017. The new one does not even run the tests since it cannot locate the `hibernate.properties`.

So, I'm not sure how it works for you without the fix.

**Comment by dreab8** [comment]
Thanks @vladmihalcea  ,

applied upstream

**Comment by vladmihalcea** [comment]
@Thanks @dreab8 

If you have time, can you take a look at these two PRs as well:

- [HHH-13614 Allow the IntegratorProvider to be supplied via its FQN in the JPA persistence.xml](https://github.com/hibernate/hibernate-orm/pull/3032)
- [HHH-13608 Oracle8iDialect should use CASE_INSENSITIVE pattern matching when checking the statement type](https://github.com/hibernate/hibernate-orm/pull/3016)

I think both are very useful and pose no risk to integrate them.

**Comment by dreab8** [comment]
Hi @vladmihalcea , you are welcome, as soon as I have time I'll give a look at them ( by the way I'll try to do it before the next release)

**Comment by vladmihalcea** [comment]
Great, thanks.

**Pull request closed without merging**
