### PR TITLE
HHH-10332: Disambiguate missing table name

### PR DESCRIPTION
**Pull request by domtoupin**
Used "table.getQualifiedTableName()" instead of "table.getName()" when building the exception to report the missing table.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
I'm reviewing it now. I was wondering why did you submit the PR for 5.0. We can commit it on master, and back port it on other versions too.

**Comment by vladmihalcea** [comment]
I have enhanced the improvement to output the qualified table name in all validation use cases (table, column, and column type), and changed the test case to match the 5.1 current code base API. For 5.0, we need to ask @gbadner if this fix is considered to be integrated.

**Comment by vladmihalcea** [comment]
Applied fix on master. Thanks.

**Comment by domtoupin** [comment]
Thanks to you! Meanwhile, we will cherry-pick commit 15c83ab61b6ffaf5f36f41f8a039eba4766a1041 to our custom fork of Hibernate 5.0.7, which comes with Wildfly 10.0.0-Final.

**Pull request closed without merging**
