### PR TITLE
HHH-10418 Support entity/collection sharing same region (5.1.x)

### PR DESCRIPTION
**Pull request by galderz**
https://hibernate.atlassian.net/browse/HHH-10418

### CODE REVIEW

**Comment by galderz** [comment]
What's the error that lgtm is complaining about? Logs are truncated

**Comment by gbadner** [comment]
@galderz, there is an inconsistency between SessionFactoryImpl and CacheImpl. 

I've added a unit test: https://github.com/gbadner/hibernate-core/commit/9f683bc367ea0ccb5f197cc6dbbbacc4fe75d001

I'll create a PR with a fix tomorrow.

**Comment by galderz** [comment]
Thx @gbadner. Let me know if you need anything from me.

**Comment by gbadner** [comment]
Superseded by https://github.com/hibernate/hibernate-orm/pull/2100

**Pull request closed without merging**
