### PR TITLE
HHH-15689, HHH-15696, HHH-15697 fix SessionFactoryBuilder.addEntityNameResolver() 

### PR DESCRIPTION
**Pull request by gavinking**
and add `Configuration.addEntityNameResolver()`

### CODE REVIEW

**Comment by gavinking** [comment]
Folks, WDYT of this?

**Comment by gavinking** [comment]
If nobody gives me any feedback on this one, I'm going to assume it's all good, which might not be a bulletproof assumption!

**Comment by dreab8** [comment]
it looks good to me!

**Comment by gavinking** [comment]
Thanks, @dreab8, merged!

**Pull request merged**
