### PR TITLE
HHH-12120 Update StandardDialectResolver to reflect the latest Dialects of PostgreSQL and MySQL

### PR DESCRIPTION
**Pull request by quaff**
Use PostgreSQL95Dialect instead of default PostgreSQL81Dialect

### CODE REVIEW

**Comment by gsmet** [comment]
It makes me think that maybe we should have the default the other way around i.e. return the latest version if the version is unknown (and be careful to return the old dialect for the old versions).

This way, we would have best effort support for the new versions of a RDBMS instead of using the oldest versions of the dialect.

What do you all think?

**Comment by quaff** [comment]
Totally agree!

**Comment by ajrepp** [comment]
Just curious -- are there plans to add dialects for Postgres 9.6, 10.0, and 10.1? How is it decided when a new dialect is needed?

- 9.6: https://www.postgresql.org/docs/9.6/static/release-9-6.html
- 10.0: https://www.postgresql.org/docs/10/static/release-10.html
- 10.1: https://www.postgresql.org/docs/10/static/release-10-1.html

**Comment by vladmihalcea** [comment]
A new Dialect is added if there is a new database feature that Hibernate could use for implementing some specific persisting mechanism.

For instance, Oracle 12c now supports SQL Standard pagination. That's a good indication that we need a new Dialect for 12c.

**Comment by vladmihalcea** [comment]
@ajrepp Superseded by this [PR](https://github.com/hibernate/hibernate-orm/pull/2066).

**Pull request closed without merging**
