### PR TITLE
HHH-10406 - Provide @CreationTimestamp and @UpdateTimestamp for Java Time

### PR DESCRIPTION
**Pull request by dewarder**

### CODE REVIEW

**Comment by kartoffelsup** [comment]
How about something like this, which would produce less code duplication?:

```java
final class TimestampGenerators {
  private static final Map<Class<?>, Supplier<ValueGenerator<?>>> generators = build();

  private TimestampGenerators() {
  }

  private static Map<Class<?>, Supplier<ValueGenerator<?>>> build() {
    final Map<Class<?>, Supplier<ValueGenerator<?>>> gens = new HashMap<>(7);
    gens.put(java.sql.Date.class, TimestampGenerators::sqlDateGenerator);
    gens.put(java.sql.Time.class, TimestampGenerators::sqlTimeGenerator);
    gens.put(java.sql.Timestamp.class, TimestampGenerators::sqlTimestampGenerator);
    gens.put(java.util.Date.class, TimestampGenerators::dateGenerator);
    gens.put(java.util.Calendar.class, TimestampGenerators::calendarGenerator);
    gens.put(java.time.Instant.class, TimestampGenerators::instantGenerator);
    gens.put(java.time.LocalDate.class, TimestampGenerators::localDateGenerator);
    return gens;
  }

  private static ValueGenerator<LocalDate> localDateGenerator() {
    return (session, owner) -> java.time.LocalDate.now();
  }

  private static ValueGenerator<java.time.Instant> instantGenerator() {
    return (session, owner) -> java.time.Instant.now();
  }

  private static ValueGenerator<java.util.Date> dateGenerator() {
    return (session, owner) -> new java.util.Date();
  }

  private static ValueGenerator<java.util.Calendar> calendarGenerator() {
    return (session, owner) -> {
      final java.util.Calendar calendar = java.util.Calendar.getInstance();
      calendar.setTime(new java.util.Date());
      return calendar;
    };
  }

  private static ValueGenerator<java.sql.Date> sqlDateGenerator() {
    return (session, owner) -> new java.sql.Date(new java.util.Date().getTime());
  }

  private static ValueGenerator<java.sql.Time> sqlTimeGenerator() {
    return (session, owner) -> new java.sql.Time(new java.util.Date().getTime());
  }

  private static ValueGenerator<java.sql.Timestamp> sqlTimestampGenerator() {
    return (session, owner) -> new java.sql.Timestamp(new java.util.Date().getTime());
  }

  @SuppressWarnings("unchecked")
  public static <T> ValueGenerator<T> get(final Class<T> type) {
    final Supplier<ValueGenerator<?>> valueGeneratorSupplier = generators.get(type);
    if (Objects.isNull(valueGeneratorSupplier)) {
      throw new HibernateException("Unsupported property type for generator annotation @CreationTimestamp/@UpdateTimestamp");
    }

    return (ValueGenerator<T>) valueGeneratorSupplier.get();
  }
}
```

```java
...
  private ValueGenerator<?> generator;

  @Override
  public void initialize(CreationTimestamp annotation, Class<?> propertyType) {
    final ValueGenerator<?> valueGenerator = TimestampGenerators.get(propertyType);  
    generator = valueGenerator;
  }
...
```

**Comment by vladmihalcea** [comment]
@kartoffelsup Very good approach separating the generators so that we can reuse them for INSERT and UPDATE. Can you provide a Pull Request with your changes? It would not be fair if I copy-paste your solution and commit it in my name. Let me know if you're willing to submit a PR. Thanks.

**Comment by kartoffelsup** [comment]
Sure, I can open a Pull Request for it.

**Comment by vladmihalcea** [comment]
Thanks. Please sign the [CLA](https://cla.jboss.org/) if you haven't already done that?

**Comment by dewarder** [comment]
Ok, approach with Map is really good. But I think ValueGenerator classes may be useful in some cases. So how about this approach?
```
static {
        generators = new HashMap<>();
		generators.put( Date.class, CurrentDateGenerator::new );
        generators.put( Calendar.class, CurrentCalendarGenerator::new );
        generators.put( java.sql.Date.class, CurrentSqlDateGenerator::new );
        generators.put( Time.class, CurrentSqlTimeGenerator::new );
		generators.put( Timestamp.class, CurrentSqlTimestampGenerator::new );
		generators.put( Instant.class, CurrentInstantGenerator::new );
		generators.put( LocalDate.class, CurrentLocalDateGenerator::new );
		generators.put( LocalDateTime.class, CurrentLocalDateTimeGenerator::new );
		generators.put( LocalTime.class, CurrentLocalTimeGenerator::new );
		generators.put( MonthDay.class, CurrentMonthDayGenerator::new );
		generators.put( OffsetDateTime.class, CurrentOffsetDateTimeGenerator::new );
		generators.put( OffsetTime.class, CurrentOffsetTimeGenerator::new );
		generators.put( Year.class, CurrentYearGenerator::new );
		generators.put( YearMonth.class, CurrentYearMonthGenerator::new );
		generators.put( ZonedDateTime.class, CurrentZonedDateTimeGenerator::new );
}
```

**Comment by vladmihalcea** [comment]
I think we can remove those package private classes with Lambdas. This is the only place where we need them.

**Comment by vladmihalcea** [comment]
Applied upstream. Thanks everyone for participating.

**Pull request closed without merging**
