### PR TITLE
HHH-17053-fix(hibernate-orm): joda-money cannot mapping with compositeType

### PR DESCRIPTION
**Pull request by ZeroWM**

### CODE REVIEW

**Comment by beikov** [comment]
This PR produces a compile error. Apart from that, you do not use a proper embeddable projection in the `CompositeUserType`. We have a few examples in the [test suite](https://github.com/hibernate/hibernate-orm/blob/570ccae476aab2a9f5a23eb7f55b5cc72153e99b/hibernate-core/src/test/java/org/hibernate/orm/test/mapping/basic/MonetaryAmountUserType.java#L20) that show how you can implement a custom composite type for monetary amounts. We even have a section in the documentation that goes into that topic in-depth: https://docs.jboss.org/hibernate/orm/6.2/userguide/html_single/Hibernate_User_Guide.html#embeddable-mapping-custom

Apart from the compile errors, I can immediately see that you are not considering the fact that Hibernate orders attributes by attribute name in alphabetical order, which means that `amount = 0` and `currency = 1`. If you fix that, your problem will probably go away, but please consider asking questions on our [Discourse forum](https://discourse.hibernate.org/) first before creating a JIRA issue straight ahead.

**Comment by gavinking** [comment]
@beikov 

> Apart from the compile errors, I can immediately see that you are not considering the fact that Hibernate orders attributes by attribute name in alphabetical order, 

Ugh, but wait, that's a bit broken, isn't it? How can I ever write a correct composite user type if I can't know what order the columns are going to be resorted into?

The column names are not know by the composite user type itself, they are defined by the use site.

**Comment by gavinking** [comment]
Oh, wait, by _attribute name_, not by column name. Excuse me, I misread. 

I guess that's OK then, though I still don't love it.

**Comment by beikov** [comment]
Read carefully, **attribute** names. The names are controlled by the author of the composite user type as the names are defined in the embeddable projection type.

**Comment by gavinking** [comment]
Yeah sure, my bad. The signature of this method is still kinda fragile though:

    Object getPropertyValue(J component, int property)

It would be better to identify the property in a more typesafe way.

**Comment by beikov** [comment]
Indeed, the javadoc is incorrect. Would you be so kind and create a PR for fixing the javadoc please?

**Pull request closed without merging**
