### PR TITLE
Respect system specific line separators

### PR DESCRIPTION
**Pull request by racon-am**

### CODE REVIEW

**Comment by Sanne** [comment]
Hi @racon-am , thanks for the patch but a bit of context would help. Is this test failing on Windows?

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by richardfontana** [comment]
@vladmihalcea this PR can be integrated without requiring the CLA. Thanks!

**Comment by vladmihalcea** [comment]
Closing it because all tests run just fine on both Windows (my machine) and Linux (Jenkins).

**Pull request closed without merging**
