### PR TITLE
HHH-9894 Changes for Informix

### PR DESCRIPTION
**Pull request by gregjones60**
Fix Boolean support for Informix

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by gregjones60** [comment]
Yes, CLA is signed!

**Comment by vladmihalcea** [comment]
Thanks for the PR. I'm going to integrate it.

**Comment by vladmihalcea** [comment]
Thanks. Applied upstream on master.

**Comment by vladmihalcea** [comment]
Thanks. Applied upstream on master.

**Pull request closed without merging**
