### PR TITLE
HHH-17154 Fix NullPointerException is thrown when constructing EntityManagerFactoryBuilderImpl

### PR DESCRIPTION
**Pull request by quaff**
https://hibernate.atlassian.net/browse/HHH-17154

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @quaff , can you please also provide a test case to avoid future regressions? Thanks

**Comment by quaff** [comment]
> Hi @quaff , thanks for the PR, can you please also provide a test case to avoid future regressions? Thanks

I will try.

**Comment by dreab8** [comment]
thanks!

**Comment by quaff** [comment]
@dreab8 Done.

**Comment by quaff** [comment]
@dreab8 Please take a look at https://github.com/spring-projects/spring-framework/issues/31151, I'm not sure it's a regression that hibernate should fix or change that spring should adapt.

**Comment by beikov** [comment]
There is an ongoing discussion about how to solve this best and I am working on this. I'll close this for now and open a new PR soon.

**Pull request closed without merging**
