### PR TITLE
HHH-11028 Test Case

### PR DESCRIPTION
**Pull request by raissi**
This is the Test Case that shows that schema placeholder in Custom SQL is not replaced with current schema

### CODE REVIEW

**Comment by Naros** [comment]
Thanks for the test case.

**Comment by raissi** [comment]
Hi Narcos,
I want to add a new Test Case involving the AbstractEntityPersister class where I think it's best to introduce the Bug Fix (that I already prepared). 
What procedure should I follow ? 
Sorry this is my first contribution to an open source project and I want to follow the procedure

**Comment by Naros** [comment]
No problem.  If you have a proposed solution to the problem, feel free to push it to this same branch with a different commit.  Additionally, if you have any other test cases, you can push those as separate commits as well.

**Comment by raissi** [comment]
Thank you for your answer. I added the second Test Case and pushed it with the my proposed fix (in separate commits).
Regards,
Laabidi

**Comment by vladmihalcea** [comment]
Closing it since HHH-11028 is closed.

**Pull request closed without merging**
