### PR TITLE
HHH-10185 In nonstrict-read-write mode the remove may be not applied

### PR DESCRIPTION
**Pull request by rvansa**
@galderz Forgot to issue this PR some time ago... Applicable to 5.0 branch, too.

### CODE REVIEW

**Comment by galderz** [comment]
Looking...

**Comment by galderz** [comment]
I've integrated it into master but could not apply the commit cleanly to 5.0 branch. Can you please send a PR for 5.0?

**Comment by rvansa** [comment]
@galderz OK, I'll check it...

**Comment by rvansa** [comment]
@galderz I've applied the commit on Friday and it went well, besides the testsuite; in 5.0 I had failures running hibernate-infinispan testsuite even without the update applied. I'll try later this week if it got fixed.

**Comment by rvansa** [comment]
Created #1146

**Pull request closed without merging**
