### PR TITLE
HHH-13758 - Limit Handler for SQL server doesn't work with CTE queries with strings literals

### PR DESCRIPTION
**Pull request by jasonex7**
Fixes [HHH-13758](https://hibernate.atlassian.net/browse/HHH-13758)

### CODE REVIEW

**Comment by Sanne** [comment]
nice catch. Thanks!

**Comment by jasonex7** [comment]
> nice catch. Thanks!

your welcome. 

How could I contribute with a backport to 5.2 branch? This is my first contribution to this project.

**Comment by Sanne** [comment]
We're very conservative with older branches, and 5.2 is not even longer supported so that would be a bit unusual. Can't you upgrade?

In case you really want to get it backported, the first step of the process is to ask nicely to @gbadner as she is responsible for all the previous branches.

**Comment by jasonex7** [comment]
Thanks for the information. It's OK for me. I found a workaround for previous versions with a custom dialect based on the previous one but with the fix.

**Pull request merged**
