### PR TITLE
HHH-16096 Passing an ExtendedBeanManager which is notified too late leads to initialization error

### PR DESCRIPTION
**Pull request by vpriscan**
Add a null check for BeanManager in org.hibernate.resource.beans.container.internal.JpaCompliantLifecycleStrategy.NamedBeanImpl.initialize and use fallback producer if null.

[HHH-16096](https://hibernate.atlassian.net/browse/HHH-16096)

[HHH-16096]: https://hibernate.atlassian.net/browse/HHH-16096?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by yrodiere** [comment]
@vpriscan I think what you're trying to do was solved by https://github.com/hibernate/hibernate-orm/pull/6027?

Can you please check and report back here?

**Review by yrodiere — CHANGES_REQUESTED** [review]
Waiting for feedback

**Comment by vpriscan** [comment]
@yrodiere Yes, the root issue (initialization error) has been avoided by that PR, 
but this PR still adds a null check and a fallback in JpaCompliantLifecycleStrategy.NamedBeanImpl.initialize for completeness and consistency with JpaCompliantLifecycleStrategy.BeanImpl.initialize, where the exact same null check and fallback exists.

**Review by yrodiere — COMMENTED** [review]
Ah, I didn't see that. Makes sense.

I'm a bit surprised https://hibernate.atlassian.net/browse/HHH-14914 introduced that code to begin with, though. I'll let @sebersole confirm it's still relevant.

**Comment by sebersole** [comment]
The build failure on Jenkins is unrelated.  Going to integrate this.  Thanks @vpriscan !

**Pull request merged**
