### PR TITLE
Fixed HHH-7407

### PR DESCRIPTION
**Pull request by beikov**

### CODE REVIEW

**Comment by beikov** [comment]
Also note the backport for 4.2 here: https://github.com/hibernate/hibernate-orm/pull/822

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by beikov** [comment]
I did. My JBoss username is christian.beikov

**Comment by vladmihalcea** [comment]
Thanks, I'm updating the issue label.

**Comment by vladmihalcea** [comment]
I'm closing this issue because [HHH-7407](https://hibernate.atlassian.net/browse/HHH-7407) was closed as out-of-date, possibly because it got fixed by [HHH-9630](https://hibernate.atlassian.net/browse/HHH-9630).

**Pull request closed without merging**
