### PR TITLE
HHH-13077 - Optimize query plan call count

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-13077

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@sebersole If you have time, can you take a look on this PR. This is a "second" attempt, as I reverted the initial commit from the master. For more details, you can check [the original PR](https://github.com/hibernate/hibernate-orm/pull/2624). Thanks.

**Comment by sebersole** [comment]
Applied upstream on master.  Thanks!

**Comment by vladmihalcea** [comment]
@sebersole Cool. Thanks for integrating it.

**Comment by gavinking** [comment]
This change broke HR. We need to figure out what to do about that.

**Pull request closed without merging**
