### PR TITLE
HHH-15618 Accept TypedParameterValue for procedure

### PR DESCRIPTION
**Pull request by quaff**
Fix https://github.com/spring-projects/spring-data-jpa/issues/2544

### CODE REVIEW

**Comment by quaff** [comment]
Could anyone review this?

**Comment by beikov** [comment]
I don't see a reason for this PR. There is an explicit API that can be used to bind parameters in a typed fashion. Also, `TypedParameterValue` is usually handled on the `Query` level, so if we do this at all, it should be handled in `ProcedureCallImpl`. Also, it's nice that you provide an implementation for 5.6, but we also need a test and possible fix for the `main` branch.

**Comment by quaff** [comment]
> I don't see a reason for this PR. There is an explicit API that can be used to bind parameters in a typed fashion. Also, `TypedParameterValue` is usually handled on the `Query` level, so if we do this at all, it should be handled in `ProcedureCallImpl`. Also, it's nice that you provide an implementation for 5.6, but we also need a test and possible fix for the `main` branch.

@beikov Updated as you suggested.

**Comment by gregturn** [comment]
Adopting Hibernate's `TypedParameterValue` wrapper is causing things to break in other places as that wrapper type percolates through our code. A big one our community runs into is stored procedures. 

With @quaff having offered a patch in the location your cited, what are the odds you could merge this patch?

**Comment by gregturn** [comment]
Regarding Hibernate 6.1, it appears to already be handled way up the hierarchy in `AbstractCommonQueryContract`.

```java
	@Override
	public CommonQueryContract setParameter(int position, Object value) {
		if ( value instanceof TypedParameterValue ) {
			@SuppressWarnings("unchecked")
			final TypedParameterValue<Object> typedValue = (TypedParameterValue<Object>) value;
			final BindableType<Object> type = typedValue.getType();
			if ( type != null ) {
				return setParameter( position, typedValue.getValue(), type );
			}
			else {
				return setParameter( position, typedValue.getValue(), typedValue.getTypeReference() );
			}
		}

		final QueryParameterImplementor<?> param = getParameterMetadata().getQueryParameter( position );

		if ( param == null ) {
			throw new IllegalArgumentException( "Positional parameter [" + position + "] is not registered with this procedure call" );
		}

		if ( param.allowsMultiValuedBinding() ) {
			final BindableType<?> hibernateType = param.getHibernateType();
			if ( hibernateType == null || isInstance( hibernateType, value ) ) {
				if ( value instanceof Collection && !isRegisteredAsBasicType( value.getClass() ) ) {
					//noinspection rawtypes,unchecked
					return setParameterList( param, (Collection) value );
				}
			}
		}

		locateBinding( position ).setBindValue( value, resolveJdbcParameterTypeIfNecessary() );
		return this;
	}
```

**Comment by beikov** [comment]
>Updated as you suggested.

@quaff the changes look good, but please also create a PR against the main branch. Chances are good that we will merge this also for 5.6 @gregturn

**Comment by quaff** [comment]
Main branch(v6) doesn't need change if I understand correctly as @gregturn
said.

Christian Beikov ***@***.***> 于2022年12月21日周三 06:06写道：

**Comment by beikov** [comment]
But it needs at least a test case to verify it works correctly.

**Comment by quaff** [comment]
> But it needs at least a test case to verify it works correctly.

@beikov I've created https://github.com/hibernate/hibernate-orm/pull/5819.

**Comment by beikov** [comment]
Thanks!

**Pull request merged**
