### PR TITLE
Testcase for HHH-12676 and HHH-12675: SecondaryTable support for UnionSubclassPersister

### PR DESCRIPTION
**Pull request by jwgmeligmeyling**
See: https://hibernate.atlassian.net/browse/HHH-12676

### CODE REVIEW

**Comment by gsmet** [comment]
@JWGmeligMeyling I see a fix for HHH-12675 got committed.

Is this PR still useful?

**Comment by JWGmeligMeyling** [comment]
I comitted a fix but after looking into the UnionSublassPerister I stumbled upon two possible issues that are largely untested in the test suite. Until I have added test cases that verify that everything still works I have to withdraw my fix :)

**Comment by gsmet** [comment]
So you're saying the included fix might have cause some regressions?

We're soon to release 5.4.0 so, if we have to revert something, we need to do it soon.

Thanks!

**Comment by gsmet** [comment]
Hey,

I would say let's focus on the other issue we talked about today (e.g. https://github.com/hibernate/hibernate-orm/pull/2480). We have a clear plan for this one so I think it can make it into 5.4.0 if you have some time to put into it.

**Comment by JWGmeligMeyling** [comment]
Cool, will do. I am occupied today with a feature in one of my other projects. When do you expect a feature lock for 5.4CR?

**Comment by gsmet** [comment]
I just sent an email on the list proposing next Wednesday. Check the thread for any update on this.

**Comment by sebersole** [comment]
I added a reproducer - `org.hibernate.orm.test.unionsubclass.secondarytables.UnionSubclassWithSecondaryTableTests`

**Pull request closed without merging**
