### PR TITLE
HHH-14229 Fix unexpected foreign key creation

### PR DESCRIPTION
**Pull request by quaff**
before this commit, foreign key is created even ConstraintMode.NO_CONSTRAINT present on the @ManyToOne side

### CODE REVIEW

**Comment by quaff** [comment]
The effective code is
```
final OneToMany oneToManyAnn = property.getAnnotation( OneToMany.class );
// foreign key should be up to @ManyToOne side
boolean ignoreForeignKey = oneToManyAnn != null && !oneToManyAnn.mappedBy().isEmpty();
if ( ignoreForeignKey ) {
	for ( CascadeType cascadeType : oneToManyAnn.cascade() ) {
		if ( cascadeType == CascadeType.ALL || cascadeType == CascadeType.REMOVE ) {
			// CascadeType.REMOVE requires `on delete cascade`
			ignoreForeignKey = false;
			break;
		}
	}
}
if ( ignoreForeignKey ) {
	key.setForeignKeyName( "none" );
}
```
other changes fixes checkstyle and generics.

**Review by NathanQingyangXu — APPROVED** [review]
Excellent

**Comment by quaff** [comment]
> The effective code is
> 
> ```java
> final OneToMany oneToManyAnn = property.getAnnotation( OneToMany.class );
> final OnDelete onDeleteAnn = property.getAnnotation( OnDelete.class );
> if ( oneToManyAnn != null && !oneToManyAnn.mappedBy().isEmpty()
> 			&& ( onDeleteAnn == null || onDeleteAnn.action() != OnDeleteAction.CASCADE ) ) {
> 	// foreign key should be up to @ManyToOne side
> 	// @OnDelete generate "on delete cascade" foreign key
> 	key.setForeignKeyName( "none" );
> }
> ```
> 
> other changes fixes checkstyle and generics.

@beikov Would you take a look at this?

**Comment by beikov** [comment]
I have this PR in my queue, but haven't looked too deep at it yet. I had problems in the past as well which is why I want to verify this works for these problems.

**Comment by quaff** [comment]
ping

**Review by gbadner — APPROVED** [review]
@beikov, this looks OK to me. Were you able to do your checks?

**Comment by beikov** [comment]
I'm sorry. I still wasn't able to do my tests, but the change of this PR is IMO fine. You can go ahead and merge it @gbadner if you looked into this already.

**Comment by gbadner** [comment]
Merged to master.

@Sanne, should this be backported to 5.4?

**Comment by Sanne** [comment]
Yes, please apply it to 5.4 as well.

**Comment by gbadner** [comment]
@Sanne, this fix depends on the fix for [HHH-14253](https://hibernate.atlassian.net/browse/HHH-14253). Here is the [commit](https://github.com/hibernate/hibernate-orm/commit/88acc9511b2e1c1cee7def27ba8dc717a8c321f8) for HHH-14253.

Should I backport HHH-14253 as well?

**Comment by gbadner** [comment]
FYI, I'm not planning to backport these to 5.3, at least not for now.

**Comment by Sanne** [comment]
I had a quick look, and I don't understand why someone would not want foreign keys generated.
Seems a strange request and I'm not sure why we accepted that?

But ok if someone needs it then both should be backported to 5.4

**Comment by quaff** [comment]
> I had a quick look, and I don't understand why someone would not want foreign keys generated.
> Seems a strange request and I'm not sure why we accepted that?
> 
> But ok if someone needs it then both should be backported to 5.4

Foreign Keys affect INSERT performance, and Referential Integrity is guaranteed by ORM.

**Comment by quaff** [comment]
> @Sanne, this fix depends on the fix for [HHH-14253](https://hibernate.atlassian.net/browse/HHH-14253). Here is the [commit](https://github.com/hibernate/hibernate-orm/commit/88acc9511b2e1c1cee7def27ba8dc717a8c321f8) for HHH-14253.
> 
> Should I backport HHH-14253 as well?

It's not depends on HHH-14253.

**Pull request merged**
