### PR TITLE
type ids as Object instead of Serializable

### PR DESCRIPTION
**Pull request by gavinking**
Here's a draft.

I have done this without impacting user-visible APIs like `Interceptor` and `Tuplizer`, but we need to decide what to do about those.

### CODE REVIEW

**Review by beikov — APPROVED** [review]
Looks good to me. I think it's also a good idea to change this in `Interceptor` and `Tuplizer`.

**Comment by gavinking** [comment]
> Looks good to me. I think it's also a good idea to change this in `Interceptor` and `Tuplizer`.

Well yeah but that's a breaking change to user code, so we need to discuss it first.

**Comment by gavinking** [comment]
OK, this now also incorporates the change to the `EntityTuplizer` methods.

**Comment by gavinking** [comment]
OK, I've now fixed up the `Interceptor` and `Lifecycle` interfaces. This is now good to go, it seems to me.

**Review by sebersole — APPROVED** [review]

**Pull request merged**
