### PR TITLE
Use PU Info Classloader

### PR DESCRIPTION
**Pull request by kaja-mohideen**
Have entity classes from different bundles loaded seamlessly.

### CODE REVIEW

**Comment by Sanne** [comment]
hi thanks for the patch!
Could you either describe what you're aiming at, or even better add some tests?

**Comment by kaja-mohideen** [comment]
This is to avoid race condition (instantiation of EM) during startup when there are multiple bundles trying to use a common bundle which owns the PersistentUnit.

**Comment by Sanne** [comment]
@kaja-mohideen ah, makes sense - thanks for the explanation!

I'll create a JIRA for this and merge it.

**Comment by Sanne** [comment]
Merged as https://hibernate.atlassian.net/browse/HHH-13696

thanks!

**Comment by kaja-mohideen** [comment]
Shows PR is not merged, but closed !

**Comment by Sanne** [comment]
@kaja-mohideen no worries, that's because we rebase before merging. Github is unable to detect this and leaves the PRs open, so we close them manually.

When in doubt, check the master branch, and search commit logs for the JIRA issues:
 - https://github.com/hibernate/hibernate-orm/commits/master

**Pull request closed without merging**
