### PR TITLE
HHHH-14688 Get IdentifierGenerator from BeanContainer if not registered

### PR DESCRIPTION
**Pull request by quaff**
https://hibernate.atlassian.net/browse/HHH-14688

### CODE REVIEW

**Comment by Sanne** [comment]
Nice, looks useful. Could you add a test please to prevent future regressions?

**Comment by quaff** [comment]
> Nice, looks useful. Could you add a test please to prevent future regressions?

Please review.

**Comment by quaff** [comment]
Could someone take a look at this? It's a small improvement.

**Review by sebersole — APPROVED** [review]
Looks good.  Thanks!

**Comment by Sanne** [comment]
thanks @quaff & @sebersole !

**Comment by quaff** [comment]
> thanks @quaff & @sebersole !

@Sanne It should be backported to 5.4, then Spring Boot users will be benefit, WDYT?

**Comment by Sanne** [comment]
I would prefer not since it's a new feature; can't I assume that Spring Boot will also upgrade to 5.5 sometime soon?

**Pull request merged**
