### PR TITLE
Support Trafodion dialect

### PR DESCRIPTION
**Pull request by haifengl**
Apache Trafodion is a webscale SQL-on-Hadoop solution enabling transactional or operational workloads on Hadoop. This branch add the SQL dialect support for Trafodion.

### CODE REVIEW

**Comment by brmeyer** [comment]
Hey @haifengl, thanks.  However, ORM is no longer accepting new Dialects, unless:

1.) Many community members have an interest in it
2.) Someone or some organization is willing to maintain it long term.  We have too many Dialects that were contributed, then abandoned.

For the former, open a JIRA ticket, allowing users to vote on it.  For the latter, if ADP, the Trafodion community, etc. are willing to back this long term, let's discuss that.

**Comment by rkakarlamudi** [comment]
Hi Brett,

We prefer option 2... meaning Esgyn Corp will maintain Trafodion dialect. Since we are the contributors of Apache Trafodion project and also are willing to maintain it for long term.

We are open to further discussion.

Regards
Rao

**Comment by brmeyer** [comment]
@rkakarlamudi & @haifengl, I'm not against that, as long as community members want it.  Like I mentioned, can you please open an ORM JIRA ticket (HHH)?  We'll use that to discuss.  https://hibernate.atlassian.net

**Comment by haifengl** [comment]
I created the JIRA ticket

https://hibernate.atlassian.net/browse/HHH-10216

Let's discuss there. Thanks!

**Pull request closed without merging**
