### PR TITLE
HHH-13916 : Pending-put should not be created by Infinispan when chec…

### PR DESCRIPTION
**Pull request by gbadner**
…king if an entity is transient

https://github.com/gbadner/hibernate-core/pull/new/HHH-13916

### CODE REVIEW

**Comment by gbadner** [comment]
An alternative is to have `AbstractEntityPersister#isTransient` call a new method,  `CacheHelper#existsInCache`, which would call `CachedDomainDataAccess#get`.

**Comment by gbadner** [comment]
I'll look into the failures tomorrow...

**Comment by gbadner** [comment]
The test failures appeared to be due to the test not cleaning up after itself properly. I pushed a commit to fix the test.

**Comment by dreab8** [comment]
What It is strange is that the tests were not failing before your change.

**Comment by dreab8** [comment]
@gbadner  I tried to remove the `deleteData()` you added and I changed the `init()` method adding at the beginning the checks
```
	inTransaction(
				session -> {
					List<Node> node = session.createQuery( "from Node").list();
					assertTrue( node.isEmpty() );
				}
		);
.....

```
the assertions is always satisfied but when i run all the tests  the `init` methos of `testOneToManyMoveElementWithDirtySimpleProperty` fails with `javax.persistence.OptimisticLockException: Row was updated or deleted by another transaction (or unsaved-value mapping was incorrect) : [org.hibernate.test.onetomany.Node#2] `

**Comment by gbadner** [comment]
@dreab8, I was finally able to dig into this again, and I see that this approach will not work. Thanks for pushing me to investigate further. I'll send an email with more details.

**Pull request closed without merging**
