### PR TITLE
HHH-9868, HHH-9881, HHH-9898 Consistency fixes in Infinispan 2LC

### PR DESCRIPTION
**Pull request by rvansa**
This PR fixes several consistency problems in Infinispan 2LC implementation and provides a test for finding further ones (after 2LC is updated in the future).

https://hibernate.atlassian.net/browse/HHH-9868
https://hibernate.atlassian.net/browse/HHH-9881
https://hibernate.atlassian.net/browse/HHH-9898

### CODE REVIEW

**Comment by rvansa** [comment]
@galderz You might be interested in these fixes.

**Comment by rvansa** [comment]
Please do not integrate yet - it seems that caching can be sometimes prevented, though there's no ongoing invalidatation.

**Comment by rvansa** [comment]
OK, works for non-transactional caches as long as JTA is used for Hibernate. I have to explore options for non-JTA yet, but first I will look on https://hibernate.atlassian.net/browse/HHH-9928 (I already have a fix https://github.com/rvansa/hibernate-orm/tree/HHH-9928) and https://hibernate.atlassian.net/browse/HHH-7898

**Comment by rvansa** [comment]
H2 in version 1.3 seems to fail many transactions due to deadlocks; this is caused by it's table-level locking. I suggest running CorrectnessTestCase only with MVCC -> H2 1.4

**Comment by rvansa** [comment]
Closing until other PRs on which this depends get merged, to not pollute here meanwhile (it will need a rebase anyway)

**Comment by dreab8** [comment]
@rvansa i have merged and closed the 2 PR:
- https://github.com/hibernate/hibernate-orm/pull/1031
- https://github.com/hibernate/hibernate-orm/pull/1020

**Comment by galderz** [comment]
@rvansa Let me know when this is ready once again and I'll have an in-depth look.

**Pull request closed without merging**
