### PR TITLE
Update SAPDBDialect.java

### PR DESCRIPTION
**Pull request by ti-ku**
Support for identity columns in SapDB/MaxDB

### CODE REVIEW

**Comment by ti-ku** [comment]
Hi again, I did a little research and all SapDB/MaxDB Versions back to the '90s support identity columns, so SAPDBDialect class could support it too.

**Comment by sebersole** [comment]
Did I apply this? Or did I inadvertently close it?

**Comment by brmeyer** [comment]
@sebersole, probably accidentally closed (or intentionally, when we didn't hear back from @ti-ku).

@ti-ku, thanks for the response!  We'll take a look...

**Comment by sebersole** [comment]
Is there a Jira for this?

**Comment by ti-ku** [comment]
Thank you!

**Comment by brmeyer** [comment]
@ti-ku, like @sebersole mentioned, is there a JIRA ticket for this?  If not, can you open one?  Thanks!

**Comment by brmeyer** [comment]
Closing.  If this is still a need, please open a JIRA ticket and we'll discuss it there.  Thanks!

**Pull request closed without merging**
