### PR TITLE
HHH-12248 Clustered 2nd level cache sometimes throws NullPointerExcep…

### PR DESCRIPTION
**Pull request by tomdearman**
This should take care of the race condition in PutFromLoadValidator.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@tomdearman 5.2 is now used only for bug fixing. All fixes must be approved by @gbadner for older branches.

The `hibernate-infinispan` module was moved to `org.infinispan:infinispan-hibernate-cache`. You should provide the fix there as well. Thanks.

**Comment by tomdearman** [comment]
Ok, I had notice it was moved, but wasn’t sure what the procedure was, I will provide the fix there too.  This is a bug so hopefully @gbadner will approve it.

**Comment by gbadner** [comment]
@vladmihalcea, this does not require me to make a decision on this.

**Comment by vladmihalcea** [comment]
@gbadner Yes. I wrote that comment before I was told that we can backport in 5.2 until we have a 5.3 Final release.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks.

Don't forget to send this PR to Infinispan project, as otherwise, the issue will fail in 5.3 since the Hibernate Infinispan caching implementation is provided by Infinispan now.

**Comment by tomdearman** [comment]
This has already been accepted and applied to infinispan 5.2.Final.

**Pull request closed without merging**
