### PR TITLE
Hhh 10427

### PR DESCRIPTION
**Pull request by gbadner**
Incorporates the commits from https://github.com/hibernate/hibernate-orm/pull/1337.

Caches the initialized services in a new field: AbstractServiceRegistryImpl#initializedServiceByRole.

AbstractServiceRegistryImpl#getService only synchroizes on this when the service is not found in initializedServiceByRole.

### CODE REVIEW

**Comment by gbadner** [comment]
@dreab8 wdyt?

**Comment by karlvr** [comment]
Would it be possible to synchronize on the serviceBinding instead of on the service registry? That would reduce the scope of the lock, and we're only trying to fix concurrency on each service, rather than between all services.

**Comment by dreab8** [comment]
@gbadner, @karlvr 
 I think it's fine probably we can do a `synchronized (initializedServiceByRole)` instead of  `synchronized (this) ` even if I think at the moment it makes no difference, we have no other methods acquiring a lock on `this`, but I may be wrong.

**Comment by Sanne** [comment]
> Would it be possible to synchronize on the serviceBinding instead of on the service registry? 

That sounded interesting, but checking the code I see that a service initialization might recursively have to initialize other services. Since such initialization orders are unpredictable, that optimisation could lead to deadlocks.

As I commented on `HHH-10427`, I'm actually surprised that we have any services being initialized concurrently.

Since this issue was observed I'm going to assume that _some_ services to this, but if it's a minority - and initialization happens only once anyway - then I would suggest to keep this code simple than to optimise for highly concurrent initializations.

**Comment by Sanne** [comment]
N.B. if initializations happen concurrently, then there are some more problematic things which could happen:

 - methods #startService and #stopService are public and can race among each other and with the initialization code
 - the #destroy method is not safe either during the above operations either.

If these need to be safe concurrently, we need two levels of locking: one as instance of the `AbstractServiceRegistryImpl` to safeguard *any* change to servicebindings (including all of teardown methods), and one more fine grained to protect start/stop operations on an individual `Service` instance.

Reading (and only reading) from the servicebindings can be optimised as a lock-less path but the #destroy method needs to allow for this, for example by wiping out the _initializedServiceByRole_ map as first thing.

I can propose these changes? Though first I'd like someone more familiar with the use case to confirm that indeed these services are meant to be taken up/down by multiple different threads.

**Comment by karlvr** [comment]
From my application, if servlets et al are the first to request a service, then they could obviously come at it from multiple threads at once. I believe that's how it's most likely to occur in my scenario.

**Comment by karlvr** [comment]
@Sanne phew, dodged a bullet on recursive service initialisation deadlocks!

**Comment by Sanne** [comment]
@karlvr yes I understand how it could happen.. I am puzzled though that we consider the bootstrap "completed" without having actually started all the services. As commented on JIRA, I think we'd rather need to ensure that. Not least to validate that they can all start successfully.

**Comment by karlvr** [comment]
@Sanne Ah I see. I'm in the interesting position of having co-opted a separate instance of the Hibernate service registry to manage a separate service registry for my app. It works well! I definitely want on-demand service creation there, so I believe I will always be subject to the race at the heart of this discussion. While that is a problem peculiar to my use, I was hoping that one day the service registry might be spun out as a separate more readily reusable component as I didn't find a similarly powerful yet simple solution!

**Comment by Sanne** [comment]
@karlvr ah right I remember this was proposed some time back on the mailing list.. it was you then :+1: 

We can make it safe for such usage, it's not actually too hard. I was simply undecided about which path to suggest.. in lack of need for concurrent & lazy initialization I'd have avoided it, but I was also thinking that this should probably be coded more defensively, i.e. guard against it just in case.

I'd like to see a way to test that we don't do such things though - in the Hibernate use case at least - as I don't think it's fair for the subsequent application threads to have some of them to incur an unpredictable delay. The main goal is great throughput though, so maybe we need to limit such checks to some for of assertions enabled during tests only.

**Comment by sebersole** [comment]
I believe a separate reentrant read/write lock may be the best option.  We'd acquire the read lock to check/get the binding and escalate it to acquiring the write lock if/when we need to create the binding

**Comment by Sanne** [comment]
@sebersole shall I propose a patch or are you taking this?

**Comment by sebersole** [comment]
If you have time today, go for it.  If not I'll get to it later this week.

**Comment by sebersole** [comment]
@Sanne As for your point above, one option would be for the service/initiator to be able to express whether the service should be initialized up-front.

BTW, we lazily create/initialize services because we simply do not know up front which all will be used/needed.  JndiService is a great example of this.  JndiService is, generally speaking, only needed if either:

1. We need to locate a DataSource
2. We need to locate a JTA component
3. We need to bind SF into JNDI

Not all applications need it, so we initialize it lazily.  And I want to make sure that still happens.  Now the services ultimately using JndiService are probably a different story as most of them can be initialized up-front.

So following along this idea of service/initiator specifying this, perhaps we assume eager initialization (which is a change in behavior) and allow the service/initiator to indicate safety for late initialization (JndiService, JmxService, etc).

Also, we can likely leverage the ServiceBinding itself as a lock mechanism.

**Comment by Sanne** [comment]
Hi @sebersole I couldn't do it yesterday but I can now. I'm about to get on a long train journey w/o connection though.. Just crossing fingers that you're not working on the same thing.

**Comment by Sanne** [comment]
Sent a new PR. It includes Andrea's and Gail's improvements.

**Pull request closed without merging**
