### PR TITLE
Backport HHH-13266 to branch 5.3 - LocalDateTime values are wrong around 1900 (caused by JDK-8061577)

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HHH-13266

@gbadner I think we should backport this to 5.3?

### CODE REVIEW

**Comment by yrodiere** [comment]
Please hold; I had to push a few test fixes for non-H2 databases in #2815. I added the commits to this PR, but let's not backport until #2815 is merged...

**Comment by gbadner** [comment]
@yrodiere, thanks for creating this PR!

**Comment by yrodiere** [comment]
#2815 was merged into branch master and it fixed the failing mariaDB, Oracle and HANA jobs.

We can safely merge this in 5.3 if that's what you want, @gbadner .

**Comment by gbadner** [comment]
I added a commit to skip the failing tests.

**Pull request merged**
