### PR TITLE
HHH-2558 - Allow batching inserts for multi-table entities and HHH-5797 - Improve batching for entity updates or deletes that use secondary tables

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-2558
https://hibernate.atlassian.net/browse/HHH-5797

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@dannnnn This is the new Pull Request. I reworked it a little bit, and tests are passing fine.

@sebersole @gbadner @Naros @dreab8 Would you mind taking a look at this one if you have time?

**Comment by dannnnn** [comment]
Nice! Glad to see it merged. Multumesc ;)

**Comment by dannnnn** [comment]
Hi everyone, according to Fixed version field the bug should've been fixed in 5.2.13, I see that 5.2.14 is already released but i still don't see the changes from
https://github.com/hibernate/hibernate-orm/pull/2082

can you help me explaining this?

**Comment by vladmihalcea** [comment]
Here's [your commit](https://github.com/hibernate/hibernate-orm/commit/50070eabddd9106681c729a56c5bfcdeddb69d4b).

**Pull request merged**
