### PR TITLE
HHH-12670 - Allows native SQL queries that take a given result Class to map the result set to the required type

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-12670

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@sebersole If you have time, please take a look at this issue too. I think it's worth implementing this mechanism for native SQL queries.

**Comment by gsmet** [comment]
@vladmihalcea maybe I misunderstood the change but aren't you changing how the results of a query are organized? That would break compatibility for existing applications, wouldn't it?

**Comment by vladmihalcea** [comment]
@gsmet Without my change, you get an Exception. With my code, it works. It would break compatibility only if previously passing a non-entity class to a query actually worked.

**Comment by gsmet** [comment]
@vladmihalcea ah ok, that makes sense :).

**Pull request merged**
