### PR TITLE
HHH-13233 add missing implementation to add attribute to subgraphs

### PR DESCRIPTION
**Pull request by zeitiger**
Hi,

I would like to fix this problem that blocks me from upgrade hibernate in my project. I hope the problem is really that easy to fix. 

My problem is that attributes of subgraphs get not fetched after 5.4, 5.3 works fine.

Have a nice day
David

### CODE REVIEW

**Comment by gbadner** [comment]
@zeitiger, please add a test case that reproduces your issue.

**Comment by gsmet** [comment]
@zeitiger as mentioned by Gail, we need a test case to be sure we don't introduce regressions.

Thanks!

**Comment by zeitiger** [comment]
I add the requested test case by reusing an existing test case that used the same API differently and extend this existing test case also to verify entityGraph structure too.

**Comment by zeitiger** [comment]
@gsmet are we good now?

**Comment by gsmet** [comment]
Perfect, thanks, will be part of 5.4.2.

**Comment by zeitiger** [comment]
@gsmet without merge?

**Pull request closed without merging**
