### PR TITLE
Update ActionQueue.java

### PR DESCRIPTION
**Pull request by dmitrygusev**
based on this thread on Twitter https://twitter.com/vlad_mihalcea/status/1306486289034891272

### CODE REVIEW

**Comment by gavinking** [comment]
What does this change do?

**Comment by dmitrygusev** [comment]
@gavinking eliminates the need of evaluating second expression if previous succeeded, as the result will be the same for both branches; this is purely based on static code analysis, possible performance optimisation

**Comment by Sanne** [comment]
Nice change. thanks!

**Comment by Sanne** [comment]
Merged and backported as https://hibernate.atlassian.net/browse/HHH-14242

**Pull request closed without merging**
