### PR TITLE
HHH-13105 - Add registries for user-defined Types as currently a custom Type is instantiated and configured 9 times

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-13105

### CODE REVIEW

**Comment by gsmet** [comment]
This is an improvement, let’s do that in 6 instead if it still needs to be done, as per our discussions on the list. 

/cc @sebersole

**Comment by vladmihalcea** [comment]
Cannot be integrated into 6.0 yet as the Type support is not fully functional.

**Comment by sebersole** [comment]
Type should be close to fully functional now, albeit in a different way.  

Could you try porting and see if it works there?

**Comment by vladmihalcea** [comment]
@sebersole I will try to see how it works once I get a little bit of spare time to do it.

**Comment by dreab8** [comment]
Thanks @vladmihalcea,
 
I'm going to close this PR because the issue has been fixed.

**Pull request closed without merging**
