### PR TITLE
HHH-13069 Update the links to JBoss Nexus to use the direct repositor…

### PR DESCRIPTION
**Pull request by Sanne**
…y over https

https://hibernate.atlassian.net/browse/HHH-13069

### CODE REVIEW

**Comment by gsmet** [comment]
@Sanne doesn't work. At least some JBoss-repackaged artifacts are not accessible.

```
Execution failed for task ':hibernate-orm-modules:provision'.
> Could not resolve all dependencies for configuration ':hibernate-orm-modules:detachedConfiguration44'.
   > Could not find org.slf4j:slf4j-ext:1.7.22.jbossorg-1.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.pom
       - https://repo.maven.apache.org/maven2/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.jar
       - http://snapshots.jboss.org/maven2/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.pom
       - http://snapshots.jboss.org/maven2/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.jar
       - file:/home/travis/.m2/repository/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.pom
       - file:/home/travis/.m2/repository/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.jar
       - https://repo.maven.apache.org/maven2/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.pom
       - https://repo.maven.apache.org/maven2/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.jar
       - https://repository.jboss.org/nexus/content/repositories/releases/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.pom
       - https://repository.jboss.org/nexus/content/repositories/releases/org/slf4j/slf4j-ext/1.7.22.jbossorg-1/slf4j-ext-1.7.22.jbossorg-1.jar
     Required by:
         project :hibernate-orm-modules
```

**Comment by gsmet** [comment]
Rebased and reverted the changes for the WildFly modules.

Let's see if Travis is happier.

**Comment by Sanne** [comment]
+1 thanks

**Comment by gsmet** [comment]
Squashed and merged, thanks!

**Pull request closed without merging**
