### PR TITLE
HHH-15142 Reuse CriteriaQuery with explicit and implicit (=literal) params

### PR DESCRIPTION
**Pull request by ettavolt**
Caused by pull request #4864.
Reverting a couple of noop changes too.

https://hibernate.atlassian.net/browse/HHH-15142

### CODE REVIEW

**Comment by beikov** [comment]
No issue key. The tests are working fine with JUnit Jupiter as you can see in the GitHub [actions runs](https://github.com/hibernate/hibernate-orm/runs/5721635188?check_suite_focus=true), so please revert the test changes you did and use the JUnit 5 API for new tests.

**Comment by ettavolt** [comment]
I've downloaded the logs from your link, run `grep -r CriteriaUpdateWithParametersTest`, and observed no match.

More over, ci/build-github.sh delegates to ci/build.sh, which in turn just calls `gradle check`.
When I was calling `gradle check` locally before my changes, I've observed no report on CriteriaUpdateWithParametersTest either. Even more: I've reverted the #4864's change in ParameterExpression, run `gradle check` again and got it passed. Only after I've migrated CriteriaUpdateWithParametersTest it started to fail.

**Comment by dreab8** [comment]
I'm working on a different solution that fixes also `ReuseCriteriaWithMixedParametersTest#predicateReuse`, and I'll give a look also at `@JPA`

**Comment by dreab8** [comment]
Hi @ettavolt 

thanks a lot for your contribution, I'm going to close this PR in favour of https://github.com/hibernate/hibernate-orm/pull/4970

**Comment by ettavolt** [comment]
Hello Andrea
I'm happy to provide something useful for the Hibernate project.
May I humbly ask for an advice to bring #3057 on the maintainers' radar? :smile:

**Comment by dreab8** [comment]
Hi @ettavolt,
 
I'm going to give a look at it in the next few days!

**Pull request closed without merging**
