### PR TITLE
HHH-10294 EntityGraph improvement: For each jpa attribute, generate also a String constant holding the attribute field name

### PR DESCRIPTION
**Pull request by reda-alaoui**
Fix for https://hibernate.atlassian.net/browse/HHH-10294

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Up :)

**Comment by vladmihalcea** [comment]
@sebersole What do you think of this idea? Should we pursue it or not?

**Comment by reda-alaoui** [comment]
Don't forget this please :)

**Comment by reda-alaoui** [comment]
Hello,
FYI, we have been using this patch for a year now without any issue.
Regards.

**Comment by reda-alaoui** [comment]
Up :D

**Comment by reda-alaoui** [comment]
Up :D

**Comment by reda-alaoui** [comment]
Up :+1:

**Comment by sebersole** [comment]
Personally I do not see the point, but it does not violate the spec and it seems to be helpful to someone so I'm ok with integrating it.

@reda-alaoui Please rebase this work against master (5.3) and we will get it integrated.  Also, I am not a fan of these interleaved.  I'd rather see them grouped together.  I.e., instead of:

````
@StaticMetamodel(Person.class)
@Generated
class Person_ {
    public static volatile SingularAttribute<Person, String> name;
    public static volatile String NAME = "name";

    public static volatile SingularAttribute<Person, Integer> pk;
    public static volatile String PK = "pk";
}
````

I'd rather see:

````
@StaticMetamodel(Person.class)
@Generated
class Person_ {
    public static volatile SingularAttribute<Person, String> name;
    public static volatile SingularAttribute<Person, Integer> pk;

    public static volatile String NAME = "name";
    public static volatile String PK = "pk";
}
````
What do you think of that ^^ @vladmihalcea ?

**Comment by vladmihalcea** [comment]
@sebersole @reda-alaoui I think we need to see an example of how this new feature is going to improve EntityGraph creation.

So, in the Jira issue, we have this MetaModel:

```
@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(UserWithPassword.class)
public abstract class UserWithPassword_ {

	public static volatile SingularAttribute<UserWithPassword, String> password;
        public static final String PASSWORD = "password";
}
```

What's the benefit of having the `PASSWORD` constant there? I would rather have a `Map` between the `String` description and the `Attribute` so that when giving the name description we can get the `Attribute`.

Even if we don't integrate this PR, the users can simply scan the MetaModel using Java reflection to get the `String` representations of the contained `Attribute`(s).

In my opinion, we should see a real test case which is not included in the PR. When we have that, we should decide if it's worth integrating.

@reda-alaoui Would you mind adding the test case that shows how you are going to make use of this new `String` attribute descriptions?

**Comment by reda-alaoui** [comment]
@vladmihalcea , @sebersole , ok I will rebase the PR from a the correct repository without interweaving and with a test case asap.

**Comment by sebersole** [comment]
Well I'd assume the intent is to get compile errors when the names change and using String-based attribute access.

But in this regard, how is this:

````
String nameName = Person_.NAME;
````

any different than this:

````
String nameName = Person_.name.getName();
````

?

**Comment by reda-alaoui** [comment]
The intent is to use the string value inside an annotation. As you certainly know, you can’t use the second form inside an annotation.

**Comment by reda-alaoui** [comment]
I opened https://github.com/hibernate/hibernate-orm/pull/2088 containing the requested changes.

**Pull request closed without merging**
