### PR TITLE
HHH-13842 - Remove the TODO along with the commented code block

### PR DESCRIPTION
**Pull request by thegeekyasian**
A snippet in the hibernate-core.gradle had a TODO task. It said

TODO: Uncomment once EntityManagerFactoryBuilderImpl no longer uses ClassLoaderServiceImpl.
The EntityManagerFactoryBuilderImpl used ClassLoaderServiceImpl until version 4.3, which was removed in the version 5.0.  

This has been removed in this commit.

### CODE REVIEW

**Comment by thegeekyasian** [comment]
> Its an ugly work around that needs resolve. Someone blaming this file and seeing "Uncommented TODO" as most recent change doesn't help with finding the historical reasons for this workaround.
> 
> Lets just resolve the issue/ TODO instead

Makes sense, how do you suggest to proceed in order to resolve this issue/TODO?

**Comment by jwgmeligmeyling** [comment]
The code was originally introduced with https://github.com/hibernate/hibernate-orm/commit/56867417e283b235aa0832affd43207cb9ea5327#diff-197d2841569f03ef77fff9b387e93425R45 for OSGI support [HHH-7527](https://hibernate.atlassian.net/browse/HHH-7527) 7 years back. Back in the day, `EntityManagerFactoryBuilderImpl` was indeed dependent on `ClassLoaderServiceImpl` [[1](https://github.com/hibernate/hibernate-orm/blob/56867417e283b235aa0832affd43207cb9ea5327/hibernate-entitymanager/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java#L772-L781)].  I'm not sure if it still is, it is for sure still dependent on `ClassLoaderService` [[2](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java#L43)].

With the general build clean up in [HHH-8733](https://hibernate.atlassian.net/browse/HHH-8733) in commit https://github.com/hibernate/hibernate-orm/commit/d1023821b151e583c078cfcf3ffb1580e73acc23#diff-197d2841569f03ef77fff9b387e93425R80 the entire instruction was commented out. This was six years ago and I am not aware of any existing OSGI issues affected by this change.

In hindsight, I think the entire comment block can be removed, together with its TODO. I think reenabling the instruction on the other hand may cause issues and should be done with care.

**Comment by thegeekyasian** [comment]
> The code was originally introduced with [5686741#diff-197d2841569f03ef77fff9b387e93425R45](https://github.com/hibernate/hibernate-orm/commit/56867417e283b235aa0832affd43207cb9ea5327#diff-197d2841569f03ef77fff9b387e93425R45) for OSGI support [HHH-7527](https://hibernate.atlassian.net/browse/HHH-7527) 7 years back. Back in the day, `EntityManagerFactoryBuilderImpl` was indeed dependent on `ClassLoaderServiceImpl` [[1](https://github.com/hibernate/hibernate-orm/blob/56867417e283b235aa0832affd43207cb9ea5327/hibernate-entitymanager/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java#L772-L781)]. I'm not sure if it still is, it is for sure still dependent on `ClassLoaderService` [[2](https://github.com/hibernate/hibernate-orm/blob/master/hibernate-core/src/main/java/org/hibernate/jpa/boot/internal/EntityManagerFactoryBuilderImpl.java#L43)].
> 
> With the general build clean up in [HHH-8733](https://hibernate.atlassian.net/browse/HHH-8733) in commit [d102382#diff-197d2841569f03ef77fff9b387e93425R80](https://github.com/hibernate/hibernate-orm/commit/d1023821b151e583c078cfcf3ffb1580e73acc23#diff-197d2841569f03ef77fff9b387e93425R80) the entire instruction was commented out. This was six years ago and I am not aware of any existing OSGI issues affected by this change.
> 
> In hindsight, I think the entire comment block can be removed, together with its TODO. I think reenabling the instruction on the other hand may cause issues and should be done with care.

That sounds better. Yes I agree that reenabling the instruction can cause the issues now, as the repo has dramatically grown since the last change.

I will remove the TODO and the comment block entirely in the existing branch.

**Comment by sebersole** [comment]
@jwgmeligmeyling is spot on.  I think removing this block is the best option.  Thanks @thegeekyasian !  

I'll apply after the CI finishes

**Comment by thegeekyasian** [comment]
Thank you @sebersole!

**Comment by thegeekyasian** [comment]
I think this can now be merged, @sebersole 
Thanks!

**Comment by thegeekyasian** [comment]
Closing this PR as it has already been fixed in one of other commits

**Pull request closed without merging**
