### PR TITLE
HHH-10643 - Attribute 'foreignKeyDefinition' of @javax.persistence.Fo…

### PR DESCRIPTION
**Pull request by vladmihalcea**
…reignKey ignored by schema exporter

### CODE REVIEW

**Comment by mkurz** [comment]
Does the this new PR also consider the case where the constraintname gets added at the end of the sql? [Like in this dialect](https://github.com/hibernate/hibernate-orm/blob/5.1.0/hibernate-core/src/main/java/org/hibernate/dialect/InformixDialect.java#L109).

**Comment by mkurz** [comment]
I am asking because when override it via `foreignKeyDefinition="FOREIGN KEY ..."` we don't know the value of the Hibernate internal `constraintName`.

Of course someone could just define the foreign key name by himself:
```java
@ForeignKey(name="myname", foreignKeyDefinition="FOREIGN KEY ... constraint myname")
```

**Comment by vladmihalcea** [comment]
Good catch. I missed than one. I have to take care of that too.

**Comment by vladmihalcea** [comment]
I pushed a new version for the Informit Dialect.

**Comment by mkurz** [comment]
Thanks! Looks good to me.
Because this is backward compatible I hope this will make it into 5.2.1

**Comment by vladmihalcea** [comment]
It will be integrated in 5.2.1 for sure. I'm going to ask if we can backport it to 5.1.x too.

**Comment by mkurz** [comment]
Cool! :+1:

**Comment by mkurz** [comment]
@vladmihalcea I can not see this in the `master` branch - only in the `5.1` branch.

**Comment by vladmihalcea** [comment]
Thanks for the tip. I'm not sure what happened when I pushed it. It might have given me an error and I didn't see it. I pushed it now.

**Comment by mkurz** [comment]
:+1:

**Pull request closed without merging**
