### PR TITLE
HHH-11625 - Update Namespace.java

### PR DESCRIPTION
**Pull request by jvdvTechno**
Fix construction of physical name: use toPhysicalSchemaName instead of toPhysicalCatalogName to create the schemaName.

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @jvdvTechno ,

thanks for the patch, , can you open a Jira for this issue?

Thanls

**Comment by dreab8** [comment]
thanks @jvdvTechno 
have you signed the [CLA](https://cla.jboss.org/)?

This PR is superseded by https://github.com/hibernate/hibernate-orm/pull/1876 containing a testcase

**Comment by jvdvTechno** [comment]
Wow, I need a *third** account just to make a one line fix? (Github, Jira,
JBoss). How about moving it all to one place? That would make things a lot
easier for new contributors.

Anyway, there is no 'sign' button on the CLA-website, so I can't sign it.


Kinds regards,

*Jeroen van der Vegt *Lead Designer

*T* +31 1 82 59 40 00
*A* Burgemeester Jamessingel 1, P.O. Box 2013, 2800 BD Gouda, The
Netherlands* | W* technolution.nl

This email is intended exclusively for the addressee(s), and may not be
passed on to, or made available for use by any person other than the
addressee(s). Technolution B.V. rules out any and every liability resulting
from any electronic transmission.

2017-04-10 15:31 GMT+02:00 Andrea Boriero <notifications@github.com>:

**Comment by dreab8** [comment]
@jvdvTechno sorry for the inconvenience.

About CLA you have to click on the View agreement button then you'll should find a sign button.

Thanks again

**Comment by jvdvTechno** [comment]
What 'View agreement' button? I only see 'Back':
[image: Inline afbeelding 2]


Kind regards,

*Jeroen van der Vegt *Lead Designer

*T* +31 1 82 59 40 00
*A* Burgemeester Jamessingel 1, P.O. Box 2013, 2800 BD Gouda, The
Netherlands* | W* technolution.nl

This email is intended exclusively for the addressee(s), and may not be
passed on to, or made available for use by any person other than the
addressee(s). Technolution B.V. rules out any and every liability resulting
from any electronic transmission.

2017-04-10 15:52 GMT+02:00 Andrea Boriero <notifications@github.com>:

**Comment by dreab8** [comment]
when logged in from https://cla.jboss.org/index.seam I see a continue button that lands me to a page with a form to compile and a View agreement button.

**Pull request closed without merging**
