### PR TITLE
HHH-9451 Propagating entity entry extra state when using identity id gen...

### PR DESCRIPTION
**Pull request by gunnarmorling**
...eration strategy

Tested successfully with OGM.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@gbadner, @dreab8: Can this one be merged? Just seeing it's still open, so it would be nice to get it into the next 4.3.x. Thx!

**Comment by gbadner** [comment]
Looking at it now...

----- Original Message -----

**Comment by gbadner** [comment]
I'll look into it further after you add a test.
Thanks,
Gail

**Comment by gunnarmorling** [comment]
Hi @gbadner, @emmanuelbernard: Pushed an update for adding a test. Also tested successfully within OGM. Good from my side now.

**Comment by emmanuelbernard** [comment]
@gbadner quick question, did you also applied it in 5.0 / master?

**Comment by gbadner** [comment]
@emmanuelbernard yes: https://github.com/hibernate/hibernate-orm/commit/8468d834ef3e60bf412e2fdf30f10a9b1f3ce88e

**Pull request merged**
