### PR TITLE
H2 2.0 backport

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-15014
https://hibernate.atlassian.net/browse/HHH-15009
https://hibernate.atlassian.net/browse/HHH-15041
https://hibernate.atlassian.net/browse/HHH-14985

### CODE REVIEW

**Comment by Sanne** [comment]
@beikov could you amend the commits comments to all relate to a JIRA code please?

**Comment by Sanne** [comment]
@famod this could interest you ^. Want to try it out?

**Comment by famod** [comment]
Thanks for the pointer @Sanne!

Could I test this as a "drop-in" replacement in Quarkus (say 2.7.0)? Meaning: Use the SNAPSHOT in quarkus-bom, build and be done with it?

**Comment by Sanne** [comment]
@famod yes that should work - this is the same version as Quarkus already uses, except with this PR.

**Comment by Sanne** [comment]
> @beikov could you amend the commits comments to all relate to a JIRA code please?

nevermind, merged as is as I needed it quickly :)

**Pull request merged**
