### PR TITLE
HHH-9939: Change configuration loading to map UserTypes

### PR DESCRIPTION
**Pull request by coladict**
Improvement proposal purpose described in detail in JIRA.

I, however will use it in our project, along with the HHH-9165 fix we've been using, that you refused with a reason that wasn't true.

### CODE REVIEW

**Comment by coladict** [comment]
Note: I cherry-picked this commit from a branch based 4.3.7 and later noticed the changes between the versions might be much for it to work. Stand by. I will be rebasing to 4.3.10 and testing locally.

**Comment by coladict** [comment]
Managed to test it within the hour. Simply forgot to come back and mention it. It still worked as before.

**Comment by coladict** [comment]
Note: I cherry-picked this commit from a branch based 4.3.7 and later noticed the changes between the versions might be much for it to work. Stand by. I will be rebasing to 4.3.10 and testing locally.

I realize it doesn't fit the style guide, but it's not a full implementation. It is merely a demonstration that it's not that hard a feature to implement.

Also, figured out my problem with positional parameters. It was because my sqlTypes() function returned {ARRAY, BIGINT}. I wouldn't have made that mistake if the docs mentioned that array's purpose. As they are right now, it's guesswork.

Still untested for JPQL. Only tested with native queries.

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by coladict** [comment]
The PR is just an example of how minor a change this feature requires. It's not meant as a final implementation.

I signed it now. Do I have to do that with every contribution? Because I have started working on an optional feature contribution for the 5.X branch.

**Comment by vladmihalcea** [comment]
Thanks. You only have to sign the CLA once.

**Comment by vladmihalcea** [comment]
I think we also need a test case for this issue too.

**Comment by vladmihalcea** [comment]
This is no longer relevant since `MetadataBuilder.applyBasicType(UserType type, String... keys)` allows you to register a `UserType` during bootstrap.

**Pull request closed without merging**
