### PR TITLE
HHH-13030 Upgrade hibernate-orm-modules WildFly version

### PR DESCRIPTION
**Pull request by fax4ever**
https://hibernate.atlassian.net/browse/HHH-13030

### CODE REVIEW

**Comment by gsmet** [comment]
@fax4ever does it solve the issue you were talking about, about jipijapa and such?

**Comment by fax4ever** [comment]
From what I've understood, with this patch we will generate WildFly modules distribution suitable just for WildFly 14, unfortunately breaking the compatibility with WildFly 13. I think that the current jipijapa module could be *potentially compatible* just with a single version of WildFly. So maybe we have to think more before to merge it. I agree with @yrodiere's idea to move the issue on 5.4.x branch, in order to keep the 5.3.x consistent with WildFly 13.

**Comment by gsmet** [comment]
Merged, thanks.

**Comment by fax4ever** [comment]
Thanks!

**Pull request closed without merging**
