### PR TITLE
HHH-4808 - SessionImpl.initializeCollection() does not release JDBC connection (if outside of a transaction)

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-4808

### CODE REVIEW

**Review by beikov — APPROVED** [review]
Looks good. Please rebase so we can rerun the tests.

**Comment by dreab8** [comment]
Thnaks @beikov , rebased it

**Comment by Sanne** [comment]
what's the status here?

**Comment by Sanne** [comment]
Nice. Should we merge it?

**Pull request merged**
