### PR TITLE
Fix for HHH-11284 require that this class is enhanced, not only its superclass(es)

### PR DESCRIPTION
**Pull request by candrews**
https://hibernate.atlassian.net/browse/HHH-11284

This pull request includes both the fix and the test showing it works.

### CODE REVIEW

**Comment by candrews** [comment]
Updated both the javassist and bytebuddy implementations and tested both.

**Comment by vladmihalcea** [comment]
@barreiro Can you take a look on this PR? Thanks

**Comment by candrews** [comment]
@barreiro @vladmihalcea can I convince someone to take a look and (hopefully) merge this?

**Comment by candrews** [comment]
@barreiro @vladmihalcea bump, please take a gander? Test case and fix are included in this PR.

**Comment by barreiro** [comment]
superseded by #1661

**Pull request closed without merging**
