### PR TITLE
HHH-3813 Automatic flush to the join table before a criteria query (4.3)

### PR DESCRIPTION
**Pull request by EtienneMiret**
Same PR as #885 but on 4.3 branch. Fixes [HHH-3813](https://hibernate.atlassian.net/browse/HHH-3813).

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by vladmihalcea** [comment]
@EtienneMiret Did you sign the [Contributor License Agreement (CLA)](https://cla.jboss.org/index.seam)?

**Comment by EtienneMiret** [comment]
Hello. Yes, I signed it a while ago. On March 5, 2015 according to jboss.org.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
