### PR TITLE
Bug fix for HHH-10549 

### PR DESCRIPTION
**Pull request by eclecticlogic**
Fix for https://hibernate.atlassian.net/browse/HHH-10549

I've changed the logic and introduced a test to verify the fix.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. First, did you sign the [CLA](https://cla.jboss.org/index.seam)?

Second, I extended the test so that we cover two cases:

. when the entity attribute type extends the db type (this case was provided by you since Money extends BigDecmal)
. when the db type extends the entity attribute type (java.sql.Date vs java.util.Date)

In the end, I'm wondering if it's worth checking against class hierarchies. I checked the JPA spec and it says nothing about matching subclasses or superclasses.

What if the match is checked like this?

```
if ( !converterDefinedType.getErasedType().equals( checkType.getErasedType() ) ) {
    return false;
}
```

I integrated your changes with my test in [this branch](https://github.com/vladmihalcea/hibernate-orm/tree/HHH-10549).

**Comment by eclecticlogic** [comment]
Yes, I did sign the CLA. 

I think equality is what Hibernate 4.3.11 checks. So equality would work. If the spec is silent, you could interpret it as room for flexibility or you could take a strict view and eschew additions. I can see scenarios where matching subclasses (via the current condition check in the patch) is beneficial (if I had business logic variants of Money but the serialization was all the same, I wouldn't want to write a converter for each derivative class).

**Comment by vladmihalcea** [comment]
I'll paste the discussion about the check:

> Steve Ebersole·2:58 PM
> @VladMihalcea no the users change is more correct
> Vlad Mihalcea·2:58 PM
> ok
> Steve Ebersole·2:59 PM
> We allow conversion of collections mapped as basic
> Vlad Mihalcea·2:59 PM
> I run his changes against my tests, and for the second one the Converter was not called at all
> Steve Ebersole·2:59 PM
> So we need to check assignability

Your changes are the right ones as described above, so I'll integrate this PR.

**Comment by vladmihalcea** [comment]
One more thing. Can you rebase from master and make sure that the identation is preserved, especially for the `AttributeConverterDescriptorImpl` class. After you make the change you can `git push --force`. With one commit is much easier to apply the fix on the 5.0 branch.

Thanks

**Comment by vladmihalcea** [comment]
Thanks, applied upstream to master.

**Pull request closed without merging**
