### PR TITLE
HHH-9777 master

### PR DESCRIPTION
**Pull request by gbadner**
Test cases and proposed fix for HHH-9777.

### CODE REVIEW

**Comment by sebersole** [comment]
I tried to look through this but I have to be honest that I find this "testing by subclass" approach incredibly difficult to follow.

**Comment by gbadner** [comment]
I used "testing by subclass" because the test functionality should be the same, regardless of whether an entity is versioned, and regardless of whether operations are cascaded to the association. 

I find it very tedious having to work with a separate test for each situation when the functionality should be the same for all cases.

**Comment by sebersole** [comment]
I am not the only one to find it tedious reading these test structures.

**Comment by gbadner** [comment]
Do I need to break these into 4 separate tests for you to look into this?

**Comment by gbadner** [comment]
@sebersole I just pushed a commit with the tests copied into the test subclasses.

**Comment by dreab8** [comment]
@sebersole @gbadner rebased and merged into master branch

**Pull request closed without merging**
