### PR TITLE
HHH-11262 - Bulk Operations attempt to create temporary tables, but user does not have permission to create table

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-11262

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@epiresdasilva @grimsa @beikov Let me know what you think.

**Comment by beikov** [comment]
Looks good but using `EXISTS` instead of the multi-column IN predicate would be even more compatible. At least SQL Server and DB2 don't support that syntax.

**Comment by vladmihalcea** [comment]
It works just fine on SQL Server. I tested it on an SQL Server Express instance.

**Comment by grimsa** [comment]
Ran the newly added test on DB2 11 z/OS (SYSIBM.VERSION = DSN11015). SQL generated can be seen below:

```sql
Hibernate: delete from XX.Engineer where (id) in (select * from ( select subselectb0_.id as id from XX.Person subselectb0_ where subselectb0_.employed=? ) HT_subselectb0_)
Hibernate: delete from XX.Doctor where (id) in (select * from ( select subselectb0_.id as id from XX.Person subselectb0_ where subselectb0_.employed=? ) HT_subselectb0_)
Hibernate: delete from XX.Person where (id) in (select * from ( select subselectb0_.id as id from XX.Person subselectb0_ where subselectb0_.employed=? ) HT_subselectb0_)
```
```sql
Hibernate: update XX.Person set name=? where (id) in (select * from ( select subselectb0_.id as id from XX.Person subselectb0_ where subselectb0_.employed=? ) HT_subselectb0_)
```

However, if I move `employed` field from `Person` to `Engineer` class, deletion test breaks. See SQL:
```sql
Hibernate: delete from XX.Engineer where (id) in (select * from ( select subselectb0_.id as id from XX.Engineer subselectb0_ inner join XX.Person subselectb0_1_ on subselectb0_.id=subselectb0_1_.id where subselectb0_.employed=? ) HT_subselectb0_)
Hibernate: delete from XX.Person where (id) in (select * from ( select subselectb0_.id as id from XX.Engineer subselectb0_ inner join XX.Person subselectb0_1_ on subselectb0_.id=subselectb0_1_.id where subselectb0_.employed=? ) HT_subselectb0_)
```
By the time the second SQL statement is executed, the relevant rows in `Engineer` table no longer exist.

I expected the IDs would be saved in memory and passed with a `WHERE <id> in (<values>)` clause, not by repeating a subselect in each query. However if going this route, you have to consider limits of values in IN clause (e.g. [1000 values for Oracle](http://stackoverflow.com/a/19003103/5082182))

Switching to `EXISTS` from multi-column IN predicate for all strategies could be another improvement, although maybe it's better to keep it separate to limit the scope of this pull request.

**Comment by vladmihalcea** [comment]
Thanks @grimsa for your feedback. Indeed this is a hairy situation. I'll check if I can see any workaround.

**Comment by beikov** [comment]
Well I had actually expected this strategy to render queries like this:

```
UPDATE/DELETE ...
WHERE id IN (
SELECT * FROM (VALUES (1),(2),...)
)
```

So the steps would involve

1. Query for the ids that are about to be update/deleted
2. Do the actual update/delete
3. Do the cascading updates/deletes based on the queried ids from 1.

**Comment by vladmihalcea** [comment]
For updates, we can just use the original query as a subselect and therefore execute a single statement instead of two. For deletes, I'm going to expand your idea into a prototype.

**Comment by beikov** [comment]
Well, not if the update affects the results of the subselect somehow.

**Comment by epiresdasilva** [comment]
The approach using ids inside the IN clause is good, but I remember when I made this solution that was a issue about the performance using this approach. When I made the solution a PostgreSQL DBA helped me and he warned me about that.

**Comment by vladmihalcea** [comment]
Closed in favor of this new [Pull Request](https://github.com/hibernate/hibernate-orm/pull/1747)

**Pull request closed without merging**
