### PR TITLE
HHH-18132 Add support for skip locked for HANA

### PR DESCRIPTION
**Pull request by fmusolino**
https://hibernate.atlassian.net/browse/HHH-18132

### CODE REVIEW

**Comment by fmusolino** [comment]
Corrected the issue with the string returned by getSkipLocked not containing the heading space and added an implementation for getForUpdateSkipLockedString in AbstractHANADialect.
Still have to fix a problem with the version detection, so leaving this in draft for now.

**Comment by fmusolino** [comment]
Hello there, 
I'm really sorry but I had some real life issues and I won't be be at my computer at least until tomorrow night, so I won't be able to make progress this weekend. I should be able to finish developing this on Monday tho.

**Comment by fmusolino** [comment]
I fixed the issue with the version detection (which was caused by a misunderstanding of mine in how HANA version numbering works). My own tests had a positive result, so I'm putting this in ready for review.

**Comment by fmusolino** [comment]
Will take a look at the failing tests as soon as I get home from work

**Comment by beikov** [comment]
Don't worry about these test failures, those are different errors. Your PR is fine. Thanks.

**Comment by fmusolino** [comment]
Thank you so much! It's actually my first time I submit a pull request for an open source project so I'm very glad this went smoothly. Thanks again.

**Comment by beikov** [comment]
Thanks for your contribution. Looking forward to your next one ;)

**Pull request merged**
