### PR TITLE
introduce @View annotation

### PR DESCRIPTION
**Pull request by gavinking**
Thought on this, everyone?

### CODE REVIEW

**Comment by gavinking** [comment]
> Looks ok to me, but how does hbm2ddl work with views?

WDYM? Isn't that the whole point of this change?

I know there's one missing thing here: I need to fix it to export views after tables, but that should also be straightforward I guess.

I mean, I *could* go to the whole effort of introducing a `View` object and a `StandardViewExporter` but it just doesn't seem worth the effort right now...

**Comment by beikov** [comment]
Sorry, hit comment too fast. I meant to ask how the validation or update process works for views.

**Comment by gavinking** [comment]
> Sorry, hit comment too fast. I meant to ask how the validation or update process works for views.

Ah good point. Maybe we should just skip em.

**Comment by sebersole** [comment]
As we discussed in chat, we can at least perform some validation of views.  Update... probably nothing

**Comment by gavinking** [comment]
Actually yeah, looking at what validator does, I think it should work perfectly fine for views.

**Pull request merged**
