### PR TITLE
add a SQLFunctionTemplate back in to ease migration

### PR DESCRIPTION
**Pull request by gavinking**
People have run into the lack of this.

### CODE REVIEW

**Comment by gavinking** [comment]
WDYT folks? Should we do this DYT?

**Comment by beikov** [comment]
Sounds ok to me, but ultimately, I think many custom registrations might have become obsolete since we have "standard" equivalents already registered. So maybe we should let people run into this to let them think about this a bit more?

**Comment by gavinking** [comment]
> Sounds ok to me, but ultimately, I think many custom registrations might have become obsolete since we have "standard" equivalents already registered. 

Yeah that's what I thought too, until stackoverflow disabused me of this notion.

**Comment by gavinking** [comment]
Looks like we're never going to do this. Or if we do one day define a simpler way to do it, it won't be the old `SQLFunctionTemplate`.

**Pull request closed without merging**
