### PR TITLE
Add original exception when selected strategy could not be loaded

### PR DESCRIPTION
**Pull request by f-lopes**
https://hibernate.atlassian.net/browse/HHH-12734
Add original exception when selected strategy could not be loaded (ClassLoadingException).

### CODE REVIEW

**Comment by gsmet** [comment]
@f-lopes nice, looks good!

Could you open a JIRA on our tracker (https://hibernate.atlassian.net/) for the Hibernate ORM project? Then the JIRA issue number should be added at the beginning of your commit message.

Thanks!

**Comment by f-lopes** [comment]
Done: https://hibernate.atlassian.net/browse/HHH-12734

Thanks!

**Comment by gsmet** [comment]
I rebased and force pushed as we had a checkstyle issue (I don't think it's related to your change but I prefer to relaunch the Travis build).

Will merge once the build is green.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request closed without merging**
