### PR TITLE
expose more AbstractEntityPersister operations to HR

### PR DESCRIPTION
**Pull request by gavinking**
Hibernate Reactive needs access to these two methods.

### CODE REVIEW

**Comment by gavinking** [comment]
I've added an additional commit, that's not *absolutely* critical, to expose some stuff in a more convenient form, and clean up the ORM code a little.

**Comment by Sanne** [comment]
thanks @gavinking , I'll merge and apply to 5.4

**Comment by gavinking** [comment]
Thanks Sanne ... hay, would you do me a favor and also take a look at #3733?

**Comment by Sanne** [comment]
Merged as https://hibernate.atlassian.net/browse/HHH-14464

**Pull request closed without merging**
