### PR TITLE
HHH-13104 - Oracle 12c / SAP Hana insert fails when entity contains only an identity-based column.

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-13104

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@Naros @breglerj Let me know what you think of this PR. Thanks.

**Comment by breglerj** [comment]
@vladmihalcea Looks good from my side.

**Comment by gsmet** [comment]
Ah, bummer, Chris had worked on it but I forgot to close the issue when I merged. Sorry about that.

In any case, your patch looks like an improvement. I'll let @Naros decide.

**Comment by gsmet** [comment]
OK, so to be clear, this patch is all about fixing the test failures we have with HANA on CI.

**Comment by Naros** [comment]
Rebased and applied to upstream master.

**Pull request closed without merging**
