### PR TITLE
HHH-9374 EntityGraph applied to subquery when using collection function

### PR DESCRIPTION
**Pull request by reda-alaoui**
Replaces https://github.com/hibernate/hibernate-orm/pull/826
We would be grateful if you merged those changes with branch 4.3 :)

### CODE REVIEW

**Comment by reda-alaoui** [comment]
Added a test case demonstrating the issue existence

**Comment by reda-alaoui** [comment]
Hi,
Can I do something to help you merge this correction?
Otherwise, what are we waiting for?

**Comment by sebersole** [comment]
Sometimes it just takes pinging us.  I scheduled it for inclusion in 5.0.3

**Comment by reda-alaoui** [comment]
Ok thanks ;)
Do you plane to backmerge the correction on current stable branch?

**Comment by sebersole** [comment]
5.0 is the stable branch

**Comment by sebersole** [comment]
Applied upstream.  Thanks!

**Comment by apinske** [comment]
Can we please have that fix in an upcoming 4.3 release?

**Pull request closed without merging**
