### PR TITLE
Fix for issue HHH-10667

### PR DESCRIPTION
**Pull request by yinzara**

### CODE REVIEW

**Comment by Naros** [comment]
@yinzara , there are a few areas in your code changes where there are missing spaces so that the code is formatted consistently.  Please take a look at `EntityType`, `EntityInstantiator`, `AbstractCompositeIdMapper`, and `ReflectionTools`.

Additionally, I would also suggest that line 454 in `EntityType` be written as follows because there isn't a need for the conditional null check that you have presented to my knowledge.
```
if ( getIdentifierType( session.getFactory() ).getReturnedClass().isInstance( value ) ) { // allow for the assumption they may try to pass the identifier instead of the entity (used by Envers)
```
Thanks!

**Comment by yinzara** [comment]
I agree with both of your comments.  I will update the pull request as suggested. Thanks!

**Comment by Naros** [comment]
@yinzara, is there a way your solution could be made without imposing an Envers-specific requirement in `EntityType` within core?

**Comment by Naros** [comment]
The contract for `EntityType#getIdentifier(Object, SessionImplemetor)` is designed to accept an entity instance and for the method to return the identifier for said entity.  This PR breaks that contract.

I'm going to take a different approach where the `MultipleIdMapper` facilitates mapping between cases where the `IdClass` holds references to the entity instance, like the `IdClassWithRelationTest`, while also supporting cases where the `IdClass` simply stores the primary key values, as in your test case.  The goal is not to change `EntityType` and handle the mappings for both cases.

**Comment by yinzara** [comment]
Naros
I agree completely with all your suggestions though will say I don't know exactly how I would implement them. I implemented the fix based on the limited knowledge I have of the Hibernate core source. If you can show me a method for fixing this without modifying core I would certainly be very appreciative.

**Comment by Naros** [comment]
@yinzara The fix is going to require modifications to the id mapping code in Envers.  I have the audit records being created but I am still working on the code needed to handle the reading back via the AuditReader.

**Comment by ggsenger** [comment]
@Naros We are hitting exactly this bug. Did you make any progress since your last comment?

**Comment by Naros** [comment]
@ggsenger I have done some work locally in a branch.  I'll try to polish that up and see if we can't get a PR pushed in the coming weeks.

**Comment by ggsenger** [comment]
@Naros I am happy to hear that and look forward to the PR.

**Comment by Ezhvtumane** [comment]
@Naros Hello, what's new with this PR?

**Pull request closed without merging**
