### PR TITLE
HHH-16421 - Add PostgresQL native any function

### PR DESCRIPTION
**Pull request by quaff**
https://hibernate.atlassian.net/browse/HHH-16421

### CODE REVIEW

**Review by gavinking — CHANGES_REQUESTED** [review]
This change is not correct, as indicated by the failing tests.

The HQL `any()` function is an aggregate function that accepts a boolean value.

It is different to the HQL/SQL `any` qualifier.

**Comment by quaff** [comment]
> This change is not correct, as indicated by the failing tests.
> 
> The HQL `any()` function is an aggregate function that accepts a boolean value.
> 
> It is different to the HQL/SQL `any` qualifier.

How to use PostgresQL native any function? It conflict with HQL any function.

**Comment by quaff** [comment]
@gavinking I've updated this PR to register `native_any` function as compromise.

**Comment by beikov** [comment]
As part of https://github.com/hibernate/hibernate-orm/discussions/5562, we can make sure that the any "function"/quantifier works with arrays, but adding a function is IMO not the way to go. You can do this in your own project if you need that right now, but in Hibernate Core, we strive for a more generally applicable solution.

**Comment by quaff** [comment]
> As part of #5562, we can make sure that the any "function"/quantifier works with arrays, but adding a function is IMO not the way to go. You can do this in your own project if you need that right now, but in Hibernate Core, we strive for a more generally applicable solution.

HQL `any` is alias of `bool_or`, which means only booleans accepted then apply logical OR operator, It's not the same thing as PostgresQL native `any`, the gap is not about arrays, but the semantic conflicts.

**Comment by beikov** [comment]
The function could have multiple meanings depending on the type of the argument, or we could also consider using the `array_contains` function i.e. in HQL `where array_contains(array, column)` renders to SQL as `where any(array) = column`.

**Comment by quaff** [comment]
> The function could have multiple meanings depending on the type of the argument, or we could also consider using the `array_contains` function i.e. in HQL `where array_contains(array, column)` renders to SQL as `where any(array) = column`.

One function have multiple meanings is not a good idea IMO, `array_contains` function is the missing piece.
FYI: PG need `any(array)` be rhs like `column = any(array)`.

**Comment by gavinking** [comment]
@beikov we can close this one, right?

**Comment by beikov** [comment]
We will add the `array_contains` function when working on https://hibernate.atlassian.net/browse/HHH-16780

**Pull request closed without merging**
