### PR TITLE
HHH-15976 Optimize row processing by pre-classifying different types of Initializer instances

### PR DESCRIPTION
**Pull request by Sanne**
https://hibernate.atlassian.net/browse/HHH-15976

[HHH-15976]: https://hibernate.atlassian.net/browse/HHH-15976?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Review by beikov — APPROVED** [review]
LGTM

**Comment by Sanne** [comment]
I'm going to improve this slightly further to reduce list allocations and iterator allocations

**Comment by Sanne** [comment]
updated to avoid iterators and resizing of ArrayList(s). cc/ @dreab8 as we paired to implement the previous version

**Comment by Sanne** [comment]
For convenience I've kept the additional changes as a separate commit

**Pull request merged**
