### PR TITLE
HHH-13458 Update Hibernate's custom IdentityMap to better match its use

### PR DESCRIPTION
**Pull request by Sanne**
A little cleanup. For master only - then we see.

 - https://hibernate.atlassian.net/browse/HHH-13458

### CODE REVIEW

**Comment by Sanne** [comment]
@dreab8 you mentioned having some thoughts on this one?

**Comment by dreab8** [comment]
@Sanne this is the one I wanted to discuss with you

**Comment by Sanne** [comment]
shoot?

**Comment by Sanne** [comment]
we merged this.

**Pull request closed without merging**
