### PR TITLE
HHH-11119 Improve performance of StringHelper.qualify() and StringHelper.unqualify()

### PR DESCRIPTION
**Pull request by dreis2211**
Fixes [HHH-11119](https://hibernate.atlassian.net/browse/HHH-11119)

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Are you sure `indexOf(char)` is faster than `indexOf(String)`? [This benchmark](http://stackoverflow.com/questions/33646781/java-performance-string-indexofchar-vs-string-indexofsingle-string) says it's the other way around.

**Comment by dreis2211** [comment]
Attached in the JIRA issue you can find the benchmark I did. So I'm pretty sure of the results I got there. As far as I can see the benchmark you shared uses @State in the **benchmark** mode, which will force all threads to use the same state, which I find a bit wrong here.

Nevertheless - even with the provided benchmark I get the expected results:

Benchmark | Mode | Cnt | Score | Error | Units
------------ | ------------- | ------------ | ------------- | ------------ | -------------
MyBenchmark.indexOfChar | avgt | 30 | 16,772 | ± 0,171 | ns/op
MyBenchmark.indexOfCharIndirect | avgt | 30 | 17,803 | ± 0,781 | ns/op
MyBenchmark.indexOfString | avgt | 30 | 19,592 | ± 0,074 | ns/op
MyBenchmark.indexOfStringIndirect | avgt | 30 | 23,250 | ± 0,074 | ns/op

**Comment by Sanne** [comment]
Very interesting to see a comparison of JMH tests. Indeed I think the ones on SO could be better, the first one is definitely flawed as it's not consuming the output of function, and I agree the shared state in the second one looks at least suspicious.

thanks @dreis2211 ! Happy to merge this.

**Comment by Sanne** [comment]
Merged. Thanks again!

**Pull request closed without merging**
