### PR TITLE
HHH-3319 make sure to include any specified where clause when fetching

### PR DESCRIPTION
**Pull request by mharray**
the size() of LazyCollectionOption.EXTRA annotated collections

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by mharray** [comment]
I have now, thanks. 

I'm also now wondering if I need to apply the same changes to the methods generateDetectRowByIndexString(), generateSelectRowByIndexString() and generateDetectRowByElementString()

**Comment by vladmihalcea** [comment]
I'm going to review it today and let you know. Thanks.

**Comment by vladmihalcea** [comment]
I tested it but there is still some work to be done in this area. For instance, if you change the collection type to be unidirectional, the `@Where` clause is not going to be applied at all. Another issue is if we remove the `@LazyCollection(LazyCollectionOption.EXTRA)`, the collection size is not properly calculated.

**Comment by vladmihalcea** [comment]
I created a new [JIRA ](https://hibernate.atlassian.net/browse/HHH-10874)issue for this one. For unidirectional collections, it requires a join as well.

**Comment by vladmihalcea** [comment]
I replaced this PR with [this one](https://github.com/hibernate/hibernate-orm/pull/1438).

**Pull request closed without merging**
