### PR TITLE
HHH-9306 With Improved formatting.

### PR DESCRIPTION
**Pull request by ptahchiev**
Here's a second try for the pull request, this time with improved formatting.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by richardfontana** [comment]
@vladmihalcea this could be integrated without requiring the CLA.

**Comment by ptahchiev** [comment]
@vladmihalcea yes, I am already a contributor.

**Comment by vladmihalcea** [comment]
[HHH-9306](https://hibernate.atlassian.net/browse/HHH-9306) is fixed now. I'm closing this PR.

**Pull request closed without merging**
