### PR TITLE
HHH-18462 Provide alternatives to deprecated org.hibernate.engine.spiMapping

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-18462

see [comments](https://github.com/hibernate/hibernate-orm/pull/8769)

[Please describe here what your change is about]

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

### CODE REVIEW

**Review by beikov — APPROVED** [review]
I like the approach. This cleans up a lot which is IMO a good thing to do for 7.0.

**Comment by gavinking** [comment]
This is fine, but @dreab8 I wonder if it might be better to pass the `Metadata` instance to methods that currently accept `Mapping`, instead of the `TypeConfiguration`. That would be sort of a "smaller" change, in that `Metadata` is currently a subtype of `Mapping`, and it avoids adding these new operations to `TypeConfiguration`, where I don't think they really belong.

`TypeConfiguration` could have a `getMetadata()` method if necessary, but I guess it's probably not needed.

WDYT?

**Comment by gavinking** [comment]
(Note that `Metadata` is implemented by both `InflightMetadataCollectorImpl` and `MetadataImpl`, so it's available at both boot and at runtime.)

**Comment by dreab8** [comment]
@gavinking  I may be wrong but i don't think it is possible, most of the time we need these information at runtime where we have no more access to the `Metadata` info

**Comment by gavinking** [comment]
> I may be wrong 

Nono, you're right and I'm wrong.

Hrrm....

**Comment by gavinking** [comment]
@dreab8 Alright, so how about this then: 

1. we simply _move_ the `Mapping` interface (perhaps renaming it `MappingContext` or whatever) into `org.hibernate.type` and undeprecate it,
2. if you guys think it's ugly that `Metadata` extends `Mapping`, no problem, it doesn't need to&mdash;any client can instantiate a `Mapping` that delegates to the `Metadata` instance (it's only three methods).

The reason I suggest this design is:

- the only reason `Mapping` really exists is to let `Type`s determine information about foreign keys, but
- those operations don't really seem to fit in with the other operations of `TypeConfiguration`, and the operations of `Type` which need a `Mapping` don't seem to have any use for them.

**Comment by beikov** [comment]
I'd be curious if we still need access to the mapping information once we get rid of using `Type` (except `BasicType`) in the runtime model. Maybe all of these methods can go away then?

**Comment by gavinking** [comment]
@beikov most likely, yes

**Comment by dreab8** [comment]
@gavinking your suggestion is to move and rename `Mapping` to `org.hibernate.type.MappingContext` and having `Metadata` and `SessionFactoryImplementor`  extending `org.hibernate.type.MappingContext`, am I right?

**Comment by gavinking** [comment]
> @gavinking your suggestion is to move and rename `Mapping` to `org.hibernate.type.MappingContext`

Yeah.

> and having `Metadata` and `SessionFactoryImplementor` extending `org.hibernate.type.MappingContext`, am I right?

That's the easiest thing, but if you don't like that option, I guess you should be able to easily change it so that it's `MetadataImplementor` which implements `MappingContext`, or some other little object e.g. an anonymous class of whatever.

**Comment by sebersole** [comment]
Closed in favor of https://github.com/hibernate/hibernate-orm/pull/8959

**Pull request closed without merging**
