### PR TITLE
HHH-14179 fix MultiLineImportExtractorTest on Windows

### PR DESCRIPTION
**Pull request by famod**
Fixes https://hibernate.atlassian.net/browse/HHH-14179

### CODE REVIEW

**Comment by beikov** [comment]
Hmm, I think we should normalize the line endings to just `\n` in the Antlr SQL generator to avoid this issue. The problem is that Git uses the platform line endings by default but can be configured to use `\n` instead.

**Comment by NathanQingyangXu** [comment]
> Hmm, I think we should normalize the line endings to just `\n` in the Antlr SQL generator to avoid this issue. The problem is that Git uses the platform line endings by default but can be configured to use `\n` instead.

IMHO, the default git config makes sense for otherwise windows user might have trouble to read the resource file per se. Also, I think we'd better keep the original sql script content as it is (without normalizing).

**Comment by beikov** [comment]
I am personally using `\n` line endings in Git on Windows and never had a problem with any tool. I think every tool handles all line ending characters already, so normalizing the line endings here should be fine. Unless someone has a reason for not doing this, I'd strongly prefer normalization.

**Comment by famod** [comment]
What about `.gitattributes`?
```
*.sql         text eol=lf
```

**Comment by NathanQingyangXu** [comment]
IDE will take care of end-of-line, but people might open the text file by
other means. I would prefer not to touch the git global setting for other
unexpected ripple effect. I think the code change in this PR seems enough.

**Comment by NathanQingyangXu** [comment]
maybe we can raise the git global end-of-line config on zulip or mail list?
but it seems a little bit overkill for this ticket, IMHO.

**Comment by famod** [comment]
I certainly won't resist if this PR is merged as is. 😉

**Comment by NathanQingyangXu** [comment]
Your pattern based git config approach is great, but I think maybe the current fix is enough? maybe add one line comment explaining the reason?

**Comment by famod** [comment]
> maybe add one line comment explaining the reason?

In the test, describing why `System.lineSeparator()` is required? Sure, why not!

**Pull request merged**
