### PR TITLE
HHH-11646 before query after query

### PR DESCRIPTION
**Pull request by RichardBradley**
Fixes https://hibernate.atlassian.net/browse/HHH-11646

See also the discussion at https://hibernate.atlassian.net/browse/HHH-10664

I have individually reviewed all 751 instances of "beforeQuery" and "afterQuery" in the codebase (at "master") and replaced all but 12 of them with "before" or "after".

The remaining instances are all method names (i.e. no "beforeQuery" or "afterQuery" words remain in any strings or comments). I'm fairly sure this is correct, but not certain!

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by dreab8** [comment]
It looks fine to me.
Thanks @RichardBradley

**Comment by RichardBradley** [comment]
> Did you sign the CLA?

I confirm that I agree to the CLA.

I visited the page https://cla.jboss.org/contributions/view_cla.seam?type=i&cid=1888808 while logged in with my "JBoss Community" account and I have read and consent to the agreement. The text said "By clicking the Sign button below", but there was no "sign" button.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks for the impressive PR.

**Comment by sebersole** [comment]
Thanks Richard!

**Pull request closed without merging**
