### PR TITLE
HHH-12906 Used the correct attribute in getAllCollectionRoles

### PR DESCRIPTION
**Pull request by fbeaufume**
Correction proposition for https://hibernate.atlassian.net/browse/HHH-12906

Issue is present in other code branches of Hibernate.

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @fbeaufume,

thanks for the PR can you please also add a test. 

Thanks

**Comment by gsmet** [comment]
@dreab8 I'm working on the test right now.

@fbeaufume good catch, thanks for the patch!

**Comment by fbeaufume** [comment]
For those who do not have the fix yet, here is a work around I use instead of "stats.getCollectionRoleNames()":
((MetamodelImplementor) sessionFactory.getMetamodel()).collectionPersisters().keySet()

**Comment by dreab8** [comment]
Hi @gsmet,
 
thanks

**Comment by gsmet** [comment]
Added tests and merged to master, 5.3 and 5.2.

**Pull request closed without merging**
