### PR TITLE
Update H2Dialect.java

### PR DESCRIPTION
**Pull request by dbcxy**
H2Dialect，h2 database column key qualifier openQuote and closeQuote " -> · .

I think he is a problem that should be repaired.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Please create a Jira issue for this. Thanks.

**Comment by gsmet** [comment]
What is the issue you are trying to solve?

Because AFAICS H2 supports both `"` and backticks and they don't have the same meaning (from what I read names in backticks are not case sensitive). I'm not convinced switching to backticks would be an improvement.

**Comment by gsmet** [comment]
Closing. Feel free to reopen with more explanation later.

**Comment by dbcxy** [comment]
But still felt that he should be treated.
I still think it's a BUG.
1 ------------------------------------------------------------
DROP TABLE IF EXISTS test
create table test
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  `select`  varchar(255)  null,
  PRIMARY KEY (id)
);

select `select` from test

result: cloumn name == SELECT
---------------
SELECT



2 ------------------------------------------------------------
DROP TABLE IF EXISTS test
create table test
(
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY,
  "select"  varchar(255)  null,
  PRIMARY KEY (id)
);

select "select" from test

result: cloumn name == "select"
---------------
"select"

**Pull request closed without merging**
