### PR TITLE
Fix Oracle test missing order by expression in select distinct

### PR DESCRIPTION
**Pull request by mbladel**

### CODE REVIEW

**Comment by gavinking** [comment]
My question about this was: what is the contract here? Are we supposed to automagically add expressions appearing in `order by` to the `select` list? i.e. is this a bug in the test, or in the criteria API? I don't know the answer to that.

**Comment by beikov** [comment]
>Are we supposed to automagically add expressions appearing in order by to the select list?

Yes, I think the translator should do that if required by the database for certain queries.

**Comment by gavinking** [comment]
> Yes, I think the translator should do that if required by the database for certain queries.

OK so then we should open an issue, because this is actually a bug.

**Comment by mbladel** [comment]
> Yes, I think the translator should do that if required by the database for certain queries.

I've ran some testing and it looks like, for `select distinct` queries, most (if not all) databases we support *require* the `order by` expressions to be included in the select clause. 

We could choose to *always* manipulate the selection items for distinct queries with a sort specification, but I also think leaving the responsibility of selecting the expressions used in the order by to the user is fine (and maybe more transparent).

**Comment by beikov** [comment]
> > Yes, I think the translator should do that if required by the database for certain queries.
> 
> I've ran some testing and it looks like, for `select distinct` queries, most (if not all) databases we support _require_ the `order by` expressions to be included in the select clause.
> 
> We could choose to _always_ manipulate the selection items for distinct queries with a sort specification, but I also think leaving the responsibility of selecting the expressions used in the order by to the user is fine (and maybe more transparent).

If most other databases have the same behavior, I agree that we shouldn't try to alter the SQL.

**Comment by quaff** [comment]
This test exists since two years ago, I'm curious why it fails recently.

**Comment by gavinking** [comment]
> This test exists since two years ago, I'm curious why it fails recently.

We already looked into this: it fails due to a change in Oracle itself.

**Comment by beikov** [comment]
Answer from Oracle:

>Some news from the dev team: previous versions allowed such a construct which is wrong. From now on 23ai has the right behavior (raises the error correctly).

>The fix will be backported to previous versions (19c, 21c).

**Pull request merged**
