### PR TITLE
HHH-10471: added ScrollableResultsStreamSupport 

### PR DESCRIPTION
**Pull request by flyingtof**
ScrollableResultsStreamSupport can be used to build a java.util.Stream upon ScrollableResults.
Added also tests to verify expected behaviour.
However, I have a doubt about the package for this code: org.hibernate.internal seems a bit odd for a support class, so I will follow any advice on this point.

### CODE REVIEW

**Comment by flyingtof** [comment]
I realized that afterwards the PR was targeting master branch, but in fact it should be 5.1 branch. Should I close the PR and create a new one?

**Comment by Naros** [comment]
I certainly wouldn't expect such a class to be exposed from within `org.hibernate.internal` as well.  Might I suggest just placing it in `org.hibernate` along side the existing `ScrollableResults` interface?

Secondly, could you make sure that the code is following the style conventions with spacing?  For example, I see a few places where you included the proper leading space to method calls, but a trailing space wasn't included before the closing parenthesis.

**Comment by sebersole** [comment]
But this requires Java 8 at runtime right?  Up to and including 5.1 only
require Java 6 for runtime.  So IMO master (5.2) is the right place to do
this, not 5.1.

For 5.2 couldn't we make this part of ScrollableResults proper?

**Comment by flyingtof** [comment]
For the target branche, I agree with you, because you're more experienced than me on Hibernate project ;-) . 
For making this code part of the ScrollableResults, it could be effectively a valuable option,but I did not know that 5.2 was planned to have Java 8 as a prerequisite. In this case, I would suggest to add the implementation of an asStream() and a asParallelStream() methods in the ScrollableResults interface, using default methods, so that implementors do not have to do the job.

**Comment by sebersole** [comment]
You could submit a PR for that :)  Master is already set to baseline on
Java 8.

**Comment by flyingtof** [comment]
Submited [PR 1350](https://github.com/hibernate/hibernate-orm/pull/1350)

**Comment by vladmihalcea** [comment]
Now, both JPA 2.2 and Hibernate 5.1 support stream methods directly at the Query level.

**Pull request closed without merging**
