### PR TITLE
HHH-18107 fixed package name

### PR DESCRIPTION
**Pull request by dk2k**
HHH-18107 fixed package name

### CODE REVIEW

**Review by gavinking — COMMENTED** [review]
This all looks correct, but I wonder if it's better to just rename the package to `org.hibernate.ucp`, since the name of the module is `hibernate-ucp`.

**Comment by dk2k** [comment]
@quaff Please take a look at this PR

**Comment by quaff** [comment]
> @quaff Please take a look at this PR

OK, I'll take a look, but I'm a contributor like you, You need official review from project member.

**Comment by beikov** [comment]
Thanks!

**Pull request merged**
