### PR TITLE
HHH-10612 Check for support of RefCursor in Java 8

### PR DESCRIPTION
**Pull request by Danny02**
The code always produced a NullpointerException with a Java8 DatabaseMetaData class, which was caught in the method. This has the effect, that the method always returns 'false' for the Java8 class  DatabaseMetaData.

### CODE REVIEW

**Comment by Danny02** [comment]
I will add a JIRA ticket in a short time

**Comment by dreab8** [comment]
Hi @Danny02 , have you signed the [CLA](https://cla.jboss.org/index.seam)?

**Comment by Danny02** [comment]
I just did, but I think it takes a while until it is accepted

**Comment by vladmihalcea** [comment]
Applied upstream on master and 5.1. Thanks for the fix.

**Pull request closed without merging**
