### PR TITLE
Update identifiers.adoc

### PR DESCRIPTION
**Pull request by macjohnny**
fixes a typo in the docs

### CODE REVIEW

**Comment by macjohnny** [comment]
one question though:
does't
https://github.com/hibernate/hibernate-orm/blame/10e36049b8fedfad0c468d711e9a279d7264666f/documentation/src/main/asciidoc/userguide/chapters/domain/identifiers.adoc#L166
contradict
https://github.com/hibernate/hibernate-orm/blame/10e36049b8fedfad0c468d711e9a279d7264666f/documentation/src/main/asciidoc/userguide/chapters/domain/identifiers.adoc#L213-L217
?

**Comment by macjohnny** [comment]
cc @Sanne

**Comment by macjohnny** [comment]
cc @gbadner @dreab8

**Comment by sebersole** [comment]
Generation as discussed in `Composite identifiers with generated properties` is not the same as identifier generators.  So no, they do not contradict.  It could maybe be worded better.

**Comment by sebersole** [comment]
Looks good.  Thanks!

**Pull request merged**
