### PR TITLE
HHH-11542 - Allow the auto-commit resolution to be configurable for RESOURCE_LOCAL transactions

### PR DESCRIPTION
**Pull request by sebersole**
https://hibernate.atlassian.net/browse/HHH-11542

### CODE REVIEW

**Comment by sebersole** [comment]
@vladmihalcea @dreab8 These are the changes I added on top of Vlad's.  I'll be pushing them upstream in a few.  Just wanted to give y'all a last chance to peek first for feedback

**Comment by sebersole** [comment]
Supersedes https://github.com/hibernate/hibernate-orm/pull/1877

**Comment by sebersole** [comment]
@dreab8 I added the default methods as we discussed

**Comment by dreab8** [comment]
rebased, fixed conflict and pushed upstream

**Pull request closed without merging**
