### PR TITLE
HHH-14554 Utilize new Validator class for Null-Checks

### PR DESCRIPTION
**Pull request by boris-unckel**
Fixes https://hibernate.atlassian.net/browse/HHH-14554

### CODE REVIEW

**Comment by boris-unckel** [comment]
@yrodiere Hello Yoann, I'm not aware on the projects structure, I hope you can help. Could you please review this PR? Or ping the component responsible lead? If I missed some contributor guideline aspect, please give me a hint, I certainly will fix that. 
Thanks in advance.

**Comment by yrodiere** [comment]
Hi,

> Could you please review this PR? Or ping the component responsible lead?

That would be @sebersole . @beikov , @gbadner or @dreab8 can probably help too.

Personally I'm not sure it's a good idea to do this in 5.5 (branch `main`) while 6.0 (branch `wip/6.0`) is being so heavily worked on, but I'll let the people doing the actual work be the judges of that.

**Comment by boris-unckel** [comment]
Thanks for your help. I can provide a wip/6.0 edition also, even if this task doubles my effort. It would save the improvement for future versions.

**Comment by boris-unckel** [comment]
@sebersole Hello Steve, could you please give this PR a chance and review/merge it? Thanks in advance.

**Pull request closed without merging**
