### PR TITLE
HHH-13724 Add initial configs for testing CockroachDB

### PR DESCRIPTION
**Pull request by rafiss**

### CODE REVIEW

**Comment by Sanne** [comment]
hi @rafiss , the changes are good, I could merge this but I'm concerned that it will consume other people: they might wonder why you're not using the postgresql driver / dependency / dialect.

I do understand this is because more changes are coming; could you add some comments in the code so that others can understand this too?

Thanks

**Comment by rafiss** [comment]
@Sanne Thank you! I agree it may be confusing. I will work on adding the CockroachDB Dialect in this PR, so that all the work is captured in this PR.

**Comment by Sanne** [comment]
hi @rafiss , I happen to have noticed you added some more commits. Let me know when you want us to have a look again? Please keep in mind we don't get notifications for further commits being added.

**Comment by rafiss** [comment]
Thanks @Sanne! We are actually still working on adding more to the Dialect, and have moved development over to our fork in the cockroachdb org for now (https://github.com/cockroachdb/hibernate-orm/tree/HHH-13724-cockroachdb-support). It's still in progress, but we definitely will ping you when we would like you to take a look again (and we may open a separate PR using that fork, and close this one).

**Comment by rafiss** [comment]
Closing this PR in favor of https://github.com/hibernate/hibernate-orm/pull/3137

**Pull request closed without merging**
