### PR TITLE
HHH-11625 - Namespace uses physicalNamingStrategy.toPhysicalCatalogName() for schema name.

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-11625

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @jvdvTechno,

did you manage to sign the CLA?

**Comment by jvdvTechno** [comment]
Nope, sorry. I tried a different browser and disabled privacy settings. I
also tried the corporate CLA and some other projects, but I do not see any
link or button other than 'back'.


Met vriendelijke groeten,


*Jeroen van der Vegt *Lead Designer

*T* +31 1 82 59 40 00
*A* Burgemeester Jamessingel 1, P.O. Box 2013, 2800 BD Gouda, The
Netherlands* | W* technolution.nl

This email is intended exclusively for the addressee(s), and may not be
passed on to, or made available for use by any person other than the
addressee(s). Technolution B.V. rules out any and every liability resulting
from any electronic transmission.

2017-04-11 13:24 GMT+02:00 Andrea Boriero <notifications@github.com>:

**Comment by dreab8** [comment]
when you load https://cla.jboss.org/index.seam do you see a continue button?

**Comment by jvdvTechno** [comment]
Jup, got it. I clicked 'individual' earlier.


Met vriendelijke groeten,


*Jeroen van der Vegt *Lead Designer

*T* +31 1 82 59 40 00
*A* Burgemeester Jamessingel 1, P.O. Box 2013, 2800 BD Gouda, The
Netherlands* | W* technolution.nl

This email is intended exclusively for the addressee(s), and may not be
passed on to, or made available for use by any person other than the
addressee(s). Technolution B.V. rules out any and every liability resulting
from any electronic transmission.

2017-04-11 16:02 GMT+02:00 Andrea Boriero <notifications@github.com>:

**Comment by Naros** [comment]
@jvdtTechno Did you sign the CLA then?

**Comment by dreab8** [comment]
@jvdvTechno it seems the CLA is signed.

Thanks a lot

**Comment by dreab8** [comment]
applied upstream

**Pull request closed without merging**
