### PR TITLE
Fix for HHH-10631

### PR DESCRIPTION
**Pull request by gmshake**
https://hibernate.atlassian.net/browse/HHH-10631

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by gmshake** [comment]
Yeah, signed two days ago, awaiting approval yet.

**Comment by vladmihalcea** [comment]
Great! Your proposal is very good, so I'll just rebase and move the test into a new method so we know why we added it in the first place. Then, I'll apply it on master. Thanks for contributing.

**Comment by vladmihalcea** [comment]
Applied upstream on master.

**Pull request closed without merging**
