### PR TITLE
HHH-9840 Allow custom key implementations for 2nd level cache regions

### PR DESCRIPTION
**Pull request by rvansa**
This is a follow up to https://github.com/hibernate/hibernate-orm/pull/974

Last commit replaced all CacheKey with Object. Because of statistics, added unwrap operation to all AccessStrategies - this is to be reviewed yet, since I had to modify SessionFactoryImplementor interface.

### CODE REVIEW

**Comment by rvansa** [comment]
Wrt type safety: can I use Java 8 type annotations to do the compile type check?

**Comment by rvansa** [comment]
@sebersole @Sanne @alexsnaps @galderz Any feedback?

**Comment by Sanne** [comment]
I can't look at it today, will try to make some time tonight or tomorrow at
latest

**Comment by galderz** [comment]
Re: Wrt type safety: can I use Java 8 type annotations to do the compile type check?

I don't know, @sebersole would be able to say.

One alternative option for additions to EntityRegionAccessStrategy...etc could be:

```
public <T> T generateCacheKey(Object id, EntityPersister persister, SessionFactoryImplementor factory, String tenantIdentifier);
public <T> T getCacheKeyId(Object cacheKey);
```

By doing that, if the caller knows what the generated cache key or generated cache key is exactly, it doesn't need to do any casting. If it doesn't know, it can simply assign to object. As far as 2LC implementations is concerned, it would not change anything, we still treat keys as opaque, but maybe for the rest of Hibernate code base it helps?

Otherwise, the rest looks fine to me.

**Comment by Sanne** [comment]
Hi Galder,
the caller (Hibernate ORM internals) doesn't use those objects so the type is not relevant for the caller.
Also, that signature would imply that the 2lc implementation needs to know what kind of key it's expected to create, while the goal is to allow implementors to have more flexibility (i.e. return whatever they see most fit from a performance perspective).

So we'll stick simply with 'Object' as it seems it's a non-problem :)

**Comment by galderz** [comment]
@Sanne Fine by me :)

**Comment by rvansa** [comment]
I have rebased the PR and added commit with checkstyle fixes (can be squashed too).

**Comment by Sanne** [comment]
merged! thanks a lot @rvansa

**Pull request closed without merging**
