### PR TITLE
HHH-12220 - Add ST_GeometryType filter to Criteria API

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-12220

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@ridoo I took your PR and refactored it a little bit. However, your test works on MySQL and PostgreSQL, but fails on Oracle and SQL Server.

So, we need that to be fixed as well in order to integrate it.

**Comment by ridoo** [comment]
@vladmihalcea thanks for cleaning up! How this is tested within the community. Is it a must to have all database types available locally?

**Comment by maesenka** [comment]
I'm currently working on this. Resolving conflicts and getting it to work on Oracle and SQL Server

**Comment by sebersole** [comment]
No longer relevant

**Pull request closed without merging**
