### PR TITLE
HHH-14982 Implement JPA Criteria extension mechanism for Spatial

### PR DESCRIPTION
**Pull request by mbladel**
https://hibernate.atlassian.net/browse/HHH-14982

### CODE REVIEW

**Comment by beikov** [comment]
Spatial tests fail for Oracle:

```
2022-11-28T16:58:49.9902342Z SpatialCriteriaTest > testGeolatteSpatialCriteriaIntersects() FAILED
2022-11-28T16:58:49.9903158Z     jakarta.persistence.PersistenceException at SpatialCriteriaTest.java:76
2022-11-28T16:58:49.9903928Z         Caused by: org.hibernate.exception.SQLGrammarException at SpatialCriteriaTest.java:76
2022-11-28T16:58:49.9904687Z             Caused by: java.sql.SQLSyntaxErrorException at SpatialCriteriaTest.java:76
2022-11-28T16:58:49.9905596Z                 Caused by: oracle.jdbc.OracleDatabaseException at SpatialCriteriaTest.java:76
2022-11-28T16:58:50.7902039Z 
2022-11-28T16:58:50.7902842Z SpatialCriteriaTest > testJtsSpatialCriteriaIntersects() FAILED
2022-11-28T16:58:50.7903600Z     jakarta.persistence.PersistenceException at SpatialCriteriaTest.java:57
2022-11-28T16:58:50.7904356Z         Caused by: org.hibernate.exception.SQLGrammarException at SpatialCriteriaTest.java:57
2022-11-28T16:58:50.7905088Z             Caused by: java.sql.SQLSyntaxErrorException at SpatialCriteriaTest.java:57
2022-11-28T16:58:50.7905708Z                 Caused by: oracle.jdbc.OracleDatabaseException at SpatialCriteriaTest.java:57
```

and for SQL Server:

```
2022-11-28T16:42:31.3234563Z 
2022-11-28T16:42:31.3235560Z SpatialCriteriaTest > testGeolatteSpatialCriteriaIntersects() FAILED
2022-11-28T16:42:31.3236500Z     jakarta.persistence.PersistenceException at SpatialCriteriaTest.java:76
2022-11-28T16:42:31.3237330Z         Caused by: org.hibernate.exception.SQLGrammarException at SpatialCriteriaTest.java:76
2022-11-28T16:42:31.3238189Z             Caused by: com.microsoft.sqlserver.jdbc.SQLServerException at SpatialCriteriaTest.java:76
2022-11-28T16:42:31.5235597Z 
2022-11-28T16:42:31.5236606Z SpatialCriteriaTest > testJtsSpatialCriteriaIntersects() FAILED
2022-11-28T16:42:31.5237410Z     jakarta.persistence.PersistenceException at SpatialCriteriaTest.java:57
2022-11-28T16:42:31.5238365Z         Caused by: org.hibernate.exception.SQLGrammarException at SpatialCriteriaTest.java:57
2022-11-28T16:42:31.5239427Z             Caused by: com.microsoft.sqlserver.jdbc.SQLServerException at SpatialCriteriaTest.java:57
```

**Comment by mbladel** [comment]
Yep I had seen those @beikov, thanks. I'll run the tests against those dbs locally and verify what causes the errors

**Review by beikov — COMMENTED** [review]
Would be great if you could copy over the java doc from the `JTSSpatialPredicates` and `GeolatteSpatialPredicates` to `SpatialCriteriaBuilder`.

I think it would be best if you try to copy the existing `org.hibernate.spatial.integration.predicates.SpatialPredicatesTest` to also cover all invocations.

**Review by beikov — APPROVED** [review]
AFAICT this looks great! Good work @mbladel 👏

**Comment by maesenka** [comment]
@mbladel Looks good! Really happy with this.

I would like to add `filter(Expression<? extends T> geometry1, T geometry2)` and `filter(Expression<? extends T> geometry1, Expression<? extends T> geometry2)` methods to the `SpatialCriteriaBuilder` interface. These predicates should make use of the faster Minimum-Bounding Rectangle style overlap functions available in many databases. The support for MBR-style functions is not available for H6, however, so we should leave that for another Jira ticket.

**Comment by mbladel** [comment]
@maesenka thanks for the feedback, big credit to you and @beikov for the idea and @dreab8 for helping too!

I've opened [HHH-15783](https://hibernate.atlassian.net/browse/HHH-15783) to remind us the possibility to add the filter methods in the future. In the meantime I'll mark this as ready for review.

**Pull request merged**
