### PR TITLE
[HHH-13911] NPE failures when executing Hibernae ORM TS against IBM JDK 8

### PR DESCRIPTION
**Pull request by lvydra**
https://hibernate.atlassian.net/browse/HHH-13911
https://issues.redhat.com/browse/JBEAP-19099

### CODE REVIEW

**Review by gavinking — CHANGES_REQUESTED** [review]
This isn't the way we usually exclude tests, and I don't think we should start doing it this way now.

**Comment by lvydra** [comment]
Hi @gavinking, thank you for the review. The idea of the changes is not to exclude affected tests, but to keep them being executed while taking care of possible null pointer exceptions. This way I got those tests running and passing on IBM JDK 8. You can also find similar approaches in other places through the tests already, though if you don't think it is a suitable solution I can try to find another one.

**Comment by gavinking** [comment]
I understand the idea. I'm saying it's the wrong way to solve the problem. It's fragile, not being specific in any way to the runtime, and a real head-scratcher to anyone who has to come along later and read that code.

**Comment by lvydra** [comment]
@gavinking Thanks for the clarification. I have looked more closely for the root cause of SessionFactory related NPE and it is caused by the failure of SessionFactory initialization in Before methods with 
`java.lang.annotation.AnnotationFormatError: java.lang.IllegalArgumentException: Wrong type at constant pool index` which is reported in
https://issues.redhat.com/browse/JBEAP-18933
https://hibernate.atlassian.net/browse/HHH-13341 
This error has been identified as a bug in JDK. 
I have tried the latest IBM JDK 8 release:
```
java version "1.8.0_421"
Java(TM) SE Runtime Environment (build 8.0.8.30 - pxa6480sr8fp30-20240801_01(SR8 FP30))
IBM J9 VM (build 2.9, JRE 1.8.0 Linux amd64-64-Bit Compressed References 20240703_73934 (JIT enabled, AOT enabled)
OpenJ9   - 177ad469d4e
OMR      - e74814c
IBM      - 3c87141)
JCL - 20240731_02 based on Oracle jdk8u421-b09
```
and it's passing. So I would suggest closing this PR and subsequent issues with this info.

**Comment by gavinking** [comment]
OK, many thanks for looking into this @lvydra, much appreciated!

**Pull request closed without merging**
