### PR TITLE
Added Altibase dialect

### PR DESCRIPTION
**Pull request by younjungpark**
I added dialect class for Altibase.
Altibase is a high performance in-memory database(http://www.altibase.com).

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by younjungpark** [comment]
Yes. I signed the CLA, but status is still in awaiting approval by project lead. 
https://cla.jboss.org/contributions/index.seam?cid=168019

cla

**Comment by richardfontana** [comment]
@vladmihalcea this need not wait for the CLA approval. @younjungpark has clearly licensed it under the appropriate license. Thanks!

**Comment by younjungpark** [comment]
Is there any problem with this pull request? If so, please let me know.
I already signed the CLA.

**Comment by vladmihalcea** [comment]
Hi @younjungpark,

You should discuss the new Dialect with @sebersole. I asked about integrating this Dialect , and this is the [response that I got](https://www.mail-archive.com/hibernate-dev%40lists.jboss.org/msg14315.html). So, basically you need to add a JIRA issue and then the Dialect is going to be integrated only if there is demand from the community for it. 

Vlad

**Comment by vladmihalcea** [comment]
I'm going to close this PR since there wasn't any request from the community for supporting Altibase.

**Pull request closed without merging**
