### PR TITLE
HHH-11260 - Apply fetch-size optimization for result streaming with MySQL

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-11260

### CODE REVIEW

**Comment by olivergierke** [comment]
Looks great, care to elaborate how this deals with the limitation the optimization introduces? The original ticket states:

> You must read all of the rows in the result set (or close it) before you can issue any other queries on the connection, or an exception will be thrown.

That means that clients *cannot* use the streamed entities to issue additional queries on the same (thread bound) connection.

```java
try (Stream<Foo> foo : query.stream()) {
  stream.forEach(it -> {
    // use "it" here to issue another query -> breaks
  }
}
```

**Comment by vladmihalcea** [comment]
That's a good point. I haven't tested that use case. I'll come back with more info.

**Comment by vladmihalcea** [comment]
I run a check, and this query works fine on H2 and MySQL:

```
try ( Stream stream = session.createQuery(
        "select me from MyEntity me" ).stream() ) {
    stream.forEach( Assert::assertNotNull );
    long count = session.createQuery( "select count(*) from MyEntity", Long.class).getSingleResult();
    assertEquals( 2, count );
}
```

So, the stream (a.k.a PreparedStatement) being open does not seem to impact other statements from executing.

**Comment by sebersole** [comment]
Personally I am -1 to this change.  There are many variables that go into whether to enable stream fetching and then determining the optimal fetch-size, and its simply not possible for Hibernate to know the various tipping points related to each query/resultset.

**Comment by vladmihalcea** [comment]
However, running this one:

```
try ( Stream stream = session.createQuery(
        "select me from MyEntity me" ).stream() ) {    
    long count = session.createQuery( "select count(*) from MyEntity", Long.class).getSingleResult();
    assertEquals( 2, count );
    stream.forEach( Assert::assertNotNull );
}
```

Throws:

```
Caused by: java.sql.SQLException: Streaming result set com.mysql.jdbc.RowDataDynamic@382775c0 is still active. No statements may be issued when any streaming result sets are open and in use on a given connection. Ensure that you have called .close() on any active streaming result sets before attempting more queries.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:868)
```

**Pull request closed without merging**
