### PR TITLE
Fix CriteriaBuidler#locate() arguments order rendering

### PR DESCRIPTION
**Pull request by dreab8**

### CODE REVIEW

**Review by beikov — COMMENTED** [review]
Great catch, but wouldn't it be better to align with the signature of the JPA spec and change the function definitions in the dialects to match that?

**Review by beikov — APPROVED** [review]
Looks great!

**Comment by dreab8** [comment]
@beikov thanks for the help!

**Comment by gavinking** [comment]
Whooaaah, wait, this change doesn't look correct to me. 

According to the JPA spec:

> The LOCATE function returns the position of a given string within a string, starting the search at a spec- ified position. It returns the first position at which the string was found as an integer. _The first argument is the string to be located; the second argument is the string to be searched;_

That is: the _first argument_ is the pattern, the second argument is the string we're searching for the pattern in.

That's what I had implemented, I believe.

**Comment by beikov** [comment]
Yeah, we are reverting this already with https://github.com/hibernate/hibernate-orm/pull/4657

IMO the spec text is a bit hard to read for a non-native speaker. I had assumed it was the other way around.

**Pull request merged**
