### PR TITLE
HHH-11838 - Id retrieving from proxy with FK leads to query execution

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-11838

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@igor-dmitriev Would you like to take a look on the issue?

**Comment by igor-dmitriev** [comment]
@vladmihalcea yeah, sure

**Comment by igor-dmitriev** [comment]
reviewed, lgtm, but I am wondering about that - https://github.com/hibernate/hibernate-orm/pull/1945#issuecomment-311001339

**Comment by vladmihalcea** [comment]
@igor-dmitriev It's probably a duplicate of this issue.

**Comment by beikov** [comment]
A test case that would probably fail is when the `getId()` method accessed other fields too. For the sake of testing, just invoke `streetName.length()` or so to verify, that such a getter should require proxy initialization i.e. it shouldn't throw a NPE, but simply load the entity when invoking `getId()`.
To determine whether the id getter or actually any method only accesses the id field, you'd have to analyze the bytecode of the method body. Determining this is probably not that easy and will only work for only the simplest methods, but that should be ok. It would be nice if the `equals` and `hashCode` methods could also avoid proxy initialization if only the id field is used.

**Comment by vladmihalcea** [comment]
@beikov That's true. The only way to fix it would be if we introduce an annotation like @SideEffects and check if the getId method is annotated with it. Usually, the getId method should be straightforward so I'm inclined to think we don't really need it.

**Comment by kullfar** [comment]
Hi, this change is breaking such case
```
@Entity
class A {
    @Column
    private String prop;

    public String getProp() {
        return prop;
    }

    public boolean isProp() {
        return prop = "some_value";
    }
}
```
Note, here is property-mapping. But two different getters. Starting from Hibernate 5.2.12 with this Pull Request applied we have now such exception at boostrapping:
Caused by: org.hibernate.MappingException: In trying to locate getter for property [prop], Class [A] defined both a `get` [public java.lang.String A.getProp()] and `is` [public boolean A.isProp()] variant

**Comment by kullfar** [comment]
I have added comment to jira
https://hibernate.atlassian.net/browse/HHH-11838

**Comment by mkurz** [comment]
You saved me some time @kullfar :smile:

**Pull request merged**
