### PR TITLE
HHH-17082 - Improve documentation of configuration settings

### PR DESCRIPTION
**Pull request by sebersole**
HHH-17082 - Improve documentation of configuration settings

https://hibernate.atlassian.net/browse/HHH-17082

### CODE REVIEW

**Comment by jonenst** [comment]
hi @sebersole 

do you have more information about this "hibernate.temp.use_jdbc_metadata_defaults"  removal ?

Also, do you plan to add a typesafe key in AvailableSettings.java ?

**Comment by sebersole** [comment]
That setting has never been "supported".

Typesafe key?

**Comment by jonenst** [comment]
By "Typesafe key" I meant a string constant like of other parameters ( https://docs.jboss.org/hibernate/orm/6.2/javadocs/constant-values.html#org.hibernate.cfg.AvailableSettings.DIALECT ) but that was a very poor choice of word indeed.

Ok so since it was documented in "Internal Properties" in https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#configurations-internal you mean it was not officially supported ? But the docs read "mainly in tools usage" so that was not immediately apparent to me.

Thank you for your time.

**Comment by sebersole** [comment]
Oh you mean a constant for `hibernate.temp.use_jdbc_metadata_defaults`...

Yeah, we never added one because its not supported for use as I said.  Supported would mean it is documented in our documentation.

**Comment by jonenst** [comment]
But it was documented until recently in  https://docs.jboss.org/hibernate/orm/6.1/userguide/html_single/Hibernate_User_Guide.html#configurations-internal 
> hibernate.temp.use_jdbc_metadata_defaults (e.g. true (default value) or false)
    This setting is used to control whether we should consult the JDBC metadata to determine certain Settings default values when the database may not be available (mainly in tools usage).

So it was supported until 6.1 ? Am I missing something ?

**Comment by gavinking** [comment]
@jonenst I mean, you just linked to a section with the following title and preamble:

> ## Internal properties
>
> The following configuration properties are used internally, and you shouldn’t probably have to configured them in your application.

And the configuration property itself has "`temp`" in its name. What do you imagine "`temp`" is supposed to mean?

Surely you _can't_ be suggesting that you weren't adequately warned that you should not rely on this thing?

Madre mia.

**Comment by jonenst** [comment]
hi @gavinking , thank you for your comment and your time. I'm just trying to help the liquibase-hibernate project used as a development tool using the liquibase diff feature. Not trying to play on words or anything. Sorry if that's what it looks like.

I think there is real confusion about the "hibernate.temp.use_jdbc_metadata_defaults". Actually I just found this comment which is explicit so that's good
https://github.com/quarkusio/quarkus/pull/15954#pullrequestreview-618541170
> A disclaimer to anyone else reading this PR, though: hibernate.temp.use_jdbc_metadata_defaults is not part of the Hibernate ORM API and may disappear completely at any moment. The name contains temp precisely because it's a temporary workaround and we will hopefully remove it at some point (without warning).

But almost comically for every explicit comment from the maintainers there are comment from (confused I guess) users like https://github.com/quarkusio/quarkus/pull/17509#issuecomment-851519160 or https://github.com/quarkusio/quarkus/pull/17509#issuecomment-851442964
> If you look at the hibernate-orm project on github you will see that this property is not so temporary like that... it has been in the code for many years and removing support for it will cause a lot of problems for many projects around the world. Thinking about it, why shouldn't we support it?

> The property hibernate.temp.use_jdbc_metadata_defaults may have the 'temp' word in it's name but it has been part of hibernate code for many years.

Just removing the docs entirely without removing the feature may lead to even more confusion in the short term?

Removing the feature may break valid use cases. I guess that's OK if there are alternatives but if users have been using the feature in these valid use cases maybe it means that it was the best thing to do, or that there were no acceptable alternative?

Note: the quarkus use case from these multiple issues (at least https://github.com/quarkusio/quarkus/pull/15954 https://github.com/quarkusio/quarkus/issues/16927 https://github.com/quarkusio/quarkus/issues/15888  https://github.com/quarkusio/quarkus/pull/17509  is very different (running a server) from the liquibase diff use case (using a development tool). It's good for them that for their use case (slow performance at startup during validation) they were able to do something better than use_jdbc_metadata_defaults=false to fix the performance problem, but it looks like this is not the case for liquibase diff ?

**Comment by jonenst** [comment]
To give you some context, liquibase-hibernate has been using "hibernate.temp.use_jdbc_metadata_defaults=false" for years (since 2016) in some cases  (see https://github.com/liquibase/liquibase-hibernate/commit/4926f5208c44b4e71912a397ecd629ee594e4a7d#diff-c3b9cea6fc1c6d243905f8eeb6cace031f04a0cfcf5801becccff63ce5701fa7R60 ).
I assume it was forgotten in the other cases, which lead to users seeing a one line message `[WARNING] HHH000342: Could not obtain connection to query metadata : The application must supply JDBC connections` until 2022. After 2022, this one line message was turned into a 80lines stacktrace, which confuses the users because they think it's a real error when in fact it's the same thing as the almost invisble warning from before, just more verbose. So one solution is just to restore the verbosity of this warning like before 2022. Another solution is to properly fix the warning. So I recently made a PR to add "hibernate.temp.use_jdbc_metadata_defaults=false" everywhere (see https://github.com/liquibase/liquibase-hibernate/pull/616/files ) but I'm trying to decide wheter it's the right thing to do or not (is the property going to continue to exist ? Is it unsupported for running server but supported for using dev tools ?)

my use case (and I think it's the general use case) for liquibase-hibernate is for developpers to automatically generate incremental liquibase changesets using `liquibase diff` after they modified jpa annotations in some java source code. So liquibase creates a hibernate "connection" to some kind of fake/virtual database representing the current state of the java source code for this purpose. There's no jdbc connection.


Do you have any advice or insight about what should be done for this use case ? Thanks.

Again, thank you for your time

**Comment by gavinking** [comment]
There's already a plan to remove this setting entirely, and make sure that its effect can be reproduced on a more granular level by setting explicit properties (e.g. for the database name and version). We have to make sure that this provides what Quarkus needs, and by extension, what other people who're currently using this unsupported setting need.

**Comment by sebersole** [comment]
> There's already a plan ... setting explicit properties (e.g. for the database name and version)

To be clear, that already exists.  The talk we are having next week is about others that may need them.  I'm not convinced any are actually missing (forQuarkus use anyway).  

@jonenst Do you happen to know the specific requirements of the liquibase-hibernate team around this?  Like what are they trying to accomplish by setting it?  If not, have them reach out (though here is not really a great place, Zulip would be ideal or a "Proposal" issue in our Jira)

**Comment by jonenst** [comment]
In the meantime https://github.com/liquibase/liquibase-hibernate/pull/616 was merged, I guess I'll revisit this when hibernate removes the setting. I'm sorry I can't be of more help :( I tried to contact the original authors but it wasn't very successful, you can see the discussion here: https://github.com/liquibase/liquibase-hibernate/commit/4926f5208c44b4e71912a397ecd629ee594e4a7d#r129500368 

Again I'm sorry, I don't know more than what I said earlier in my long message.. liquibase-hibernate creates a hibernate "connection" to some kind of fake/virtual database representing the current state of the java source code for the purpose of generating the liquibase changesets that make the database schema match the source code annotations (a diff to apply to the database schema in other words).
 
I'll forward your invitation to the liquibase team, thanks !

Regarding quarkus, I was mentionning it only because I think it showed the confusion around "hibernate.temp.use_jdbc_metadata_defaults" and in their case from what I understand they correctly identified that using this parameter was not the proper fix (instead they fixed the actual performance problems). I'm personally not using quarkus, only liquibase-hibernate.

**Comment by jonenst** [comment]
Hi, https://github.com/liquibase/liquibase-hibernate/pull/616 was reverted , so users are back to seeing the exception.... here's what happens for users. Do you know what liquibase-hibernate should use instead of `hibernate.temp.use_jdbc_metadata_defaults=false`
Thanks in advance,

- go to https://start.spring.io/ (currently 3.1.5), use maven, add the following
  - Spring Web
  - Spring Data JPA SQL
  - Liquibase Migration SQL
  - H2 Database

- init the liquibase file in src/main/resources/db/changelog/db.changelog-master.xml  with an empty changelog
```xml
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
</databaseChangeLog>
```

- add the liquibase-hibernate6 dependency in pom.xml (sorry this is kind of verbose, not sure if it can be reduced or not):
```xml
<plugin>
    <groupId>org.liquibase</groupId>
    <artifactId>liquibase-maven-plugin</artifactId>
    <version>4.20.0</version>
    <!-- Liquibase dependencies-->
    <dependencies>
        <dependency>
          <groupId>org.liquibase.ext</groupId>
          <artifactId>liquibase-hibernate6</artifactId>
          <version>${liquibase.version}</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-data-jpa</artifactId>
            <version>3.1.2</version>
        </dependency>
        <dependency>
            <groupId>jakarta.validation</groupId>
            <artifactId>jakarta.validation-api</artifactId>
            <version>3.0.2</version>
        </dependency>
        <dependency>
          <groupId>org.hibernate</groupId>
          <artifactId>hibernate-validator</artifactId>
          <version>8.0.1.Final</version>
        </dependency>
        <dependency>
          <groupId>jakarta.el</groupId>
          <artifactId>jakarta.el-api</artifactId>
          <version>5.0.1</version>
        </dependency>
    </dependencies>
</plugin>
```

- run this liquibase diff command:
```bash
$ mvn \
-Dliquibase.url=jdbc:h2:./target/dummyDB \
-Dliquibase.changeLogFile=src/main/resources/db/changelog/db.changelog-master.xml \
-Dliquibase.referenceUrl=hibernate:spring:com.example.demo?dialect=org.hibernate.dialect.H2Dialect \
-Dliquibase.referenceDriver=liquibase.ext.hibernate.database.connection.HibernateDriver \
-Dliquibase.diffChangeLogFile=src/main/resources/db/changelog/db.changelog-master.xml \
clean test-compile liquibase:update liquibase:diff
```
[INFO] No changes found, nothing to do
src/main/resources/db/changelog/db.changelog-master.xml is not modified

- add an entity to DemoApplication.java
```java
@jakarta.persistence.Entity
class DemoEntity {

    @jakarta.persistence.Id
    private java.util.UUID id;

    @jakarta.persistence.Column
    private long age;

}
```
- run this liquibase diff command:
- observe the changed file:
$ cat src/main/resources/db/changelog/db.changelog-master.xml
```xml
    <changeSet author="harperjon (generated)" id="1700149184550-1">
        <createTable tableName="DemoEntity">
            <column name="id" type="BINARY(16)">
                <constraints nullable="false" primaryKey="true" primaryKeyName="DemoEntityPK"/>
            </column>
            <column name="age" type="BIGINT"/>
        </createTable>
    </changeSet>
```
- rerun, observe no changes in the file
- change age in java to private int
- rerun, observe the changes:
$ cat src/main/resources/db/changelog/db.changelog-master.xml
```xml
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-3.5.xsd">
    <changeSet author="harperjon (generated)" id="1700149184550-1">
        <createTable tableName="DemoEntity">
            <column name="id" type="BINARY(16)">
                <constraints nullable="false" primaryKey="true" primaryKeyName="DemoEntityPK"/>
            </column>
            <column name="age" type="BIGINT"/>
        </createTable>
    </changeSet>
    <changeSet author="harperjon (generated)" id="1700149379729-1">
        <modifyDataType columnName="age" newDataType="int" tableName="DemoEntity"/>
    </changeSet>
</databaseChangeLog>
```

The exception is shown at each command
```
java.lang.UnsupportedOperationException: The application must supply JDBC connections
    at org.hibernate.engine.jdbc.connections.internal.UserSuppliedConnectionProviderImpl.getConnection (UserSuppliedConnectionProviderImpl.java:44)
    at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator$ConnectionProviderJdbcConnectionAccess.obtainConnection (JdbcEnvironmentInitiator.java:284)
  ...
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:407)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:348)
```

Note: Predictably, if you don't set `?dialect=org.hibernate.dialect.H2Dialect` in the referenceUrl liquibase-hibernate url, you get
```
[ERROR] org.hibernate.service.spi.ServiceException: Unable to create requested service [org.hibernate.engine.jdbc.env.spi.JdbcEnvironment]: Unable to determine Dialect without JDBC metadata (please set 'javax.persistence.jdbc.url', 'hibernate.connection.url', or 'hibernate.dialect')
```
and it doesn't work at all. But if you set it everything works.

**Comment by sebersole** [comment]
Thanks for the reply @jonenst, that helps.  In your use case, setting the database name and version should be enough?

* `jakarta.persistence.database-product-name`
* one of
  ** `jakarta.persistence.database-product-version`
  ** `jakarta.persistence.database-major-version` and optionally `jakarta.persistence.database-minor-version`.

See also the discussion at https://hibernate.atlassian.net/browse/HHH-17425

**Comment by jonenst** [comment]
Hi @sebersole , so you mean to say that in a future version of hibernate (do you know which one ?), the following code in main  

https://github.com/hibernate/hibernate-orm/blob/55431f292b1f2b2cd2178d03a7599125e7672490/hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java#L106
https://github.com/hibernate/hibernate-orm/blob/55431f292b1f2b2cd2178d03a7599125e7672490/hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java#L116 )

will be inverted to prioritize explicitconfiguration when enough properties are specified ( see https://github.com/hibernate/hibernate-orm/blob/55431f292b1f2b2cd2178d03a7599125e7672490/hibernate-core/src/main/java/org/hibernate/engine/jdbc/env/internal/JdbcEnvironmentInitiator.java#L385-L386 )

Until this future version is published, we should use `hibernate.temp.use_jdbc_metadata_defaults=false` ? (liquibase-hibernate shades a recent hibernate version, currently https://github.com/liquibase/liquibase-hibernate/blob/a4f21c028ee50736c320ab528b277bc432c077b6/pom.xml#L54 )

**Comment by sebersole** [comment]
I guess I had assumed they were integrating with Hibernate via the SchemaTooling SPI which does not need connections (though the built-in tools will when asked to physically export to the database, ofc).

> so you mean to say that .. will be inverted to prioritize explicitconfiguration when enough properties are specified?

Yes, that's exactly what I mean.  Once we know the full compliment of values from Quarkus and other use-cases.

**Pull request merged**
