### PR TITLE
HHH-18337 - SequenceStyleGenerator not respecting physical naming strategy

### PR DESCRIPTION
**Pull request by mbladel**
Also change a failing test so it doesn't pass `null` as creation context

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

https://hibernate.atlassian.net/browse/HHH-18337

### CODE REVIEW

**Review by beikov — COMMENTED** [review]
Can we maybe skip calling `create` instead of calling it with `null`? Is that method maybe called multiple times?

**Comment by mbladel** [comment]
> Can we maybe skip calling `create` instead of calling it with `null`?

Sure I guess, it's only used in `SequenceStyleGenerator` and meant to provide the context so that's fair.

> Is that method maybe called multiple times?

Not in this case or any that I know of.

**Comment by gavinking** [comment]
> > Can we maybe skip calling `create` instead of calling it with `null`?
> 
> Sure I guess, it's only used in `SequenceStyleGenerator` and meant to provide the context so that's fair.

Wait, why is it getting called with a null context?? 

> Can we maybe skip calling create instead of calling it with `null`? 

I don't understand. That seems to be contrary to the contract of `createIdentifierGenerator()`.

**Comment by mbladel** [comment]
> Wait, why is it getting called with a null context??

Because of the [default implementation](https://github.com/hibernate/hibernate-orm/blob/b09b27c7d69712480f304fbb6e543d91bf06598a/hibernate-core/src/main/java/org/hibernate/id/factory/IdentifierGeneratorFactory.java#L89) in `IdentifierGeneratorFactory`.

**Comment by gavinking** [comment]
Didn't I mark that as deprecated?

**Comment by gavinking** [comment]
> Didn't I mark that as deprecated?

I did.

**Comment by gavinking** [comment]
Well, I suppose it's OK then.

**Review by beikov — APPROVED** [review]

**Review by gavinking — APPROVED** [review]

**Pull request merged**
