### PR TITLE
EntityManager#find() throws IllegalArgumentException for wrong arguments

### PR DESCRIPTION
**Pull request by dreab8**

### CODE REVIEW

**Review by beikov — COMMENTED** [review]
Shouldn't the test use jpa compliance instead? Maybe we should update the tck-runner with the new compliance settings.

**Comment by sebersole** [comment]
> Shouldn't the test use jpa compliance instead? Maybe we should update the tck-runner with the new compliance settings.

JPA bootstrapping enables compliance by default.  `@Jpa` uses JPA boostrapping (its the main difference ultimately with `@SessionFactory`)

**Review by sebersole — COMMENTED** [review]
I'm not sure that `CoercionException` should be wrapped as `IllegalArgumentException` in all cases, but I also cannot think of specific cases where `CoercionException` would be thrown that should not be.

**Comment by dreab8** [comment]
My bad it seems the `hibernate.jpa.compliance.load_by_id` is not set to `true` when using `@Jpa` this is causing the issue, so @beikov we have to set this value for the tck-runner

**Comment by sebersole** [comment]
`@Jpa` should really just set the top-level value.

**Pull request closed without merging**
