### PR TITLE
[HHH-16979] Fix subclasses being skipped on generated joins.

### PR DESCRIPTION
**Pull request by The-Huginn**
https://hibernate.atlassian.net/browse/HHH-16979

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @The-Huginn , 

thanks for the PR, can you please add also a test case?
Thanks

**Comment by beikov** [comment]
There is a test failure with this change. See https://github.com/hibernate/hibernate-orm/pull/7087/checks?check_run_id=15394366846

**Review by beikov — APPROVED** [review]
Looks good to me. Could you please also switch to `getModel()` in `SqmPluralValuedSimplePath` for the sake of uniformity?

**Comment by beikov** [comment]
Thanks!

**Pull request merged**
