### PR TITLE
HHH-13741 - LOG_SLOW_QUERY parameter doesn't always log SQL

### PR DESCRIPTION
**Pull request by sebersole**
https://hibernate.atlassian.net/browse/HHH-13741

Simpler (and I'd argue more correct) alternative  to https://github.com/hibernate/hibernate-orm/pull/5088

### CODE REVIEW

**Review by beikov — APPROVED** [review]

**Comment by herisson-88** [comment]
Thanks a lot, will improove performance logging of hundreds of ours projets !

**Comment by ozkanpakdil** [comment]
hey @beikov and @herisson-88
Can please you tell when will this be published ? or which version we will see it ?
Thank you

**Comment by herisson-88** [comment]
https://hibernate.atlassian.net/browse/HHH-13741 it's mark next 6.3 I see.

**Comment by sebersole** [comment]
You can see from the linked Jira it will be in 6.3.  I am working on the 6.3 release as we speak.

**Comment by hojongs** [comment]
Hello,
Are there any plans to apply this change in the 5.6.x release?

**Comment by LukaszSkowronek** [comment]
Hello, i am using version 6.3.1.Final and it seems like it is not working. I still get Slow query took 130 milliseconds [HikariProxyPreparedStatement@1859255735 wrapping oracle.jdbc.driver.OraclePreparedStatementWrapper@1aaab222]

**Comment by beikov** [comment]
Hey, there was something missing unfortunately, but I fixed it now: https://github.com/hibernate/hibernate-orm/commit/f84c2b56dbcd1a883d3e9f8ceb647bb1e3e935bc
You'll have to wait until 6.3.2, but it would be nice if you could try the snapshot and confirm it works for you.

**Comment by LukaszSkowronek** [comment]
Hey, i will check. Do you know when it will be released?

**Comment by beikov** [comment]
6.3.1 was just released a few days ago, so it might take a few more days until we cut a 6.3.2 release.

**Comment by mpela81** [comment]
Hi, When is 6.3.2 release expected to be out? We'd love getting this fix.

**Comment by beikov** [comment]
By the end of this week or at the start of the next week.

**Comment by mpela81** [comment]
> By the end of this week or at the start of the next week.

Hi, It looks like the plan has changed for 6.3.2 including this fix? Thanks

**Comment by mpela81** [comment]
Hi @beikov, @sebersole, 
Can a 6.3.x stable release be done, including this fix please?
We are undergoing a migration to 6.3.x and require LOG_SLOW_QUERY to work. Waiting for 6.4.x to get this fixed would be quite problematic (and creating our own 6.3.x fork is not really a good option either).

Thanks!

**Pull request merged**
