### PR TITLE
HHH-14725 Fix reset handling on BlobProxy

### PR DESCRIPTION
**Pull request by Naros**
https://hibernate.atlassian.net/browse/HHH-14725

### CODE REVIEW

**Review by beikov — APPROVED** [review]
LGTM

**Comment by beikov** [comment]
How about wrapping an `InputStream` to make sure closing only happens at the end of a TX when we do resource cleanup in Hibernate? If we see that the `InputStream` doesn't support marking, we could read the contents first into a `byte[]` and then serve data from there, or alternatively, write into a temporary file and serve data from that.

**Comment by oppahansi** [comment]
Is there maybe an ETA when this will be merged?
We have encountered an issue with exactly this problem recently.

Our workaround for now is:
We `refresh` the `Entity` with the `Blob` using the `EntityManager`  **before** operating on the `Blob's InputStream/Bytes`.

**Comment by Naros** [comment]
> How about wrapping an `InputStream` to make sure closing only happens at the end of a TX when we do resource cleanup in Hibernate? If we see that the `InputStream` doesn't support marking, we could read the contents first into a `byte[]` and then serve data from there, or alternatively, write into a temporary file and serve data from that.

Hi @beikov do we have another proxy type that does this so I can use that as a reference guide?

**Comment by beikov** [comment]
It's fine, let's merge this as soon as tests succeed.

**Comment by beikov** [comment]
The test seems to fail @Naros

**Comment by gavinking** [comment]
@Naros What is the status of this one?

**Comment by dreab8** [comment]
Closing this one in favour of https://github.com/hibernate/hibernate-orm/pull/9402 where I rebased the PR and fixed a problem with the test.

**Pull request closed without merging**
