### PR TITLE
HHH-11262 CTE based bulk id update/delete strategy

### PR DESCRIPTION
**Pull request by epiresdasilva**
This PR fixes the [HHH-11262](https://hibernate.atlassian.net/browse/HHH-11262) as requested in the issue [5](https://github.com/epiresdasilva/cte-multi-table-bulk-id-stategy/issues/5) of my solution for multi table bulk id strategy based in CTE.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks. I'm going to review and integrate it after I come back from my vacation. Merry Christmas!

**Comment by grimsa** [comment]
Funny to find some activity related to multi table bulk ID strategies as I just wrote a [blog post](http://g.rimsa.lt/hibernate-multi-table-bulk-id-strategies/) about them :)

In any case, I tried the cte-multi-table-bulk-id-stategy project a few months ago and it generated SQL that failed for both H2 and DB2 databases.

@epiresdasilva , does this PR contain any changes in the implementation compared to what's in cte-multi-table-bulk-id-stategy repo? I'm unable to test it as part of the Hibernate project (could not set up local build yet), but if the implementation is the same, I could do that with the original repo.

**Comment by epiresdasilva** [comment]
@vladmihalcea Thanks. Merry Christmas for you and for your family.

@grimsa This PR have no changes compared to what's in my repo. The development was made exclusivelly for PostgreSQL, but it will be awesome to support H2 and DB2 databases. Thanks and Merry Christmas! :)

**Comment by beikov** [comment]
You can wrap any update or delete statement in a `select from old table(update/delete)` or `select from new table(update/delete)` so using a CTE shouldn't be a problem. Finally using the VALUES clause with parameters requires a cast to the target type of the parameter in case of a usage like you propose.

**Comment by vladmihalcea** [comment]
@epiresdasilva Thanks for the Pull Request. BTW, did you sign the [CLA](https://cla.jboss.org/)?

**Comment by vladmihalcea** [comment]
I played with this PR and I made it work for SQL Server and PostgreSQL, but it's quite difficult for Oracle since it does not support DML in WITH clause, nor it does support VALUES lists.

**Comment by epiresdasilva** [comment]
@vladmihalcea yes, I've signed the CLA. Unfortunately i've no skills with Oracle DB. I need to study about Oracle to understand how it works with CTE.

**Comment by vladmihalcea** [comment]
Thanks. I've done some progress on this issue. I'm now thinking of isolating the CTE logic so that we can use this approach for PostgreSQL and SQL Server, while allowing for some different approach for Oracle or DB2, as suggested by @grimsa and @beikov

**Comment by vladmihalcea** [comment]
I've done a lot of refactoring to the original commit and now it's working on both PostgreSQL and SQL Server. It's not done yet, but you can try to take a look at the [current implementation](https://github.com/vladmihalcea/hibernate-orm/tree/HHH-11262).

**Comment by vladmihalcea** [comment]
Superseded by [this Pull Request](https://github.com/hibernate/hibernate-orm/pull/1733). Please review it.

**Comment by gansai** [comment]
Hi @vladmihalcea , I had a look at the article; [Bulk-id strategies when you can’t use temporary tables](http://in.relation.to/2017/02/01/non-temporary-table-bulk-id-strategies/)  . It looks like for Oracle, (where the user does not have privelege to create temporary tables) we could adopt InlineIdsInClauseBulkIdStrategy or InlineIdsOrClauseBulkIdStrategy. I just wanted to comment here, regarding InlineIdsInClauseBulkIdStrategy, in the context of some handling by Oracle.

Suppose we have more than 1000 expressions in the IN clause, Oracle does not accept it, if we are sending > 1000 (single items) . It has an error code: ORA-01795. Please refer to http://docs.oracle.com/cd/B10501_01/server.920/a96525/e1500.htm#1001274

So, users could definitely, safely adopt InlineIdsOrClauseBulkIdStrategy strategy to avoid this error during application runtime, depending on the scenario.

Moreover, the limit of 1000 applies to sets of single items: (x) IN ((1), (2), (3), ...)
There is no limit if the sets contain two or more items: (x, 0) IN ((1,0), (2,0), (3,0), ...), as is the case provided as example in the [article](http://in.relation.to/2017/02/01/non-temporary-table-bulk-id-strategies/).

**Pull request closed without merging**
