### PR TITLE
HHH-13209 : Allow for ServiceRegistry "suspend and restore"

### PR DESCRIPTION
**Pull request by Sanne**
- https://hibernate.atlassian.net/browse/HHH-13209

### CODE REVIEW

**Comment by gsmet** [comment]
@Sanne there is one test failure on Travis:
```
org.hibernate.test.schemaupdate.IdentifierHelperTest > testAutoQuotingDisabled FAILED
    java.lang.UnsupportedOperationException at IdentifierHelperTest.java:39
```
can you reproduce it?

**Comment by Sanne** [comment]
I've not seen that before, I'll run it again..

**Comment by Sanne** [comment]
nope, can't reproduce.

**Comment by Sanne** [comment]
oh actually I can. Seems unstable :(

**Comment by Sanne** [comment]
So it was just a regular bug. Not sure why I couldn't reproduce it initially, probably my fault.

In short: my code was expecting to be able to "clear()" the config map. That actually works fine in practice, except this single test manages to somehow sneak an immutable map as configuration.

That's actually highlighting that I need to take into account the map could have been user-injected by some weird framework over our SPI, so adjusted my patch to deal with it - even if none of our code would hit that today.

**Comment by gsmet** [comment]
Rebased and merged.

**Pull request closed without merging**
