### PR TITLE
HHH-17960: Fix proper default session type for JD repositories even in Quarkus

### PR DESCRIPTION
**Pull request by FroMage**
And tests

As discussed at https://hibernate.atlassian.net/browse/HHH-17960

### CODE REVIEW

**Comment by FroMage** [comment]
The error in CI is:

```
java.lang.AssertionError: There was a compilation error during annotation processing:
/home/runner/work/hibernate-orm/hibernate-orm/tooling/metamodel-generator/target/classes/processor-generated-test-classes/org/hibernate/processor/test/hrPanache/_PanacheBook.java:6: error: cannot access jakarta.data.metamodel.SortableAttribute
import jakarta.data.metamodel.SortableAttribute;
                             ^
  bad class file: /home/runner/.gradle/caches/modules-2/files-2.1/jakarta.data/jakarta.data-api/1.0.0-SNAPSHOT/cca3668e18597f5e1c8544c68ef0dccc470bae33/jakarta.data-api-1.0.0-SNAPSHOT.jar(/jakarta/data/metamodel/SortableAttribute.class)
    class file has wrong version 61.0, should be 55.0
    Please remove or make sure it appears in the correct subdirectory of the classpath.
```

I'm frankly not sure why this happens, apparently 55 is Java 11, and 61 is Java 17. But that JD dep is also used from the jpamodelgen tests, so I'm not sure why it works there and not here.

@gavinking any idea?

**Comment by gavinking** [comment]
We are not currently running the JD tests on the CI, I'm just running them by hand.

**Comment by FroMage** [comment]
Oh, damn.

**Comment by gavinking** [comment]
I guess it would be nice to set up a CI job for these things which require newer Javas.

**Comment by FroMage** [comment]
So… I suppose the best thing to do is to disable those tests in this PR?

**Comment by gavinking** [comment]
Well, we could tie them to the `jakartaDataTest` task, and run them manually.

**Comment by FroMage** [comment]
> Well, we could tie them to the jakartaDataTest task, and run them manually.

That seems like a good idea. Let me try.

**Comment by FroMage** [comment]
@gavinking there's a pipeline job stuck, but otherwise, test seems to pass.

Any chance you can review?

**Review by gavinking — APPROVED** [review]
LGTM

**Comment by FroMage** [comment]
Thanks.

**Comment by FroMage** [comment]
I've no ide about the CI issues, can we get this merged?

**Comment by FroMage** [comment]
Approuved, but wasn't merged :) Thanks!

**Pull request merged**
