### PR TITLE
HHH-18858 array fields and static metamodel

### PR DESCRIPTION
**Pull request by cigaly**
Jira issue [HHH-18858](https://hibernate.atlassian.net/browse/HHH-18858)

When array property is annotated with one of `@ManyToMany`, `@OneToMany`, or `@ElementCollection`, field in generated meta model class should be of type `jakarta.persistence.metamodel.ListAttribute`, currently is `jakarta.persistence.metamodel.SingularAttribute`. 

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

[HHH-18858]: https://hibernate.atlassian.net/browse/HHH-18858?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

https://hibernate.atlassian.net/browse/HHH-18868

### CODE REVIEW

**Comment by gavinking** [comment]
@cigaly Is this actually for [HHH-18868](https://hibernate.atlassian.net/browse/HHH-18868)?

**Comment by cigaly** [comment]
No, for [HHH-18868](https://hibernate.atlassian.net/browse/HHH-18868) is PR [#9353](https://github.com/hibernate/hibernate-orm/pull/9353)

This one is creating `ListAttribute` field for array properties annotated as `OneToMany`, `ManyToOne`, or `ElementCollection`. If I not forgot something, other array properties should be treated as `SingleAttribute`

**Comment by gavinking** [comment]
I think it might be the same problem.

**Review by gavinking — APPROVED** [review]
LGTM, can I merge it if the tests succeed?

**Comment by cigaly** [comment]
Yes, of course

**Comment by cigaly** [comment]
> @cigaly Is this actually for [HHH-18868](https://hibernate.atlassian.net/browse/HHH-18868)?

Sorry, my mistake. I've just seen that comments in commits are mentioning wrong issue :-(

**Pull request merged**
