### PR TITLE
HHH-18056 Support for JPA 32 table options

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-18056

### CODE REVIEW

**Comment by sebersole** [comment]
I missed `TableGenerator#options` in the original list on the Jira.  Do you think you could do that here?  

Or should we create a new Jira?  We'll need to account for `SequenceGenerator#options` as well, so could group those that way instead.

**Comment by dreab8** [comment]
@sebersole  let's create another Jira, already started working on Column options :P

**Comment by sebersole** [comment]
Here you go :)

https://hibernate.atlassian.net/browse/HHH-18096

**Comment by dreab8** [comment]
Thanks

**Pull request merged**
