### PR TITLE
Only cast LONG32 to text on PG to avoid type comparison related issues

### PR DESCRIPTION
**Pull request by beikov**
----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

### CODE REVIEW

**Comment by gavinking** [comment]
@beikov Why are you proposing to do this?

**Comment by gavinking** [comment]
Remember that we have defined `LONG32VARCHAR` to mean:

> In principle, the type must accommodate strings of length 2147483647, though this is not an absolutely hard requirement, since such large strings do not occur in practice.

But PostgreSQL looks like it has the following upper limit for `varchar`:

```
hreact=# create table V(V varchar(2147483647));
ERROR:  length for type varchar cannot exceed 10485760
LINE 1: create table V(V varchar(2147483647));
                         ^
```

which is about two orders of magnitude too small.

**Comment by beikov** [comment]
See the discussion on Zulip for details: https://hibernate.zulipchat.com/#narrow/channel/132094-hibernate-orm-dev/topic/PostgreSQL.20text.20vs.2E.20varchar.20weirdness

**Comment by beikov** [comment]
For context, blindly casting to `text`, which is what we are doing right now, leads to issues like this one: https://ci.hibernate.org/view/ORM/job/hibernate-orm-nightly/job/main/687/testReport/junit/org.hibernate.orm.test.function.array/ArrayContainsTest/Build___postgresql_12___Test___testNodeBuilderArray_SessionFactoryScope_/

Performance problems like https://hibernate.atlassian.net/browse/HHH-18780 are also possible.

**Pull request merged**
