### PR TITLE
rename isEmptyOrWhitespace() to isBlank()

### PR DESCRIPTION
**Pull request by gavinking**
And use it in more places.

### CODE REVIEW

**Comment by Sanne** [comment]
Nice cleanup, thanks!
I see the "isBlank" method could also be implemented in a more efficient way.. I'll do that right away, create a JIRA and apply.

**Comment by Sanne** [comment]
https://hibernate.atlassian.net/browse/HHH-14190

**Comment by Sanne** [comment]
merged and backported

**Comment by sebersole** [comment]
Nice!

**Pull request closed without merging**
