### PR TITLE
move the code for generating check constraints to Dialect

### PR DESCRIPTION
**Pull request by gavinking**
cc @beikov this is what I meant.

I think that's cleaner, and potentially more flexible, even if perhaps not entirely necessary.

### CODE REVIEW

**Comment by beikov** [comment]
Not sure what is wrong there, but there are many test failures.

**Comment by gavinking** [comment]
OK, lemme see what's going on.

**Comment by gavinking** [comment]
> OK, lemme see what's going on.

Yeah, OK, no need to panic. What's going on is I'm a retard, as usual.

**Comment by gavinking** [comment]
@beikov I believe it's fixed, despite the remaining failure on Derby.

**Comment by beikov** [comment]
Looking good now! No new failures when comparing to wip/6.0 so this is fine. I think though, that the `getCheckCondition` method should be part of `org.hibernate.type.BasicType` to allow generating check conditions for other types as well. I understand your argument about SQL generation shouldn't be part of the `JavaTypeDescriptor` so what do you think about moving this to `org.hibernate.type.BasicType`?

**Comment by gavinking** [comment]
> Looking good now! No new failures when comparing to wip/6.0 so this is fine. I think though, that the `getCheckCondition` method should be part of `org.hibernate.type.BasicType` to allow generating check conditions for other types as well. I understand your argument about SQL generation shouldn't be part of the `JavaTypeDescriptor` so what do you think about moving this to `org.hibernate.type.BasicType`?

I *think* I thought it should go on `JavaTypeDescriptor` so that other types like user types could take advantage of this, but it's possible I got that wrong.

WDYT, @sebersole?

**Comment by sebersole** [comment]
> > the `getCheckCondition` method should be part of `org.hibernate.type.BasicType` to allow generating check conditions for other types as well. I understand your argument about SQL generation shouldn't be part of the `JavaTypeDescriptor` so what do you think about moving this to `org.hibernate.type.BasicType`?
> 
> I _think_ I thought it should go on `JavaTypeDescriptor` so that other types like user types could take advantage of this, but it's possible I got that wrong.
> 
> WDYT, @sebersole?

I'd have to pull this locally and see exactly what is calling this functionality but my initial thought was adding this as part of `BasicValuedModelPart`.  It would have access to all of the needed information.  And unless I miss something, we'd only ever issue constraints for basic types so that ModelPart would be proper.

What that does under the covers is the question.  I'd be inclined to make the method on `BasicValuedModelPart` default since it seems like the determination here would be "static".  I like it on Dialect if this varies by Dialect; but IIUC that's not what happens ATM and I cannot think if a case where it would.

Personally I'd have that delegate to JTD

**Comment by gavinking** [comment]
I'm going to merge this. After rethinking it I decided that it really is cleaner and more flexible to move the part of this that renders SQL to the `Dialect` hierarchy.

I had a look at `ModelPart` and couldn't quite figure out what Steve is thinking about that. @sebersole if you want to move the contract from the descriptor to `ModelPart`, it's best you do it.

**Pull request merged**
