### PR TITLE
improve use of generics in CollectionSemantics hierarchy

### PR DESCRIPTION
**Pull request by gavinking**

### CODE REVIEW

**Comment by sebersole** [comment]
Looks good.  However the test failures seem to be real.

**Comment by gavinking** [comment]
> Looks good. However the test failures seem to be real.

Ah, OK, I didn't realize. Strange that adding generics could break *behavior*.

**Comment by gavinking** [comment]
> Looks good. However the test failures seem to be real.

@sebersole are you *sure* about that? I've just run the tests on five databases locally, and all fine, no failures.

**Comment by gavinking** [comment]
I've rebased and repushed. Let's see if that helps.

**Comment by beikov** [comment]
The tests that are failing are also failing on wip/6.0 already, so the change does not introduce test failures.

**Comment by beikov** [comment]
Thanks!

**Comment by gavinking** [comment]
> Thanks!

Thank *you*.

**Comment by sebersole** [comment]
I'm sure the tests failed on GH Actions, yes.

But I've seen false failures on the "other" database jobs on a few of my
PRs as well.  I think those jobs may just be unreliable

**Pull request merged**
