### PR TITLE
HHH-12413 Don't clear parameterListBindingMap to allow subsequent callers of expandListValuedParameters to receive the expanded query string

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-12413

### CODE REVIEW

**Comment by gsmet** [comment]
Hi @beikov ,

The commit message refers to HHH-12143 whereas it should be HHH-12413.

**Comment by gsmet** [comment]
Is it possible to add a test so that we don't break this behavior later on?

**Comment by beikov** [comment]
Yeah of course, I just wanted to create the PR to see if the tests still run through.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
