### PR TITLE
HHH-12675 - Respect inverse property for JoinedSubclassEntityPersister

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
See: https://hibernate.atlassian.net/browse/HHH-12675

### CODE REVIEW

**Comment by gsmet** [comment]
Hi @JWGmeligMeyling ,

Looks very nice from a quick look. Could you separate the new tests instead of inserting it into an existing one? It will be easier to debug and see what's going on with your test case.

Thanks!

**Comment by JWGmeligMeyling** [comment]
@gsmet 

I can do that, but a complete separation of the test cases would require the introduction of new `Pool` and `SwimmingPool` test entities which would be completely duplicates of the existing ones besides the `inverse` property. This is because one superclass has to map the secondary table with `inverse=true`, and the other one with `inverse=false`. Keeping the mappings as is (both mappings on one superclass type) would not really simplify debugging, as the EntityPersister will still have to deal with both cases separately anyway. I can duplicate the test domain classes as well, but this will result in 3 mostly duplicate classes.

So do you just want to split out a separate test case operating on the same entities (which has to be an entity with two secondary tables, one of which is mapped as inverse table)? This would make the test easier to read, show where its different from the other scenario, and provide better test adequacy (as the non-inverse and inverse test pass or fail separately). But I am not sure how this would be easier to debug, as the EntityPersister still has to handle both cases. Or should I just copy and alter all related test classes instead?

**Comment by JWGmeligMeyling** [comment]
I've updated the PR so that it has two separate test cases.

**Comment by JWGmeligMeyling** [comment]
@gsmet  Any reason why this is removed from the milestone? Are there any blockers?

My current workaround requires no-op queries to be executed for every update, which is really quite nasty:

```java
@org.hibernate.annotations.Table(appliesTo = "joined_view", inverse = true,
    // Ugly, but required, as inverse=true is broken... See: https://hibernate.atlassian.net/browse/HHH-12675
    sqlInsert = @SQLInsert(sql = "INSERT INTO noop_table (id) SELECT ? WHERE FALSE", check = ResultCheckStyle.NONE ),
    sqlUpdate = @SQLUpdate(sql = "UPDATE noop_table SET id = ? WHERE FALSE", check = ResultCheckStyle.NONE),
    sqlDelete = @SQLDelete(sql = "DELETE FROM noop_table WHERE discount_code_id = ? AND FALSE", check = ResultCheckStyle.NONE)
)
```

**Comment by gsmet** [comment]
@JWGmeligMeyling the rationale was mostly that I found it a bit too risky for a corner case which was probably an issue all along. It seems more reasonable to commit it to 5.4.

**Comment by JWGmeligMeyling** [comment]
@gsmet Any plans to commit this to 5.4 now masters on 5.4?

**Pull request merged**
