### PR TITLE
HHH-12776 NullPointerException when executing native query. 

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-12776

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@dreab8 I reverted your change in the `AbstractSharedSessionContract` class and the test still passes successfully.

**Comment by dreab8** [comment]
Hi @vladmihalcea 
discussing with @gsmet we discovered my test does not really reproduce the issue.
First the Entity have to be Audited, and then depends on the order 
`getFactory().getMetamodel().getEntities().stream()` returns the values.

**Comment by vladmihalcea** [comment]
@dreab8 @gsmet I see there's a provided test case in the Jira issue. Should we try to use that one instead?

**Comment by dreab8** [comment]
here the test https://github.com/hibernate/hibernate-orm/pull/2398
but as I said it may not fail due to the order `getFactory().getMetamodel().getEntities().stream()` returns the entities

**Comment by dreab8** [comment]
rejected

**Pull request closed without merging**
