### PR TITLE
Hhh 17675

### PR DESCRIPTION
**Pull request by HJK181**
https://hibernate.atlassian.net/browse/HHH-17675

### CODE REVIEW

**Comment by HJK181** [comment]
> Please drop the commit with the formatting changes and also add the changes you have done in `H2Dialect` to `H2LegacyDialect`.

I'll do. But may I ask why I should drop the code format? I mean the file does not correspond to the code formatting rules mentioned in the repositories readme and as its modified with this change, why not fix that as well?

**Comment by HJK181** [comment]
@beikov did the requested changes.

**Comment by beikov** [comment]
>I'll do. But may I ask why I should drop the code format? I mean the file does not correspond to the code formatting rules mentioned in the repository's readme and as it's modified with this change, why not fix that as well?

There are many files that don't comply 100% to our code formatting rules and sometimes the rules produce hard to read code, but changing the code formatting in PRs that try to address a specific issue is kind of noisy to me. If you want to apply formatting rules to files, I'd like to ask you to please do that in a separate PR. There have been attempts to do that in the past though, and we rejected it because such changes usually cause more trouble for backporting than they help for reading code. Not sure what the best way forward is. I'll bring that up in our team meeting next week and let you know what we decided.

**Comment by HJK181** [comment]
Should new files be formatted with that formatting rules? If not, I'd vote to adjust the readme as it is some effort for the first contribution to setup the IDE accordingly.

**Comment by beikov** [comment]
>Should new files be formatted with that formatting rules? If not, I'd vote to adjust the readme as it is some effort for the first contribution to setup the IDE accordingly.

Yes, new files should be formatted properly as well as the code fragments that you add.

**Pull request merged**
