### PR TITLE
Changes for Rx

### PR DESCRIPTION
**Pull request by DavideD**
If possible, I woud like to relax some of the scopes of some methods so that I can reuse them or override them in Hibernate ORM. Let me know if I need to create a JIRA for this.

Thanks

### CODE REVIEW

**Comment by Sanne** [comment]
changes look ok. I'd prefer to have a JIRA to refer to as that's a rule in ORM.

Could you create one, mention it in the commits as per the usual template, and then merge? Thanks!

**Comment by DavideD** [comment]
Jira: https://hibernate.atlassian.net/browse/HHH-13878

**Comment by sebersole** [comment]
We need to be careful about these changes.  Making them accessible may help
y'all, but it also means some user and is going to use it as well

**Comment by Sanne** [comment]
agreed @sebersole - we're trying to be careful generically speaking.  Specifically, these changes aren't very concerning, would you agree?

**Pull request merged**
