### PR TITLE
HHH-16815 fix issues with query plan cache and ascending()/descending()

### PR DESCRIPTION
**Pull request by gavinking**

### CODE REVIEW

**Comment by sebersole** [comment]
Not a fan of having to expand `SqmInterpretationKey` to support this.  @Sanne do you see any performance impact here?

**Comment by Sanne** [comment]
I wouldn't expect this to have a significant performance impact; I might be wrong as I don't think we have a benchmark covering for this but I'm not overly concerned - especially as it seems necessary.

Obviously there's _some_ hit; mainly that such keys consume a fair bit of memory with all these fields, and the new one being a List doesn't help; I'll give it a shot to compact the list representation.

**Comment by beikov** [comment]
We could make queries that add orderings non-cacheable by returning `CRITERIA_HQL_STRING` in the `public String getQueryString()` and call `setQueryPlanCacheable(false)` in the `addOrdering` method. The query string wouldn't match the "new" query after adding an order anyway, so it seems better to return a different string there.

Is there a real benefit of these methods though now that we merged https://github.com/hibernate/hibernate-orm/pull/6895 ? It seems much more reasonable to me to add orderings based on that API instead of trying to mutate a query object.

```java
session.createQuery( 
  session.getCriteriaBuilder().createQuery( "...", resultClass )
    .addOrder( session.getCriteriaBuilder().asc( field ) )
);
```

is IMO not that much worse than

```java
session.createQuery( "...", resultClass )
    .ascending( field)
);
```

Also, converting to the criteria representation in a dedicated step also allows more flexibility.

**Comment by Sanne** [comment]
I followed up to HHH-16815 here, not directly related with Gavin's changes but it will improve efficiency a little
 - https://github.com/hibernate/hibernate-orm/pull/6902

**Comment by gavinking** [comment]
> Is there a real benefit of these methods though now that we merged https://github.com/hibernate/hibernate-orm/pull/6895 ?

Oh, absolutely. The code to mutate a criteria object and add an order is unfortunately quite a lot uglier than you might expect. You have to find the `Root` object you're looking for, typecast it to the type you know it is, call `get()`, etc. Very verbose and not typesafe.

**Comment by gavinking** [comment]
(Note that your code is wrong, since `CriteriaBuilder().asc()` accepts an `Expression`, not a `SingularAttribute`.)

**Comment by beikov** [comment]
Indeed, I made a mistake in the example code, but like we discussed on Zulip, I think it's better to add these utility methods to e.g. `JpaCriteriaQuery`, so this could look like:

```java
session.createQuery( 
  session.getCriteriaBuilder().createQuery( "...", resultClass )
    .ascending( field )
);
```

**Pull request merged**
