### PR TITLE
HHH-14697 TimePropertyTest fails on MySQL 8.0 with a ComparisonFailure

### PR DESCRIPTION
**Pull request by RanabirChakraborty**
Issue: https://hibernate.atlassian.net/browse/HHH-14697

JBEAP Issue: https://issues.redhat.com/browse/JBEAP-22070

### CODE REVIEW

**Comment by RanabirChakraborty** [comment]
@gbadner can you check this once :)

**Comment by RanabirChakraborty** [comment]
@gbadner Can you pleas take a look :)

**Comment by gbadner** [comment]
@RanabirChakraborty, thanks for the new PR. I'm confused though, because I am not seeing a failure running the test without your fix using `MySQL8Dialect`.

**Comment by gbadner** [comment]
The issue reproduces using mysql-connector-java-8.0.23, but does not reproduce using the current version used as a dependency in 5.3.

I will merge this issue, since mysql-connector-java-8.0.23 is used for testing EAP 7.4. I will deal with upgrading the mysql-connector-java dependency in a separate jira.

**Pull request merged**
