### PR TITLE
HHH-17172 Fix to retrieve matching session factory either by uuid or name during serialization/deserialization

### PR DESCRIPTION
**Pull request by marceloverdijk**
https://hibernate.atlassian.net/browse/HHH-17172

### CODE REVIEW

**Comment by Sanne** [comment]
Hi @marceloverdijk , yes I'll backport it to 6.2 as well :+1:

**Comment by Sanne** [comment]
It's merged. I've pushed it manually as I added some more comments in the tests.

Many thanks! Will backport in a moment as well.

**Comment by marceloverdijk** [comment]
@Sanne do you have an idea when the next (6.2.10) release will be?
I checked https://hibernate.atlassian.net/projects/HHH?selectedItem=com.atlassian.jira.jira-projects-plugin%3Arelease-page but couldn't find any more details, except all issues in 6.1.10 are closed/resolved.

**Comment by Sanne** [comment]
yes sorry this isn't (yet) communicated well. We used to do periodic releases of maintained branches, every two weeks.
But w'ere in the mid of setting up a new experiment: to release a micro of any maintained branches every single day (provided there are changes). The idea is that if there's a bugfix, someone is waiting for it (so any delay is a waste for at least someone) - and if we merged it, it was already verified so it's not like we'd be reckless.
But we're setting up this system, as it needs to be fully automated, which implies a bunch of additional integration tests need to also become fully automated.

It's also a big shift in mindset, perhaps an experiment, but hopefully it explains why JIRA no longer has an expected date.

For 6.2.10 I have to check if we're ready to trigger the first one.. but even if not, I'd like to see it out very soon: either today or beginning of next week.

**Comment by marceloverdijk** [comment]
Thx for the feedback @Sanne 
We can upgrade next week 👍

But the Micro release experiment sounds very interesting. Like you said, once verified and merged a new release should be good (especially as it is fully automated).

**Pull request closed without merging**
