### PR TITLE
HHH-14537 : EntityNotFoundException thrown when non-existing association with @NotFound(IGNORE) mapped has proxy in PersistenceContext

### PR DESCRIPTION
**Pull request by gbadner**
https://hibernate.atlassian.net/browse/HHH-14537

### CODE REVIEW

**Review by sebersole — CHANGES_REQUESTED** [review]
I think the change is reasonable.  

I would prefer to see a "better" test though - the whole double mapping of the FK obfuscates what is being tested.  Just use the (non-existent) Employee proxy as the association when saving the Task.

**Comment by gbadner** [comment]
> I would prefer to see a "better" test though - the whole double mapping of the FK obfuscates what is being tested. Just use the (non-existent) Employee proxy as the association when saving the Task.

@sebersole, I'm not sure what you mean about "the whole double mapping of the FK".

I added `Employee#location` (without `@NotFound(IGNORE)` and test, `#testExistingProxyWithNonExistingAssociation`, to be able to test that when `Task#employee` exists, but `Task#employee#location` FK refers to a non-existing entity, that `EntityNotFoundException` is properly thrown.

Did you mean about making `Task#employee` non-insertable and non-updatable? I thought that was an interesting way to still have access to the ID for the non-existing entity.

**Comment by sebersole** [comment]
```

					// just use proxy to the non-existing Employee#2 to create Task#2
					final Employee emp2 = session.load( Employee.class, 2 );
					final Task task2 = new Task( 2, emp2 );
					session.persist( task2 );
```

**Comment by gbadner** [comment]
@sebersole, I just pushed a commit that removes {{Task#employeeId}} and just assigns the proxy to {{Task#employee}} as you suggested.

I also added a couple of tests that show that lazy associations with the non-existing entity are assigned a proxy, and eager associations with the same non-existing entity mapped {{@NotFound(IGNORE)}} is set to {{null}}.

@sebersole, please confirm if this is the outcome you were expecting.

**Review by sebersole — APPROVED** [review]
Looks good to me +1

**Comment by sebersole** [comment]
Do you know the reason for the failure on the Oracle job?

**Comment by beikov** [comment]
>Do you know the reason for the failure on the Oracle job?

Like I was writing in the Zulip topic about GH actions and Oracle EE, this is due to the use of Oracle XE. I will try to deactivate this test for Oracle XE tomorrow and see how I can improve the CI situation as a whole.

**Comment by gbadner** [comment]
Thanks for the review @sebersole!

**Pull request merged**
