### PR TITLE
HHH-9331 Aggregate functions for subqueries not working for 4.3 branch

### PR DESCRIPTION
**Pull request by Alex-Diez**
I've fix SUM, AVG, MIN, MAX aggregation function
but still can't fix COUNT(subquery) case

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by Alex-Diez** [comment]
Yes

**Comment by vladmihalcea** [comment]
Thanks. I updated the issue to Ready for Review.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
