### PR TITLE
HHH-9291

### PR DESCRIPTION
**Pull request by moriarty-s3a**
This changes the order of the parameter values for a with clause as they are added to the query so that they match the order of the joins that were previously generated.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
This looks like a merge commit
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by moriarty-s3a** [comment]
I submitted this PR while at a former employer, so I need to get permission.  I'll see what I can do.

**Comment by moriarty-s3a** [comment]
I received the necessary permissions and signed the CLA, but it is awaiting official approval by said employer.

**Comment by vladmihalcea** [comment]
@moriarty-s3a What happened to this PR that it now has 250+ commits. Can you isolate the changes? Otherwise, we will have to close it.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
