### PR TITLE
HHH-10728 - NullPointerException when using CriteriaBuilder.selectCase with CriteriaBuilder.equal

### PR DESCRIPTION
**Pull request by DrBAXA**
Related to https://hibernate.atlassian.net/browse/HHH-10728.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by DrBAXA** [comment]
Sure, I have signed it.

**Comment by vladmihalcea** [comment]
Thanks

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
