### PR TITLE
HHH-5274 HQL-Insert with Select and Sub-Select fails for 4.3 branch

### PR DESCRIPTION
**Pull request by Alex-Diez**

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by Alex-Diez** [comment]
Yes

**Comment by vladmihalcea** [comment]
Thanks. I updated the issue to Ready for Review.

**Comment by vladmihalcea** [comment]
The issue is fixed now, thanks for your contribution.

**Pull request closed without merging**
