### PR TITLE
HHH-13944 HQL/JPQL size() does not work (anymore) with nested expression

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-13944

### CODE REVIEW

**Review by beikov — APPROVED** [review]

**Comment by quaff** [comment]
Which commit breaks it?

**Comment by gbadner** [comment]
Has anyone looked into the failures? I looked briefly and here is what I see:

* derby is failing due to some classloading issue;

* mariadb and mssql are failing due to connection issues;

* DB2 fails due to com.ibm.db2.jcc.am.SqlFeatureNotSupportedException for tests that involve NClob;

* oracle has tests failing for several reasons:

2020-12-04T11:42:22.9165779Z org.hibernate.jpa.test.graphs.FetchGraphTest > testCollectionEntityGraph FAILED
2020-12-04T11:42:22.9168003Z     javax.persistence.PersistenceException at EntityManagerFactoryBuilderImpl.java:1336
2020-12-04T11:42:22.9169864Z         Caused by: org.hibernate.MappingException at IdentityColumnSupportImpl.java:45
2020-12-04T12:13:02.5174275Z org.hibernate.jpa.test.lock.LockTest > testQueryTimeout FAILED
2020-12-04T12:13:02.5176054Z     org.junit.runners.model.TestTimedOutException at LockTest.java:996
2020-12-04T12:43:02.5164689Z 
2020-12-04T12:43:02.5166205Z org.hibernate.jpa.test.lock.LockTest > testQueryTimeoutEMProps FAILED
2020-12-04T12:43:02.5167869Z     org.junit.runners.model.TestTimedOutException at LockTest.java:1089
2020-12-04T12:43:03.4164238Z 
2020-12-04T12:43:03.4166048Z org.hibernate.jpa.test.lock.LockTest > testUpdateWithPessimisticReadLockSkipLocked FAILED
2020-12-04T12:43:03.4167733Z     javax.persistence.RollbackException at LockTest.java:270
2020-12-04T12:43:03.4169004Z         Caused by: javax.persistence.PersistenceException at LockTest.java:270
2020-12-04T12:43:03.4170695Z             Caused by: org.hibernate.exception.ConstraintViolationException at LockTest.java:270
2020-12-04T12:43:03.4172558Z                 Caused by: java.sql.SQLIntegrityConstraintViolationException at LockTest.java:270
2020-12-04T12:43:03.4174090Z                     Caused by: oracle.jdbc.OracleDatabaseException at LockTest.java:270
2020-12-04T12:43:04.1164393Z 
2020-12-04T12:43:04.1168832Z org.hibernate.jpa.test.lock.LockTest > testUpdateWithPessimisticReadLockWithoutNoWait FAILED
2020-12-04T12:43:04.1171086Z     javax.persistence.RollbackException at LockTest.java:315
2020-12-04T12:43:04.1172590Z         Caused by: javax.persistence.PersistenceException at LockTest.java:315
2020-12-04T12:43:04.1174497Z             Caused by: org.hibernate.exception.ConstraintViolationException at LockTest.java:315
2020-12-04T12:43:04.1176609Z                 Caused by: java.sql.SQLIntegrityConstraintViolationException at LockTest.java:315
2020-12-04T12:43:04.1178405Z                     Caused by: oracle.jdbc.OracleDatabaseException at LockTest.java:315
2020-12-04T12:43:04.1179291Z 
2020-12-04T12:43:07.3166119Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testConfiguration FAILED
2020-12-04T12:43:07.3168633Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:391
2020-12-04T12:43:07.3171004Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:391
2020-12-04T12:43:07.3173059Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:391
2020-12-04T12:43:09.1163823Z 
2020-12-04T12:43:09.1166305Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testDefaultPar FAILED
2020-12-04T12:43:09.1168851Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:81
2020-12-04T12:43:09.1171698Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:81
2020-12-04T12:43:09.1173704Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:81
2020-12-04T12:43:10.9163615Z 
2020-12-04T12:43:10.9166944Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testDefaultParForPersistence_1_0 FAILED
2020-12-04T12:43:10.9169587Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:115
2020-12-04T12:43:10.9171761Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:115
2020-12-04T12:43:10.9173655Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:115
2020-12-04T12:43:12.6163610Z 
2020-12-04T12:43:12.6166119Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testExcludeHbmPar FAILED
2020-12-04T12:43:12.6168520Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:212
2020-12-04T12:43:12.6170769Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:212
2020-12-04T12:43:12.6172722Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:212
2020-12-04T12:43:14.9163231Z 
2020-12-04T12:43:14.9165495Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testExplodedPar FAILED
2020-12-04T12:43:14.9167770Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:189
2020-12-04T12:43:14.9170061Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:189
2020-12-04T12:43:14.9172511Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:189
2020-12-04T12:43:16.7183613Z 
2020-12-04T12:43:16.7228034Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testExtendedEntityManager FAILED
2020-12-04T12:43:16.7263706Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:341
2020-12-04T12:43:16.7266071Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:341
2020-12-04T12:43:16.7267969Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:341
2020-12-04T12:43:18.5163728Z 
2020-12-04T12:43:18.5166186Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testExternalJar FAILED
2020-12-04T12:43:18.5168506Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:445
2020-12-04T12:43:18.5170704Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:445
2020-12-04T12:43:18.5172586Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:445
2020-12-04T12:43:20.2164054Z 
2020-12-04T12:43:20.2166552Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testListeners FAILED
2020-12-04T12:43:20.2169507Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:321
2020-12-04T12:43:20.2173411Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:321
2020-12-04T12:43:20.2175703Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:321
2020-12-04T12:43:22.0163576Z 
2020-12-04T12:43:22.0166047Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testListenersDefaultPar FAILED
2020-12-04T12:43:22.0168551Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:151
2020-12-04T12:43:22.0170932Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:151
2020-12-04T12:43:22.0172891Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:151
2020-12-04T12:43:23.7163899Z 
2020-12-04T12:43:23.7166560Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testORMFileOnMainAndExplicitJars FAILED
2020-12-04T12:43:23.7169201Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:501
2020-12-04T12:43:23.7171507Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:501
2020-12-04T12:43:23.7173547Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:501
2020-12-04T12:43:25.5217191Z 
2020-12-04T12:43:25.5219518Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testOverriddenPar FAILED
2020-12-04T12:43:25.5221727Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:302
2020-12-04T12:43:25.5229640Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:302
2020-12-04T12:43:25.5235840Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:302
2020-12-04T12:43:27.2163448Z 
2020-12-04T12:43:27.2245419Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testRelativeJarReferences FAILED
2020-12-04T12:43:27.2248653Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:471
2020-12-04T12:43:27.2250904Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:471
2020-12-04T12:43:27.2263536Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:471
2020-12-04T12:43:29.0163842Z 
2020-12-04T12:43:29.0165501Z org.hibernate.jpa.test.packaging.PackagedEntityManagerTest > testSpacePar FAILED
2020-12-04T12:43:29.0167628Z     org.hibernate.service.spi.ServiceException at PackagedEntityManagerTest.java:278
2020-12-04T12:43:29.0169891Z         Caused by: org.hibernate.exception.GenericJDBCException at PackagedEntityManagerTest.java:278
2020-12-04T12:43:29.0171633Z             Caused by: java.sql.SQLException at PackagedEntityManagerTest.java:278
2020-12-04T12:43:31.4163757Z 
2020-12-04T12:43:31.4165711Z org.hibernate.jpa.test.packaging.ScannerTest > testCustomScanner FAILED
2020-12-04T12:43:31.4167580Z     org.hibernate.service.spi.ServiceException at ScannerTest.java:90
2020-12-04T12:43:31.4169606Z         Caused by: org.hibernate.exception.GenericJDBCException at ScannerTest.java:90
2020-12-04T12:43:31.4171380Z             Caused by: java.sql.SQLException at ScannerTest.java:90
2020-12-04T12:45:04.9165423Z org.hibernate.query.criteria.internal.hhh11877.HHH111877Test > testNoExceptionThrow FAILED
2020-12-04T12:45:04.9168468Z     javax.persistence.PersistenceException at EntityManagerFactoryBuilderImpl.java:1336
2020-12-04T12:45:04.9170500Z         Caused by: org.hibernate.MappingException at IdentityColumnSupportImpl.java:45
2020-12-04T12:45:05.6163874Z 
2020-12-04T12:45:06.3166258Z org.hibernate.query.criteria.internal.hhh14197.HHH14197Test > testValidSQLGenerated FAILED
2020-12-04T12:45:06.3168332Z     javax.persistence.PersistenceException at EntityManagerFactoryBuilderImpl.java:1336
2020-12-04T12:45:06.3170518Z         Caused by: org.hibernate.MappingException at IdentityColumnSupportImpl.java:45
2020-12-04T12:45:07.0165493Z 
2020-12-04T13:37:06.1165779Z org.hibernate.test.batch.BatchOptimisticLockingTest > testBatchAndOptimisticLocking FAILED
2020-12-04T13:37:06.1168022Z     org.junit.ComparisonFailure at BatchOptimisticLockingTest.java:105
2020-12-04T13:37:06.8163897Z 
2020-12-04T13:37:14.8202188Z org.hibernate.test.annotations.manytoone.NotNullManyToOneTest > classMethod FAILED
2020-12-04T13:37:14.8212130Z     org.hibernate.testing.junit4.CallbackException at TestClassMetadata.java:208
2020-12-04T13:37:14.8264479Z         Caused by: org.hibernate.MappingException at IdentityColumnSupportImpl.java:45
2020-12-04T13:37:16.1164788Z 
2020-12-04T13:39:21.6167075Z org.hibernate.test.annotations.selectbeforeupdate.UpdateDetachedTest > testUpdateDetachedWithAttachedPersistentSet FAILED
2020-12-04T13:39:21.6170158Z     javax.persistence.PersistenceException at UpdateDetachedTest.java:152
2020-12-04T13:39:21.6172484Z         Caused by: org.hibernate.exception.SQLGrammarException at UpdateDetachedTest.java:152
2020-12-04T13:39:21.6175604Z             Caused by: java.sql.SQLSyntaxErrorException at UpdateDetachedTest.java:152
2020-12-04T13:39:21.6177405Z                 Caused by: oracle.jdbc.OracleDatabaseException at UpdateDetachedTest.java:152
2020-12-04T13:39:22.4163703Z 
2020-12-04T14:06:18.7168093Z org.hibernate.test.bytecode.enhancement.lazy.proxy.inlinedirtychecking.DirtyCheckPrivateUnMappedCollectionTest > classMethod FAILED
2020-12-04T14:06:18.7172633Z     org.hibernate.testing.junit4.CallbackException at TestClassMetadata.java:208
2020-12-04T14:06:18.7174679Z         Caused by: org.hibernate.MappingException at IdentityColumnSupportImpl.java:45
2020-12-04T14:06:19.8164179Z 
2020-12-04T14:07:07.7166304Z org.hibernate.test.bytecode.enhancement.mutable.MutableTypeEnhancementTestCase > testMutateMutableTypeObject FAILED
2020-12-04T14:07:07.7169514Z     javax.persistence.PersistenceException at MutableTypeEnhancementTestCase.java:30
2020-12-04T14:07:07.7171725Z         Caused by: org.hibernate.exception.SQLGrammarException at MutableTypeEnhancementTestCase.java:30
2020-12-04T14:07:07.7173783Z             Caused by: java.sql.SQLSyntaxErrorException at MutableTypeEnhancementTestCase.java:30
2020-12-04T14:07:07.7175703Z                 Caused by: oracle.jdbc.OracleDatabaseException at MutableTypeEnhancementTestCase.java:30
2020-12-04T14:07:08.4163724Z

**Comment by gbadner** [comment]
The changes look OK to me, but I am not absolutely sure that it won't have unexpected side effects. I'm in the process of adding a bunch of tests.

**Comment by gbadner** [comment]
I just pushed a commit with tests that add `join fetch` to queries. I also added a test for `size()` on one-to-many associations.

**Comment by gbadner** [comment]
This looks good to me. Provided that the failing tests pass now, I would approve this.

**Comment by gbadner** [comment]
@dreab8, has anyone looked into the test failures?

**Review by gbadner — APPROVED** [review]

**Comment by gbadner** [comment]
Merged. Thanks Andrea, and sorry for the delay!

**Pull request closed without merging**
