### PR TITLE
HHH-13221 - When lazy fetching child entities outside the session DB commit is fired in a read-only transaction.

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-13221

### CODE REVIEW

**Comment by gsmet** [comment]
This one requires a proper review by Gail, please don't merge it yet.

**Comment by vladmihalcea** [comment]
It's not a critical easy. I tried various scenarios and it was always just one select being triggered, even for join formula, custom loaders or using caching.

We can post pone it as long as it's necessary.

**Comment by gbadner** [comment]
I just pushed a change to the test to use ```FetchMode.SELECT``` to load an association. This forces the association to loaded in a different statement.

I don't think this is a good idea.

**Comment by vladmihalcea** [comment]
@gbadner Thanks for the commit. I think we should close this PR and reject the issue.

**Pull request closed without merging**
