### PR TITLE
HHH-11242 - [enhancer] load class on isolated class pool to avoid it being frozen

### PR DESCRIPTION
**Pull request by barreiro**

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks. I'm closing this PR then.

**Comment by candrews** [comment]
@sebersole,
This issue is kind of a big deal (the enhancer is totally broken without it) - can it please be merged?

FWIW, I tested this change and it fixed the problem and it didn't seem to cause any other problems.

**Comment by gbadner** [comment]
@candrews, I set the fix version for HHH-11242 as 5.2.7 so it won't fall through the cracks.

**Comment by gbadner** [comment]
@barreiro, is there a test case for this?

**Comment by candrews** [comment]
@gbadner the maven and gradle enhancer is completely broken and not working at all until this issue is fixed.

It's really unfortunate if we're going to have 2 releases in a row with this broken functionality.

**Comment by candrews** [comment]
@barreiro @sebersole Any updates on this? I fear another Hibernate release may occur with broken Gradle and Maven bytecode enhancement functionality.

**Comment by barreiro** [comment]
Added a simple test case for the Maven plugin. Although I'm not sure of the reliability of the test, I think it's a good addition.

**Pull request merged**
