### PR TITLE
[4.2] performance improvements that reduce memory allocation

### PR DESCRIPTION
**Pull request by stuartwdouglas**
This PR contains several commits that reduce memory allocation. Most of the improvements are based around allocating collections lazily, and reducing iterator allocations by not iterating over empty lists.

If you guys are happy with these changes I will prepare a PR for master as well, however there have been changes in this area so I want to be sure that these changes will be accepted before spending any time forward porting them.

### CODE REVIEW

**Comment by sebersole** [comment]
I am fine with these.  In the future though, we work from master out.  I'll apply both sets of changes once we have the PR for master.  Thank!

**Comment by sebersole** [comment]
Also, we *always* perform commits against a Jira.  In the future please create a Jira and reference the Jira issue key in the commit message.  

Don't worry about it for this PR,  I'll simply squash these commits altogether and amend the commit message

**Comment by Sanne** [comment]
@stuartwdouglas the iterator allocation trick is very interesting, could you share how you noticed those? I haven't seen them in previous recordings, but also I haven't seen a perf recording in many months.

**Comment by stuartwdouglas** [comment]
I just noticed them in an allocation recording (I can't remember if it was YJP or flight recorder, it was a while ago). 

None of these optimisations make a huge difference by themselves, but they do add up.

**Comment by scottmarlow** [comment]
Is this a community change for WildFly 9.x/10.x or targeted for EAP 6.x?

**Pull request closed without merging**
