### PR TITLE
Fixed HHH-11157 and extended identifier handling

### PR DESCRIPTION
**Pull request by beikov**

### CODE REVIEW

**Comment by gbadner** [comment]
@beikov, thanks for the pull request! We still need add a test case for this, so please add a commit with a test case.

**Comment by beikov** [comment]
Well, actually the testcase for HHH-9329 could have already caught that error if the tests were run on Derby, but apparently they aren't. Maybe you need to add a build matrix entry for that?
Anyway, I would still like to add a flag for disabling this behavior just in case and add some tests for other databases with special identifiers.

**Comment by vladmihalcea** [comment]
@beikov There's an easier way to test on any DB. All you need to do is just run:

`> gradle clean test -Pdb=derby`

The `databases.gradle` contains all the supported DBs we use for testing. There you can also customize your own DB credentials if they differ.

I'm going to test this PR against the `WithClauseTest` on Derby.

**Comment by vladmihalcea** [comment]
Tests running just fine on Derby now and on H2 as well. Applied upstream, thanks.

**Pull request closed without merging**
