### PR TITLE
HHH-16552 - Add CockroachDB v23.1 to docker startup script

### PR DESCRIPTION
**Pull request by maesenka**
The guys at Cockroach Labs asked to test also against the 23.1 version. 

I've added the configuration to the docker startup script. Could you add a job for the new version to Jenkins? Maybe replace the 20.1 job with this one?

### CODE REVIEW

**Comment by scottmarlow** [comment]
@maesenka I'm curious if you know what kind of testing with CockroachDB v23.1 will happen, where and which Hibernate ORM version will be tested with?  

Thanks

**Comment by maesenka** [comment]
The Jenkins CI tests include jobs to test the main branch against the two latest CockroachDB releases. The tests run on a server that I host on behalf of Cockroach Labs. Cockroach Labs proposes to test the latest release candidate.

**Comment by beikov** [comment]
You can add a new entry to the `nightly.Jenkinsfile` for the nightly version if you want. Just look for uses of e.g. `cockroachdb_21_2` in that file and copy config sections accordingly.

**Comment by beikov** [comment]
Please just add a new entry instead of replacing, as we still want to keep testing against the minimum supported version of CockroachDB.

**Review by beikov — APPROVED** [review]

**Comment by beikov** [comment]
Looks great now. Please rebase and squash commits to resolve the conflict, then this can go in

**Pull request merged**
