### PR TITLE
HHH 11544 - Test and fix

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-11544

### CODE REVIEW

**Comment by dreab8** [comment]
org.hibernate.test.inheritance.discriminator.MultiSingleTableLoadTest is failing, a wrong SQL query is generated.

**Comment by beikov** [comment]
This should do it, although I haven't run the full testsuite with it.

**Comment by gbadner** [comment]
Before rebasing master these test fails:
`org.hibernate.test.inheritance.discriminator.MultiInheritanceImplicitDowncastTest#testQueryConstruction`
`org.hibernate.test.annotations.genericsinheritance.GenericsInheritanceTest#classMethod`

After rebasing master, the first test passes, but the second test still fails.

**Comment by beikov** [comment]
I'd give it a look on the weekend. If that is too late for the release, just move it to the version please.

**Comment by Naros** [comment]
No problem @beikov, I've gone ahead and pushed it out to the next release cycle.

**Comment by beikov** [comment]
Huh, I'm not seeing any of these failures locally after rebasing. How did you invoke the build @gbadner ?

**Comment by gbadner** [comment]
I'm not seeing any failures now.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
