### PR TITLE
finally get rid of Session.connection()/disconnect()/reconnect()

### PR DESCRIPTION
**Pull request by gavinking**
This nasty stuff has stuck around for far too long.

### CODE REVIEW

**Comment by sebersole** [comment]
Yes, I removed the need for these years ago.

Been delaying dropping them because they potentially break user code and really have no harm.

But I agree, with this major, it is time

**Comment by sebersole** [comment]
I'll merge once the actions and checks finish

**Comment by sebersole** [comment]
Sheesh these actions take forever

**Comment by sebersole** [comment]
Merging this as the test failures seem to be consistent with the failures from all jobs.  As far as I know, @beikov said he has a fix for those already.

**Comment by gavinking** [comment]
Thanks!

**Pull request merged**
