### PR TITLE
HHH-11867 - @UpdateTimestamp not working with @Inheritance( strategy = JOINED )

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-11867.

The field is not updated when a field in the child entity is modified because` getTableUpdateNeeded( dirtyFields, hasDirtyCollection )` states the parent  table, where the `@UpdateTimestamp` field is declared, does not require to be updated.

Changes to `EntityMetamodel` class are deletions of private unused methods.

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @vladmihalcea I have included your solution but changed a little bit the test, what do u think?

**Comment by vladmihalcea** [comment]
In your latest commit there is no change to the test:

```
Showing  with 43 additions and 108 deletions.
+38 −21  hibernate-core/src/main/java/org/hibernate/persister/entity/AbstractEntityPersister.java
+5 −87  hibernate-core/src/main/java/org/hibernate/tuple/entity/EntityMetamodel.java
```

**Comment by dreab8** [comment]
@vladmihalcea  https://github.com/hibernate/hibernate-orm/pull/2165/commits/b5bd7ad890688a91063a0409068273353f223ed1

**Comment by dreab8** [comment]
Thanks @vladmihalcea,

I'm going to integrate it.

**Comment by dreab8** [comment]
applied upstream

**Pull request closed without merging**
