### PR TITLE
HHH-12741 Register new reserved words added in mysql 8.0

### PR DESCRIPTION
**Pull request by quaff**
https://dev.mysql.com/doc/refman/8.0/en/keywords.html#keywords-new-8-0-A

https://hibernate.atlassian.net/browse/HHH-12741

### CODE REVIEW

**Comment by gsmet** [comment]
@quaff thanks for the PR!

Could you create a JIRA issue here https://hibernate.atlassian.net/ and prepend your commit message with the JIRA number?

Thanks!

**Comment by gsmet** [comment]
@vladmihalcea I'm surprised we don't have any reserved keywords for MySQL right now as they have a lot of them. Do you happen to know why?

**Comment by vladmihalcea** [comment]
@sebersole Do you happen to know the answer to @gsmet 's question above?

**Comment by quaff** [comment]
It should handled by `DatabaseMetaData.getSQLKeywords()`,  but mysql jdbc driver `com.mysql.cj.jdbc.DatabaseMetaData.ProcedureType.MYSQL_KEYWORDS` doesn't add new reserved words in order to keep back compatibility

**Comment by gsmet** [comment]
@quaff interesting, thanks!

Is there a reason why you haven't added all of them? I see `WINDOW (R)` for instance that is missing in your PR.

**Comment by vladmihalcea** [comment]
The SQL keyword got from the DB metadata got to the `IdentifierHelper`, but we need to check if they are available to queries as well. Maybe that's a problem too.

**Comment by gsmet** [comment]
@quaff I merged your PR, thanks. Will be included in the upcoming 5.3.2.

**Pull request closed without merging**
