### PR TITLE
HHH-17706 Optimize FK comparison to eliminate unnecessary left join

### PR DESCRIPTION
**Pull request by quaff**
Fix regression introduced by ef155c22c1c2e57d0ce9fcc21f506efa1bba5be2

https://hibernate.atlassian.net/browse/HHH-17706

### CODE REVIEW

**Comment by quaff** [comment]
This PR indeed break `org.hibernate.orm.test.entitygraph.EntityGraphAndJoinTest`, but I think that should be fixed in another commit as an improvement before merging this one.
Hibernate should select FK instead of PK from relation table, because the order by clause will always use FK no mater entity graph is using.
```sql
    select
        distinct p1_0.id,
        a1_0.id,  -- should be p1_0.address_id
        a1_0.description,
        p1_0.name 
    from
        Person p1_0 
    left join
        Address a1_0 
            on a1_0.id=p1_0.address_id 
    where
        a1_0.description='test' 
    order by
        p1_0.address_id
```

**Comment by mbladel** [comment]
As I mentioned in more details on the Jira, we opted to avoid optimizing away explicit joins (see [discussion on previous pr](https://github.com/hibernate/hibernate-orm/pull/7570#discussion_r1406220076)) to prevent problematic queries. I also fear the checks you're using won't be enough to ensure we can avoid using the target side key to create correct queries, except for very simple cases like the test you're introducing.

Closing this PR for now.

**Comment by quaff** [comment]
> I’m also skeptical about the actual performance impact of creating the join since primary keys should be indexed and the query results are the same.

@scordio Could you take some time to verify that as @mbladel said?

**Comment by scordio** [comment]
@quaff sure, I'm getting in touch with our Db2 team for a more detailed analysis – will get back to you as soon as I have the details.

**Comment by gavinking** [comment]
But .... why wouldn't you guys just change the query to use `get()` instead of `join()`? That's the most natural way to write this query if you don't want the join!

**Comment by scordio** [comment]
@gavinking I'm totally with you if I would define the query manually but the case I originally reported is https://github.com/spring-projects/spring-data-jpa/issues/3349 so Spring Data JPA generates the query.

That's why I was asking if an enhancement should be considered in there (https://github.com/spring-projects/spring-data-jpa/issues/3349#issuecomment-1927099355) but obviously workarounds are possible in the client code.

**Comment by gavinking** [comment]
Look, I'm just saying.....

```java
package org.example;

import org.hibernate.StatelessSession;
import org.hibernate.annotations.processing.Find;

import java.util.List;

interface BookRepository {

  StatelessSession session();

  @Find
  List<Book> findAllByPublisher(long publisher$id);

}
```

Generated by annotation processor:

```java
package org.example;

import jakarta.annotation.Generated;
import jakarta.annotation.Nonnull;
import jakarta.enterprise.context.Dependent;
import jakarta.inject.Inject;
import jakarta.persistence.metamodel.StaticMetamodel;
import java.util.List;
import org.hibernate.StatelessSession;

@Dependent
@StaticMetamodel(BookRepository.class)
@Generated("org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
public class BookRepository_ implements BookRepository {

	
	private final @Nonnull StatelessSession entityManager;
	
	@Inject
	public BookRepository_(@Nonnull StatelessSession entityManager) {
		this.entityManager = entityManager;
	}
	
	public @Nonnull StatelessSession session() {
		return entityManager;
	}
	
	/**
	 * Find {@link Book} by {@link Book#publisher.id publisher.id}.
	 *
	 * @see org.example.BookRepository#findAllByPublisher(long)
	 **/
	@Override
	public List<Book> findAllByPublisher(long publisher$id) {
		var builder = entityManager.getFactory().getCriteriaBuilder();
		var query = builder.createQuery(Book.class);
		var entity = query.from(Book.class);
		query.where(
				builder.equal(entity.get(Book_.publisher).get(Publisher_.id), publisher$id)
		);
		return entityManager.createQuery(query).getResultList();
	}


}
```

Not only can freely rename the method `findAllByPublisher()` to whatever you like, but you can _easily_ debug that generated code.

SQL:
```sql
    select
        b1_0.isbn,
        b1_0.duration,
        b1_0.price,
        b1_0.publication_date,
        b1_0.publisher_id,
        b1_0.quantitySold,
        b1_0.text,
        b1_0.title,
        b1_0.type 
    from
        books b1_0 
    where
        b1_0.publisher_id=?
```

But I can't force you to use [this](https://docs.jboss.org/hibernate/orm/6.4/introduction/html_single/Hibernate_Introduction.html#generator). It's something you have to realize for yourself.

**Comment by gavinking** [comment]
(You can of course use your own preferred flavor of "session" here. I personally like `StatelessSession` for DAO-style repositories.)

**Comment by scordio** [comment]
Absolutely, I understand that a Hibernate-only solution would work without issues, and I do appreciate the hint!

I'm just coming from a codebase strongly connected to Spring Data JPA and I'd like to understand how the Spring Data team sees the current issue before evaluating a tech change, given that there are already other ways in Spring Data to get the right query generated.

(I know, Hibernate is already there and features can be used, but maybe you get what I mean 🙂)

**Comment by gavinking** [comment]
Of course, I understand.

**Pull request closed without merging**
