### PR TITLE
HHH-9959 Upgrade to the latest Validator release

### PR DESCRIPTION
**Pull request by hferentschik**

### CODE REVIEW

**Comment by hferentschik** [comment]
@sebersole, could you merge this for the ORM 5 final release? 
Regarding f84ecc0, that is just a little build script improvement. Allows to skip in particular Findbugs which at least on my machine takes a long time.

**Comment by hferentschik** [comment]
> What gradle task are you executing?

clean build

> you can just run gradle with -x findbugsMain -x findbugsTest -x checkstyleMain

true, true, but I think my way is considerable shorter. It also allows to skip the tasks of the whole plugins without knowing which task the plugin adds. Anyways, just drop the the commit if you think it is not worth it.

**Comment by sebersole** [comment]
So while you are developing, just run `clean test`.  `build` adds all kinds of other things you are not interested in.  You should run a full build just once prior to calling your work done.  Or even just `check`.

Anyway, in terms of 21a7529000cd35fecd224a7bf85ccecde7f2b6ff just push that one.  It looks fine.  We don't do crazy 3 member reviews of simple dependency updates for ORM ;)

**Comment by hferentschik** [comment]
> Anyway, in terms of 21a7529 just push that one

+1

> We don't do crazy 3 member reviews of simple dependency updates for ORM ;)

;-)

**Comment by sebersole** [comment]
Hardy, did you push 21a7529 ?

**Pull request closed without merging**
