### PR TITLE
HHH-17167 Unable to locate parameter for RESTRICT - DELETE error when removing entity with RowId

### PR DESCRIPTION
**Pull request by mbladel**
https://hibernate.atlassian.net/browse/HHH-17167

### CODE REVIEW

**Review by beikov — APPROVED** [review]
LGTM. Do the changes impact HR? @DavideD

**Comment by DavideD** [comment]
They require some changes in HR because the signature on some methods as change, it should be fine but I haven't try to fix the compilation errors yet.
I will do it today and let you know

**Comment by mbladel** [comment]
@DavideD tanks for checking, just for context the signature changes were needed to clear up the default delete behavior when a `@RowId` is available. Before, the *static* delete operation built at boot time used the primary key, while whenever a row-id was available we always built a *dynamic* delete. Since the row-id case is the most common and should be the default, the operations have now been switched, which is also consistent with what we already did for updates.

**Review by DavideD — APPROVED** [review]
It works fine with Hibernate Reactive after fixing a few compilation errros.

Thanks for the warning.

**Pull request merged**
