### PR TITLE
HHH-13300 query.getSingleResult() throws org.hibernate.NonUniqueResultException instead of javax.persistence.NonUniqueResultException

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net//browse/HHH-13300

### CODE REVIEW

**Comment by gbadner** [comment]
In addition, the following do not convert the exception if the SessionFactory was JPA bootstrapped.

- ```AbstractProducedQuery.java`#executeUpdate``` (should be changed)
- ```AbstractSharedSessionContract#close``` (not sure about this one)
- ```SessionImpl#fireRefresh``` (should be changed so it is consistent with ```SessionImpl#merge```)

I'm not sure about ```AbstractSharedSessionContract#close```, because it does not implement ```EntityManager#close```.

I'm still thinking about this...

**Comment by yrodiere** [comment]
> I'm not sure about `AbstractSharedSessionContract#close`, because it does not implement `EntityManager#close`.

I would argue that `AbstractProducedQuery#list` is not related to JPA either, yet it converts exceptions to JPA depending on the bootstrap and settings.

Please let me know of your decision :)

**Comment by gbadner** [comment]
I agree ```AbstractProducedQuery#list``` looks inconsistent.

**Comment by gbadner** [comment]
I pushed a test and fix for ```Query#executeUpdate```. The others can be dealt with later.

@yrodiere, if my commits look good to you, then I'm fine with merging this. Thanks for finding this bug.

**Comment by yrodiere** [comment]
It looks good! Merged, thanks.

**Pull request merged**
