### PR TITLE
HHH-18538 Improve database connection info from configured DataSource

### PR DESCRIPTION
**Pull request by quaff**
[Please describe here what your change is about]

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

https://hibernate.atlassian.net/browse/HHH-18538

### CODE REVIEW

**Comment by quaff** [comment]
CC @jrenaat

**Comment by jrenaat** [comment]
Thanks!

**Comment by gavinking** [comment]
Hey, wait, @quaff, @jrenaat, this is going to log the `toString()` of the `DataSource` object. That doesn't sound right! There's no contract that `DataSource.toString()` has to return something suitable for logging.

**Comment by gavinking** [comment]
See https://github.com/hibernate/hibernate-orm/pull/8859/commits/2260c4eeb06743afb0b578b9f3dba85c0b03e262

**Comment by quaff** [comment]
> There's no contract that `DataSource.toString()` has to return something suitable for logging.

I don't think the contract is important here, it will return something to help identifying which `DataSource` is using, it's better than `null`.

**Pull request merged**
