### PR TITLE
HHH-16420 - Make CriteriaBuilder.function() supports array result type

### PR DESCRIPTION
**Pull request by quaff**
Fix https://hibernate.atlassian.net/browse/HHH-16420
Fix https://hibernate.atlassian.net/browse/HHH-16419 Partially

### CODE REVIEW

**Comment by quaff** [comment]
Maybe it's better to push down the enhancement to `TypeConfiguration::getBasicTypeForJavaType`?

**Comment by beikov** [comment]
This should definitely rather be handled in `org.hibernate.type.BasicTypeRegistry#getRegisteredType` i.e. if the type can not be found in the basic type registry, lookup the `JavaType` first and construct the `BasicType` from that similar to how `org.hibernate.boot.model.process.internal.InferredBasicValueResolver#from` does it for the `reflectedJtd` when the `explicitJdbcType` is null.

**Comment by quaff** [comment]
I've given up changing `BasicTypeRegistry`, it break many tests I can not fix, now the changes applied to `TypeConfiguration::getBasicTypeForJavaType`, feel free to close it if you have better solution.

**Comment by beikov** [comment]
>This should definitely rather be handled in `org.hibernate.type.BasicTypeRegistry#getRegisteredType` i.e. if the type can not be found in the basic type registry, lookup the `JavaType` first and construct the `BasicType` from that similar to how `org.hibernate.boot.model.process.internal.InferredBasicValueResolver#from` does it for the `reflectedJtd` when the `explicitJdbcType` is null.

I gave you pretty exact instructions on how to implement this. If you can't manage to do that, then I'll try to work on this as part of my array function extensions.

**Pull request closed without merging**
