### PR TITLE
HHH-15146 + HHH-15147 Fix jpamodelgen-jakarta annotation processor processing javax.* annotations instead of jakarta.* annotations

### PR DESCRIPTION
**Pull request by yrodiere**
* [HHH-15147](https://hibernate.atlassian.net/browse/HHH-15147): hibernate-jpamodelgen-jakarta annotation processor ignores jakarta.* annotations
* [HHH-15146](https://hibernate.atlassian.net/browse/HHH-15146): Run tests against hibernate-jpamodelgen-jakarta

See also https://hibernate.zulipchat.com/#narrow/stream/132096-hibernate-user/topic/Hibernate.20jpamodegen.205.2E6.2E7.2EFinal.20does.20not.20work , https://github.com/spring-projects/spring-boot/issues/30445

### CODE REVIEW

**Review by beikov — COMMENTED** [review]
AFAICT, this LGTM

**Comment by yrodiere** [comment]
Ha, it looks like I fixed the module by mistake while adding tests xD I'll split the fix and tests into two commits, to make things clearer.

**Comment by yrodiere** [comment]
Here @beikov , I moved the fix to a separate commit to be clearer.

**Review by beikov — APPROVED** [review]

**Comment by yrodiere** [comment]
Merged, thanks!

**Pull request merged**
