### PR TITLE
fix HHH-13312

### PR DESCRIPTION
**Pull request by pro100leo**
see https://hibernate.atlassian.net/browse/HHH-13312 for details

### CODE REVIEW

**Comment by gsmet** [comment]
@pro100leo the fix looks good, thanks for catching it.

Any chance you could add a test case?

**Comment by pro100leo** [comment]
Ok, I will add test today

**Comment by pro100leo** [comment]
@gsmet , 
Sorry, but I didn't managed to build hibernate-core project locally with eclipse after an hour of attempts.
Unfortunately, I don't have free time now to try more, so I can't write a Unit-test for this issue now.
Probably, I will try once again in several days.

**Comment by gsmet** [comment]
@pro100leo yeah setting up Hibernate ORM in Eclipse is not an easy task unfortunately. 

Could you create a test case using our test case template? See 
https://github.com/hibernate/hibernate-test-case-templates/tree/master/orm/hibernate-orm-5 . 

It’s easy and would be very helpful. If you can’t, just drop your entity and how you build your query and I’ll take care of it. 

I plan to release 5.4.2 on Wednesday and that would be nice to fix it in this release. 

Thanks!

**Comment by pro100leo** [comment]
@gsmet 
I created a test case according to your template.
Currently it produces Exception on 5.3.1
Code is available here : https://pastebin.com/42269Tnu

**Comment by gsmet** [comment]
Closing, superseded by https://github.com/hibernate/hibernate-orm/pull/2817 which includes a test case.

**Pull request closed without merging**
