### PR TITLE
HHH-11176: Add support for Tuple results for native queries

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-11176

### CODE REVIEW

**Comment by galovics** [comment]
Looks good to me. Thank you for the little adjustments!

**Comment by vladmihalcea** [comment]
Applied upstream, thanks @galovics

**Comment by tdjac0bs** [comment]
Also, it breaks with null values.

**Comment by tdjac0bs** [comment]
PS: i tried to add this comment to the issue, but it's read only for me (maybe because it's a new user).

**Comment by vladmihalcea** [comment]
@tdjac0bs Please open a new Jira issue and report all your findings. Thanks

**Comment by galovics** [comment]
@tdjac0bs If the ticket is done, link it here. I'll take a look. Thx!

**Comment by tdjac0bs** [comment]
Hello, thank you for the quick response, please see the following ticket: https://hibernate.atlassian.net/browse/HHH-11897

**Pull request merged**
