### PR TITLE
HHH-10382 GetterFieldImpl creates unnecessary objects

### PR DESCRIPTION
**Pull request by golovnin**
https://hibernate.atlassian.net/browse/HHH-10382

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by golovnin** [comment]
git log --author=golovnin should answer your question. And if I say yes, how are you going to verify it? And if you are able to verify it, then why are you asking me this question? But more seriously I have signed it in 2012 or so.

**Comment by vladmihalcea** [comment]
Unfortunately, only Steve has access to the people who sign the CLA, so that's why I asked you. Thanks for replying.

**Comment by vladmihalcea** [comment]
Thanks. Applied upstream on master.

**Pull request closed without merging**
