### PR TITLE
Fix for HHH-10510

### PR DESCRIPTION
**Pull request by andrei-ivanov**

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Is this really a fix for [HHH-10511](https://hibernate.atlassian.net/browse/HHH-10511)? The JIRA description is about a many-to-many/one-to-many attribute type resolving.

**Comment by andrei-ivanov** [comment]
Grr, it's for HHH-10510, sorry about that

**Comment by vladmihalcea** [comment]
Makes sense now: https://hibernate.atlassian.net/browse/HHH-10510

Two things before I merge it:

1. Did you sign the CLA?
2. Is there any unit test for this?

**Comment by andrei-ivanov** [comment]
I don't think I've signed it. Can you point me to the instructions please?
Regarding the unit test, like I've mentioned in the issue, I can't manage to make Hibernate replicate the problem without a mock :-(

**Comment by vladmihalcea** [comment]
The CLA page is [here](https://cla.jboss.org/index.seam). Regarding a test, I'll write on the JIRA issue instead.

**Comment by andrei-ivanov** [comment]
CLA signed

**Comment by vladmihalcea** [comment]
Great. I wrote a step-by-step guide for writing the Unit Test. Let me know if there's anything I can help you with.

**Comment by vladmihalcea** [comment]
I created a new [PR](https://github.com/hibernate/hibernate-orm/pull/1292) containing both your change and a test case for this issue

**Pull request closed without merging**
