### PR TITLE
HHH-14655 Upper case the information schema sequence identifier again to fix issues with case sensitive databases

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-14655

### CODE REVIEW

**Comment by gavinking** [comment]
OOoops, my bad: I did the right thing in H6, but then futzed it up here. There's even a comment explaining that it's needed. I suck.

**Review by gavinking — APPROVED** [review]

**Comment by beikov** [comment]
NP Gavin, happens to the best ;)

**Comment by gavinking** [comment]
P.S. @beikov I think the comment should be improved.

Instead of "this should work" which sounds like the person didn't test it, I think it should explain the situation, that is, that the database server can have defined "collation mode", some of which have case-sensitive table names (though this is not the default).

**Comment by gavinking** [comment]
Thanks for cleaning up my mess.

**Pull request merged**
