### PR TITLE
HHH-9602 - Add materialized view support for schema validation

### PR DESCRIPTION
**Pull request by dargiri**
Added new dialect for PostgreSQL 9.3 that supports materialized views & enable materialized view support for schema validation.

### CODE REVIEW

**Comment by dargiri** [comment]
Please merge these changes also into latest 4.x version if they're planned.

**Comment by dargiri** [comment]
Attached test case to reproduce bug: https://github.com/dargiri/HHH-9602-test

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by dargiri** [comment]
@vladmihalcea Hello, did it just now. As I understood it might take some time:

> Contributor agreement "JBoss Individual Contributor Agreement (GPL/LGPL)", for: Hibernate, verified successfully! You will receive an e-mail when your application will be accepted or rejected.

**Comment by sebersole** [comment]
I think overall I'd prefer to see generic "additional table type(s)" support via Dialect and possibly from settings as well.  The idea being the ability to augment the list of org.hibernate.tool.schema.extract.internal.InformationExtractorJdbcDatabaseMetaDataImpl#tableTypes ultimately used in the filter.

The difference is in the specificity for the PR approach.  I'd much rather see a more generic solution that allows the Dialect to more generically augment the type-types filter list.  This is the same functionality exposed by the `EXTRA_PHYSICAL_TABLE_TYPES = "hibernate.hbm2dll.extra_physical_table_types"` setting

**Comment by sebersole** [comment]
@dargiri Do you feel like taking on that change?

**Comment by sebersole** [comment]
I could not send you a PR, @dargiri but here is what I mean: https://github.com/sebersole/hibernate-core/tree/HHH-9602

**Comment by sebersole** [comment]
I was not able to send a PR to your repo @dargiri 

But here are the changes I propose : https://github.com/sebersole/hibernate-core/tree/HHH-9602

**Comment by vladmihalcea** [comment]
@sebersole Would you like to send a new PR for this issue?

**Comment by vladmihalcea** [comment]
[HHH-9602](https://hibernate.atlassian.net/browse/HHH-9602) is fixed now. I'm closing this PR.

**Pull request closed without merging**
