### PR TITLE
HHH-17442 Use FlushMode.MANUAL for select query in ValidityAuditStrategy

### PR DESCRIPTION
**Pull request by vincentstradiot**
https://hibernate.atlassian.net/browse/HHH-17442

### CODE REVIEW

**Comment by vincentstradiot** [comment]
Hi @beikov, I don't know how contribution review is managed at your side, but could someone have a look at my suggestion when you have time? :) Or should I wait until my ticket is planned for the current sprint? Thanks in advance.

**Review by Naros — APPROVED** [review]
@beikov, this LGTM, and I don't see any particular downsides to Envers.

**Comment by beikov** [comment]
Thanks for the review and thanks for your work @vincentstradiot. Sorry it took so long, but Hibernate Envers is more in maintenance mode than being actively developed, so it might take some time until @Naros gets around to review enhancements.

**Comment by vincentstradiot** [comment]
No problem, thanks @Naros and @beikov for the review and merging the changes.

**Pull request merged**
