### PR TITLE
[5.0] HHH-11254 Timestamps cache fails validation if eviction strategy = MANUAL

### PR DESCRIPTION
**Pull request by pferraro**
https://hibernate.atlassian.net/browse/HHH-11254

Backport of PR #1629

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@gbadner Since this targeting 5.0, Gail needs to approve the change request.

**Comment by gbadner** [comment]
@pferraro, does this really apply to 5.0? IIUC, EvictionStrategy#MANUAL is new to Infinispan 8.2.5. I didn't think 8.2.5 was used with Hibernate 5.0.

Please let me know.

**Comment by pferraro** [comment]
@gbadner WildFly master uses Hibernate 5.0.x in concert with Infinispan 8.2.5.Final, so yes, this applies to 5.0.

**Comment by gbadner** [comment]
@pferraro , WildFly master is going to be upgraded to use 5.1 by https://issues.jboss.org/browse/WFLY-6854, so 5.0 shouldn't need the upgrade, should it?

**Comment by pferraro** [comment]
@gbadner That depends on whether or not @scottmarlow plans to retain the 5.0 modules and integration (as he has for 4.1 and 4.3).  Scott?

**Comment by scottmarlow** [comment]
@gbadner @pferraro, we plan to replace the WildFly ORM 5.0 jars with 5.1 and update the Hibernate 5.0 integration, to work with the 5.1 ExtendedBeanManager extension.

**Comment by pferraro** [comment]
@gbadner In that case, this PR is optional.  However, if we plan to retain support for Hibernate 4.1 and 4.3 in WF (@scottmarlow ?), then we should backport this change to those branches as well.

**Comment by scottmarlow** [comment]
We don't "support" the older 4.1/4.3 versions of Hibernate ORM, it is more for migration from the older Hibernate versions to the Hibernate version that we package.

**Comment by pferraro** [comment]
@scottmarlow Poor choice of words - what I mean is that 2nd level cache will break on these versions unless this change is backported.

**Comment by scottmarlow** [comment]
This code change looks compatible with older versions of Infinispan but I'm not sure its needed, unless we want Infinispan 8.2.5.Final to work with ORM 5.0 or 4.1/4.3, for a specific reason.  I'm not against the change being back ported though.

**Comment by scottmarlow** [comment]
More directly, I don't mind if Hibernate ORM 5.0 and earlier do not work with Infinispan 8.2.5.Final.

**Comment by beikov** [comment]
We are not backporting anymore to 5.0

**Pull request closed without merging**
