### PR TITLE
HHH-17720 - Add common JAXB contracts for named queries

### PR DESCRIPTION
**Pull request by jrenaat**
[Please describe here what your change is about]

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

https://hibernate.atlassian.net/browse/HHH-17720

### CODE REVIEW

**Comment by jrenaat** [comment]
> The changes look good, though I want to discuss naming. Its a bit hard here, but I think the names you choose for the interfaces are a bit verbose.

I admit that `JaxbNamedQueryOrNamedStoredProcedureSuperclass` is verbose, but not without some thought; i went for similar naming as `JaxbEntityOrMappedSuperclass`

> For `JaxbNamedQueryOrNamedStoredProcedureSuperclass`, the difficulty ofc comes from the fact that the most natural name here is "named query", but that's confusing in that `<named-query/>` is just one. That's why I went with "base".

The difficulty is that there is little commonality between named stored procedure and the tow others (named query and named native query)

> How about this...
> 
> 1. Use the xjb file to rename "named query" to "named hql query".

I don't quite understand what you mean here

> 2. Use `JaxbNamedHintableQuery` as the base interface (rename of `JaxbNamedQueryBase`).

I understand where you are going with this, i actually tought of that but i found it to be lacking in descriptiveness.
I won't make an issue of it though, don't like my suggestion either, only that it refelcts more what it superclasses ... but indeed verbose.

> 3. Because of the rename from (1) we could then use `JaxbNamedQuery extends JaxbNamedHintableQuery` as the base for named hql and native queries.
> 
> Still not great, but I think a little bit better.
> 
> WDYT?

**Comment by sebersole** [comment]
> i went for similar naming as `JaxbEntityOrMappedSuperclass`

Yep, and I made a mistake there and it should have been `JaxbIdentifiableType` or somesuch.


> > For `JaxbNamedQueryOrNamedStoredProcedureSuperclass`, the difficulty ofc comes from the fact that the most natural name here is "named query", but that's confusing in that `<named-query/>` is just one. That's why I went with "base".
> 
> The difficulty is that there is rather little commonality between named stored procedure and the two others (named query and named native query), which makes having a superclass for the 3 s bit awkward.

Sure, but the hints specifically are nice to handle commonly.  Which you can see is the only actual use of this atm.


> > 1. Use the xjb file to rename "named query" to "named hql query".
> 
> I don't quite understand what you mean here

For `<named-query/>` XJC currently produces a class named `JaxbNamedQueryImpl` right?  So I was saying, we could have it produce a class named `JaxbNamedHqlQueryImpl` instead.  That way we'd have

* `JaxbNamedHqlQueryImpl`
* `JaxbNamedNativeQueryImpl`

both of which could implement the common `JaxbNamedQuery` interface.

----

Again, I'm not saying this is all "great".  But I think its better than we have here or had before.

Ideally, imo, we'd have

* `JaxbNamedQuery` (notice no `*Impl`) as the base interface with just name and hints
* `JaxbNamedStoredProcedureQueryImpl` which implements `JaxbNamedQuery` 
* <some other interface here> which is the commonality between named hql and native queries.  I have a hard time coming up with a great name here though.  `JaxbNamedSimpleQuery`?  This interface would extend the `JaxbNamedQuery` interface.  `JaxbNamed(Hql)QueryImpl` and `JaxbNamedNativeQueryImpl` would implement this interface

**Comment by jrenaat** [comment]
Still fiddling with names ...
I do think we should reserve the `JaxbNamedQuery` as the interface for `JaxbNamedHqlQuery`and `JaxbNativeNamedQuery`, just seems to make more sense. The interface above that which includes the `JaxbNamedStoredProcedureImpl` is the troublesome one .... called it `JaxbQueryHintable`, could also be `JaxbNamedQueryHintable` ... dunno
Nomenclature is a bitch.

**Comment by sebersole** [comment]
Nice!

**Pull request merged**
