### PR TITLE
HHH-17772, HHH-17773 initial support for Jakarta Data annotations

### PR DESCRIPTION
**Pull request by gavinking**
Current status:

- [x] Basic support for `@Repository`, `@Insert`, `@Delete`, `@Update`, `@Find`, and `@Query`
- [x] Add `@Save`, interpreting it as `upsert()` (i.e. SQL `MERGE`)
- [x] Support for `@Param`, `@By`, and `@OrderBy`
- [x] Respect `@Repository(dataStore="my-persistence-unit")`
- [x] Basic support for `Sort`, `Order`, `Limit`
- [ ] Support for `PageRequest`, `Page`, `Slice`, and `KeysetAware` stuff
- [ ] Generation of Jakarta Data-specific static metamodel
- [x] Exception type conversion

https://hibernate.atlassian.net/browse/HHH-17773
https://hibernate.atlassian.net/browse/HHH-17772

### CODE REVIEW

**Comment by gavinking** [comment]
So this is 'bout ready to merge:

- I will do the Data-variant of the static metamodel later (I don't believe it's a requirement to certify the TCK anyway).
- We don't plan to implement magical method name queries at this stage.
- @beikov is the expert on the pagination stuff, and has agreed to work on that part of it.

I definitely _do_ need to improve the tests, but that can also be done in a separate PR.

**Comment by gavinking** [comment]
> I will do the Data-variant of the static metamodel later 

Actually, it's done in #7892.

> @beikov is the expert on the pagination stuff, and has agreed to work on that part of it.

In fact I have made a really good start on this in #7899 but I'm still going to need Christian's help on a couple of things.

**Comment by maxandersen** [comment]
> Jakarta Data Compiled with

what version is Jakarta Data targeting? please don't say its 21? :)

**Comment by gavinking** [comment]
Not sure. I don't _think- there's any newer language features used in the APIs. At least not that I can recall off the top of my head.

**Comment by gavinking** [comment]
```
        <maven.compiler.release>17</maven.compiler.release>
        <maven.compiler.source>17</maven.compiler.source>
```

**Pull request merged**
