### PR TITLE
 HHH-13000 - Fix for refreshing entities under PESSIMISTIC_WRITE lock

### PR DESCRIPTION
**Pull request by JWGmeligMeyling**
Testcase provided separately in #2550 

Issue: https://hibernate.atlassian.net/browse/HHH-13000

### CODE REVIEW

**Comment by JWGmeligMeyling** [comment]
If 5.3.x is going to be around for a while (i.e. WF15?) I'd like to see this backported too

**Comment by vladmihalcea** [comment]
@beikov @JWGmeligMeyling I think that we should do this as well:

    postRefreshLockMode = currentLockMode;

I want to test it for PESSIMISTIC_READ as well, so I'll add some extra test, and submit a new PR to replace this one afterward.

**Comment by JWGmeligMeyling** [comment]
Ok, thanks! 👍

**Comment by JWGmeligMeyling** [comment]
By the way, I agree with you that `postRefreshLockMode = currentLockMode;` should be set.

**Comment by vladmihalcea** [comment]
Superseded by [this PR](https://github.com/hibernate/hibernate-orm/pull/2552).

**Pull request closed without merging**
