### PR TITLE
HHH-6781 Class level @Where annotation is not enforced on collections of that class

### PR DESCRIPTION
**Pull request by Vlad-Kuznetsov**
Added processing of @Where annotation from class and from association joining them and operator
added test for filtering both clauses

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by Vlad-Kuznetsov** [comment]
Yes. Just signed

**Comment by vladmihalcea** [comment]
Thanks, I'm going to review your PR.

**Comment by vladmihalcea** [comment]
I fixed the tests that were failing and rebased it. Therefore, this PR is replaced by [this one](https://github.com/hibernate/hibernate-orm/pull/1387).

**Comment by Vlad-Kuznetsov** [comment]
Could you also tell me how to fix the documentation, to clarify the behavior for users.

**Comment by vladmihalcea** [comment]
Now I realized we didn't mention it. We have to add it somewhere here:

    hibernate-orm\documentation\src\main\asciidoc\userguide\chapters\domain\DomainModel.adoc

**Pull request closed without merging**
