### PR TITLE
Patch for HHH-1237

### PR DESCRIPTION
**Pull request by michael-schnell**
A patch for bug "Escaping : with :: in queries" (HHH-1237) was provided four years ago, but never applied to the code: https://hibernate.atlassian.net/browse/HHH-1237

I canceled my old pull request from 11 May 2014 (https://github.com/hibernate/hibernate-orm/pull/738/) and created this new one. Hopefully it gets into the branch this time.

### CODE REVIEW

**Comment by gbadner** [comment]
Please add a test case.

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by richardfontana** [comment]
@vladmihalcea this can be merged without needing the CLA.

**Comment by michael-schnell** [comment]
Please merge the new pull request https://github.com/hibernate/hibernate-orm/pull/1352 that includes now a test and cancel this one.

**Comment by Naros** [comment]
Closing in favor of PR https://github.com/hibernate/hibernate-orm/pull/1352.

**Pull request closed without merging**
