### PR TITLE
HHH-9663 Test and implement orphan removal of assocations within embeddables

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-9663

### CODE REVIEW

**Review by sebersole — APPROVED** [review]

**Comment by gavinking** [comment]
These changes need to be replicated in Reactive.

**Comment by dazey3** [comment]
@beikov @gavinking @sebersole 

Hello! I was looking at your testing for this issue and I notice that you have an @Id annotation on your @Embeddable object. I think this might be an error in your testing.

**Comment by beikov** [comment]
Hey @dazey3 

I took the test from https://github.com/hibernate/hibernate-orm/pull/2233 and didn't give that part much attention. I agree though that it looks odd. My guess, Hibernate just ignores `@Id` on embeddables.

**Comment by dazey3** [comment]
@beikov 

Interesting that hibernate does not issue any warnings or validation exceptions. I don't have much experience with Hibernate, but it did look odd to me so I figured I'd point it out. If Hibernate silently ignores, then ok. Thanks!

**Pull request merged**
