### PR TITLE
HHH-15900 ID attributes  with "select" generator are mapped to identity columns

### PR DESCRIPTION
**Pull request by mbladel**
https://hibernate.atlassian.net/browse/HHH-15900

### CODE REVIEW

**Comment by gavinking** [comment]
Hrm. I wonder if this is the correct fix for this. Perhaps a better fix would be to stop using `instanceof IdentityGenerator` to drive DDL generation.

**Comment by gavinking** [comment]
What I mean is: this points to us needing a more robust/flexible way of deciding when to use an identity column.

**Comment by mbladel** [comment]
@gavinking I agree, considering a more solid way of distinguishing identity columns would definitely not hurt. Still, separating `SelectGenerator` from `IdentityGenerator` made sense IMO because sometimes it could be applied to something you just want to select (e.g. a column populated by a simple trigger) but that is not an identity.

**Comment by gavinking** [comment]
Ah, OK, but I’m not sure it’s a good way to do that. The whole `InDatabaseGenerator` branch does that, and in a more efficient way, since multiple fields can be fetched in a single select.

**Comment by gavinking** [comment]
Well, actually the real difference between the `select` generator and the other `InDatabaseGenerator`s is that it uses a `@NaturalId` to locate the inserted row instead of using the PK. And this makes it a bit of an odd thing that doesn't fit completely comformtably within either the older or new abstractions. And as a result it actually *doesn't* work for anything except the PK column.

Like I wrote:

```java
 * Arguably, this class breaks the natural separation of responsibility between the
 * {@linkplain InDatabaseGenerator generator} and the coordinating
 * code, since it's role is to specify how the generated value is <em>retrieved</em>.
```

**Comment by gavinking** [comment]
Now, on the other hand, what you're saying is that the original purpose of the `select` generator was not to be a worse `identity` generator but to handle other cases like triggers, and yeah, OK, looks like you're right about that and I simply messed up when I refactored all this stuff.

So I guess this proposed change is correct.

**Comment by gavinking** [comment]
Yep, you're right, nice catch, thanks.

**Comment by mbladel** [comment]
Thank you for taking the time to clarify the issue!

**Pull request merged**
