### PR TITLE
fix broken float type precision conversion

### PR DESCRIPTION
**Pull request by gavinking**
it is not the case that ln(10) = log_2(10)

@beikov

### CODE REVIEW

**Review by beikov — APPROVED** [review]
Looks good to me. Yeah I apparently didn't think this totally through before, so thanks for making sure this is correct :)

**Comment by gavinking** [comment]
But WTH is up with those HSQLDB failures, surely they can't be related to this change?

**Comment by beikov** [comment]
I'd say don't mind these failures. These seem related to some DST changes. Did DST change 3 hours ago in the TZs we test for? :D 
FWIW, I would love to get rid of the HSQL dialect from hibernate-core, but that's a different discussion.

**Comment by gavinking** [comment]
> I'd say don't mind these failures.

Yeah, agreed. Just ran the tests on a local hsqldb and nothing failed.

> Did DST change 3 hours ago in the TZs we test for? :D

Well the same thought occurred to me, but Dec 13 seems like a strange date to change clocks....

**Comment by gavinking** [comment]
Screw it, I'm merging, `main` was already failing.

**Pull request merged**
