### PR TITLE
Implement support for delayed collections with FKs based on non-primary keys

### PR DESCRIPTION
**Pull request by beikov**
Factored out from #3799

### CODE REVIEW

**Review by dreab8 — APPROVED** [review]
it looks good to me :)

**Comment by gavinking** [comment]
What does "delayed collections" mean?

**Comment by beikov** [comment]
>What does "delayed collections" mean?

@gavinking: Represents a "lazy collection" where we just fetch the FK to be able to create a `PersistenetCollection`. I didn't come up with that term, but I assume that nobody has a problem with changing the name if you come up with something better.

**Comment by gavinking** [comment]
I still don't understand. Is there a test for this, or an example somewhere?

**Pull request merged**
