### PR TITLE
CI: use ci/build.sh in Jenkinsfile and only run checkstyle in the H2 build

### PR DESCRIPTION
**Pull request by yrodiere**
cc @gavinking

### CODE REVIEW

**Comment by gavinking** [comment]
Thanks man!!

**Comment by yrodiere** [comment]
The TIDB is giving me trouble, I added a bit of logs, let's try again...

**Comment by yrodiere** [comment]
Looks like this was a transient failure.

Everything seems to be working now, and I checked that `checkstyleMain` is only being executed when testing against H2.

This only affects CI, local builds will be unaffected.

So, ready to merge as far as I'm concerned.

**Comment by beikov** [comment]
Great work, thanks!

**Pull request merged**
