### PR TITLE
Fixes for documentation of schema-generation

### PR DESCRIPTION
**Pull request by martin-v**

### CODE REVIEW

**Comment by martin-v** [comment]
Any update?

**Comment by dreab8** [comment]
Hi @martin-v ,
 is there an associated Jira ?
Thanks

**Comment by martin-v** [comment]
No, there is no jira task. I found the errors in the documentation while working with hibernate.

**Comment by dreab8** [comment]
I created a [Jira](https://hibernate.atlassian.net/browse/HHH-14064) and applied the PR upstream.

Thanks @martin-v

**Pull request closed without merging**
