### PR TITLE
Fix blind cast of CallableStatement

### PR DESCRIPTION
**Pull request by theturrible**

### CODE REVIEW

**Comment by dreab8** [comment]
@theturrible , can you open a Jira for this issue, and add a test case
Thanks a lot

**Comment by vladmihalcea** [comment]
@theturrible I tried to check when this branch is executed, and it's not the regular ProcedureCall. Is it that you were using stored procedure for CRUD?

**Comment by mk2301** [comment]
I think this is issue [HHH-10256](https://hibernate.atlassian.net/browse/HHH-10256)

**Comment by vladmihalcea** [comment]
Fixed with [the following commit](https://github.com/hibernate/hibernate-orm/commit/3adb0d76be65a098096274f2dbd9c34fac0788f5).

**Pull request closed without merging**
