### PR TITLE
HHH-18196 Remove Session#save / Session#update / Session#saveOrUpdate

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-18196
https://hibernate.atlassian.net/browse/HHH-18195

this [commit](https://github.com/hibernate/hibernate-orm/pull/8692/commits/425f5192a33c76ecaedfafa547eb7adab397f01b) contains all the changes to main relate to `Session#save` ,`Session#update` and `Sesion#saveOrUpdate`. the other commits contain changes to tests 

this [commit](https://github.com/hibernate/hibernate-orm/pull/8692/commits/cb278756661efa037b83c16eb2a18aff33984d51) removes  @SelectBeforeUpdate

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

https://hibernate.atlassian.net/browse/HHH-18195

### CODE REVIEW

**Comment by gavinking** [comment]
Woooooo, finally, after all these years :)

**Comment by dreab8** [comment]
if all tests pass we can merge this and tomorrow I'll start writing the migration guide

**Comment by sebersole** [comment]
Hm, I think my comment on the migration-guide commit got lost...

I think we should keep the "removals" section minimal and just say "we removed #update and #saveOrUpdate" and cover the implications in a dedicated section.

I can work on that if you prefer (you mentioned you might, so just reiterating that here I can).

**Comment by sebersole** [comment]
I merged it.  We can work on the migration guide in follow up tasks - there is more work to be done there anyway.

Thanks!

**Comment by jpmsilva** [comment]
In light of issues regarding the handling of JPA lifecycle events and Hibernate events, as seen [here](https://discourse.hibernate.org/t/preinserteventlistener-receives-incomplete-copy-of-entity/9310), would it be possible to hold off the removal of these methods?
Currently, when using the persist-or-merge strategy, event handlers potentially receive an incomplete copy of the entity in the event payload.
Using save-or-update instead presents no such issue.

**Comment by gavinking** [comment]
> In light of issues regarding the handling of JPA lifecycle events and Hibernate events, as seen [here](https://discourse.hibernate.org/t/preinserteventlistener-receives-incomplete-copy-of-entity/9310), would it be possible to hold off the removal of these methods?

Nope, they are already gone. We're not going to put them back. (Really, they should have been removed about a decade ago.)

**Pull request merged**
