### PR TITLE
HHH-11138 - Upgrade to Javassist 3.21 (Java 9 support)

### PR DESCRIPTION
**Pull request by sebersole**

### CODE REVIEW

**Comment by sebersole** [comment]
I did this as a PR because we need to decide what version to apply this change to.

**Comment by Sanne** [comment]
Looks safe for master? Why not?

**Comment by Sanne** [comment]
(except the "SNAPSHOT" dependency of course)

**Comment by Sanne** [comment]
@sebersole sorry I forgot about this PR. Seems obsolete? I recently updated ORM to Javassist 3.22.0-GA (HHH-12048).

**Comment by Naros** [comment]
This has been in 5.2 and 5.3 for a while since https://github.com/hibernate/hibernate-orm/commit/9ed4438f172bf28d9fb3ab7278c3c04393c60ac4, closing it as stale.

**Pull request closed without merging**
