### PR TITLE
HHH-8306

### PR DESCRIPTION
**Pull request by whitingjr**
Add Gradle task and plugin for entity enhancements. Configuration supports defining more that one context. The default configuration is one context.

### CODE REVIEW

**Comment by kaqqao** [comment]
It's pretty much impossible to find any info on how to actually use this plugin... Could you please provide at least some basic info?

**Comment by vladmihalcea** [comment]
The new Usre Guide has a [section about the Gradle plugin]()http://docs.jboss.org/hibernate/orm/5.1/userguide/html_single/Hibernate_User_Guide.html#BytecodeEnhancement-enhancement-gradle).

**Comment by sebersole** [comment]
Which is information taken from the older topical guide:
http://docs.jboss.org/hibernate/orm/5.0/topical/html/bytecode/BytecodeEnhancement.html

**Comment by kaqqao** [comment]
Thanks for the links!
Still can't get it to work for the life of me, but I guess this isn't the right place for asking for help on that.
Should you care about the issues I'm having, I have a [question on StackOverflow](http://stackoverflow.com/questions/35552109/how-to-setup-hibernate-gradle-plugin-for-bytecode-enhancement). Thanks again.

**Comment by barreiro** [comment]
@vladmihalcea don't know if this causes some confusion or not, but the new user guide seems to lack the changes made in HHH-10359 (in particular regarding the default values).

**Comment by vladmihalcea** [comment]
I'll have to check what has changed and update the doc.

**Pull request closed without merging**
