### PR TITLE
HHH-13608 Oracle8iDialect should use CASE_INSENSITIVE pattern matching when checking the statement type

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-13608

### CODE REVIEW

**Comment by dreab8** [comment]
rebased and applied upstream.

Thanks @vladmihalcea

**Comment by vladmihalcea** [comment]
@dreab8 Thanks for integrating it.

**Comment by dreab8** [comment]
Hi @vladmihalcea , I have reverted this commit due to failures of `org.hibernate.test.queryhint.QueryHintTest#testQueryHint()` and `org.hibernate.test.queryhint.QueryHintTest#testQueryHintAndComment()`

**Comment by dreab8** [comment]
sorry @vladmihalcea I think I spotted the issue

**Comment by vladmihalcea** [comment]
I was fixing and testing it now. If you already fixed it, I'll leave it the. It requires a replace for the entity name as the entity uses an explicit name as it should.

**Comment by dreab8** [comment]
yes I have already done, Thanks

**Pull request closed without merging**
