### PR TITLE
HHH-4369 Introduce @Comment for comment on column

### PR DESCRIPTION
**Pull request by quaff**

### CODE REVIEW

**Comment by Valenzione** [comment]
Very interested in this! +1

**Comment by quaff** [comment]
Could anyone review it?

**Comment by vmsh0** [comment]
> Could anyone review it?

For all it's worth (I'm not an Hibernate developer) I went through the PR and everything looks fine. Let's hope it gets pulled.

**Comment by gbadner** [comment]
Oops, I inadvertently gave this a thumbs-up. I haven't actually looked at this...

**Comment by JasonQJC** [comment]
good feature, I need this

**Review by MurraySpeight — APPROVED** [review]

**Comment by ArayChou** [comment]
I am eager to have this feature. When can I use this feature? Thanks.

**Review by potados99 — APPROVED** [review]
I am really waiting on it!

**Review by potados99 — APPROVED** [review]

**Comment by quaff** [comment]
@Sanne Could you take a look at this? It seems lots of people want it.

**Comment by Sanne** [comment]
hey all, yes this looks nice!

Many thanks and sorry for not having seen it sooner - thanks @quaff and @beikov for reminding me

**Comment by shirohoo** [comment]
Wow! very interested in this! Thanks ! 😄😄😄

**Comment by quaff** [comment]
> in oralce database, when add new column field，it's don't work!

Please file a new issue to hibernate [JIRA](https://hibernate.atlassian.net/), test case is required.

**Pull request merged**
