### PR TITLE
HHH-14006 Extended Bytecode enhancement fails for inherited public fields

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HHH-14006

### CODE REVIEW

**Comment by barreiro** [comment]
@yrodiere  what about `javassist` bytecode enhancer ... have you ran the tests with `hibernate.bytecode.provider=javassist`?

**Comment by yrodiere** [comment]
@yrodiere I did not. Isn't it deprecated and disabled by default?

I can see if there is a way to fix the problem there too, but if we want to drop support for javassist soon, I personally would vote against even trying.

**Comment by yrodiere** [comment]
@barreiro I just ran the test, and it passes without any change with Javassist.

Turns out we use `getField`, not `getDeclaredField`, in the Javassist enhancer:

```
							|| !enhancementContext.isPersistentField( targetCtClass.getField( fieldName ) )
```

**Comment by gsmet** [comment]
Yeah, I would say let's not even try if we don't have anyone explicitly asking for it.

**Comment by barreiro** [comment]
@yrodiere thanks for checking. I usually try keep both implementations up to date so that we can compare how both behave when there are issues.

**Comment by Sanne** [comment]
thank @yrodiere ! Merged it

**Pull request closed without merging**
