### PR TITLE
HHH-17715 Upgrade Antlr to 4.13.1

### PR DESCRIPTION
**Pull request by scottmarlow**
https://hibernate.atlassian.net/browse/HHH-17715

### CODE REVIEW

**Comment by scottmarlow** [comment]
backport is https://github.com/hibernate/hibernate-orm/pull/7800

**Comment by beikov** [comment]
Wdyt about updating ANTLR in Quarkus for this @gsmet @yrodiere?

**Comment by yrodiere** [comment]
> Wdyt about updating ANTLR in Quarkus for this @gsmet @yrodiere?

In 6.5, that's fine by me.

In 6.4... If it's just a micro I guess that's fine too? I only know of Panache using Antlr in Quarkus, but I guess there are other libraries -- @gsmet would know better than me.

**Comment by Sanne** [comment]
It also needs to be aligned with the versions Drools and KIA needs: there's several extensions in Quarkus and they need to be strictly aligned.

**Comment by scottmarlow** [comment]
> It also needs to be aligned with the versions Drools and KIA needs: there's several extensions in Quarkus and they need to be strictly aligned.

It is sounding like an expensive upgrade to make if it impacts all ^ in terms of testing and possibly making adjustments.

**Comment by Sanne** [comment]
Indeed. To be clear I wouldn't upgrade ANTLR unless we have a concrete reason to wish to upgrade (like I similarly said for Bytebuddy in the other thread): is there a good reason for Wildfly wishing to upgrade? I see no link to a Wildfly issue..

IMO just wanting to use the latest is not necessarily one; I don't mean of course that we'd want to keep using very old libraries, but I see no reason to chase micro updates aggressively.

**Comment by Sanne** [comment]
Found the WildFly PR, gave more context there:
 - https://github.com/wildfly/wildfly/pull/17552#issuecomment-1932983358

**Comment by scottmarlow** [comment]
> Found the WildFly PR, gave more context there:
> 
>     * [Bump version.antlr from 4.13.0 to 4.13.1 wildfly/wildfly#17552 (comment)](https://github.com/wildfly/wildfly/pull/17552#issuecomment-1932983358)

Thanks @Sanne!  I'll close the issue and these pull requests.

**Pull request closed without merging**
