### PR TITLE
Hhh 11090 master

### PR DESCRIPTION
**Pull request by gbadner**
Pull request for HHH-11090.

### CODE REVIEW

**Comment by sebersole** [comment]
You asked for me to comment on the general approach...  So the (big!) part missing here is supporting changes in these unique keys.  This is something specific I had to account for (for example) in natural-id support.  This is the code in `org.hibernate.engine.internal.NaturalIdXrefDelegate`.  You'd need something similar here.  IMO this overhead is not worth it.

**Comment by gbadner** [comment]
Thanks for the feedback.

I just came across the code you mention for natural IDs. I will look into whether that functionality can be leveraged instead.

**Comment by sebersole** [comment]
If the UK is the natural-id it certainly could.

**Comment by sebersole** [comment]
Well actually stepping back on this a bit...

I guess your work here so far is really just to add an entry into `StatefulPersistenceContext#entitiesByUniqueKey` in places where we are missing it.  Since we already cache these values, I think its appropriate to push those values properly.  That is fine.  The lack of invalidation on change is a separate issue, since we already do not do that

**Comment by gbadner** [comment]
@sebersole, for mutable, unique properties that are not natural IDs, I think it makes sense to simply delete the mappings in StatefulPersistenceContext#entitiesByUniqueKey after the (load, merge, etc) operation completes. It could be in the OperationContext in H6. I'd have to look into how this could work in H5. WDYT?

**Comment by sebersole** [comment]
That is a safe approach for sure.  And if we are moving to that paradigm of scoping that cache to the context of that load, then I think it makes sense to move that off of `StatefulPersistenceContext`.  I'm not sure if `OperationContext` is the correct place for that, or something more like `org.hibernate.engine.loading.internal.LoadContexts`, or something entirely new.  `LoadContexts` is available already, so that would not necessarily have to wait for 6.0.  

Let's hold off on the 6.0 part until after we get `OperationalContext` integrated into that base and then you, me, @dreab8 and @Naros can all discuss that aspect more informed.

**Comment by sebersole** [comment]
@gbadner Where do we stand with this one?

**Pull request closed without merging**
