### PR TITLE
[master] HHH-11254 Timestamps cache fails validation if eviction strategy = MANUAL

### PR DESCRIPTION
**Pull request by pferraro**
https://hibernate.atlassian.net/browse/HHH-11254

### CODE REVIEW

**Comment by sebersole** [comment]
@rvansa @pferraro Can you also conceive of a test that asserts this change?

**Comment by pferraro** [comment]
@sebersole The current tests that cover query caching already flow through this validation. If we additionally to validate that EvictionStrategy.MANUAL is allowable (the only other strategy for which isEnabled() does not return true), then we'd need to upgrade to Infinispan to 8.2.5.Final.

**Comment by rvansa** [comment]
I think this can get in as-is - Infinispan just got another enum value that's effectively `NONE` but provides different warnings. `EvictionStrategy.isEnabled()` returns false for those two enum values.

**Comment by Sanne** [comment]
@pferraro +1 to upgrade to Infinispan to 8.2.5.Final, I'll do that.

**Comment by Sanne** [comment]
I'll merge this as we need the fix. If anyone still thinks a test is due, please open a follow-up JIRA so we can address that as a separate task.

**Comment by Sanne** [comment]
thanks @pferraro ! closing this as it's being cherry-picked.

**Pull request closed without merging**
