### PR TITLE
HHH-10838 Upgrade to Gradle 2.13 and respective wrapper files

### PR DESCRIPTION
**Pull request by Sanne**
The changes in the `gradlew` file are generated by the upgrading script of the wrapper.

### CODE REVIEW

**Comment by dreab8** [comment]
@Sanne should not be updated also the gradle/wrapper/gradle-wrapper.jar?

**Comment by Sanne** [comment]
> should not be updated also the gradle/wrapper/gradle-wrapper.jar?

My tests seem to state it's not required. The script downloads the right wrapper on demand. Let me know if this doesn't work for you..

**Comment by dreab8** [comment]
@Sanne you are right, it was just for consistence, we have this jar on github

**Comment by Sanne** [comment]
ok I'll not change it then: seems rather annoying to keep updating a binary file in the repository.

**Comment by Sanne** [comment]
closing this as it's obsolete now, @sebersole upgraded to Gradle 3.0-milestone-1

**Pull request closed without merging**
