### PR TITLE
HHH-10924 Replace ConcurrentServiceBinding by ConcurrentHashMap

### PR DESCRIPTION
**Pull request by golovnin**
https://hibernate.atlassian.net/browse/HHH-10924

### CODE REVIEW

**Comment by Sanne** [comment]
Hi @golovnin , please explain why?

I created this `ConcurrentServiceBinding` specifically to for this use case, and to resolve a performance problem which we had with `ConcurrentHashMap`.

Of course things change, so maybe now this is no longer true but I'd like to see some evidence about it.

**Comment by golovnin** [comment]
@Sanne please read the description of HHH-10924. It contains the explanation.

**Comment by Sanne** [comment]
awesome, thanks! Sorry I missed it.

**Comment by Sanne** [comment]
rebasing and testing again: will merge soon.

**Comment by Sanne** [comment]
merged, thanks! Very nice to see other people deeply interested in squeezing the most performance possible out of it :+1:

**Pull request closed without merging**
