### PR TITLE
Minor refactoring to make some logic accessible to Hibernate Reactive

### PR DESCRIPTION
**Pull request by DavideD**
Fix [HHH-15761](https://hibernate.atlassian.net/browse/HHH-15761)

### CODE REVIEW

**Review by beikov — APPROVED** [review]
LGTM

**Comment by DavideD** [comment]
I've also added scope change for `QuerySqmImpl#isSimpleValuesInsert`

**Comment by DavideD** [comment]
I've rebased this PR to the latest changes, I'm going to merge it if it passes the build.

**Comment by DavideD** [comment]
I'm closing this pr.
I will send a new one with more changes

**Pull request closed without merging**
