### PR TITLE
New testing `@Jpa` annotation

### PR DESCRIPTION
**Pull request by sebersole**

### CODE REVIEW

**Review by dreab8 — APPROVED** [review]
It looks great :+1:

**Review by beikov — APPROVED** [review]
Looks great!

**Comment by beikov** [comment]
According to the CI run there are 2 compiler errors though:

```
/home/runner/work/hibernate-orm/hibernate-orm/hibernate-core/src/test/java/org/hibernate/orm/test/annotations/id/generationmappings/NewGeneratorMappingsTest.java:51: error: cannot find symbol
@ServiceRegistry(settings = @ServiceRegistry.Setting(name =Environment.HBM2DDL_AUTO, value = ""))
> Task :hibernate-core:compileTestJava
                                            ^
  symbol:   class Setting
  location: @interface ServiceRegistry
/home/runner/work/hibernate-orm/hibernate-orm/hibernate-core/src/test/java/org/hibernate/test/id/idClass/IdClassNamingStrategyTest.java:34: error: cannot find symbol
@ServiceRegistry(settings = @ServiceRegistry.Setting(name = IMPLICIT_NAMING_STRATEGY, value = "component-path"))
```

**Comment by jrenaat** [comment]
> According to the CI run there are 2 compiler errors though:
> 
> ```
> /home/runner/work/hibernate-orm/hibernate-orm/hibernate-core/src/test/java/org/hibernate/orm/test/annotations/id/generationmappings/NewGeneratorMappingsTest.java:51: error: cannot find symbol
> @ServiceRegistry(settings = @ServiceRegistry.Setting(name =Environment.HBM2DDL_AUTO, value = ""))
> > Task :hibernate-core:compileTestJava
>                                             ^
>   symbol:   class Setting
>   location: @interface ServiceRegistry
> /home/runner/work/hibernate-orm/hibernate-orm/hibernate-core/src/test/java/org/hibernate/test/id/idClass/IdClassNamingStrategyTest.java:34: error: cannot find symbol
> @ServiceRegistry(settings = @ServiceRegistry.Setting(name = IMPLICIT_NAMING_STRATEGY, value = "component-path"))
> ```

IINM these classes aren't present in Steve's PR head; they are in two commits by Andrea on nov 25 and nov 18, respectively.
The topic branch should prob. be rebased onto wip/6.0 to get the latest commits?

**Review by jrenaat — COMMENTED** [review]
Looks great, but the topic branch should perhaps have to be updated with the latest from wip/6.0

**Review by jrenaat — APPROVED** [review]

**Comment by dreab8** [comment]
I managed to fix the compilation errors caused by the new tests I added, pushing it to wip/6.0.

**Pull request closed without merging**
