### PR TITLE
HHH-14574 Avoid NPEs from LoadContexts.cleanup(ResultSet)

### PR DESCRIPTION
**Pull request by dreis2211**
See https://hibernate.atlassian.net/browse/HHH-14574

### CODE REVIEW

**Review by educhastenier — APPROVED** [review]
Looks good to me :+1: even if there is no unit test (Just kidding 😃  there would be no value of such a test)

**Comment by educhastenier** [comment]
Why not fix it on a previous maintenance branch?

**Comment by dreis2211** [comment]
I'd appreciate this, @educhastenier - but I'd leave an eventual backport decision to the maintainers. It should apply cleanly.

**Comment by dreab8** [comment]
Thanks @dreis2211 for the PR

**Pull request merged**
