### PR TITLE
HHH-11634 - reordering inserts issue

### PR DESCRIPTION
**Pull request by MirekSz**
Persist ordering to make error occur

### CODE REVIEW

**Comment by vladmihalcea** [comment]
I reopened the issue.

**Comment by vladmihalcea** [comment]
I fixed it. I'll push the fix tomorrow.

**Comment by MirekSz** [comment]
Super, I'm very curious of the solution because its strange bug. I hope that explanation in jira comment(https://hibernate.atlassian.net/browse/HHH-11634?focusedCommentId=93241&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-93241) helps you a bit.
 Of course persisting SaleDocumentItem before SaleDocument it's weird but its quite big app with 3000 entities and sometimes cross module algorithm create some strange order

**Comment by vladmihalcea** [comment]
Applied [this fix](https://github.com/hibernate/hibernate-orm/commit/020414e1aa79058c8a3196898a815079c38a8315) and it works fine now.

**Pull request closed without merging**
