### PR TITLE
HHH-13225 - fix minorVersionToMatch comparison

### PR DESCRIPTION
**Pull request by zeratul021**
...and generify Dialect class for type safety, updated tests.

### CODE REVIEW

**Comment by gsmet** [comment]
Looks good to me, thanks. I'm making a few changes to the tests so that the `@TestForIssue` annotation is really on the new tests and I'll merge.

**Comment by gsmet** [comment]
I thought a bit more about it and unfortunately `BasicDialectResolver` is considered SPI so something the user could consume and/or extend so we cannot break it for now.

We should do that in 6 though if the class is still there. I'll do that when I forward port this patch to 6.

**Comment by gsmet** [comment]
Merged the part I could merge. Thanks!

**Comment by zeratul021** [comment]
@gsmet I've checked the merged commit seems to contain everything.
Or did you mean that you couldn't merge to current 5.4.x branch (not sure what branching setup/workflow is used here)?

**Comment by gsmet** [comment]
Hmmm, no, it does not contain everything but you're right one one thing: it does contain one of the change I didn't want. I will push an additional commit to remove the `<? extends Dialect>` from the third constructor.

Is it what bugged you or did I miss another thing?

**Comment by zeratul021** [comment]
@gsmet I think thats what mislead me. I saw the SPI change in generic signature and assumed you merged all of it. Thanks

**Pull request closed without merging**
