### PR TITLE
HHH-17956 Criteria multiselect ignores type of the criteria query and always returns list of Object[]

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-17956

### CODE REVIEW

**Comment by gavinking** [comment]
@beikov please also consider what happens with the following code:

```java
var query = factory.getCriteriaBuilder().createQuery(String[].class);
var bookRoot = query.from(Book.class);
query.multiselect(bookRoot.get("isbn"), bookRoot.get("title"), bookRoot.get("pages"));
var resultList = entityManager.createQuery(query).getResultList();
```

If we're going to allow this sort of thing, then we need to check upfront that the type of the `Selection`s passed to `multiselect()` are actually assignable to the element type of the array.

This was previously not necessary because we assumed that the array type was always `Object[]`.

**Comment by gavinking** [comment]
A second item of feedback is: even the javadoc of `multiselect()` doesn't suggest that _primitive_ arrays should be supported here.  Quote:

> If the type of the criteria query is `CriteriaQuery<X[]>` for **some class X**, an instance of type `X[]` will be returned for each row.

And I don't think primitive arrays make sense because it's pretty hard for us to validate that a `Selection<Integer>` is non-null.

Furthermore, it seems that the support for primitive arrays is leading to most of the complexity in this PR. If support for primitive arrays were removed, I guess this would be a whole lot simpler, no?

**Comment by beikov** [comment]
> And I don't think primitive arrays make sense because it's pretty hard for us to validate that a `Selection<Integer>` is non-null.

If users requests an `int[]` as result type, they must ensure the values are non-null.

>Furthermore, it seems that the support for primitive arrays is leading to most of the complexity in this PR. If support for primitive arrays were removed, I guess this would be a whole lot simpler, no?

Of course handling primitive arrays requires more code, but I think it's useful and our session with @franz1981 has shown that performance is not an issue, so we might as well do it IMO.

**Comment by gavinking** [comment]
> I think it's useful

It seems to me that the complexity/usefulness ratio here is really quite low.

**Pull request merged**
