### PR TITLE
Issue HHH-12368.

### PR DESCRIPTION
**Pull request by toughpheeckouse**

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Superseded by this [Pull Request](https://github.com/hibernate/hibernate-orm/pull/2572).

**Comment by Marco-Sulla** [comment]
Excuse me, but the problem is: why Hibernate is not able to create LOBs with Postgres? For what I know, Postgres support them.

**Comment by Marco-Sulla** [comment]
> Excuse me, but the problem is: why Hibernate is not able to create LOBs with Postgres? For what I know, Postgres support them.

Hello?

**Comment by vladmihalcea** [comment]
I no longer work for the Hibernate project, so you are better off asking the Hibernate team on the official forum about this issue.

**Pull request closed without merging**
