### PR TITLE
HHH-13226 : Corrected Typo

### PR DESCRIPTION
**Pull request by asutosh936**

### CODE REVIEW

**Comment by gsmet** [comment]
Thanks! Unfortunately, it's a bit more complicated: you need to keep the old ones and deprecate them as people might already use them.

Both properties would need to be supported (with the new one taking precedence over the old one if both are set).

**Comment by asutosh936** [comment]
@gsmet - Have tried to implement the review comments You provided. Not sure the changes are correct but kindly review and let me know how I can help further on this issue.

**Comment by Sanne** [comment]
hi @asutosh936 , 

you're going in the right direction, but you also need to ensure that:
 - the new property is being applied when people set it (search for references to the contstants in the code)
 - the old property is also applied, yet logs a warning about using a deprecated configuration property

See for example `org.hibernate.tool.schema.internal.Helper#interpretNamespaceHandling` ; there might be more such cases.

**Comment by asutosh936** [comment]
@gsmet @Sanne - Kindly review and merge if changes looks good.

**Comment by gsmet** [comment]
@asutosh936 are you sure you pushed your changes? I don't see any compatibility code?

**Comment by asutosh936** [comment]
@gsmet - Have pushed the changes.

**Comment by Sanne** [comment]
thanks @asutosh936 , I merged your fix and added a couple additional commits to address some more backwards compatibility aspects.

**Pull request closed without merging**
