### PR TITLE
prefer localtime, localtimestamp on H2, HSQL, and Postgres (H6)

### PR DESCRIPTION
**Pull request by gavinking**
- As suggested by @famod we need to use `localtime` instead of `current_time` because of changes in H2.
- However, it actually makes sense to use `localtime` and `localtimestamp` on other databases too, starting with HSQLDB and Postgres.
- Also much more clearly document this stuff in the Javadoc for `Dialect`.

See https://github.com/hibernate/hibernate-orm/pull/3412

### CODE REVIEW

**Comment by gavinking** [comment]
@dreab8 @sebersole Please note that this is a change to H6, not master.

**Comment by dreab8** [comment]
thanks @gavinking  added 6.0 label

**Review by beikov — APPROVED** [review]

**Comment by beikov** [comment]
We (Andrea and I) will merge it after reviewing all your other PRs.

**Comment by dreab8** [comment]
Merged, thanks @gavinking !

**Pull request closed without merging**
