### PR TITLE
HHH-10601 - Persistence.generateSchema - the output file contains duplicated DDL statements

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-10601

### CODE REVIEW

**Comment by sebersole** [comment]
So the problem is that creating the SF kicked off "auto schema tooling"?

**Comment by dreab8** [comment]
Yes, it is.

**Comment by dreab8** [comment]
In SF constructor the
 			SchemaManagementToolCoordinator#process(...) Is call again.

**Comment by sebersole** [comment]
Sounds reasonable then

**Comment by dreab8** [comment]
applied to 5.1 and master

**Pull request closed without merging**
