### PR TITLE
HHH-7898 Regression on org.hibernate.cache.infinispan.query.QueryResu…

### PR DESCRIPTION
**Pull request by rvansa**
…ltsRegionImpl.put(Object, Object)

* Moved query cache update to second phase of transaction commit
* Query caches are now recommended to be non-transactional (transactional ones will be slower)

JIRA: https://hibernate.atlassian.net/browse/HHH-7898

### CODE REVIEW

**Comment by rvansa** [comment]
One thing worth mentioning: with this fix, if the same transaction executes the same query, the value is not in transactional context nor committed in the cache and therefore, it will result in cache miss.
This is not revealed by current tests since the cache was made non-transactional, and the region detects current transaction based on the transaction manager retrieved from the cache, not from the transaction manager used to executed the whole operation. Therefore, the tests execute non-transactional code.

**Comment by rvansa** [comment]
I've added a logic that does not break one of the unit tests, but it's based on some other changes that await as PR. Though, I am not sure if I should implement the same logic for non-JTA transactions - currently it simply writes the entry before the transaction commits. However, can I execute another JDBC transaction from afterCompletion? TransactionCoordinator does not have any API for suspend.

**Comment by sebersole** [comment]
````
TransactionCoordinator tc = ...;
tc.createIsolationDelegate().delegateWork( ... )
````

**Comment by rvansa** [comment]
@sebersole Ah, ok :) I'll make this TX impl agnostic :)

**Comment by rvansa** [comment]
@sebersole Using the isolation delegate simplifies the code a lot, though, it would be better if I didn't have to obtain the connection when I don't need it.

**Comment by rvansa** [comment]
Reworked... I had to reshuffle the query cache tests a bit to correctly use sessions, but it was worth it.

**Comment by sebersole** [comment]
@rvansa We already have the Connection.  There is no overhead in it being there.  -1 for adding a new method just to not accept it.

**Comment by sebersole** [comment]
@rvansa On HHH-7898 you mentioned that this work also needed to account for HHH-9988.  But I do not see a PR for that.  Did you address that one here?  Somewhere else?  Not at all?

**Comment by rvansa** [comment]
@sebersole It seemed to me that `JtaIsolationDelegate.doTheWork` obtains separate connection, if it does not, my mistake.

Wrt HHH-9988: When using TransactionCoordinator, HHH-9988 is not necessary in fact, I'll correct it. Sorry about making things messy with several related JIRAs awaiting PRs. Btw., is there any recommended practice to tag the PR when it depends on another not-integrated changes?

**Comment by sebersole** [comment]
@rvansa actually you are right I think in regards to the Connection.  I guess I am ok with adding a new method there.  Let me know if you'd prefer me to work on that.

In regards to HHH-9988, awesome.  So should HHH-9988 be closed?

In regards to "dependent PRs".. The best you can refer to them and make sure everything is cross linked.  For now, maybe ping me on IRC and walk me through which need applied?

**Comment by dreab8** [comment]
Thanks @rvansa ,

PR fixed conflicts, rebased and merged

**Pull request closed without merging**
