### PR TITLE
HQL numeric literal tests

### PR DESCRIPTION
**Pull request by sebersole**
@beikov Can you tell me where I am missing your concern over numeric literals?  All these tests pass, so I must be missing something

### CODE REVIEW

**Comment by gavinking** [comment]
> I don't know if code in the SQM/SQL translators could ever calculate something with the literals

This is a good point. 👍 We should make sure that the translator never simplifies numeric expressions involving literals. That is, we should make sure that every numeric literal is passed through "literally", and not attempt to interpret it as a `Double`.

I think that _is_ already the case, but if there's some doubt about it we should check. 

(I just did a quick search for callers of `Double.parseDouble()`, and I don't see anything obvious, but I did not look carefully.)

> The JPA spec 4.6.1 and SQL spec 5.3 say that numbers without type suffixes have to be exact.

Mmmmm, actually I think that single sentence of the JPA spec is _extremely_ ambiguous, which is why I'm proposing to the JPA group that it be clarified. My best reading of the spec is that it's simply silent on the _semantics_ of numeric literals. It defines the _syntax_ that should be accepted, without specifying the interpretation of that syntax. OTOH, I think the reasonable inference is that the semantics/typing of JPQL literals is supposed to be the same as the semantics of Java literals.

On the other hand, I _do_ agree with you Christian that in the—admittedly extremely unlikely, and frankly even a bit suspicious—case that we encounter a literal with more digits than can be represented as a double (~15 decimal digits) then we need to make certain that this literal is passed through to the database unmolested so that it will be interpreted in SQL. We should make sure we don't call `Double.parseDouble()` on it.

**Comment by gavinking** [comment]
> I think that is already the case, but if there's some doubt about it we should check.

Ooops, I'm wrong, we do indeed truncate floating point literals to 10 digits. So we need to fix that. (I don't know where we do it, but it happens somewhere.)

So @beikov is 100% right.

**Comment by sebersole** [comment]
I'm thinking we should push this until after the 6.3 (Alpha/Beta/CR) release today.  It's not a great situation, but I don't think it is massively critical for a pre-production release and I'd rather not keep pushing that release.

But let's devise the plan moving forward here...  This breaks down into 2, 3 questions I think:

1. How do we handle the literal value in terms of what we render into the SQL?
2. How do we type the AST nodes?  
3. As a follow-on to (2), how do we treat "known overflows"?  Ignore or error...

WRT (1), I think its going to be best to embed the text as-is into the SQL directly as opposed to embedding the parsed value.  That will help with the loss of precision.

WRT (2) and (3), I think it really comes down to whether we want to parse the values or do something like your length counting @beikov.  Parsing for decimal values, if we go that route, should be done using `BigDecimal`.

**Comment by sebersole** [comment]
After looking at the code, my first thought was a new `SqmDecimalLiteral` and corollary `SqlDecimalLiteral` nodes that handle these concerns.  However, it seems like this will end up being a lot of work at all of the various call sites where a `SqmLiteral` is currently created (roughly 57).

**Comment by beikov** [comment]
IMO we don't need any new SQM nodes. AFAICT parsing and typing such a literal as `BigDecimal` should always work because all numeric types can be widened to `BigDecimal` according to our currently implemented rules. So (1) and (2) should be covered by https://github.com/hibernate/hibernate-orm/pull/6885
Since that solution will parse the literal into a type that can fit the value, (3) is not a concern as there won't be an overflow.

**Comment by beikov** [comment]
The sections from the JPA spec say

>Exact numeric literals support the use of Java integer literal syntax as well as SQL exact numeric literal syntax.
>Approximate literals support the use Java floating point literal syntax as well as SQL approximate numeric literal syntax.

The SQL spec specifies the scientific notation `1.123e10` to be the approximate numeric literal syntax and even though the spec does not explicitly say that such literals need to be typed as `BigDecimal`/`BigInteger` or anything alike, the word "exact" implies to me that there should be no loss of information.

**Comment by gavinking** [comment]
@beikov My best interpretation of that (admittedly-highly-ambiguous) section of the JPA spec is that a literal like `123.456` or `1.23e10` should be interpreted exactly as it is in Java. So the following query:

    select 123.456

should return type `Double`, not `BigDecimal`, exactly as it does in all versions of Hibernate prior to H6.

i.e. the type of such a literal _from the point of view of the HQL language_ is `Double`.

However, that doesn't mean we should truncate the precision of literals which can't be represented as a double. As you quite rightly point out, we should never do that. Rather, we should pass the literal value unmodified to the database.

As to the JPA spec ambiguity, I'm going to talk to Lukas about that this week, because I think we can quite easily get that nailed down.

**Comment by beikov** [comment]
Since we have unparsed numeric literals in the SQL AST now, I'll close this.

**Pull request closed without merging**
