### PR TITLE
HHH-11907 - Add the getResultStream() default method in org.hibernate.query.Query

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-11907

### CODE REVIEW

**Comment by Sanne** [comment]
LGTM ! Thanks

**Comment by sebersole** [comment]
As I mentioned on the mailing list, I have asked for clarification from the E.G. regarding the name of this method.  As I remember from E.G. discussions we had all agreed to name this `#stream` rather than `#getResultStream`.  `#getResultStream` was the original proposal, so I think that "changes doc" you saw may have just not been updated.

Let's wait to hear back about that.  If my memory is correct, we'd really have nothing to do here as we already define `#stream`

**Comment by vladmihalcea** [comment]
@sebersole I saw that the [JPA spec page](https://www.jcp.org/en/jsr/detail?id=338) does not yet offer a final spec document. I'll check the web site from time to time and come back to this issue once we know for sure what's been decided.

**Comment by sebersole** [comment]
I asked specifically.  So I'll let you know as soon as I know :)

**Comment by ggam** [comment]
@vladmihalcea  the documenta are available on the JPA spec repository https://github.com/javaee/jpa-spec/tree/master/jsr338-MR

@sebersole did you post the message directly to the JPA mailing list?. I haven't received the email although I'm subscribed. Moreover, I sent a message myself this week but seems like it didn't work either.

**Comment by sebersole** [comment]
I asked the lead directly as well as sending an email to the E.G. via reply to the original discussion thread.  I have not heard back from the spec lead and have not checked the email I use for the E.G. (I will tomorrow)

**Comment by vladmihalcea** [comment]
@sebersole As you mentioned in the [Hibernate mailing list](http://lists.jboss.org/pipermail/hibernate-dev/2017-August/016406.html), it looks like `getResultStream` is what was chosen in the end, so we can integrate this issue.

**Pull request merged**
