### PR TITLE
HHH-10837 Add new setting to disable/enable scanning for the static metamodel.

### PR DESCRIPTION
**Pull request by golovnin**
https://hibernate.atlassian.net/browse/HHH-10837

### CODE REVIEW

**Comment by Sanne** [comment]
Great idea! Could you add the new configuration property also in the documentation?

**Comment by golovnin** [comment]
@Sanne Thank you for pointing me to the docs because while looking for the place where to add the documentation for the new setting I found this setting `hibernate.ejb.metamodel.population` (never seen it before). But even when I set this setting to `disabled` Hibernate still searches for the classes of the static metamodel. Therefore I think there is a bug in `MetamodelImpl`. I think the line 219 should be inside the if-block in lines 213-218. It would be nice if @sebersole can take look at it and confirm whether my assumption is valid or not. If my assumption is valid, then we can close this PR and the JIRA issue and I can create a new JIRA issue and a new PR with the bugfix.

**Comment by vladmihalcea** [comment]
Hi, @golovnin

I believe we should have the `context.wrapUp();` inside that if that you suggested, so you can change the JIRA issue description and provide a new PR with that fix.

**Comment by sebersole** [comment]
@golovnin - we decided for 5.x we will need a second setting. 

`hibernate.ejb.metamodel.population` is intended to indicate whether to build the JPA types (`javax.persistence.Metamodel`).  I'm inclined to think that `hibernate.ejb.metamodel.population=disabled` ought to additionally stop searching for the JPA static metamodel.  But we decided it is worthwhile to have a second enum setting that parallels `hibernate.ejb.metamodel.population` but that controls looking for and populating the static metamodel.  We'll call this `hibernate.jpa.static_metamodel.population`.

For 6.0 we will drop the `hibernate.ejb.metamodel.population` setting as we will be combining type systems.

**Comment by dreab8** [comment]
@golovnin @sebersole @vladmihalcea 

what about ?

```
if ( jpaMetaModelPopulationSetting != JpaMetaModelPopulationSetting.DISABLED ) {
	MetadataContext context = new MetadataContext(
		sessionFactory,
		mappingMetadata.getMappedSuperclassMappingsCopy(),
		jpaMetaModelPopulationSetting
	);

	for ( PersistentClass entityBinding : mappingMetadata.getEntityBindings() ) {
		locateOrBuildEntityType( entityBinding, context );
	}
	handleUnusedMappedSuperclasses( context );

	context.wrapUp();

	this.jpaEntityTypeMap.putAll( context.getEntityTypeMap() );
	this.jpaEmbeddableTypeMap.putAll( context.getEmbeddableTypeMap() );
	this.jpaMappedSuperclassTypeMap.putAll( context.getMappedSuperclassTypeMap() );
	this.jpaEntityTypesByEntityName.putAll( context.getEntityTypesByEntityName() );

	applyNamedEntityGraphs( mappingMetadata.getNamedEntityGraphs().values() );
}

```

**Comment by dreab8** [comment]
I'm going to apply the changes discussed with @sebersole and submit a new PR.

Thanks 
@golovnin

**Comment by dreab8** [comment]
The nre PR https://github.com/hibernate/hibernate-orm/pull/1440

**Comment by golovnin** [comment]
I'm OK with the proposed changes. Thanks to everyone!

**Pull request closed without merging**
