### PR TITLE
HHH-13243 - Respect @ManyToAny.fetch setting to FetchType.EAGER

### PR DESCRIPTION
**Pull request by johnlinp**
This patch fixes the ManyToAny fetch mode for both annotation and XML configuration. Test cases are provided too.

### CODE REVIEW

**Comment by johnlinp** [comment]
Hi @vladmihalcea,

Can you take a look at this pull request? Thank you!

**Comment by vladmihalcea** [comment]
The 5.4 branch is for bug fixing only, so we will have to integrate this one on 6.0. I'll review it after the Alpha2 release, as not all mappings are working properly as of writing.

**Comment by johnlinp** [comment]
Hi @vladmihalcea, I thought it is a bug?

**Comment by johnlinp** [comment]
Hi @vladmihalcea, ping?

**Comment by vladmihalcea** [comment]
The 6.0 Alpha2 was not released, so I'm still waiting that release in order to integrate this PR.

**Comment by johnlinp** [comment]
Hi @vladmihalcea,

Since you said "5.4 branch is for bug fixing only" and this is a bug, I thought this PR should go into 5.4 branch?

**Comment by vladmihalcea** [comment]
This might be a bug, but it's not a critical one. If @gsmet think it should be merged, then we could merge it. Otherwise, we'll review it for 6.0.

**Comment by johnlinp** [comment]
This problem is similar to https://github.com/hibernate/hibernate-orm/pull/2683. It might be a good idea to fix them in the same major version.

**Comment by vladmihalcea** [comment]
In the meantime, it was decided to avoid integrating non-critical issues into 5.4. So, it's not me who takes the decision whether this will be integrated or not.

**Comment by johnlinp** [comment]
I see. Thanks for the explanation.

**Comment by johnlinp** [comment]
Hi @dreab8,

I saw you removed the 6.0 label, so I assume that this PR won't go with 6.0 release. Do you have any plan on which release this PR should merge into?

**Comment by dreab8** [comment]
Hi @johnlinp, we are using the 6.0 label for PR targeting the wip/6.0 branch so I removed it from this PR but I have not added the new label for PR we want to imclude in 6.0 but are targeting the master branch.

**Comment by dreab8** [comment]
Hi @johnlinp, we are using the 6.0 label for PR targeting the wip/6.0 branch so I removed it from this PR but I have not added the new label for PR we want to include in 6.0 but are targeting the master branch.

**Comment by johnlinp** [comment]
So, should I change the target branch to wip/6.0?

**Comment by dreab8** [comment]
not so easy, `ToAny` has not been yet implemented in 6.0.

**Comment by dreab8** [comment]
Hi @johnlinp,
I'm looking at the PR and thinking creating a new one to apply to 7 and probably to 6.6 but containing only the changes  addressing annotations (hbm has been deprecated and we are not planning to apply changes to that part anymore)

I can create a new PR but can you  please add as a comment to this PR the following
```
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).
```
thanks a lot.

**Comment by johnlinp** [comment]
@dreab8 Yes, please. Thank you for taking care of this!

By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

**Comment by dreab8** [comment]
Thanks @johnlinp,
 
superseded by https://github.com/hibernate/hibernate-orm/pull/9369

**Pull request closed without merging**
