### PR TITLE
HHH-16498 Hibernate DDL validation fails on enum database column type

### PR DESCRIPTION
**Pull request by cigaly**
See issue [HHH-16498](https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16498)

[Fixed version of [PR 6462](https://github.com/hibernate/hibernate-orm/pull/6462)]

[HHH-16498]: https://hibernate.atlassian.net/browse/HHH-16498?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

### CODE REVIEW

**Comment by cigaly** [comment]
Problem has been cause because `org.hibernate.tool.schema.internal.ColumnDefinitions#stripArgs` has beem leaving trailing space(s) after removing arguments.

Additionally, I will suggest to make folowing change as well:

```diff --git a/hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java b/hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
index 97c4fbf109..6ebde27fdf 100644
--- a/hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
+++ b/hibernate-core/src/main/java/org/hibernate/dialect/MySQLDialect.java
@@ -889,7 +889,7 @@ public class MySQLDialect extends Dialect {
        @Override
        public String getEnumTypeDeclaration(String name, String[] values) {
                StringBuilder type = new StringBuilder();
-               type.append( "enum (" );
+               type.append( "enum(" );
                String separator = "";
                for ( String value : values ) {
                        type.append( separator ).append('\'').append( value ).append('\'');
```

Although there is nthing wrong with existing code, but it can cause more problems similar to this one.

**Comment by beikov** [comment]
Just to confirm, the validation works now after you rebased? I'm fine with adding a test, but please squash the commits to remove the "unnecessary" commits.

**Comment by cigaly** [comment]
I've forgot to squash commits, so I've created completely new branch, starting from main and applied previous changes, changes test case, reverted initial patch, made proper fix (which is now very simple) . Now all checks are passing with this new PR.

**Comment by beikov** [comment]
Ok, then please push these changes ;)

**Comment by cigaly** [comment]
I've already pushed this morning. After changes in main branch, only prroblem is that ColumnDefinitions.stripArgs was leaving trailings space(s).

**Comment by beikov** [comment]
Please just drop the commits a3073844239d5274f496ed867eff381fc418c41d, 34be435c2aeda4e14639eb19477cd6cd711a0c15 and 6a6f8c4a5ab75af65d7b593055f7442f53ff8cae

**Review by beikov — APPROVED** [review]

**Comment by cigaly** [comment]
Patch for 6.2 is in [PR 6541](https://github.com/hibernate/hibernate-orm/pull/6541)

**Pull request merged**
