### PR TITLE
HHH-17164 - Proper, first-class soft-delete support

### PR DESCRIPTION
**Pull request by sebersole**
HHH-17164 - Proper, first-class soft-delete support

https://hibernate.atlassian.net/browse/HHH-17164

### CODE REVIEW

**Review by beikov — COMMENTED** [review]
Wouldn't it be better to merge the contents of `SoftDeleteColumn` into `SoftDelete` to avoid two different annotations? Since everything is defaulted anyway, it wouldn't be a big deal to do that AFAICT.

**Comment by sebersole** [comment]
It's nice to be able to define these at different levels.

**Comment by sebersole** [comment]
I am wondering though if we really want to allow nulls in the database for these mappings.  Not speaking about how common or uncommon such a strategy is, but more thinking about the queries needed to handle soft-deletes.

A sneaky aspect, that affects this, which I had not considered initially is that soft-deletes will require behavior very similar to `@NotFound` mappings.  Or at least might, depending on how we want to treat many-to-one references to a soft-deleted row.  Specifically whether we want to manage the "extra" referential integrity ourselves and force nulling the fk value or if we want to consider data like this as valid:

```
customer {
    id = 1,
    removed=true,
    ...
}

order {
    id = 1,
    cust_fk = 1,
    ...
}
```

**Comment by beikov** [comment]
>It's nice to be able to define these at different levels.

Even if we have a single annotation, it would still be possible to define this at different levels (package + class + attribute). Due to our defaulting in the annotation, we can easily detect that e.g.

```
@SoftDelete(converter = MyConverter.class)
package com.mycompany.entity;
```

```
...
@SoftDelete(column = "removed")
public class MyEntity {
   ...
}
```

for `MyEntity` we also use the `MyConverter`, because the converter used in the `@SoftDelete` annotation at the entity level is the default one. I acknowledge that this might be confusing if package level configurations can't be overridden so that defaults are used again for specific entities, but then I'd argue that this would be an unrealistic case anyway. Because why would anyone want to have different database representations for this soft deleted flag across a model? The only reasonable override is IMO the column name, like in the example above.

>I am wondering though if we really want to allow nulls in the database for these mappings. Not speaking about how common or uncommon such a strategy is, but more thinking about the queries needed to handle soft-deletes.

I'd say let's disallow the column to be nullable. It's IMO unreasonable to allow a third state for this type of column. Allowing null wouldn't buy the user any storage space anyway, so I think for our first class support we should simply limit ourselves to reasonable uses. If people cry up, we can still add null support later if we want to.

>"Valid" insofar as loading that data and treating the corresponding Order#customer as null

I agree that to-one associations will/should behave as if all associations to types that are soft-deletable are annotated with `@NotFound(IGNORE)`. In fact, I think we could even model it this way i.e. set the not found action in the runtime model to `IGNORE` if the target type is soft-deletable.

**Comment by sebersole** [comment]
I understand we *can* do all these things you mention.  However, the other aspect to splitting or not is separation of concerns.  Personally I am not a fan of uber-annotations just to consolidate into a single one.  I'd argue we have 2 distinct pieces of configuration info -

* How to handle the boolean values
* Describe the column.

Now, given the the neutering of `@SoftDeleteColumn` from my last pushes, I can see moving back to a single annotation also.  When more was configurable for the column I liked the separation for that reason.  But right now there are 3 values configurable there - 

1. name
2. length of char-based columns
3. nullability

I can definitely see an argument to dropping nullability as I mentioned above.  The need to craft predicates like `deleted is null or deleted = ?` is clearly sub-optimal.  At least as an initial offering, anyway.  If people request allowing nullability, we can reconsider.

And, is length really useful?  Personally I've never seen this as anything more than 1 in the real world ('Y'/'N', 'T'/'F', ...).

If we remove those 2, we now have just the column-name, which is even more persuasive in terms of having one annotation.  But if we are allowing configuration of multiple aspects of the column, I still prefer keeping them split.  I could be persuaded by quorum though :D

You do bring up a good point about "overrides" from the package level.  At the moment I treat that as a complete replacement - it effectively ignores the package-level annotation when you apply one more locally (class or attribute).  There is definitely a discussion to be had though wrt allowing override of just parts (which is irrespective of single v. multiple annotations btw).

Lastly, given the ability to define this at the package level, I have also been thinking about the ability to disable soft-deletes at the class and attribute levels (akin to converter).  I think it is forced to require users to use different Java packages if they want some to be soft-deleted and others not.  I also am not convinced that annotating the package necessarily means you want collections soft-deletable.  Something like

```
/**
 * Enable for the package...
 */
@SoftDelete(converter = MyConverter.class)
package com.mycompany.entity;
```

```
package com.mycompany.entity;

/**
 * Disable for this particular entity
 */
@Entity
@SoftDelete(enabled=false)
class TheEntity { 
    ...
    /**
     * Disable for this collection
     */
    @ElementCollection
    @SoftDelete(enabled=false)
    Collection<String> someStrings;
}
```

**Review by beikov — COMMENTED** [review]
Looks great. Just a minor comment about the lines that CodeQL complains about, it seems the JDBC based tests try to verify that the tables contain the soft-delete columns. You also added a few tests that verify this by running HQL/find operations and checking the emitted SQL. I prefer the latter also because it would get rid of the CodeQL warning :)

Great work!

**Comment by sebersole** [comment]
Thanks for the feedback!

> Looks great. Just a minor comment about the lines that CodeQL complains about, it seems the JDBC based tests try to verify that the tables contain the soft-delete columns. You also added a few tests that verify this by running HQL/find operations and checking the emitted SQL. I prefer the latter also because it would get rid of the CodeQL warning :)

Honestly not too worried about CodeQL warnings on tests.  But I can change the few that still use that.  However there are lots of tests using HQL, load, etc.  The schema verify ones are just attempting to check the exported schema in a number of cases - writing HQL, load, etc operations to test all such cases is simply not feasible nor desirable.

> Great work!

Thanks :)

**Comment by sebersole** [comment]
Applied

**Pull request closed without merging**
