### PR TITLE
HHH-10215 Upgrade to Infinispan 8.0

### PR DESCRIPTION
**Pull request by rvansa**
This mostly involved removal of hacks required for 7.2.x - 8.0.1 compatibility. I have used configuration templates to stress the fact that we use these as templates rather than create the caches described in the config. I plan to add more changes in another PR to streamline the configuration a bit more and reduce the possibility of misconfiguration (e.g. when using old configuration).

### CODE REVIEW

**Comment by sebersole** [comment]
So should I go ahead and apply this?  Or was there something you wanted me or Galder to look at?

**Comment by rvansa** [comment]
@sebersole Generally, if something was just a preview, I would tag it with 'Preview' label. And since it is not, it deserves a proper review as any PR. In this case, I am not changing anything about the logic (such stuff should have Galder's eye), so you may check that I am not introducing something rotten and apply that.
Thanks for taking care.

**Comment by rvansa** [comment]
Added the 'Ready for review', I should have set that to mark it more clearly.

**Comment by sebersole** [comment]
Not sure exactly what you want me to review in such a PR.  This is all related to Infinispan code.  I literally have zero clue if you have "introduced something rotten" in regards to Infinispan calls; you would know that infinitely better than me ;)

So if I do not hear anything back in the next few hours, I will just apply this upstream

**Comment by rvansa** [comment]
OK, I am just used to the fact that any line of code must be seen by two pairs of eyes.

Then just go on and integrate. Thank you.

**Comment by sebersole** [comment]
Applied upstream.  Thanks

**Pull request closed without merging**
