### PR TITLE
HHH-13184 org.hibernate.dialect.Database does not return latest oracle dialect

### PR DESCRIPTION
**Pull request by avasilev**
Default should return latestDialectInstance.

https://hibernate.atlassian.net/browse/HHH-13184

### CODE REVIEW

**Comment by gsmet** [comment]
Outch, this is an ugly one. Will create a JIRA and merge.

**Comment by avasilev** [comment]
I have created JIRA: https://hibernate.atlassian.net/browse/HHH-13184

**Comment by gsmet** [comment]
Ah, shoot :) Missed it as you didn't prefix your commit message.

Thanks, will clean everything and merge.

**Comment by avasilev** [comment]
I have attached the pull request to the ticket.
Thanks

**Comment by gsmet** [comment]
Adjusted the commit message and merged. Thanks for taking the time to report it and push a PR!

It will be included in the upcoming 5.4.1.Final.

**Pull request closed without merging**
