### PR TITLE
HHH-15812 Firebird dialect improvements

### PR DESCRIPTION
**Pull request by mrotteveel**
Fixes [HHH-15812](https://hibernate.atlassian.net/browse/HHH-15812)

### CODE REVIEW

**Review by beikov — APPROVED** [review]
Nice work. Looks good to me

**Comment by gavinking** [comment]
Excellent, looks very comprehensive!

**Comment by mrotteveel** [comment]
I still have some tests failing with the dialect, but so far I have been able to attribute most of them to bugs in Jaybird (or bugs in Jaybird obscure the actual problem). I'll investigate those further after I have been able to fix them in Jaybird. There also some failures when all tests are run, but not when the test is run individually: a table is still in use by some previous test, so it can't be dropped, resulting in the wrong table columns during the test.

**Comment by mrotteveel** [comment]
@beikov This can be merged

**Pull request merged**
