### PR TITLE
HHH-11372, HHH-11373, HHH-11381 Performance fixes in 2LC

### PR DESCRIPTION
**Pull request by rvansa**
@gbadner Review if you like, I'll merge this next week if I don't find out further trouble.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Hi @rvansa. Can you add a Jira issue for this so we can better track what's been changed. Thanks.

**Comment by rvansa** [comment]
@vladmihalcea It has JIRA issues, see commits: HHH-11372 HHH-373 and HHH-11381. I'll add them to PR name. though.

**Comment by galderz** [comment]
@rvansa Apologies for delay, looking at this today

**Comment by galderz** [comment]
Looks good, integrating

**Pull request merged**
