### PR TITLE
Custom schema exporters for org.hibernate.tool.hbm2ddl.SchemaExport

### PR DESCRIPTION
**Pull request by m-szalik**

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)? And we should also add a JIRA for this issue too.

**Comment by m-szalik** [comment]
CLA signed - waiting for approval.
Jira: https://hibernate.atlassian.net/browse/HHH-10685

**Comment by vladmihalcea** [comment]
Thanks, I updated the task status.

**Comment by m-szalik** [comment]
That PR is almost 2 years old.
When I started to resolve merge conflicts  I realised that hiberante-orm now has already that functionality.
IMHO that PR can be closed.

**Pull request closed without merging**
