### PR TITLE
Test and fix for HHH-10690

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-10690

### CODE REVIEW

**Comment by Naros** [comment]
The fix looks fine, although the hbm mappings exhibit this problem too.  I'll add a test case using hbm for full test coverage.

**Comment by Naros** [comment]
@sebersole After applying @beikov's fix we end up creating a single entry in the JPA Metamodel where `AbstractEntity` will either specify the id/data types as either Integer/String or Long/Integer or some combination.  This means the other concrete entity implementation has incorrect metamodel values.

@beikov checked against EclipseLink and in this situation, when you query either of the two concrete entity's for their **id** attribute for example, the declaring type is the concrete entity class and the java type reflects the parameterized type.

I propose as part of building the metamodel, we have a second attribute resolution phase we do in `AbstractManagedType#lock()` that will look for parameterized attributes and build a list of overridden attributes.  This override list would only apply to methods that don't query declared attributes in the metamodel.

This way when inspecting `AbstractEntity`, the types returned are `Serializable` as we'd expect but for each concrete entity type in the metamodel, the id and data attributes would be overridden and calling 
`getAttribute( "id" )` for example would return `Integer` for type-1 and `Long` for type-2 entities.

Do you have any concerns or questions if we tackle this in this manor instead?  

<pre>
@MappedSuperclass
public class AbstractEntity&lt;ID extends Serializable, E extends Serializable&gt; {
  private ID id;
  private E data;
}

@Entity
public class ConcreteEntity1 extends AbstractEntity&lt;Integer, String&gt; {
}

@Entity
public class ConcreteEntity2 extends AbstractEntity&lt;Long, Integer&gt; {
}
</pre>

**Comment by sebersole** [comment]
The JPA spec says nothing about how to handle this.  But I agree that how you say EclipseLink handles that situation seems reasonable - namely to use the type bound by the concrete class when reporting the "id type".  I think we also want to make sure that works with normal attributes too then.

**Comment by sebersole** [comment]
I am adding the following method and todo comments to 6.0's `org.hibernate.persister.entity.spi.EntityPersister` contract:

````


	/**
	 * Access to information about the entity identifier, specifically relative to this
	 * entity (in terms of Java parameterized type signature in regards to all "id attributes").
	 * Generally this delegates to {@link EntityHierarchy#getIdentifierDescriptor()} via
	 * {@link #getHierarchy()}.  We'd want to override the value coming from
	 * {@link EntityHierarchy#getIdentifierDescriptor()} in cases where we have a
	 * MappedSuperclass to the root entity and that MappedSuperclass defines the identifier
	 * (or any attributes really) using a parameterized type signature where the attribute
	 * type has not been concretely bound and is instead bound on the root entity.
	 *
	 * @todo (6.0) : we should consider doing the same for normal attributes (and version?) as well
	 * 		in terms of cases where generic type parameters for an entity hierarchy have not
	 * 		been bound as of the root entity
	 *
	 * 	@todo (6.0) : how should we handle the attribute as defined on the MappedSuperclass and the attribute defined on the subclass (with the conretely bound parameter type)?
	 * 		I mean specifically.. do we mark the MappedSuperclass attributes (somehow) as having an "unbound" attribute type and
	 * 		mark the subclass attribute as being a "bridged" attribute?
	 *
	 * @since 6.0
	 */
	IdentifierDescriptor getIdentifierDescriptor();
````

Much of the discussion there relates to this condition.  So essentially what I am proposing is treating these attribute in a fashion similar to how the compiler does with "bridge methods".  So here we have 2 distinct entity hierarchies (ConcreteEntity1 and ConcreteEntity2) each sharing the same super type as a MappedSuperclass (AbstractEntity).  So the java doc discussion essentially asks how we should specifically model this.  I propose that we:

1. Define the attributes for id and data on MappedSuperclass(AbstractEntity) but to somehow mark them as having "unbound" parameter types (`<ID>` and `<E>`). 
2. *Re-*define these attributes on EntityPersister(ConcreteEntity1) and EntityPersister(ConcreteEntity2) to report the bound types (Integer,String) and (Long,Integer) and somehow mark them as "bridge attributes", possibly with a reference to the super unbound attribute it "bridges".
3. However, who should we report as the owner of these attributes on EntityPersister(ConcreteEntity1) and EntityPersister(ConcreteEntity2)?  EntityPersister(ConcreteEntity1) and EntityPersister(ConcreteEntity2) seem the most reasonable, especially if we give these "bridge attributes" reference to the unbound attribute it "bridges".

Anyway, would love to hear y'alls thoughts...

**Comment by Naros** [comment]
Based on what @beikov discovered with EclispeLink, the declared owner is the type which binds the attribute's type in the hierarchy.  To me that would also mean should we have the following example, the "bridge attributes" would be bound by `BaseEntity` and not `SomeEntity`.  That seems the most reasonable.
<pre>
@MappedSuperclass
public class AbstractEntity<ID extends Serializable, D> {
  @Id
  private ID id;
  private D data;
}

@MappedSuperclass
public class BaseEntity extends AbstractEntity&lt;Long, String&gt; {
  private Integer value;
}

@Entity
public class SomeEntity extends BaseEntity {
}
</pre>

**Comment by sebersole** [comment]
@Naros What you said is exactly what I said :)  You just created a new example.  So right, I also believe that the type which first binds the type parameters should be reported as the declarer of the attribute.  Further I strongly believe that it is an error for these type parameters to remain unbound before we reach the root entity.

Anyway, taking your new example (although the same exists in @beikov's original example as well) the question is really how to handle reporting the attribute when the application grabs the MappedSuperclass.  I.e., again using your example, I think we all agree that the following are all true:

````
IdentifiableType abstractEntityType = (IdentifiableType) emf.getMetamodel().managedType( AbstractEntity.class );
assert abstractEntityType.getId( Object.class ).getDeclaringType() == abstractEntityType;
try {
    // this throws an IllegalArgumentException...
    abstractEntityType.getId( Long.class );
}
catch(IllegalArgumentException ignore) {}

IdentifiableType baseType = (IdentifiableType) emf.getMetamodel().managedType( BaseEntity.class );
assert baseType.getId( Object.class ).getDeclaringType() == baseType;
assert baseType.getId( Long.class );.getDeclaringType() == baseType;

EntityType entityType = emf.getMetamodel().entity( SomeEntity.class );
assert entityType.getId( Object.class ).getDeclaringType() == baseType;
assert entityType.getId( Long.class );.getDeclaringType() == baseType;
````

Additionally I proposed that `abstractEntityType#getId` and `baseType#getId` return completely different attribute instances but that they would know about each other.  The return from `abstractEntityType#getId` would understand that it is "virtual", "unbound", <whatever term you like>.  Additionally the return from `baseType#getId` would understand:
1. That it is a "bridge" attribute in that it binds the type parameter
2. The "virtual" attribute it "covariantly overrides"

My concern here TBH is how to handle calls to `IdentifiableType#getDeclaredId`.  Do both `abstractEntityType` and `baseType` reply that they declare the id?  That seems wrong to me.  In this vein, another option is that we do not consider an attribute as declared until its type parameters are bound and that the declarer is the class that binds the type.  That would mean that in terms of this new example, `abstractEntityType` would actually report not knowing about an id attribute.  This approach IMO has a lot of merit.

**Comment by sebersole** [comment]
Additionally, if we were to take the route of not considering an attribute as declared until its parameterized type is bound then I would still consider that attribute understanding the fact that it bridges a "virtual attribute" defined on a particular super class.

**Comment by sebersole** [comment]
Here's another interesting case to consider as well...

````
@MappedSuperclass
public class AbstractEntity<ID extends Serializable, D> {
  @Id
  private ID id;
  private D data;
}

@MappedSuperclass
public class BaseEntity<ID extends Number> extends AbstractEntity<ID, String> {
  private Integer value;
}

@Entity
public class SomeEntity extends BaseEntity<Long> {
}
````

**Comment by beikov** [comment]
Although EclipseLink fails some of the tests, I think this should be the appropriate behavior

```
        EntityType<ConcreteEntity1> entity1 = metamodel.entity(ConcreteEntity1.class);
        EntityType<ConcreteEntity2> entity2 = metamodel.entity(ConcreteEntity2.class);
        EmbeddableType<ConcreteEntity1Id> embeddable1 = metamodel.embeddable(ConcreteEntity1Id.class);
        EmbeddableType<ConcreteEntity2Id> embeddable2 = metamodel.embeddable(ConcreteEntity2Id.class);
        
        assertNotNull(embeddable1);
        assertNotNull(embeddable2);
        assertEquals(embeddable1, entity1.getIdType());
        assertEquals(embeddable2, entity2.getIdType());
        
        // Id can be found by concrete subtype
        assertEquals(entity1.getAttribute("id"), entity1.getId(ConcreteEntity1Id.class));
        assertEquals(entity2.getAttribute("id"), entity2.getId(ConcreteEntity2Id.class));
        
        // But also by any upper bound
        // NOTE: EclipseLink fails here
        assertEquals(entity1.getAttribute("id"), entity1.getId(Serializable.class));
        assertEquals(entity2.getAttribute("id"), entity2.getId(Serializable.class));

        // Not allowed to use concrete subtype on supertype
        // NOTE: EclipseLink fails here
        try {
            entity1.getSupertype().getId(ConcreteEntity1Id.class);
            fail("Should not be allowed to query the id by concrete subtype!");
        } catch (IllegalArgumentException e) {}
        try {
            entity2.getSupertype().getId(ConcreteEntity2Id.class);
            fail("Should not be allowed to query the id by concrete subtype!");
        } catch (IllegalArgumentException e) {}
        
        // But the upper bound should work
        // NOTE: EclipseLink fails here
        assertEquals(entity1.getSupertype().getAttribute("id"), entity1.getSupertype().getId(Serializable.class));
        assertEquals(entity2.getSupertype().getAttribute("id"), entity2.getSupertype().getId(Serializable.class));
        
        // Attributes have concrete types on subtypes
        assertEquals(embeddable1.getJavaType(), entity1.getAttribute("id").getJavaType());
        assertEquals(embeddable2.getJavaType(), entity2.getAttribute("id").getJavaType());
        
        // But have the upper bound type on the supertype
        // NOTE: EclipseLink fails here
        assertEquals(Serializable.class, entity1.getSupertype().getAttribute("id").getJavaType());
        assertEquals(Serializable.class, entity2.getSupertype().getAttribute("id").getJavaType());

        // Attributes are not considered as declared
        try {
            entity1.getDeclaredId(ConcreteEntity1Id.class);
            fail("Subtype should not declare the id!");
        } catch (IllegalArgumentException e) {}
        try {
            entity2.getDeclaredId(ConcreteEntity2Id.class);
            fail("Subtype should not declare the id!");
        } catch (IllegalArgumentException e) {}
        try {
            entity1.getDeclaredAttribute("id");
            fail("Subtype should not declare the id attribute!");
        } catch (IllegalArgumentException e) {}
        try {
            entity2.getDeclaredAttribute("id");
            fail("Subtype should not declare the id attribute!");
        } catch (IllegalArgumentException e) {}
        
        // But the declaring types are the concrete subtypes
        assertEquals(entity1, entity1.getAttribute("id").getDeclaringType());
        assertEquals(entity2, entity2.getAttribute("id").getDeclaringType());
        assertEquals(Type.PersistenceType.ENTITY, entity1.getAttribute("id").getDeclaringType().getPersistenceType());
        assertEquals(Type.PersistenceType.ENTITY, entity2.getAttribute("id").getDeclaringType().getPersistenceType());
        
        assertTrue(entity1 == entity1.getAttribute("id").getDeclaringType());
        assertTrue(entity2 == entity2.getAttribute("id").getDeclaringType());
        
        // Except if they got queried from the supertype
        assertEquals(entity1.getSupertype(), entity1.getSupertype().getAttribute("id").getDeclaringType());
        assertEquals(entity2.getSupertype(), entity2.getSupertype().getAttribute("id").getDeclaringType());
        
        // Attributes are different
        assertTrue(entity1.getAttribute("id") != entity2.getAttribute("id"));
        assertNotEquals(entity1.getAttribute("id"), entity2.getAttribute("id"));
        
        assertTrue(entity1.getAttribute("id") != entity1.getSupertype().getAttribute("id"));
        assertTrue(entity2.getAttribute("id") != entity2.getSupertype().getAttribute("id"));
        assertNotEquals(entity1.getAttribute("id"), entity1.getSupertype().getAttribute("id"));
        assertNotEquals(entity2.getAttribute("id"), entity2.getSupertype().getAttribute("id"));
```

**Comment by sebersole** [comment]
@beikov I completely disagree with:

````
// But the upper bound should work
// NOTE: EclipseLink fails here
assertEquals(entity1.getSupertype().getAttribute("id"), entity1.getSupertype().getId(Serializable.class));
assertEquals(entity2.getSupertype().getAttribute("id"), entity2.getSupertype().getId(Serializable.class));
````

I do not know *how* EclipseLink fails, but I agree that this should be a failure.

**Comment by sebersole** [comment]
@beikov I also disagree with:

````
// But the declaring types are the concrete subtypes
...

// Except if they got queried from the supertype
...

// Attributes are different
...
````

I guess it comes down to how you view "declaring" an attribute in terms of "binding" its type.  To me, at some level, those are one in the same.  

And the more I think about it, the more I hate the idea of returning different attributes for the same attribute...  Even saying it sounds counter-intuitive ;)

I lean more and more to my second option where we simply say that the these attributes are declared on the class that does the type binding - i.e. SomeEntity, ConcreteEntity1, ConcreteEntity2 in our examples.  Here, querying for an attribute against a super type where the attribute has a yet-unbound type should not be allowed.

**Comment by beikov** [comment]
@sebersole EclipseLink fails at `entity1.getSupertype().getId(Serializable.class)`. This should work since the type variable on the supertype has the upper bound `Serializable`, but EclipseLink does something weird here, I guess it has a bug.

If you don't return different attributes how would you handle the different type bindings? Or do you mean non-different in the sense that `equals` would be true for attributes queried from different subtypes? I guess the fact that `getDeclaringType()` returns the concrete subtype is debatable, since it is in fact _declared in the supertype_, but _refined in the subtype_.
But not making the attribute accessible/discoverable in the supertype feels kind of wrong.

**Comment by sebersole** [comment]
Well see you keep saying that "it is in fact declared in the supertype" which is exactly what I am arguing - the way that JPA defines its metamodel, I think it is easy to argue that an attribute is not truly declared until its type is bound.

**Comment by sebersole** [comment]
Long story short... I think you are making the assumption (which is reasonable on the surface) that declared here in JPA means the same thing as normal Java usage.  That is actually the premise also of my first proposal.  So in that approach there would in fact be 2 attributes in the hierarchy and they would in fact be different instances.

But that is what I am saying make no logical sense.  I mean just ask yourself logically... "does it make sense that when I query for an attribute named `id` at different points in the hierarchy that I get back completely different attributes?"  That's where I start having problems with this first approach and started looking at alternative approaches.

**Comment by beikov** [comment]
TBH I think retrieving different attributes depending on where it has been queried in the hierarchy is a lot better than having to manually resolve type variables like it is requried in Java Reflection, but that's just my opinion.
My main concern is that attributes which depend on type variables currently have the upper bound type as java type and that leads to embeddable id types bound via type variables not being available in the metamodel. Whether the declaring type should be the supertype or the subtype should definitely be decided by the EG since both approaches seem reasonable, it just seems _nicer_ to return a declaring type for which an attributes type variable has been resolved.

**Comment by dreab8** [comment]
I tend to agree with @sebersole when he says "... that an attribute is not truly declared until its type is bound."

**Comment by sebersole** [comment]
I am starting to wonder whether allowing this to report the different resolved types at each subclass[1] would be the best.  I think it certainly has more work involved, so I think we should consider the feasibility of implementing that for 6.0.  Is it feasible?

[1] E.g., to use the example above... `Long` for `id` and `String` for `data` when retrieved from `SomeEntity`, but `Serializable` and `Object`, respectively, when retrieved from `AbstractEntity`

**Comment by Naros** [comment]
That's the approach that has my vote, @sebersole

**Comment by dreab8** [comment]
in my opinion if doable it would be the best approach

**Comment by sebersole** [comment]
@dreab8 Yes but the "doable"-ility is what concerns me :)

**Comment by dreab8** [comment]
@sebersole I have the same concern for this reason i say if doable :)

**Comment by Naros** [comment]
The one concern you had previously was equality.  

In 5.2, I played with the idea that an attribute maintained a list of `AttributeBinding`s which defined the declaring class, type, and other context specific values.  

When a managed type returned attributes, if an attribute had a single `AttributeBinding`, it returned that attribute instance as-is.  In the cases where multiple bindings were found, I used a decorator to delegate the appropriate binding methods to the right binding based on managed type or merely delegate to the underlying attribute.

This worked nicely for allowing object equality, but obviously didn't support reference equality.

**Comment by sebersole** [comment]
@Naros yes, but the equality problem was in regards to having 2 distinct `PersistentAttribute` references for the various "type resolution levels".  Here I am discussing something else; here we'd have just the one `PersistentAttribute` reference, but we'd be able to ask *something* (something external to the attribute itself) to resolve its type relative to a specific hierarchy class.

**Comment by JWGmeligMeyling** [comment]
Is this delayed until 6.0 or perhaps even integrated into 6.0 or just a stale PR for 5.x?

**Comment by gsmet** [comment]
AFAICS, it's something that needs fixing but we need some work to be done.

**Comment by beikov** [comment]
Closing this as the JIRA issue was now closed as well.

**Pull request closed without merging**
