### PR TITLE
Upgrade gradle to 3.2.1

### PR DESCRIPTION
**Pull request by rhart**
Regenerated gradle wrapper

### CODE REVIEW

**Comment by rhart** [comment]
I assumed you don't require a jira issue for changes like this.  Happy to create one if needs be.

**Comment by sebersole** [comment]
Why 3.2.1?  What has it added that is important/nice?

**Comment by sebersole** [comment]
And yes we do have a `build` Jira component

**Comment by rhart** [comment]
>Why 3.2.1? What has it added that is important/nice?

I just noticed that you were still on a milestone release and 3.2.1 is the latest and greatest.  There will have been many bug fixes and performance improvements.

>And yes we do have a build Jira component

I can create a ticket if you wish to proceed with the upgrade.

**Comment by dreab8** [comment]
Jira cretaed https://hibernate.atlassian.net/browse/HHH-11346

**Comment by dreab8** [comment]
Thanks @rhart 
rebased and applied upstream

**Pull request closed without merging**
