### PR TITLE
Switch from Geronimo JTA to Narayana JTA

### PR DESCRIPTION
**Pull request by Sanne**
# Broken

I simply followed up on #1587 with the hope that changing the bundle would be enough.
The OSGi tests don't seem happy yet, but I couldn't really look at it... sharing so that someone can follow up.

Updated the related docs as well.

### CODE REVIEW

**Comment by brmeyer** [comment]
Hey @Sanne, the main reason we were using Geronimo in hibernate-osgi is it's a first-class-citizen in the OSGi realm.  At the time, JBoss JTA didn't support it at all.  @sebersole, am I misremembering anything on that?

**Comment by sebersole** [comment]
Right, at the time a lot of JBoss jars were not valid OSGi bundles (mainly
I remember them defining unnecessary dependencies).

**Comment by brmeyer** [comment]
That's right -- it was pulling in some other EE API jars that were completely optional.  @Sanne, I'll take a look...

**Comment by psiroky** [comment]
@brmeyer did you have a chance to look at this?

We (Drools, jBPM, OptaPlanner) generally use JBoss Spec jars, so this geronimo one is creeping in and we need to add exclusions, so would be great to fix it if possible.

**Comment by brmeyer** [comment]
Sorry folks, life gets in the way ;)

@sebersole Pulled down their manifest and it looks like those imports are now correctly optional:

```
Import-Package: javax.enterprise.context;resolution:=optional;version=
 "[1.1,2)",javax.enterprise.util;resolution:=optional;version="[1.1,2)
 ",javax.interceptor;version="[1.2,2)",javax.transaction.xa;version="[
 1.2,2)
```

I'll pull this down and give it a smoke test...

**Comment by brmeyer** [comment]
Hey @Sanne, was there a JIRA for this?  Also, someone willing to mitigate the conflicts, with the promise that I'll merge it right away?

**Comment by brmeyer** [comment]
Never mind @Sanne, will take care of it -- simple.
https://hibernate.atlassian.net/browse/HHH-11439

**Comment by brmeyer** [comment]
@sebersole Spoke too soon.  The JBoss JTA bundle made most packages optional, but still requires `javax.interceptor`.  Not necessarily against adding it, but we don't otherwise use it

**Comment by brmeyer** [comment]
Note: JBoss JTA does require `javax.interceptor` which we'll need to add, but that's a standard bundle that Karaf's built-in JTA features install as well -- not an issue.

**Comment by brmeyer** [comment]
Manually merged

**Comment by psiroky** [comment]
Thanks a lot @brmeyer!

**Comment by Sanne** [comment]
awesome, thanks @brmeyer ! this has been bugging our needs for "getting the exclusions right" for a long time.

Just wondering, why should Hibernate ORM depend on `javax.interceptor` directly; shouldn't we rather patch Narayana to depend on it explicitly? Let me know if it's worth letting the Narayana team know..

**Comment by brmeyer** [comment]
Hey @Sanne!  Just mentioned this to Steve, elsewhere:

> Hey @sebersole, in general, yes, but I didn't have as big of an issue with this one in general. Karaf itself pulls in this same dependency if you install their out-of-the-box "JTA" feature (@psiroky, that's the main reason I chose that artifact and not JBoss -- consistency). That doesn't mean we should have had to add it here, but it wasn't as big as a problem as the prior problems.

**Pull request closed without merging**
