### PR TITLE
HHH-14820 Reproducer - Customized EnumType not working with hbm mapping in Hibernate 6

### PR DESCRIPTION
**Pull request by gtoison**
A simple unit test illustrating issue HHH-14820 : since Hibernate ORM 6 the custom NamedEnumUserType is only instantiated once (while there aretwo enums configured with this type).

When trying to execute a query that NamedEnumUserType has the last enum class and `Enum.valueOf(...)` fails.

The test is currently marked with `@Ignore` so it needs to be removed to get a failing result.

See [the JIRA HHH-14820 issue](https://hibernate.atlassian.net/browse/HHH-14820)

### CODE REVIEW

**Comment by beikov** [comment]
Thanks a lot for the test case. I'll look into it ASAP.

**Comment by sebersole** [comment]
I'm curious what actually fails for you here.  The test passes for me rebased on top of current 6.0 branch.  And honestly looking at the test.

**Comment by gtoison** [comment]
Did you remove the `@Ignore` ?
I was not sure what was the right way to add a failing unit test

**Comment by sebersole** [comment]
> Did you remove the `@Ignore` ? I was not sure what was the right way to add a failing unit test

Probably you meant to execute the query...

**Comment by sebersole** [comment]
Ok, that was it.  You probably removed the execution at some point

**Comment by sebersole** [comment]
BTW, have a fix already.  Running the full tests and I'll push for you to try

**Comment by gtoison** [comment]
Sorry that was not super clear, I tried again with the latest version of the wip/6.0 branch and test failed with this error:

```
> Task :hibernate-core:test

NamedEnumUserTypeTest > testNamedEnumUserType FAILED
    jakarta.persistence.PersistenceException at ExceptionConverterImpl.java:167
        Caused by: org.hibernate.HibernateException at JdbcValuesResultSetImpl.java:312
            Caused by: java.lang.IllegalArgumentException at Enum.java:238
```

It's great to hear that fix is coming up, thank you very much for looking into it!

**Comment by gtoison** [comment]
Yes sorry I was trying to say that the @Ignore annotation needs to be removed
In some projects the etiquette for submitting a failing unit test is to commit it disabled so you don't break the build.

I've removed it in a new commit for the sake of clarity. Sorry for the noise!

**Comment by sebersole** [comment]
But this is your test method:

```
		doInHibernate( this::sessionFactory, s -> {
			s.createQuery( "from Person p", Person.class );
		} );
```

The query is not executed.    In other words I only got this to fail when I changed that to

```
		doInHibernate( this::sessionFactory, s -> {
			s.createQuery( "from Person p", Person.class ).list();
		} );
```

**Comment by sebersole** [comment]
Fixed - https://github.com/hibernate/hibernate-orm/commit/c799f858013b8043ce2e17b3ba8b5d83b6a4d1c7

**Pull request closed without merging**
