### PR TITLE
HHH-12861 SchemaUpdate doesn't work with Sybase

### PR DESCRIPTION
**Pull request by dreab8**
Hi @simkam, can you give a try to this PR? Thanks

### CODE REVIEW

**Comment by simkam** [comment]
@dreab8 SchemaUpdateWithKeywordAutoQuotingEnabledTest passes with this fix and sybase

**Comment by dreab8** [comment]
Thanks @simkam, I have just pushed another commit with this also NumericValidationTest should pass.

**Comment by gsmet** [comment]
@dreab8 looks good to me. Please merge to master and 5.3 when you think it's ready.

**Comment by dreab8** [comment]
Thanks @simkam @gsmet 
squashed and applied to master and 5.3

**Pull request closed without merging**
