### PR TITLE
Fix incorrect additional joins being generated when non-fetch joining and selecting a plural association

### PR DESCRIPTION
**Pull request by sebersole**
This first commit is just tests illustrating the problem until we can all discuss the better design approach to fix this - either we stop implicitly "converting" the collection selection as its {element} path or later better handle the "mismatched" NavigablePaths in terms of resolving TableGroups

### CODE REVIEW

**Comment by beikov** [comment]
I think this is something we "fixed" in 5.x by specifying the force-discriminator option, although I never really liked that, so +1 from me to fix this and maybe we can get rid of the force-discriminator stuff?

**Comment by dreab8** [comment]
I played a little bit with this issue https://github.com/dreab8/hibernate-orm/commit/a746442e345bbc127a7bbd63fa81f3f68d0a1b36

**Comment by sebersole** [comment]
> I think this is something we "fixed" in 5.x by specifying the force-discriminator option, although I never really liked that, so +1 from me to fix this and maybe we can get rid of the force-discriminator stuff?

The inheritance is completely irrelevant here.  The problem is the joins and it happens even without inheritance.

**Comment by sebersole** [comment]
> I played a little bit with this issue [dreab8@a746442](https://github.com/dreab8/hibernate-orm/commit/a746442e345bbc127a7bbd63fa81f3f68d0a1b36)

This is similar to the possible second approach I mentioned initially.

I think we should at least try to change the node used in the selection for this case.  At the moment we implicitly use the element's source-path.  IMO that is the "cleanest" solution

**Pull request closed without merging**
