### PR TITLE
HHH-9708: Removing wrong error reports by the AnimalSniffer plug-in

### PR DESCRIPTION
**Pull request by gunnarmorling**
@sebersole: This removes wrong error reports by the AnimalSniffer plug-in and also the reference to Java 8's `KeySetView` type.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@sebersole Pushed one more commit to do some clean-up. It's good to merge from my side, AnimalSniffer will detect errors such as the usage of `KeySetView` in `SessionFactoryImpl` now and report them properly (this PR also removes this particular usage in `SessionFactoryImpl`, so you'd have to add a bad reference for testing this). AS is applied by default.

The only remaining issue is that AS for me is only applied to all modules when running `./gradlew build`. When running `./gradlew compileJava` only, it only is applied to _hibernate-core_ and _hibernate-entitymanager_ (see the log at https://gist.github.com/gunnarmorling/03d4343aa43398a547a3). Not sure why that is, I assume it is related to the way how the plug-in is registered with the Gradle build lifecycle. If you have an idea how to fix this, that'd be cool, otherwise I'm fine with it as is as it runs properly during `build` which is what happens on CI etc.

**Comment by sebersole** [comment]
It did not run on the others because they were considered up-to-date.  Doesn't make sense to run AS if nothing was compiled:

    :hibernate-envers:compileJava UP-TO-DATE
    ...
    :hibernate-gradle-plugin:compileJava UP-TO-DATE
    ...
    etc...

**Comment by gunnarmorling** [comment]
No, even with `./gradlew clean compileJava` it isn't run (see the updated Gist, it e.g. compiles _hibernate-envers_ but does not run AS to that module). But I figured that the plug-in is applied after the `classes` task rather than `compileJava`. Added one more commit to change that.

**Comment by sebersole** [comment]
Here is the project I mentioned to you: https://github.com/sebersole/gradle-mixed-jdk/tree/master

**Comment by sebersole** [comment]
Pretty sure this one is out of date now

**Pull request closed without merging**
