### PR TITLE
Fix sybase LobSchemaUpdateTest failure

### PR DESCRIPTION
**Pull request by dreab8**

### CODE REVIEW

**Review by sebersole — COMMENTED** [review]
Looks reasonable to me.

**Review by beikov — APPROVED** [review]

**Comment by sebersole** [comment]
Seems to me this should have a Jira as it changes user experience?

**Comment by dreab8** [comment]
this are failure caused by this commit https://github.com/hibernate/hibernate-orm/commit/d8df261847d5fdeb8f9168b1391ec1e2f1531428

**Comment by sebersole** [comment]
No no.  Its fine.  The original one should have had one

**Comment by sebersole** [comment]
Does this need backported?

**Comment by dreab8** [comment]
only to 6.,5

**Comment by dreab8** [comment]
@sebersole I'm going to prepare the PR for 6.5

**Comment by sebersole** [comment]
> @sebersole I'm going to prepare the PR for 6.5

I'd say just cherry-pick and push it

**Pull request merged**
