### PR TITLE
 HHH-9495 - Implemented @Convert support for collections

### PR DESCRIPTION
**Pull request by markus-s24**
This pull request implements @Convert support for collections. I am not sure, if it handles every case, but at least for my use case it works. It would be nice, if someone takes a look at it.

### CODE REVIEW

**Comment by gbadner** [comment]
Please add a commit with a test case.
Thanks,
Gail

**Comment by sebersole** [comment]
Mark, why so many commits in this pull request?

**Comment by markus-s24** [comment]
Removed merged upstream commits.

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by markus-s24** [comment]
No, but I signed it now.

2016-04-12 15:33 GMT+02:00 Vlad Mihalcea <notifications@github.com>:

**Comment by vladmihalcea** [comment]
The [HHH-9495](https://hibernate.atlassian.net/browse/HHH-9495) is already fixed, so I'm closing this PR.

**Pull request closed without merging**
