### PR TITLE
HHH-16737 Widen types for numeric literals without explicit type suffix if necessary

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-16737

### CODE REVIEW

**Comment by gavinking** [comment]
@beikov does this change the semantics of HQL?

It looks like it changes the type of a floating point literal like `1.23`.

**Comment by beikov** [comment]
It seems the Hibernate 6 parser/AST changed the behavior. In 5 we always produced exact literals, so even though this changes the behavior slightly, I think it is a good change. We'll discuss this on Wednesday in our team meeting though.

**Comment by gavinking** [comment]
Let's discuss it here, since I can't be at the team meeting. WDYM by "exact literal"?

**Comment by gavinking** [comment]
OK, so indeed there was a change of behavior here.

1. In Hibernate 5, `select 1.3 from Book` gives me a `Double`, which is consistent with the interpretation of floating-point literals in Java, but
2. in H6, it gives me a `Float`, which is not.

So it seems like reverting to the behavior of Hibernate 5 would be reasonable.

Now, I'm not sure what this patch does, and I'm probably misunderstanding, but it almost looks like the syntax `select <literal>` would be assigned a different type depending on how many digits of precision the `<literal>` value has. Is that correct?

**Review by gavinking — CHANGES_REQUESTED** [review]
OK, so I spent some time reflecting on this last night.

So ultimately I don't think it's a good idea to have the type of a literal depend on the number of digits of precision. Java doesn't do that; indeed, I don't know of any statically-typed language which does that. The type assigned to a literal in HQL is visible to the program when the literal occurs in the `select` clause, and I just don't think this should be subject to weird implicit behaviors. Users already have a perfectly good way to ask for a `Float` or `Long` literal (or `BigInteger`/`BigDecimal` literals) if they need one, and it's consistent with what they already know how to do in Java.

So sticking with the straightforward solution:

- floating point literals have type `Double` by default, as in H5, and in Java, and
- integer literals have type `Integer` by default, and
- an error is thrown if there would be a loss of precision

is not only perfectly fine in terms of what users _actually need_ (nobody actually uses literals with huge numbers of digits), but it's also simpler. Which makes it easier to document, and easier to understand. We don't need to introduce something weirder, more complex, and less explicit to accommodate a usage scenario that's essentially non-existent.

**Comment by gavinking** [comment]
Another thing: this whole issue would never have arisen if the JPA spec wasn't so atrociously ambiguous on the semantics of literal values. So I will make some time to write up a proposal to clarify all this in the spec.

**Comment by beikov** [comment]
As far as I understand the SQL specification, there are two types of literals, exact and approximate numeric literals. Denoting approximate literals requires the use of the `e`/`E` character to signify the exponent part. See https://www.contrib.andrew.cmu.edu/~shadow/sql/sql1992.txt section `5.3 <literal>` or page 90.

Here comes a quote from the JPA spec section 4.6.1

>Exact numeric literals support the use of Java integer literal syntax as well as SQL exact numeric literal syntax.
>Approximate literals support the use Java floating point literal syntax as well as SQL approximate numeric literal syntax.
>Appropriate suffixes can be used to indicate the specific type of a numeric literal in accordance with the Java Language Specification. Support for the use of hexadecimal and octal numeric literals is not required by this specification.

AFAIU this, JPA follow the SQL spec, but additionally allows to denote the type via the Java syntax type suffixes.

Playing a bit around with PostgreSQL which allows to introspect the runtime type of an expression, it seems that what I have implemented here is in accordance to what the SQL spec says and how most DBs behave. I'd even go one step further and only parse decimal literals as float/double if explicitly requested through the type suffix and not bother about checking if a value exactly representable.

Consider the following SQL query for playing aroung in PostgreSQL:

```
select pg_typeof(1), pg_typeof(1000000000000), pg_typeof(10000000000000000000), pg_typeof(1.0), pg_typeof(1e)
```

The result is `integer, bigint, numeric, numeric, numeric`, which is explained in the [PostgreSQL docs](https://www.postgresql.org/docs/current/sql-syntax-lexical.html#id-1.5.3.5.9.9.5.1). Oracle behaves the same way https://docs.oracle.com/cd/B14117_01/server.101/b10759/sql_elements003.htm#sthref385

My [other PR](https://github.com/hibernate/hibernate-orm/pull/6861) which implements type inference for HQL parsing would take care of treating a numeric literal as float/double when comparing them to a float/double property.

**Comment by beikov** [comment]
Superseded by https://github.com/hibernate/hibernate-orm/pull/6885

**Pull request closed without merging**
