### PR TITLE
HHH-12603 - re-enabled plugin in build.gradle

### PR DESCRIPTION
**Pull request by aepedraza**
This is my first PR. When I first cloned the repo in my local I got the reported error message. After my changes I got the following output:

```
$ ./gradlew clean eclipse --refresh-dependencies

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 7m 21s
86 actionable tasks: 68 executed, 18 up-to-date
```

I don't know if there is any way to test this fix.

### CODE REVIEW

**Comment by gsmet** [comment]
Hi  @aepedraza ,

I'm wondering if this is still useful with the latest Eclipse? With the Gradle plugin, I mostly import the Gradle project into Eclipse.

And then I have to fix things that are not supported by Eclipse manually (the generated classes for the logger are not added to the build IIRC). One other limitation I have is that the jars are not linked to their sources anymore, which is a real pain.

To be honest, I'm an Eclipse user but I'm considering switching to IDEA to work on ORM...

Is this supposed to fix these issues? What does it bring to the table?

**Comment by aepedraza** [comment]
Hi @gsmet, I believe it's a matter of taste. To be honest too, I never used the Gradle Eclipse plugin to run from command line, but if it's possible to enable this, it can make a better _"developer experience"_ to someone who is used to Gradle form the command line.

> And then I have to fix things that are not supported by Eclipse manually (the generated classes for the logger are not added to the build IIRC). One other limitation I have is that the jars are not linked to their sources anymore, which is a real pain.

What things and jars are you referring to? Sorry, I'm not an expert in gradle.
Another option is to simply remove the [reference to the wiki](https://developer.jboss.org/wiki/ContributingToHibernateUsingEclipse) in [CONTRIBUTING.MD](https://github.com/hibernate/hibernate-orm/blob/master/CONTRIBUTING.md). I don't know if, as a contributor, I can edit or remove content from the wiki, if you know how to do it please let me know.

PS: @Naros what should I add and/or do with the _Requires clarification_ label?

**Comment by Naros** [comment]
I added the label primarily for two reasons:
1. gsmet had inquired about the what this change serves or provides
2. To indicate that we didn't necessarily want to integrate this trivial PR just yet without more discussion.

@aepedraza Is there any particular reason why the two `allprojects` blocks cannot be merged together at the top rather than having two of them in the script?

I also see we have the inclusion of these 2 plugins in our 6.0 development branch but this was modified during some recent build script tidying we did.  @sebersole, do you have a preference as to whether we add this back in or not?

**Comment by Naros** [comment]
> Another option is to simply remove the reference to the wiki in CONTRIBUTING.MD.  I don't know if, as a contributor, I can edit or remove content from the wiki, if you know how to do it please let me know.

I meant to comment on this and missed it, sorry.  Lets wait to get some feedback from sebersole.  It very well could just be an oversight on a recent commit or perhaps a deliberate change which as you mention implies we need to update other resources.  Lets just confirm either way first.

**Comment by marschall** [comment]
I originally opened the JIRA: the issue I'm having is that the [contributing guide](https://github.com/hibernate/hibernate-orm/blob/master/CONTRIBUTING.md) for Eclipse links to the [wiki](https://developer.jboss.org/wiki/ContributingToHibernateUsingEclipse) which says one should run:

```
./gradlew clean eclipse --refresh-dependencies
```

which doesn't work because the tasks are missing. For me any of these solutions would work:

1. Officially not supporting Eclipse and removing all references from the documentation.
1. Requiring and documenting the Eclipse Gradle plugin.
1. Reenabling the eclipse tasks in Gradle.

**Comment by aepedraza** [comment]
> Is there any particular reason why the two allprojects blocks cannot be merged together at the top rather than having two of them in the script?

Actually there's no reason, I just didn't saw the first block in the script. I'll be fixing it right away.
While we wait some feedback from @sebersole, I'd suggest to include the uncommented lines and add the workaround in CONTRIBUTING.MD, which would be to comment the lines or run the command `./gradlew clean --refresh-dependencies` (without invoking `eclipse` plugin).
I'll be awaiting for your comments, in the meantime I'll be adding some commits with my suggestions

**Comment by Naros** [comment]
@aepedraza Could you rework your PR and eliminate the merge commit for me?  We have some tips in https://github.com/hibernate/hibernate-orm/blob/master/CONTRIBUTING.md where we discuss creating a topic/feature branch and making your changes there and submitting your PR based on that branch to us.  It just keeps the history much cleaner when we do merge your work.

**Comment by sebersole** [comment]
I guess it comes down to this... For IntelliJ users I'd only recommend using the importer.  Is that true for Eclipse at this point as well?  Is their Gradle import support good now?  If so, that should be the only recommended way.

And then, does their Gradle project importer use information configured on `org.gradle.plugins.ide.eclipse.model.EclipseModel` to customize the import the way that IntelliJ does?  If so, we could consider enabling that plugin if we actually have something to configure - but, again, atm this PR is not doing that.

**Comment by dwadler** [comment]
When I imported Hibernate using the Gradle importer, I had over 700 errors across numerous projects.

**Comment by sebersole** [comment]
You mean compile errors?  From missing (not yet) generated sources?  Even
enabling the idea/eclipse plugin won't help with those.  It's pretty common
practice to build a project first for this and it's not a concern.

If you mean other kinds of errors, we'd need to know about them
specifically.

For what it's worth, I do a fresh import into intellij probably 2 or 3
times a month and switch between the various branches (needing a re-import)
way more frequently and never have any problems with it - aside from code
generation of course.

**Comment by sebersole** [comment]
Btw I reached out to the JetBrains folks about this and here is what they
told me.

1) run a Gradle task on import is already a requested feature @
https://github.com/JetBrains/gradle-idea-ext-plugin/.  We will use that as
soon as it is available.  Vote for it of you wish

2) there is an "extension plugin" similar to Gradle's `idea` plugin
intended to allow extra configuration of the import process -
https://github.com/JetBrains/gradle-idea-ext-plugin/. I'll look through
that a little to see if anything there can help us; I was completely
unaware of this plugin

>

**Comment by dwadler** [comment]
I just did a fresh clone of hibernate-orm master, did a clean and build (twice). Then imported the Gradle project into Eclipse which resulted in 775 errors.
image

**Comment by aepedraza** [comment]
> Could you rework your PR and eliminate the merge commit for me? We have some tips in https://github.com/hibernate/hibernate-orm/blob/master/CONTRIBUTING.md where we discuss creating a topic/feature branch and making your changes there and submitting your PR based on that branch to us

@Naros, apologize about my dirty commits. I can move my clean commits to a branch for this ticket but, AFAIK, I should start a new PR as the referenced branches will be changing, am I correct?

BTW, should this be done with `cherry-pick`or something else? what do you suggest? (Sorry, I'm not sooo good in git commits cleaning).

Thanks in advance for your answers

**Comment by sebersole** [comment]
And does it work when *just* applying the plugin (like this PR does)?

**Comment by aepedraza** [comment]
I'm closing this PR as the compare branch is wrong and dirty commits were generated. Apologize

**Pull request closed without merging**
