### PR TITLE
Fixed and reorganized tests in hibernate-jcache

### PR DESCRIPTION
**Pull request by jrenaat**
Signed-off-by: Jan Schatteman <jschatte@redhat.com>

### CODE REVIEW

**Review by beikov — COMMENTED** [review]
`RefreshUpdatedDataTest` is failing on derby, other than that, this looks ok

**Review by beikov — APPROVED** [review]

**Comment by jrenaat** [comment]
Still looking into issues with this PR; I removed the extension from BaseUnitTestCase from one (or several) Tests, and that provokes at least one of those to hang, which was previously caught by the Timeout Junit Rule.

**Comment by dreab8** [comment]
Hi @jrenaat, try to add `@BaseUnitTest` to the tests where you have removed `extends BaseUnitTestCase`

**Comment by jrenaat** [comment]
I have ignored the RefreshUpdatedDataTest for the sybase and hsqldb environments, because it simply hangs 8db locking issues?), but now running into another ~170 tests failing in sybase (not apparently related to the changes in hibernate-jcache).
Locally, only two fail (consistently), and this can only be reproduced by running all hibernate-core tests (i.e. not by running the failing test individually); the exception message is "Converting `org.hibernate.exception.JDBCConnectionException` to JPA `PersistenceException` : Error calling Driver#connect" --> connections not being closed somewhere?

**Comment by beikov** [comment]
This should be fine. I guess this is just a temporary issue.

**Pull request merged**
