### PR TITLE
HHH-10956 test cases and fix

### PR DESCRIPTION
**Pull request by pdinc-oss**
see https://hibernate.atlassian.net/browse/HHH-10956

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @pdinc-oss ,

the issue it is how you define the `IdClass`

for such a case
```
@Entity
@IdClass(PK.class)
public static class NodeS {

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	private Long nid;

	@Id
	@ManyToOne
	private HeadS hid;
        ...
}
```
the class has to be
```
class PK implements Serializable {

	private Long nid;

	private HeadS hid;

	public PK(Long nid, HeadS hid) {
		this.nid = nid;
		this.hid = hid;
	}
        ...
}
```
and not
```
class PK implements Serializable {

	private Long nid;

	private Long hid;

	public PK(Long nid, Long hid) {
		this.nid = nid;
		this.hid = hid;
	}

	... 
}
```

**Comment by dreab8** [comment]
I think the gist of the issue is this case 
```
@Entity
@IdClass(PK.class)
public static class NodeI {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	private Long nid;

	@Id
	@ManyToOne
	private HeadI hid;
    
        ...
}

public static class PK implements Serializable {

	private Long nid;

	private HeadI hid;

	public PK(Long nid, HeadI hid) {
		this.nid = nid;
		this.hid = hid;
	}
}

```
and the PR seems not solving it.

**Comment by pdinc-oss** [comment]
> Hi @pdinc-oss ,
> 
> the issue it is how you define the `IdClass`
> 
> for such a case
> 
> ```
> @Entity
> @IdClass(PK.class)
> public static class NodeS {
> 
> 	@Id
> 	@GeneratedValue(strategy = GenerationType.SEQUENCE)
> 	private Long nid;
> 
> 	@Id
> 	@ManyToOne
> 	private HeadS hid;
>         ...
> }
> ```
> 
> the class has to be
> 
> ```
> class PK implements Serializable {
> 
> 	private Long nid;
> 
> 	private HeadS hid;
> 
> 	public PK(Long nid, HeadS hid) {
> 		this.nid = nid;
> 		this.hid = hid;
> 	}
>         ...
> }
> ```

JPA 2 spec 2.4.1.3 Examples of Derived Identities, 

Case (a): The dependent entity uses IdClass to represent a composite key:

```
public class DependentId {
 String name; // matches name of @Id attribute
 long emp; // matches name of @Id attribute and type of Employee PK
}
@Entity
@IdClass(DependentId.class)
public class Dependent {
 @Id String name;
// id attribute mapped by join column default
 @Id @ManyToOne Employee emp;
...
}
```

HeadS is the Entity type and its Id type is Long.

I backed out the changes to SimpleValue.java/AbstractEntityTuplizer.java and [changed the IdClasses to match](https://github.com/hibernate/hibernate-orm/files/4522903/CompositeIdFkGeneratedValueIdentityTest.java.deviate-from-case-a.txt) and it does [pass the tests](https://github.com/hibernate/hibernate-orm/files/4522898/HHH-10956-no-patch-deviate-from-case-a-PASS.pdf) in Hibernate.

But when testing 2.4.1.3, case a without the patch the following [tests fails](https://github.com/hibernate/hibernate-orm/files/4522892/HHH-10956-no-patch-follow-spec-FAILED.pdf):

- testCompositePkWithIdentityAndFKByAuto: No part of a composite identifier may be null
- testCompositePkWithIdentityAndFKByAuto2: No part of a composite identifier may be null
- testCompositePkWithIdentityAndFKBySequence: No part of a composite identifier may be null
- testCompositePkWithIdentityAndFKBySequence2: No part of a composite identifier may be null
- testCompositePkWithIdentityAndFKByTable: No part of a composite identifier may be null
- testCompositePkWithIdentityAndFKByTable2: No part of a composite identifier may be null

These tests are expected to fail / ignored:
- testCompositePkWithIdentityAndFKByIdentity: No part of a composite identifier may be null
- testCompositePkWithIdentityAndFKByIdentity2: skipped

**Comment by pdinc-oss** [comment]
> I think the gist of the issue is this case
> ```
> 	@Id
> 	@GeneratedValue(strategy = GenerationType.IDENTITY)
> 	private Long nid;
> 	@Id
> 	@ManyToOne
> 	private HeadI hid;
> ```
> and the PR seems not solving it.

When Mark Paluch opened this ticket, he gave an overly narrow test case. Now since then HHH-9662 has addresses a specific, contributory, issue I have omitted it from this patch. But even with HHH-9662 and without this patch Mark's error message will persist.

It is important to note, that the test case provided by Mark is no longer accessible and the other commenters have indicated it is an issue for other GenerationTypes. This tet case test Auto, Identity, Sequence, and Table. The negative results when the patch is removed speaks for itself.

**Comment by dreab8** [comment]
@pdinc-oss thanks for the clarification

**Comment by pdinc-oss** [comment]
> @pdinc-oss thanks for the clarification

Not a problem, it is a big tangle out there.

BTW, applied the fix to [Vianney Dubus' bug demonstration](https://github.com/pdinc-oss/HHH-10956-test-case) too

**Comment by dreab8** [comment]
Hi @pdinc-oss , I created a new PR based on yours, I noticed a case that should cause an exception but it doesn't with your change.

**Comment by dreab8** [comment]
superseded by https://github.com/hibernate/hibernate-orm/pull/3376

**Pull request closed without merging**
