### PR TITLE
HHH-18783 cast(x as Character) on MySQL and Maria

### PR DESCRIPTION
**Pull request by gavinking**
Based on #9194.

@cigaly WDYT?

[Please describe here what your change is about]

----------------------
By submitting this pull request, I confirm that my contribution is made under the terms of the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0.txt)
and can be relicensed under the terms of the [LGPL v2.1 license](https://www.gnu.org/licenses/old-licenses/lgpl-2.1.txt) in the future at the maintainers' discretion.
For more information on licensing, please check [here](https://github.com/hibernate/hibernate-orm/blob/main/CONTRIBUTING.md#legal).

----------------------

https://hibernate.atlassian.net/browse/HHH-18783

### CODE REVIEW

**Comment by cigaly** [comment]
Hope that this will work. Only afraid that some things are very strange in MySQL. 

Do you think that `java.lang.Character` should always be represented with something (char?) of length 1?

**Comment by gavinking** [comment]
> Do you think that `java.lang.Character` should always be represented with something (`char`?) of length 1?

I recently changed it to map to `varchar(1)` by default, because `char` columns are just too weird/broken.

**Comment by cigaly** [comment]
> > Do you think that `java.lang.Character` should always be represented with something (`char`?) of length 1?
> 
> I recently changed it to map to `varchar(1)` by default, because `char` columns are just too weird/broken.

Unfortunately, in MySQL you can write `cast(x as char(3))`, but not `cast(x as varchar(3))`

In this particular case, if `CastTarget.length` was 1 for `java.lang.Character`, there will be no problem with `cast(x as Character)`

**Comment by gavinking** [comment]
@cigaly Right, and that's a thing that is in principle supposed to be handled via the `DdlType` object which distinguishes the cast type from the column type.

Unfortunately, MySqlAstTranslator has deviated from the narrow path here, and is doing things its own way, and that's why this hack was necessary. I opened a JIRA issue to fix this.

**Pull request merged**
