### PR TITLE
added many-to-one on-delete="cascade" xml mapping

### PR DESCRIPTION
**Pull request by kedzie**
I don't know if there was a reason this already wasn't in the XML mapping DTD/XSD.  but i added it because I needed it.  I cannot use annotations in my project, we are using generated sources.

### CODE REVIEW

**Comment by kedzie** [comment]
Has anyone taken a look at this?

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by richardfontana** [comment]
@vladmihalcea this can be merged without needing the CLA.

**Comment by vladmihalcea** [comment]
Hi @kedzie,

We need a JIRA issue for this and also a test case. Can you provide those?

Thanks

**Comment by vladmihalcea** [comment]
I'm closing this issue since I provide a [new PR](https://github.com/hibernate/hibernate-orm/pull/1392) that handles on-delete in a similar way with annotations.

**Pull request closed without merging**
