### PR TITLE
Remove FrontBaseDialect

### PR DESCRIPTION
**Pull request by gavinking**
This database had a recent release (October last year) and it runs on Mac, so I was keen to try it. It didn't last long on my machine because&mdash;recent release notwithstanding&mdash;it looks all quite antiquated and it didn't work especially well with Hibernate.

I doubt anyone is using this.

### CODE REVIEW

**Comment by NathanQingyangXu** [comment]
I know nothing about this, but I share the curiosity. So I found three tickets containing 'frontbase':
https://hibernate.atlassian.net/projects/HHH/issues/HHH-12886?filter=allopenissues&orderby=priority%20DESC&keyword=frontbase

According to http://db-engines.com/en/ranking, the db ranks at 181.
No comment, though.

**Comment by gavinking** [comment]
> I found three tickets containing 'frontbase'

Heh, so we do have clear evidence that someone once used `FrontbaseDialect` back in 2006 ;-)

**Comment by NathanQingyangXu** [comment]
> > I found three tickets containing 'frontbase'
> 
> Heh, so we do have clear evidence that someone once used `FrontbaseDialect` back in 2006 ;-)

Well, I think it is much recent if you search 'frontbase' in the exception log content in https://hibernate.atlassian.net/browse/HHH-12886.
Screen Shot 2020-02-01 at 1 06 19 PM

The ticket was created 2018 Aug 5.

**Comment by gavinking** [comment]
> Well, I think it is much more recent if you search 'frontbase' in the exception log content 

@NathanQingyangXu You're mistaken. If you read the log more closely, and the issue description, you'll see that the user was using H2.

**Comment by NathanQingyangXu** [comment]
> > Well, I think it is much more recent if you search 'frontbase' in the exception log content
> 
> @NathanQingyangXu You're mistaken. If you read the log more closely, and the issue description, you'll see that the user was using H2.

yeah, you are right, :(.

**Pull request merged**
