### PR TITLE
HHH-13777 UnsupportedOperationException is thrown for MappedSuperclas…

### PR DESCRIPTION
**Pull request by dreab8**
…s if the id is declared on subclasses

https://hibernate.atlassian.net/browse/HHH-13777

@sebersole any advice for a better name than `isNotDeclaredIdentifierDescriptorLegal()` is really appreciated.

### CODE REVIEW

**Comment by sebersole** [comment]
`#isMissingIdentifierLegal` ?

Anyway, I think the solution looks good

**Comment by sebersole** [comment]
or how about flipping the logic and have `#isIdMappingRequired`

**Comment by dreab8** [comment]
I like it, I'll make the change and push it. Thanks

**Comment by dreab8** [comment]
applied Steve suggestion and pushed

**Pull request closed without merging**
