### PR TITLE
HHH-10956 Persisting partially-generated composite Ids fails with HibernateException: No part of a composite identifier may be null

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-10956
it is based on https://github.com/hibernate/hibernate-orm/pull/3368, and it fixes an issue with null values for composite id see testCompositePkWithSequenceGeneratorAndNullValue()

### CODE REVIEW

**Comment by pdinc-oss** [comment]
liking the negative checks
why the throws exception everywhere?
based on your changes to AbstractEntityTuplizer, my spidy sense feels there may be further optimization - will check when I get to the office.

**Comment by pdinc-oss** [comment]
I made an [update](https://github.com/pdinc-oss/hibernate-orm/commit/f1f271dcb725ee1ece1e9faf508b75cb78558f02). Not sure how to add to this pull request, see: https://github.com/hibernate/hibernate-orm/pull/3378

**Comment by dreab8** [comment]
Thanks @pdinc-oss,

applied to master and 5.4

**Comment by Clopma** [comment]
When I saw this I was 100% sure that setting 5.4 version to my project would not fix the bug. And I was right, It didn't.

**Pull request closed without merging**
