### PR TITLE
HHH-10684 - No target script generated for update action when using schema-generation

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-10684

### CODE REVIEW

**Comment by sebersole** [comment]
What is the reasoning behind just switching the order of the executions working?

**Comment by dreab8** [comment]
in the case of update, the database action update the database and so the script action generates an empty script.

**Comment by sebersole** [comment]
Ok, makes sense

**Comment by dreab8** [comment]
applied to 5.1 and master

**Pull request closed without merging**
