### PR TITLE
Backport HHH-14315 + HHH-14323 + HHH-14370 + HHH-14371 + HHH-14372 to branch 5.4 - Upgrade to Gradle 6.7 and use toolchains for per-JDK builds

### PR DESCRIPTION
**Pull request by yrodiere**
* [HHH-14372](https://hibernate.atlassian.net/browse/HHH-14372): Upgrade to Weld 3.1.5.Final in tests
* [HHH-14371](https://hibernate.atlassian.net/browse/HHH-14371): Add --add-opens options required for tests
* [HHH-14370](https://hibernate.atlassian.net/browse/HHH-14370): Add --add-opens options required for Gradle
* [HHH-14323](https://hibernate.atlassian.net/browse/HHH-14323): Backport HHH-13682 to 5.4: Generate Java 13/14 bytecode for tests when building with JDK13/14
* [HHH-14315](https://hibernate.atlassian.net/browse/HHH-14315): Upgrade to Gradle 6.7 and use toolchains for per-JDK builds

### CODE REVIEW

**Comment by gbadner** [comment]
@yrodiere, who would be the appropriate reviewer? I'm not familiar with why these changes were made in master, so I don't feel comfortable reviewing myself.

**Comment by yrodiere** [comment]
Hi @gbadner, and happy new year! No problem, Sanne was involved in this from the start, I'll ask him for a review. I just noticed something doesn't work on JDK15 though, so I'll try and fix that first.

**Comment by yrodiere** [comment]
@Sanne I think we can merge this into 5.4:

* Interested third parties confirmed that they can handle Gradle 6.7.
* I checked that the build passes on [JDK15](https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-yoann-jdk15/10/) and [JDK16](https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-yoann-jdk16/21/)
* I created Jenkins jobs for [JDK15](https://ci.hibernate.org/view/ORM/job/hibernate-orm-5.4-h2-jdk15/) and [JDK16](https://ci.hibernate.org/view/ORM/job/hibernate-orm-5.4-h2-jdk16/)

**Comment by Sanne** [comment]
very nice! thanks

I'll run one last check locally..

**Pull request merged**
