### PR TITLE
HHH-11007 - Add Hibernate Envers tests to WildFly modules distribution.

### PR DESCRIPTION
**Pull request by Naros**
https://hibernate.atlassian.net/browse/HHH-11007

### CODE REVIEW

**Comment by Sanne** [comment]
The `xml` files of the modules are missing.. I guess you forgot to include them in the git commit @Naros ?

Also it would be great if you could add a test as it's really tricky to understand if the class visibility is correct w/o trying it out.

If you follow the steps of the existing Arquillian test, it should be simple to add one using Envers?

**Comment by Naros** [comment]
@Sanne Looking back over this, I noticed hibernate-envers is being included in the core module xml.  I assume I need to split that out to its own xml file with module dependencies?

**Comment by Sanne** [comment]
@Naros you're right, it seems it was already included. No I wasn't asking to split it out, I'd rather keep the same module structure as what Wildfly has been using so far (for the ORM version it regularly integrates).

N.B. I opened the JIRA issue on behalf of a user .. he might have been wrong, I didn't double check!

But from his comment it sounds like it wasn't working. Maybe just add the integration test to verify it, without changing the module? Then if it actually works fine, you can change the JIRA description to reflect that we're only adding a test.

**Comment by Naros** [comment]
@Sanne it appears all we needed was to add Envers as a test compile dependency and add the suggested test.  I'll adjust JIRA accordingly.

**Comment by gunnarmorling** [comment]
Would be nice to backport this to 5.1, too (assuming there is going to be another 5.1.x release).

**Comment by Naros** [comment]
Applied upstream.

**Pull request closed without merging**
