### PR TITLE
HHH-11028 Test Case (version 5.1) + Fix

### PR DESCRIPTION
**Pull request by raissi**
These are the Test cases + the fix for the issue that I previously reported against version 4.3

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Should we close the [previous Pull Request](https://github.com/hibernate/hibernate-orm/pull/1515)?

**Comment by raissi** [comment]
The previous PR is for version 4.3 and there is a minor difference in the Test classes. I don't know about the procedure so I will let you do what is better

**Comment by raissi** [comment]
Is there any news considering the reported issue ?

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
