### PR TITLE
HHH-12064 - Issue with unidirectional one-to-many association with a join column that references a column that is not the primary key

### PR DESCRIPTION
**Pull request by marcellor**
A one-to-many association is causing Hibernate to 
throw 
`INFO: HHH000327: Error performing load command : org.hibernate.property.access.spi.PropertyAccessException: 
`
when loading an entity via Session.get(domainClass, identifier), under the following conditions:
1. the association collection is annotated with @Fetch(FetchMode.JOIN)
2. the association's join column is referencing a non-primary key of the owning entity
3. the association's join column value is referencing a non-existing record of the associated table (the "many" side).

```
package org.hibernate.bugs;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.junit.Before;
import org.junit.Test;

/**
 * Issue with unidirectional one-to-many association with a join column that
 * references a column that is not the primary key.
 */
public class ORMStandaloneTestCase {

  private SessionFactory sf;


  @Before
  public void setup() {
    StandardServiceRegistryBuilder srb = new StandardServiceRegistryBuilder().applySetting("hibernate.show_sql", "true")
        .applySetting("hibernate.format_sql", "true").applySetting("hibernate.hbm2ddl.auto", "update");

    Metadata metadata = new MetadataSources(srb.build()).addAnnotatedClass(Customer.class).addAnnotatedClass(Order.class)
        .buildMetadata();

    sf = metadata.buildSessionFactory();
  }


  @Test
  public void unidirectionalOneToManyAssociationTest() throws Exception {
    Session session = sf.openSession();
    Transaction tx = session.beginTransaction();

    try {
      // Save the entity on the One side
      Customer customer = new Customer();
      customer.idCode = "ABC";
      customer.translationId = 1L;

      session.persist(customer);
    } finally {
      tx.commit();
      session.close();
    }

    try {
      session = sf.openSession();
      tx = session.beginTransaction();

      // Attempt to load the entity saved in the previous session
      session.get(Customer.class, "ABC");

    } finally {
      tx.commit();
      session.close();
    }
  }

  @Entity
  public static class Customer implements Serializable {

    @Id
    @Basic
    public String      idCode;

    @Basic
    @Column(precision = 15, scale = 0)
    public Long        translationId;

    @Fetch(FetchMode.JOIN)
    @OneToMany(fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "translationId", referencedColumnName = "translationId")
    public List<Order> translations;
  }

  @Entity
  public static class Order implements Serializable {

    @Id
    @Basic
    @Column(precision = 15, scale = 0)
    public long id;

    @Basic
    @Column(precision = 15, scale = 0)
    public long translationId;
  }
}
```

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. We need a Jira issue to better track the changes and also a test case to see the problem in action. Would you mind adding those as well?

**Comment by gbadner** [comment]
This sounds like https://hibernate.atlassian.net/browse/HHH-9370...

**Comment by vladmihalcea** [comment]
@gbadner I tried it and it does not fix HHH-9370, so I'll create a new issue for it.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
