### PR TITLE
HHH-17257 ElementCollection is missing elements after update if embeddable type has primitive columns marked as nullable

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-17257 

this should resolve a case the user reported that  https://github.com/hibernate/hibernate-orm/pull/7372 haven't fixed

### CODE REVIEW

**Comment by gavinking** [comment]
> this should resolve a case the user reported that https://github.com/hibernate/hibernate-orm/pull/7372 haven't fixed

But isn't that case simply a user error that we should detect and report? The key columns of a `@CollectionTable` have to be non-null, don't they?

**Comment by dreab8** [comment]
Hi @gavinking ,

given 
```
@Embeddable
public static class MyEmbeddable {
  @Column
  // the field is considered non-optional because of its primitive type
  private int intField;

@Column
// the field is considered non-optional because of its primitive type
private boolean booleanField;
}
...
we were considering `intField` and booleanField` as nullable when they are not because are primitive.

**Comment by dreab8** [comment]
I think that for 
```
@ElementCollection(fetch = FetchType.EAGER)
Set<MyEmbeddable> elementCollection;
```
 we have never required that all the fields of the `MyEmbeddable` have to be non-null.

**Comment by gavinking** [comment]
Right, but I'm referring to this comment:

> I think it still breaks if the “key” field is a primitive and marked as nullable in the `@Column` annotation.

But the key field of a collection is an FK referring to the PK of the owning entity. It can't be null, can it?

**Comment by dreab8** [comment]
I think the user used the word `key` incorrectly, the field of the embeddable (_the `key` primitive field_ ) is not part of the collection PK neither of the FK.

**Comment by gavinking** [comment]
> I think the user used the word key incorrectly

Oh, OK, fine. Sorry for the noise.

**Review by beikov — APPROVED** [review]

**Pull request merged**
