### PR TITLE
HHH-9271 IdentityGenerator broken with quoted identifiers

### PR DESCRIPTION
**Pull request by ogatakex**
Fix for https://hibernate.atlassian.net/browse/HHH-9271

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Replaced this PR with [this one](https://github.com/hibernate/hibernate-orm/pull/1301) which contains a replicating test and tries to deal with both quoted and unquoted identifiers (in case some JDBC driver will use a quoted identifier in the `ResultSet`)

**Comment by vladmihalcea** [comment]
Hi @ogatakex ! Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by ogatakex** [comment]
Hi @vladmihalcea 
Yes, I signed the CLA. Please check.

**Comment by vladmihalcea** [comment]
Thanks. Unfortunately, only Steve is authorized to check that CLA app, so that's why I was asking you to confirm.

**Pull request closed without merging**
