### PR TITLE
HHH-14622 Improved iteration of PreLoadEventListener

### PR DESCRIPTION
**Pull request by Sanne**
To be followed up by matching changes in Hibernate Reactive:
 - https://github.com/hibernate/hibernate-reactive/commit/d13012d1b23a374a827b4f02d696269cbb1777a3

Lots of code deletions :)

### CODE REVIEW

**Review by DavideD — APPROVED** [review]
Nice

**Comment by DavideD** [comment]
This should also be merged in 5.4, or we won't be able to build with both versions in Hibernate Reactive

**Comment by Sanne** [comment]
Didn't I do already?

**Comment by DavideD** [comment]
Yeah sorry. I didn't check before writing the comment

**Pull request merged**
