### PR TITLE
[HHH-11203] fix some minor test issues

### PR DESCRIPTION
**Pull request by simkam**
https://hibernate.atlassian.net/browse/HHH-11203
related 5.0 PR https://github.com/hibernate/hibernate-orm/pull/1604

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @simkam ,

can you open a different jira for this PR?

Thanks

**Comment by simkam** [comment]
created https://hibernate.atlassian.net/browse/HHH-11203 and update commit message and PR description

**Comment by dreab8** [comment]
Thanks @simkam

**Comment by dreab8** [comment]
applied to master
Thanks @simkam

**Comment by Sanne** [comment]
I just noticed HHH-11199 refers to this, yet is marked open. Something wrong with the JIRA state?

**Comment by simkam** [comment]
@Sanne HHH-11199 is for 5.branch and I'm not sure if it was fixed, related PR is still open #1604. This PR was for upstream and HHH-11203 (requested by Andrea, see comments above)

**Comment by Sanne** [comment]
thanks for clairfying @simkam . I think 5.0 is no longer maintained but I'll leave this open a bit more so that the team can confirm. Sorry it took so long :(

**Pull request closed without merging**
