### PR TITLE
HHH-12629: PR

### PR DESCRIPTION
**Pull request by nikowitt**
Pull request for
https://hibernate.atlassian.net/browse/HHH-12629

Regards, Niko

### CODE REVIEW

**Comment by Sanne** [comment]
Thanks! always great to delete some dead code.

Regarding the protected methods: we'll apply this change _temporarily_ so to help you with your migration, but I can't promise they will stay protected for long (or for any other version), deal?

We'll have to figure out a better solution for your 61+ joins :)

**Comment by nikowitt** [comment]
Definititely, thank you! The trouble is that we cannot change the database architecture, so I need to have a solution for this. But is there a particular reason that the methods cannot stay protected (as they used to be)? loadFromSessionCache is also still protected.

**Comment by Sanne** [comment]
I'm not sure if there is a strong reason, but anything in _internal_ packages is bound to change often.

There is also some possibility that this was an important change if I look at who made it; Stale is the lead of the performance team and sometimes it implies obscure yet important optimisations - I doubt it's the case so let's apply this but I'll eventually have to confirm with him, and he might want this reverted.

**Comment by Sanne** [comment]
merging

**Comment by nikowitt** [comment]
Thanks for merging. Can you update me about any progress about the internal discussion?

**Comment by Sanne** [comment]
FYI we don't really do internal discussions; we'll likely discuss this either on HipChat public rooms, developer mailing list, or via a new feature JIRA.

Probably best if you could start by opening a JIRA? It will need some time as half the team is away discussing ORM6 details.

**Comment by nikowitt** [comment]
Sure. Created https://hibernate.atlassian.net/browse/HHH-12632.

**Pull request closed without merging**
