### PR TITLE
HHH-17245 Better conform to SQLite/Xerial driver limitations.

### PR DESCRIPTION
**Pull request by hendriks73**
- Added `getAlterTableToAddUniqueKeyCommand()`, which always returns `""`,  because SQLite does not support unique constraints in `ALTER TABLE`  statements (see [here](https://www.sqlite.org/omitted.html)). 
- Added `getDefaultUseGetGeneratedKey()`, which always returns `false`, as the Xerial driver apparently does not support GET_GENERATED_KEYS.

https://hibernate.atlassian.net/browse/HHH-17245

### CODE REVIEW

**Comment by hendriks73** [comment]
I don't want to impose, but perhaps one of the original authors of the SQLite Dialect, @beikov or @vladmihalcea, could take a look at this.

Thanks so much!

**Comment by vladmihalcea** [comment]
I've never used SQLite, so I wasn't the author of that Dialect.

**Comment by hendriks73** [comment]
Sorry to bother you, @vladmihalcea. You're [listed as author](https://github.com/hibernate/hibernate-orm/blob/3345658d9d991583da22a7118d08fca9cb9c8e5c/hibernate-community-dialects/src/main/java/org/hibernate/community/dialect/SQLiteDialect.java#L93) in the source and I didn't check git blame. I guess it's more or less all @beikov 's work.

**Comment by vladmihalcea** [comment]
That Javadoc is not accurate.

**Comment by hendriks73** [comment]
OK. I have removed the corresponding author tag.

**Comment by hendriks73** [comment]
Thank you, much appreciated!

**Pull request merged**
