### PR TITLE
HHH-14360 Test a fix for NPE due to non-existing previous state in bytecode enhanced dirty attribute resolving

### PR DESCRIPTION
**Pull request by beikov**
https://hibernate.atlassian.net/browse/HHH-14360

### CODE REVIEW

**Review by jwgmeligmeyling — APPROVED** [review]

**Review by dreab8 — APPROVED** [review]
it looks good to me :+1:

**Comment by tlamr** [comment]
Running our integration tests with this change fixes the null pointer issue for us.

Thanks a lot!

**Comment by Sanne** [comment]
Looks straight forward, but many CI tests failed :/ I'll schedule a re-run as it doesn't seem related.

**Comment by Sanne** [comment]
Re-running.. CI seems to be having a bad day.

**Comment by Sanne** [comment]
thanks all! Merged and backported

**Pull request merged**
