### PR TITLE
Backport HHH-15265 + HHH-15270 to branch 5.6 - Default catalog/schema fixes

### PR DESCRIPTION
**Pull request by yrodiere**
* [HHH-15270](https://hibernate.atlassian.net/browse/HHH-15270): Inconsistent precedence of orm.xml implicit catalog over "default_catalog" in XML-mapped entities
* [HHH-15265](https://hibernate.atlassian.net/browse/HHH-15265): SchemaExport.execute does not add the configured schema to comments

Backport of #5046 to branch 5.6.

### CODE REVIEW

**Comment by beikov** [comment]
Unfortunately, the test report for the failing test couldn't be generated because the file name is too long for Linux, so I can't tell you what it is that goes wrong. Could you please look into the failure?

**Comment by Sanne** [comment]
not important, but there's a typo in the package names `qualfiedTableNaming`

**Comment by Sanne** [comment]
ah, the package names are actually important: the test is defined in package `org.hibernate.test.boot.database.qualfiedTableNaming` - but the XML mapping is pointing to `org.hibernate.orm.test.boot.database.qualfiedTableNaming` - this is causing a classloading failure.

**Comment by Sanne** [comment]
rebased and added a commit

**Comment by yrodiere** [comment]
Right, the automatic conflict resolution in git seems to have handled the folder renaming in ORM 6, but I didn't take the time to check it worked... Sorry about that, and thanks for taking care of it!

**Pull request merged**
