### PR TITLE
HHH-9951 - Fixes/Improvements for @Formula usage. 

### PR DESCRIPTION
**Pull request by michaelhum**
Enforce lower-case storage of custom keyword to reduce confusion with @Formula generation.
Check column types when determining if a token needs to be escaped.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by michaelhum** [comment]
Just did, thanks.

**Comment by vladmihalcea** [comment]
You're welcome. This PR needs to be analyzed along with [this one](https://github.com/hibernate/hibernate-orm/pull/1308) as well and see which one needs to be merged, or if we need to combine them both.

**Comment by vladmihalcea** [comment]
Replaced this PR with [this one](https://github.com/hibernate/hibernate-orm/pull/1370/) which is rebased, uses Hibernate code style, and adds the license headers.

**Pull request closed without merging**
