### PR TITLE
HHH-13741 : Logging SQL query when using LOG_SLOW_QUERY

### PR DESCRIPTION
**Pull request by jai-yadav**
https://hibernate.atlassian.net/browse/HHH-13741

### CODE REVIEW

**Comment by sebersole** [comment]
Unfortunately we no longer support 5.4 and therefore no longer do releases of it.  I can apply the PR as it applies cleanly, but you'd have to run a custom build.

Have you considered migrating to 5.6 or 6.0, which are the currently supported versions?

**Comment by jai-yadav** [comment]
@sebersole We are in process of migrating to 6.0 but it's taking it's time. It would be great if you can approve this PR and I'll try to incorporate the changes to 5.6 and 6.0 as well. Thanks.

**Comment by ozkanpakdil** [comment]
I upgraded to spring boot 2.7.4 which brings hibernate core 5.6.11 and I see 
```
org.hibernate.SQL_SLOW                   : SlowQuery: 80 milliseconds. SQL: 'HikariProxyPreparedStatement@1363216410 wrapping oracle.jdbc.driver.OraclePreparedStatementWrapper@279aac5f'
```
which version of hibernate should I use ?

**Comment by herisson-88** [comment]
https://github.com/hibernate/hibernate-orm/pull/7030

**Pull request closed without merging**
