### PR TITLE
HHH-14724 Test-case for metamodel compile error with converters and validation

### PR DESCRIPTION
**Pull request by theigl**
Test case for https://hibernate.atlassian.net/browse/HHH-14724

I hijacked an existing test by adding bean validation to a list converter. With this change, two tests in `org.hibernate.jpamodelgen.test.collectionbasictype.CollectionAsBasicTypeTest` result in compilation errors.

I can add a separate test-case if that makes more sense.

### CODE REVIEW

**Comment by Sanne** [comment]
@beikov seems related to #3254 . Could you have a look?

**Comment by theigl** [comment]
@Sanne: You are right. I already documented that in the JIRA ticket.

I also pushed a tentative fix to this PR. It works, but it isn’t perfect, because it relies on string manipulation to strip annotation metadata from the type string.

**Comment by beikov** [comment]
I understand the problem, but I need to debug the compilation process to find out how to properly solve this. I'll try to work on this ASAP.

**Comment by theigl** [comment]
@beikov: The easiest way to see what's going on is to set a breakpoint [here](https://github.com/hibernate/hibernate-orm/pull/4096/files#diff-d8f1b1fed51ad23139cac274c7338e19ced95f0224ad39f3c4efea830b718481R82) and run the `CollectionAsBasicTypeTest`.

The type contains the metadata and I found no way of stripping it before converting it to a string. There is `com.sun.tools.javac.code.Type#stripMetadata` but this would require casting the instance to a concrete implementation which isn't a good idea.

**Comment by beikov** [comment]
I know. I'm currently working on a visitor based solution to handle this.

**Comment by beikov** [comment]
Hey @theigl, can you test the fix I provided?

**Comment by theigl** [comment]
@beikov: Your fix solves the original issue, but results in other compilation errors:

```
Caused by: javax.lang.model.type.UnknownTypeException: Unknown type: java.lang.Object&com.project.domain.DomainObject&com.project.domain.Owned
    at javax.lang.model.util.AbstractTypeVisitor6.visitUnknown (AbstractTypeVisitor6.java:156)
    at javax.lang.model.util.AbstractTypeVisitor6.visitIntersection (AbstractTypeVisitor6.java:137)
    at com.sun.tools.javac.code.Type$IntersectionClassType.accept (Type.java:1275)
    at org.hibernate.jpamodelgen.util.TypeRenderingVisitor.visitTypeVariable (TypeRenderingVisitor.java:119)
    at com.sun.tools.javac.code.Type$TypeVar.accept (Type.java:1695)
    at org.hibernate.jpamodelgen.util.TypeRenderingVisitor.visitDeclared (TypeRenderingVisitor.java:103)
    at com.sun.tools.javac.code.Type$ClassType.accept (Type.java:1151)
    at org.hibernate.jpamodelgen.util.TypeRenderingVisitor.toString (TypeRenderingVisitor.java:48)
    at org.hibernate.jpamodelgen.util.TypeUtils.toTypeString (TypeUtils.java:77)
    at org.hibernate.jpamodelgen.util.TypeUtils$EmbeddedAttributeVisitor.visitExecutable (TypeUtils.java:463)
    at org.hibernate.jpamodelgen.util.TypeUtils$EmbeddedAttributeVisitor.visitExecutable (TypeUtils.java:439)
    at com.sun.tools.javac.code.Type$MethodType.accept (Type.java:1513)
    at org.hibernate.jpamodelgen.util.TypeUtils.updateEmbeddableAccessTypeForMember (TypeUtils.java:290)
    at org.hibernate.jpamodelgen.util.TypeUtils.updateEmbeddableAccessType (TypeUtils.java:284)
    at org.hibernate.jpamodelgen.util.TypeUtils.determineAccessTypeForHierarchy (TypeUtils.java:251)
    at org.hibernate.jpamodelgen.annotation.AnnotationMetaEntity.init (AnnotationMetaEntity.java:169)
    at org.hibernate.jpamodelgen.annotation.AnnotationMetaEntity.<init> (AnnotationMetaEntity.java:75)
    at org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor.handleRootElementAnnotationMirrors (JPAMetaModelEntityProcessor.java:243)
    at org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor.process (JPAMetaModelEntityProcessor.java:131)
    at com.sun.tools.javac.processing.JavacProcessingEnvironment.callProcessor (JavacProcessingEnvironment.java:980)
```

It doesn't say which entity causes the issues but I'm suspecting this one:

```
@Entity
@Inheritance(strategy = InheritanceType.SINGLE_TABLE)
public abstract class UserLike<T extends DomainObject & Owned> {
	public abstract EntityReference<T> getObject();
}

@Entity
public class PictureLike extends UserLike<Picture> {
	@Override
	public EntityReference<ProfilePicture> getObject() {
		return new EntityReference<>(Picture.class, getLikedId());
	}
}
```

I can try to provide a failing test.

**Comment by beikov** [comment]
Could you try again? This should be fixed now.

**Comment by theigl** [comment]
@beikov: My project still fails to compile. I pushed a test-case demonstrating the issue.

**Comment by beikov** [comment]
Ok, but now it should work :) @theigl

**Comment by theigl** [comment]
My project compile now. Thanks @beikov!

**Comment by beikov** [comment]
Awesome, thanks for confirming!

**Comment by johnou** [comment]
@beikov will https://github.com/hibernate/hibernate-orm/pull/3254 be eligible for backport to 5.4.x?

**Comment by Sanne** [comment]
This was already included in 5.4

**Comment by johnou** [comment]
@Sanne from what I can see the original fix was reverted https://github.com/hibernate/hibernate-orm/commit/df6d44f646d05f0fa3460887d0d05e9717031209 in 5.4 and the fix in main has not been backported https://github.com/hibernate/hibernate-orm/commit/17c5fab50e9a1c90a96a01498b8c95b1646194cc

**Pull request merged**
