### PR TITLE
HHH-2897 Adding support for use of sequence objects in DB2 V8 OS390

### PR DESCRIPTION
**Pull request by Lemongrass3110**
Added a new Dialect for DB2 390 version 8 and newer

Fixes HHH-2897

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the Pull Request. Did you sign the [CLA](https://cla.jboss.org/)?

**Comment by vladmihalcea** [comment]
@sebersole This commit looks fine according to [IBM docs](http://www.ibm.com/developerworks/data/library/techarticle/0302fielding/0302fielding.html). Is there any reason why I should not integrate it?

**Comment by Lemongrass3110** [comment]
Sorry I seem to have missed your comment back in April.
I believe I have taken the code from the original issue https://hibernate.atlassian.net/browse/HHH-2897 and adjusted the code to extend the original hibernate DB2 dialect.
Additionally I submitted this as a pull request to make it easier for you to merge it and close this issue.
I have not signed any CLA yet, but if it is a requirement and you think that I could do that based on my explanation above I can sign it if you need it.

**Comment by vladmihalcea** [comment]
You still need to sign the CLA, otherwise I can't integrate your changes.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks

**Pull request closed without merging**
