### PR TITLE
HHH-0372 OffsetDateTime value changes after fetching the row from the database

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-10372

I have found no other way than changing the OffsetDateTimeType from TimestampType to VarcharType. 

The problem is the lost of the ZoneOffset info during the 
```java
Timestamp ts = Timestamp.from( offsetDateTime.toInstant() );

OffsetDateTime offsetDateTimeAfterConversion = OffsetDateTime.ofInstant( ts.toInstant(), ZoneId.systemDefault() );
```
conversion

### CODE REVIEW

**Comment by dreab8** [comment]
refused

**Comment by davecramer** [comment]
As this is 4 yeas old I guess it's a bit late to comment but I just happen to be looking at how hibernate handles timezone in postgres. This test does not use a timestamp with a timezone so I'm baffled as to what it is testing ? Can someone please elaborate ?

**Comment by dreab8** [comment]
Hi @davecramer ,

not sure what baffled you , first the test verifies that when an Entity with a field of type `OffsetDateTime` is persisted and then retrieved the value of the filed is the same, second the PR was refused.

**Comment by davecramer** [comment]
While it may be persisted. In postgres it does not use a timestamp with a time zone so that is the baffling part ?

**Comment by dreab8** [comment]
what I do not understand is why you are baffled by a test that was written to show that hibernate had a problem persisting `OffsetDateTime` fields?

**Comment by davecramer** [comment]
I guess I would presume that an OffsetDateTime field would have to store the offset in the database. Is that not correct ?

**Comment by dreab8** [comment]
my point is that I do no understand why you are baffled by a test written because someone reported (see https://hibernate.atlassian.net/browse/HHH-10372) that hibernate had an issue with storing `OffsetDateTime`

**Comment by davecramer** [comment]
fair enough. Where can I find where and how hibernate is supposed to use timestamp with time zones?

**Pull request closed without merging**
