### PR TITLE
HHH-11764 - JTS geometry being bound to byte array instead of PGgeometry

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-11764

### CODE REVIEW

**Comment by maesenka** [comment]
HI Vlad, 

I'm going to review this in more detail, but I have some preliminary questions. 

1. Do you have any idea why the error "org.postgresql.util.PSQLException: ERROR: function st_buffer(bytea, integer) is not unique" occurs for the issue reporter? I have integration test cases that also run these functions, and I have never experienced this problem (see the integration test code).
2. Why did you put the fix in a a new dialect? 
3. Isn't this an issue for other functions? In other words, don't we need the cast to Geometry in all functions that take an argument? 
4. Would this fix also address the JDBCDSLOG issue?

**Comment by vladmihalcea** [comment]
Hi,

1) I think something might have changed in Postgres 9.5. Are you running an older version of Postgres on your tests?
2) The fix is not in a new Dialect. The `databases.gradle` is where we define the test environments for integration testing.
3) It could be, but for the moment, we don't have other tests failing to know which other methods we need to cast arguments as well.
4) I'm not sure what we can do about jdbcdslog since it's beyond our scope. It could be that the Postgres Driver has changed the way it passes through he Geometry object types.

**Comment by maesenka** [comment]
See my latest comment on https://hibernate.atlassian.net/browse/HHH-11764

If you don't mind, I would rather manually merge your changes. And work from there to find a more general solution.

**Comment by vladmihalcea** [comment]
Sure. You can close this PR and send a new one with a more generic fix. I'm glad you found a better way to address it.

**Comment by maesenka** [comment]
work integrated in a7fc440e4c533a32b956044c9c421727d70afa79

**Pull request closed without merging**
