### PR TITLE
treat integral types as equivalent for purposes of schema validation

### PR DESCRIPTION
**Pull request by gavinking**
... and update.

### CODE REVIEW

**Comment by gavinking** [comment]
@sebersole shall I merge it?

**Comment by beikov** [comment]
Why would we want this? If you have a model:

```
@Entity
public class MyEntity {
    Short value;
}
```

and change it to

```
@Entity
public class MyEntity {
    Integer value;
}
```

hbm2ddl would not report the change.

**Comment by gavinking** [comment]
See the discussion on Zulip. It's a stopgap measure to help with the fact that something changed in how we map enum types.

**Review by sebersole — COMMENTED** [review]
It looks fine as a stop-gap, as noted

**Pull request merged**
