### PR TITLE
HHH-12603 - Contributing using Eclipse Documentation out of Date

### PR DESCRIPTION
**Pull request by aepedraza**
This is a continuation of [this PR](https://github.com/hibernate/hibernate-orm/pull/2313) with clean commits and according to the contributing guidelines.

The changes presented firstly are the same as before closing the previous PR. Some changes based on the suggestions stated there will be uploaded ASAP.

### CODE REVIEW

**Comment by aepedraza** [comment]
@sebersole what do you think of this changes? (`f7c7b19` and `6a14235`) I left the `idea` plugin as it's not involved in this ticket.

**Comment by Sanne** [comment]
Thanks @aepedraza ! Could you remove the commits which are not related to the specifics of importing into Eclipse?

**Comment by aepedraza** [comment]
Hi @Sanne, right away I'll be on it. In fact, the last commits are mistakenly pushed into this branch. I should do it in another branch related to another ticket. I'm terribly sorry

**Comment by aepedraza** [comment]
Done! @Sanne. Now please check if my changes for this ticket are good enough. Thank you so much for warning me about my commits

**Comment by Sanne** [comment]
Thanks! I'll quickly check an import in both Idea and Eclipse then I'll merge it.

**Comment by Sanne** [comment]
merged

**Pull request closed without merging**
