### PR TITLE
HHH-8732 Upgraded Ehcache to 2.7.5

### PR DESCRIPTION
**Pull request by alexsnaps**
This not only addresses HHH-8732, but actually upgrades the ehcache dependency to a newer stable release, 2.7.4, which isn't compatible (compile & runtime) with older releases (new stats API & some config changes, as covered by HHH-8732)

### CODE REVIEW

**Comment by Akansha1988** [comment]
I still see ValueMode as an issue with Hibernate 5.2.FINAL and Terracotta 4.3 enterprise verison. Is the fix released for ORM 5X?

**Comment by alexsnaps** [comment]
@Akansha1988 Really hard to help here, you may want to drop a complete report to the ehcache users google group here : https://groups.google.com/forum/#!categories/ehcache-users/ehcache-hibernate

**Comment by alexsnaps** [comment]
@Akansha1988 Looks like you're right. Something is odd here. Am addressing this as part of HHH-10124

**Comment by alexsnaps** [comment]
Investigating this a little further, looks like the commit got "lost" on master around the 4.3.0.Final release (way back when). I _think_ at the time master was to be 5.0. Anyways, I guess all will make it in as part of 5.1

**Comment by Akansha1988** [comment]
Thanks Alex!

**Comment by sebersole** [comment]
@alexsnaps Is the commit you are talking about on the upstream hibernate-orm/metamodel branch?  That was master for a while, and the plan was for it to be 5.0, but developing the planned changes there took way too long so we decided to move the work on master off to that branch I mentioned; some of the work from that branch got moved to the new master to form what actually got released as 5.0.  Confusing I know...  sorry

**Comment by alexsnaps** [comment]
Ah! That may explain. I'll search as soon as I can. This PR is the
cherry-picked change from my initial branch. If it is on that branch would
it then better be merged back from there instead?

**Comment by sebersole** [comment]
Its up to you.  Not sure how likely it is to apply cleanly.

**Comment by alexsnaps** [comment]
It's on that branch. I don't think we can get this over in any sane way
though... or not that I know.
So this PR is probably best. Effectively the exact same thing... other than
this now having a newer version.
I guess, if the PR is fine, with you, it could be merged when you see fit.
Alex

**Comment by sebersole** [comment]
Ok.  I'll create a new Jira and link this PR to it and try to get it applied today.

**Comment by sebersole** [comment]
FWIW, GitHub at least seems to think this will not apply cleanly to master...

**Comment by alexsnaps** [comment]
Y, this one won't work, but #1142 should

**Comment by sebersole** [comment]
I guess I misunderstood when you commented "the PR" on *this* PR ;)

**Comment by Akansha1988** [comment]
@alexsnaps Hi Alex, just wanted to check if there is any update on the fix?

**Comment by alexsnaps** [comment]
@Akansha1988 it got merged in as #1142 that'll be in 5.1 only though iirc...

**Comment by Akansha1988** [comment]
@alexsnaps Could you please let me know when is 5.1 expected?

**Comment by alexsnaps** [comment]
Dunno, @sebersole ?

**Comment by sebersole** [comment]
Sometime after the holidays.  Not sure yet exactly.

**Pull request closed without merging**
