### PR TITLE
HHH-11386 Keep columns sequence align to sequence of entity fields fix

### PR DESCRIPTION
**Pull request by galovics**
One test introduced to verify that the fix works properly. 

Also I did some cleanup in the PropertyContainer class as one of the fields was passed as an argument to private methods which in this case was totally unnecessary.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
This cannot be migrated in 5.x because it will break all the existing auto-generated database schemas. The only way to include it is if we provide a configuration:

    hibernate.mapping.entity.attribute.sorting

which can take two values: 

`true`:: this is the current default, and we need it for backward compatibility
`false`:: this is the new option which must be enabled explicitly, and then we can switch to using the order in which entity attributes are declared

**Comment by Naros** [comment]
I struggle with the relevance of this change.

I can understand from a new schema generation perspective how this allows a developer to have a nice alignment of field order in the entity class with the table column positions.

As changes are made to the entity class and new fields are added, the schema generation process always appends those to the end of the existing table schema.  So unless you intend to mandate your developers never add a field in between existing fields and they're always added to the end of your class, this alignment concept makes no sense.

I also believe there are developers like myself when adding a field that might have some relevance to an existing field in an entity, that those related fields be grouped together in the entity class from a code readability and maintenance perspective rather than completely separated to maintain some java-class field / schema column alignment, but that's merely my opinion and ymmv.

Other than having some clear way to influence `@EmbeddedId` / `@IdClass` / multi `@Id`column order for optimal PK index generation, I really have a hard time seeing why this even needs changing.

**Comment by sebersole** [comment]
Personally I agree with @Naros here

**Comment by vladmihalcea** [comment]
@galovics Please see the comments above and let me know if there was any particular reason or use case that justified this issue. Otherwise, we can close it.

**Comment by galovics** [comment]
@vladmihalcea I just randomly picked it up. I'd say lets close it.

**Comment by Naros** [comment]
As I mentioned to @vladmihalcea on HipChat, I do think there is _merit_ for addressing something wrt `@EmbeddedId` / `@IdClass` / multi- `@Id` composite keys here.  

Take the following example:
<pre>
@Embeddable
public class ItemId implements Serializable {
  private Long customerId;
  private Long plantId;
  private Long itemId;
  // getter/setters
}
</pre>

This would generate the following composite key (if memory serves me well):
<pre>
customerId, itemId, plantId
</pre>

The problem I faced with this is that the PK was not optimized based on broadest to least broadest column order, therefore creating very wonky b-tree primary key indexes.  The optimal key we wanted/needed was:
<pre>
customerId, plantId, itemId
</pre>

So being able to have a better way to influence this rather than relying on the notion of _make sure to name your composite key fields alphabetically in their desired column order_ would **be** useful in some form and preferably adopted into JPA imo.

**Comment by Naros** [comment]
So I would advocate a solution at least for composite-ids here, as that makes logical sense.  

Its something that we generally configure on table initial creation and is something that we usually _manually_ change if we must since many tools don't cope with this scenario.

So perhaps a PR that addresses specifically that case would be something we could morph this JIRA to address and use a configuration option as @vladmihalcea suggests for backward compatibility?

**Pull request closed without merging**
