### PR TITLE
HHH-17776 - Add test and fix

### PR DESCRIPTION
**Pull request by jrenaat**
https://hibernate.atlassian.net/browse/HHH-17776

### CODE REVIEW

**Review by beikov — CHANGES_REQUESTED** [review]
I was hoping that you would fix the call sites that use the `SqmFromClause` and expect it to be non-null even though it might be nullable or ensure that the `SqmQuerySpec#fromClause` is always non-null, but setting the `fromClause` within the various select operations is not what I had in mind.
Personally, I prefer the latter i.e. ensuring the field is never `null`.

**Comment by jrenaat** [comment]
> I was hoping that you would fix the call sites that use the `SqmFromClause` and expect it to be non-null even though it might be nullable

Assuming that you mean putting not-null-checks around the call sites of `fromClause`, that's what it started out doing, but then I noticed that in some places `setFromClause(new SqmFromClause()) is done, and thought it was better to ensure that `fromClause` is never null

> or ensure that the `SqmQuerySpec#fromClause` is always non-null, but setting the `fromClause` within the various select operations is not what I had in mind. Personally, I prefer the latter i.e. ensuring the field is never `null`.

Do you mean that setting `new SqmFromClause()`should happen in `SqmQuerySpec`instead of in the selects?

**Comment by beikov** [comment]
>Do you mean that setting new SqmFromClause()should happen in SqmQuerySpecinstead of in the selects?

Yes, for example.

**Comment by jrenaat** [comment]
I had to add trim() on the main query multiselect to get it to work for hsqldb and derby; both were adding traling spaces in a rather absurd and somewhat unpredictable way to one of the result values (which varied when changing the literal values for name and surname).
I could only find one issue in stackoverflow that mentioned something similar, but no explanation nor solution.
Not sure if perhaps it would even be better to just exclude this test for hsqldb and derby?

**Comment by beikov** [comment]
It seems HSQLDB and Derby choose a fixed size character type for literals rather than a varchar type for the column subquery result, which leads to a whitespace padding. You could fix that by explicitly casting the literal to varchar, though I don't know how that works since we usually omit casts that lead to the "same" SQL type.

You could do the following in `DerbySqlAstTranslator` and `HSQLSqlAstTranslator` to make this work:

```java
	@Override
	protected void renderSelectExpression(Expression expression) {
		if ( isInSubquery() && expression instanceof Literal ) {
			renderCasted( expression );
		}
		else {
			renderSelectExpressionWithCastedOrInlinedPlainParameters( expression );
		}
	}
```

**Comment by jrenaat** [comment]
> You could do the following in `DerbySqlAstTranslator` and `HSQLSqlAstTranslator` to make this work:
> 
> ```java
> 	@Override
> 	protected void renderSelectExpression(Expression expression) {
> 		if ( isInSubquery() && expression instanceof Literal ) {
> 			renderCasted( expression );
> 		}
> 		else {
> 			renderSelectExpressionWithCastedOrInlinedPlainParameters( expression );
> 		}
> 	}
> ```
That seems indeed to do the trick, thanks.

**Pull request merged**
