### PR TITLE
HHH-17463 UnsupportedOperationException when using JAKARTA_JDBC_URL

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-17463

### CODE REVIEW

**Review by beikov — COMMENTED** [review]
Maybe I'm missing something, but shouldn't the JAKARTA_JDBC_URL etc. be normalized like the other properties in `org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl#normalizeDataAccess`? I feel like this approach is tackling the problem from the wrong angle.

**Comment by dreab8** [comment]
In this case  `SessionFactoryBuilderImpl` is used  and not `EntityManagerFactoryBuilderImpl`.

**Comment by beikov** [comment]
IMO `SessionFactoryBuilderImpl` should normalize the settings similar to how `EntityManagerFactoryBuilderImpl` does it, so that the connection provider implementation don't have to take care of that.

**Comment by dreab8** [comment]
Unfortunately  it's too late, the `DriverManagerConnectionProviderImpl` builds the `ConnectionCreator` passing the configurations  values before the construction of the `SessionFactory`

**Comment by beikov** [comment]
IMO the `org.hibernate.cfg.Configuration#buildSessionFactory()` should do all of this config property merging into the `standardServiceRegistryBuilder#getSettings()` before the `ServiceRegistry` is built.

**Comment by beikov** [comment]
Note that https://discourse.hibernate.org/t/deprecated-settings-necessary-for-bootstrapping/8678 runs into that exact issue.

**Comment by beikov** [comment]
Superseded by https://github.com/hibernate/hibernate-orm/pull/7613

**Pull request closed without merging**
