### PR TITLE
HHH-10130

### PR DESCRIPTION
**Pull request by carstenartur**
Testcase to show performance of bulk insert

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Thanks for the PR. Did you sign the [CLA](https://cla.jboss.org/index.seam)?

**Comment by carstenartur** [comment]
Hi,
At least i thought i have..
Did i miss to sign it?







Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Vlad Mihalcea <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [hibernate/hibernate-orm] HHH-10130 (#1088)
Datum: 12.04.2016, 14:33 Uhr
An: hibernate/hibernate-orm <hibernate-orm@noreply.github.com
<mailto:hibernate-orm@noreply.github.com> >
CC: Carsten Hammer <carsten.hammer@t-online.de
<mailto:carsten.hammer@t-online.de> >

Thanks for the PR. Did you sign the CLA <https://cla.jboss.org/index.seam> 
?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/hibernate/hibernate-orm/pull/1088#issuecomment-208881343>

**Comment by carstenartur** [comment]
Hi Vlad,
Just checked again the cla page of Jboss. Could be i did not sign it 
because there is no Button visible to do it..







Gesendet mit der Telekom Mail App
<http://www.t-online.de/service/redir/emailmobilapp_ios_smartphone_footerlink.htm>

-----Original-Nachricht-----
Von: Vlad Mihalcea <notifications@github.com
<mailto:notifications@github.com> >
Betreff: Re: [hibernate/hibernate-orm] HHH-10130 (#1088)
Datum: 12.04.2016, 14:33 Uhr
An: hibernate/hibernate-orm <hibernate-orm@noreply.github.com
<mailto:hibernate-orm@noreply.github.com> >
CC: Carsten Hammer <carsten.hammer@t-online.de
<mailto:carsten.hammer@t-online.de> >

Thanks for the PR. Did you sign the CLA <https://cla.jboss.org/index.seam> 
?

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/hibernate/hibernate-orm/pull/1088#issuecomment-208881343>

**Comment by vladmihalcea** [comment]
@sebersole, Can you validate if @carstenartur has signed the CLA?

**Comment by carstenartur** [comment]
Suddenly the cla page changed appearance and I could confirm it. Hope that is enough..

**Comment by vladmihalcea** [comment]
I checked out your PR, verified the changes, and I realized that you were making some wrong assumptions about how HQL bulk insert should be working. Check the [JIRA issue](https://hibernate.atlassian.net/browse/HHH-10130) for more details about why I closed this PR and the issue altogether.

**Pull request closed without merging**
