### PR TITLE
Issue with unidirectional one-to-many association with a join column that references a column that is not the primary key

### PR DESCRIPTION
**Pull request by marcellor**
A one-to-many association is causing Hibernate to 
throw 
`INFO: HHH000327: Error performing load command : org.hibernate.property.access.spi.PropertyAccessException: 
`
when loading an entity via Session.get(domainClass, identifier), under the following conditions:
1. the association collection is annotated with @Fetch(FetchMode.JOIN)
2. the association's join column is referencing a non-primary key of the owning entity
3. the association's join column value is referencing a non-existing record of the associated table (the "many" side).

```
package org.hibernate.bugs;

import java.io.Serializable;
import java.util.List;

import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToMany;

import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;
import org.hibernate.boot.Metadata;
import org.hibernate.boot.MetadataSources;
import org.hibernate.boot.registry.StandardServiceRegistryBuilder;
import org.junit.Before;
import org.junit.Test;

/**
 * Issue with unidirectional one-to-many association with a join column that
 * references a column that is not the primary key.
 */
public class ORMStandaloneTestCase {

  private SessionFactory sf;


  @Before
  public void setup() {
    StandardServiceRegistryBuilder srb = new StandardServiceRegistryBuilder().applySetting("hibernate.show_sql", "true")
        .applySetting("hibernate.format_sql", "true").applySetting("hibernate.hbm2ddl.auto", "update");

    Metadata metadata = new MetadataSources(srb.build()).addAnnotatedClass(Customer.class).addAnnotatedClass(Order.class)
        .buildMetadata();

    sf = metadata.buildSessionFactory();
  }


  @Test
  public void unidirectionalOneToManyAssociationTest() throws Exception {
    Session session = sf.openSession();
    Transaction tx = session.beginTransaction();

    try {
      // Save the entity on the One side
      Customer customer = new Customer();
      customer.idCode = "ABC";
      customer.translationId = 1L;

      session.persist(customer);
    } finally {
      tx.commit();
      session.close();
    }

    try {
      session = sf.openSession();
      tx = session.beginTransaction();

      // Attempt to load the entity saved in the previous session
      session.get(Customer.class, "ABC");

    } finally {
      tx.commit();
      session.close();
    }
  }

  @Entity
  public static class Customer implements Serializable {

    @Id
    @Basic
    public String      idCode;

    @Basic
    @Column(precision = 15, scale = 0)
    public Long        translationId;

    @Fetch(FetchMode.JOIN)
    @OneToMany(fetch = FetchType.LAZY, orphanRemoval = true)
    @JoinColumn(name = "translationId", referencedColumnName = "translationId")
    public List<Order> translations;
  }

  @Entity
  public static class Order implements Serializable {

    @Id
    @Basic
    @Column(precision = 15, scale = 0)
    public long id;

    @Basic
    @Column(precision = 15, scale = 0)
    public long translationId;
  }
}
```

### CODE REVIEW

**Comment by vladmihalcea** [comment]
I think it's better to base this PR on top of master instead of 5.0. Could you send a new PR for the master branch? Thanks.

**Comment by Sanne** [comment]
P.S. like @vladmihalcea we'd love a patch which applies directly on the latest version of master, _but_ if you're not familiar with git and/or github we can help of course! Let us know if you need some guidance, or if you prefer someone from the team could try extracting your patch.

Alternatively you can also attach a traditional patch file to a JIRA ticket.

Your test is very welcome, thanks again.

**Comment by marcellor** [comment]
Hi,

I have the changes ready to commit to the PR.
How can I change the base this PR on top of master instead of 5.0? Should I
close it and open a new one? Can you please help?

Thanks,
Marcello

**Comment by vladmihalcea** [comment]
You can create a new branch from master, then `git cherry pick commit-hash` where commit-hash is the hash of your commit.

**Comment by marcellor** [comment]
Hi,

I am not very familiar with git. I have created a local branch and I am
trying to push it to remote, but I get permission denied. Do I need to
generate SSH keys?

Thanks,
Marcello

**Comment by Naros** [comment]
@marcellor It would probably help if you read https://github.com/hibernate/hibernate-orm/blob/master/CONTRIBUTING.md.  This describes the procedure for creating a fork of the repo to your github account, cloning, creating a feature branch, etc.

**Comment by marcellor** [comment]
Thanks,

I have created the following PR with test case and code commits:
https://github.com/hibernate/hibernate-orm/pull/1789

**Pull request closed without merging**
