### PR TITLE
HHH-17005 - Replace monitor with a Java lock to avoid pinning 

### PR DESCRIPTION
**Pull request by cescoffier**
When using virtual threads, holding a monitor lock when performing an I/O _pins_ the carrier thread. 
To work around this behavior, this PR replaces the monitor lock with a ReentrantLock, supported by the virtual threads (no pinning).

I've successfully tested the change in a Quarkus application (by cherry-picking the change in the 6.2 branch). The pinning disappeared. It allows having a simple (but complete) CRUD application using Hibernate from virtual threads without having any issues.

https://hibernate.atlassian.net/browse/HHH-17005

### CODE REVIEW

**Comment by marko-bekhta** [comment]
Hey @cescoffier maybe it's worth updating other optimizers in the same manner? Or maybe at least the `PooledOptimizer`  since in Quarkus there's a config property to pick between `pooled-lo, pooled, none`...

**Comment by cescoffier** [comment]
Hello @marko-bekhta !

Definitely! Sorry, still discovering the code base. I will have a look at the other optimizers.

**Comment by cescoffier** [comment]
@marko-bekhta I updated the other implementations that were using a synchronized method.

**Review by beikov — APPROVED** [review]

**Review by Sanne — CHANGES_REQUESTED** [review]
Many thanks @cescoffier !

Unfortunately this is also introducing a suble change in safety, as there are other `synchronized` methods which used to share the same lock on "this".
The other methods were not blocking so technically would be OK from a Loom perspective, but now they're allowed to race with the `generate` method since they are using a different monitor.

I can take it further if you like, it's very helpful to have this starting point as I didn't know exactly which methods were affected. Unless you want to finish it? Let us know.

**Comment by cescoffier** [comment]
@Sanne Do you mean that there are other classes using something like `synchronized(optimizer)` (with optimizer being the instance where I removed the synchronized and used a lock)? Do you have a location in the code where this is used?

If this is the case, to keep the semantics, we could introduce a `getLock` method in the AbstractOptimizer class and use that lock instead of the `synchronized(optimizer)`. But before going there, I would like to see where it's used (to have an idea of the radius).

**Comment by cescoffier** [comment]
@Sanne Oh yes! Definitely an overlooked. Thanks for catching it. I will fix my PR. 
I was a bit afraid of the pattern I described in my last comment, as it could have leaked everywhere.

**Comment by cescoffier** [comment]
@Sanne Fixed (hopefully)

**Comment by cescoffier** [comment]
Should I be concerned by the jenkins mailext failure?

**Comment by beikov** [comment]
>Should I be concerned by the jenkins mailext failure?

Don't worry about this. It's just a wrong reporting on GH. The failure is actually when running on s390x. Some tests @Sanne recently added are failing on that architecture for some reason.

**Review by Sanne — APPROVED** [review]
Great, thanks! I'm itching now to actually improve the algorithm, but priorities... this will do for now.

FWIW Hibernate Reactive uses a better pattern already, as we had already hit a problem here of not being able to rely on the locks.

**Pull request merged**
