### PR TITLE
Move to jboss-transaction api

### PR DESCRIPTION
**Pull request by ctomc**
https://issues.jboss.org/browse/JBEE-160 was fixed some time ago.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
I ran all tests using the JBoss JTA lib, and we get this failure:

```
org.hibernate.osgi.test.OsgiIntegrationTest > classMethod FAILED
    java.lang.RuntimeException
        Caused by: org.osgi.framework.BundleException
            Caused by: java.lang.NoClassDefFoundError
                Caused by: java.lang.ClassNotFoundException
```

The geronimo JTA lib works just fine.

**Comment by ctomc** [comment]
What class was not found? Change to the osgi descriptors ware verified by @brmeyer just for use case of hibernate, so I am puzzled why this happens.

**Comment by vladmihalcea** [comment]
It complains that it cannot find `org.hibernate.integrator.spi.Integrator`

```
Caused by: java.lang.ClassNotFoundException: org.hibernate.integrator.spi.Integrator not found by PAXEXAM-PROBE-56d23239-fe53-4417-a5a0-b9f676de504f [102]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

Caused by: java.lang.ClassNotFoundException: org.hibernate.integrator.spi.Integrator not found by PAXEXAM-PROBE-56d23239-fe53-4417-a5a0-b9f676de504f [102]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1532)
	at org.apache.felix.framework.BundleWiringImpl.access$400(BundleWiringImpl.java:75)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1955)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

Maybe @brmeyer can take a look on it since I'm not very versed in OSGI.

**Comment by Sanne** [comment]
I noticed the module definition was not updated, so in hope that would be enough to fix the test I gave it a shot.

It wasn't enough.

Yet, to share the little improvement I'll close this PR and hopefully @brmeyer will be able to have a look at #1648 .

**Pull request closed without merging**
