### PR TITLE
HHH-10416 Drop superfluous immutable-entity cache configuration.

### PR DESCRIPTION
**Pull request by pferraro**
Default to entity cache configuration if undefined.

https://hibernate.atlassian.net/browse/HHH-10416

### CODE REVIEW

**Comment by scottmarlow** [comment]
I'm thinking that we should keep the DEF_IMMUTABLE_ENTITY_RESOURCE but set it to "entity" instead, so that any code that references that constant, won't break.

**Comment by scottmarlow** [comment]
@pferraro @sebersole what do you guys think?  We probably could do the same for the pr#1208 change as well (for 5.0).  If @sebersole approves, I'll handle the change.

**Comment by scottmarlow** [comment]
@rvansa feedback from you, is welcome also.  If we don't apply this change, we should add immutable-entities to the WF clustering configuration.

**Comment by pferraro** [comment]
@scottmarlow I've restored this constant for the 5.0 branch and marked as @Deprecated.  That should allow us to remove it for master.

**Comment by sebersole** [comment]
Applied upstream.

**Pull request closed without merging**
