### PR TITLE
HHH-16097 Move all tests from documentation into hibernate-core

### PR DESCRIPTION
**Pull request by dreab8**
https://hibernate.atlassian.net/browse/HHH-16097
WIP

### CODE REVIEW

**Review by beikov — APPROVED** [review]

**Comment by sebersole** [comment]
Sweet!

**Comment by sebersole** [comment]
Do you think this is ready to go @mbladel ?   The sooner we integrate it, the less babysitting you have to do to keep it synced

**Comment by mbladel** [comment]
> Do you think this is ready to go @mbladel ? The sooner we integrate it, the less babysitting you have to do to keep it synced

@sebersole after the push I did today think it's ready, I was just waiting for https://github.com/hibernate/hibernate-orm/pull/6229 to solve the last few test failures when adding the Jackson XML dependency. LMK if you want me to squash to a single commit before merging it.

**Comment by sebersole** [comment]
Pulled this locally to rebase and resolve conflicts.  I'll integrate upstream after.

**Comment by sebersole** [comment]
Integrated upstream.  Pushed to main already; running tests locally on 6.2 from cherry-pick

**Pull request closed without merging**
