### PR TITLE
HHH-13151 fetch on treated entity

### PR DESCRIPTION
**Pull request by Vineg**
https://hibernate.atlassian.net/browse/HHH-13151

### CODE REVIEW

**Comment by Vineg** [comment]
@beikov I run ./gradlew :hibernate-core:checkstyleTest --stacktrace and it crashes on file I'm not even changed.

```
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Exception was thrown while processing D:\git\hibernate-orm\hibernate-core\src\test\java\org\hibernate\internal\util\ReflectHelperTest.java
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:281)
        at com.puppycrawl.tools.checkstyle.Checker.process(Checker.java:196)
        at com.puppycrawl.tools.checkstyle.ant.CheckstyleAntTask.processFiles(CheckstyleAntTask.java:371)
        ... 65 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: TokenStreamRecognitionException occurred during the analysis of file D:\git\hibernate-orm\hibernate-core\src\test\java\org\hibernate\internal\util\ReflectHelperTest.java.
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:188)
        at com.puppycrawl.tools.checkstyle.api.AbstractFileSetCheck.process(AbstractFileSetCheck.java:78)
        at com.puppycrawl.tools.checkstyle.Checker.processFile(Checker.java:301)
        at com.puppycrawl.tools.checkstyle.Checker.processFiles(Checker.java:271)
        ... 67 more
Caused by: D:\git\hibernate-orm\hibernate-core\src\test\java\org\hibernate\internal\util\ReflectHelperTest.java:16:57: Unexpected character 0xa9 in identifier
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaLexer.nextToken(GeneratedJavaLexer.java:405)
        at antlr.TokenStreamHiddenTokenFilter.consume(TokenStreamHiddenTokenFilter.java:38)
        at antlr.TokenStreamHiddenTokenFilter.nextToken(TokenStreamHiddenTokenFilter.java:134)
        at antlr.TokenBuffer.fill(TokenBuffer.java:69)
        at antlr.TokenBuffer.LA(TokenBuffer.java:80)
        at antlr.LLkParser.LA(LLkParser.java:52)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.identifierStar(GeneratedJavaRecognizer.java:466)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.importDefinition(GeneratedJavaRecognizer.java:326)
        at com.puppycrawl.tools.checkstyle.grammars.GeneratedJavaRecognizer.compilationUnit(GeneratedJavaRecognizer.java:189)
        at com.puppycrawl.tools.checkstyle.TreeWalker.parse(TreeWalker.java:440)
        at com.puppycrawl.tools.checkstyle.TreeWalker.processFiltered(TreeWalker.java:175)
        ... 70 more
```

Does it works for you?

**Comment by beikov** [comment]
Interesting, the Travis build doesn't report problems.
The problem you are facing is most probably due to you having a non-US locale which causes files to be generated that contain localized comments which don't seem to be properly parseable.
@gsmet do you have anything to add here? If you don't, I'd go ahead and merge this.

**Comment by Vineg** [comment]
I don't see checkstyleTest in Travis build

**Comment by gsmet** [comment]
Travis is running a full `check` which executes the Checkstyle check.

I'll rerun one on my laptop just to be sure and merge.

**Comment by gsmet** [comment]
Merged, thanks!

**Pull request closed without merging**
