### PR TITLE
HHH-14922 - Inconsistent precedence of orm.xml implicit catalog/schema over "default_catalog"/"default_schema"

### PR DESCRIPTION
**Pull request by sebersole**
HHH-14922 - Inconsistent precedence of orm.xml implicit catalog/schema over "default_catalog"/"default_schema"

### CODE REVIEW

**Comment by sebersole** [comment]
The failure here is related to hibernate-core-jakarta.  No idea why the test only fails for Oracle and only in the -jakarta form

**Review by beikov — APPROVED** [review]
Looks good to me

**Review by yrodiere — CHANGES_REQUESTED** [review]
As explained on https://github.com/hibernate/hibernate-orm/pull/4351, if we address HHH-14921, we'll need a completely different solution for HHH-14922, unfortunately.

Let's discuss this on Zulip before merging anything? Please?

**Comment by yrodiere** [comment]
Since we merged #4371, I don't think this patch is necessary anymore, so I'm going to close this PR.

Some of the improvements are probably still useful, but that'll need some work, so I'll let Steve get back to it when there's no longer higher priority stuff to be done (that should take a while...).

**Pull request closed without merging**
