### PR TITLE
HHH-9582: MavenEnhancePlugin "Unable to enhance persistent attribute".

### PR DESCRIPTION
**Pull request by johnny-mac**
Create a loadingClassLoader (used to search for classes referenced from
the processed classes) that includes the path to the classes to enhance,
and not only the plugin's class path.

### CODE REVIEW

**Comment by barreiro** [comment]
I'm going to have close this PR because the maven plugin code has since diverged. 

Anyway, I fixed the the issue based on the reproducer you provided. @johnny-mac thanks a lot for that, it was really helpful.

**Comment by joelicious** [comment]
Is the fix for this issue available in the 4.x baseline or only 5 CR2?

(Can we use the 5 CR2 plugin for the 4.x baseline?)

**Comment by barreiro** [comment]
@joelicious, these are two very different questions. To answer the former, no, the fixes on the plugins are only on 5 and not back-ported to 4.x. As for using the enhanced entities on 4.x, I can't remember of any SPI change, so in theory it could work (tbh, I haven't tried it). On a more practical side, most features are only implemented on 5 and this is where you'll see most benefit, so I would strongly recommend upgrading. Also, there is little to no interest in fixing bugs on 4.x given the reasons above, while for 5 I always try to fix them as soon as possible.

**Comment by sebersole** [comment]
4.x will not even recognize the enhancements from the 5.0 Enhancer.  So to
take advantage of these changes you'd have to use 5.0 for runtime as well.

**Comment by joelicious** [comment]
Thank you for your response.  If Hibernate 4.x is a must in the environment I am in, what would you recommend?  If I use the ant task - is this issue present there too?

**Comment by sebersole** [comment]
The 4.0 and 5.0 enhancement are completely different things; the 5.0
enhancement was completely re-written from scratch.  So just because a bug
or fix is needed for the 5.0 one, does not mean the same bug/fix is needed
for 4.0.  TIAS.

**Pull request closed without merging**
