### PR TITLE
Fixed HHH-10517

### PR DESCRIPTION
**Pull request by bdragan**
Fixed HHH-10517: ClassCastException using Restrictions.in with child classes in Criteria based on parent class.

### CODE REVIEW

**Comment by vladmihalcea** [comment]
Looks good, Bogdan. Have you signed the [CLA](https://cla.jboss.org/) so I can integrate it?

**Comment by bdragan** [comment]
Thanks. Yes, I signed it.

**Comment by vladmihalcea** [comment]
I checked the JIRA issue and I can't integrate this change because the old Criteria query is [no longer maintained](https://hibernate.atlassian.net/browse/HHH-10517).

**Comment by vladmihalcea** [comment]
Thanks for the PR. I applied it upstream. It will be available on both 5.1 and 5.0.

**Comment by bdragan** [comment]
Great, thanks Vlad!

**Pull request closed without merging**
