### PR TITLE
HHH-11076: Remember enabled filters when allowLoadOutsideTransaction is true

### PR DESCRIPTION
**Pull request by heruan**

### CODE REVIEW

**Comment by dreab8** [comment]
Hi @heruan ,

thanks for the PR, can you please add to it a test?.

And if you haven't already done can you sign the [CLA](https://cla.jboss.org/) .

Thanks a lot

**Comment by gbadner** [comment]
@dreab8, when a test is available, I'd like to review for backporting to 5.1.

**Comment by vladmihalcea** [comment]
I'm going to add a test case and integrate it.

**Comment by vladmihalcea** [comment]
Applied upstream, thanks.

**Comment by heruan** [comment]
I've added some commits, since this was closed and applied externally instead of merged but then it was rolled back, I think it could be safely reopened to discuss improvements; otherwise I can pull a new one. What do you think?

**Comment by sebersole** [comment]
As I mentioned on the Jira, I personally agree with Gail (IIUC) and think this should be rolled back.

**Comment by sebersole** [comment]
@heruan The concern here is performance.  You are adding a Map (of the enabled filters) to each and every PersistentCollection that gets instantiated just in case we want to initialize it later outside of the Session.  That's a big concern

**Comment by heruan** [comment]
Thank you @sebersole for your feedback, I understand the performance concern but I think that if an entity is loaded enabling some filters on its collections, one would expect to see the filters applied when those collections are loaded regardless of being outside the transaction (risks of inconsistency are already accepted enabling the setting).

If there are no filters enabled, the map would be empty (or never instantiated at all, if we check the presence of filters first) but if there are filters enabled, these are retained and respected. I'm realizing right now there could be filters not related with that specific attribute, but we can tell that from the metadata.

I'll issue an uptaded PR to discuss these details and find an optimal solution, since in my opinion HHH-11076 still holds as a bug.

**Comment by sebersole** [comment]
@heruan I understand your point of view.  

However, regardless of your stance on the "correctness" of allowing initialization outside Session, my concern is that you are threatening to hurt the performance of apps not using that feature.  This comes in 2 forms:

1.  First, simply having the Map field declared on the Class as instance state increases its memory footprint.  How bad that effect is depends on a few things.  
2. Then, yes as you point out, null versus an actual Map instantiation would affect the memory footprint even more.

So at the bare minimum I think this should be changed to not copy the filters if this "initialize outside of Session" setting is disabled.

I wonder if we can actually isolate this "initialize outside of Session" code even more though.  Something like an interface that controls the initialization outside of the originating Session.  That would isolate 3 fields (`sessionFactoryUuid`, `allowLoadOutsideTransaction`, plus this filter map) encapsulating them in an implementation of that interface specifically for when that setting is enabled.

**Comment by sebersole** [comment]
Since this PR is closed, maybe we should continue this discussion on the Jira...

**Pull request closed without merging**
