### PR TITLE
Upgrade build scan plugin to 1.3

### PR DESCRIPTION
**Pull request by rhart**
Add build scan recipe for git commit metadata

### CODE REVIEW

**Comment by rhart** [comment]
I assumed you don't require a jira issue for changes like this.  Happy to create one if needs be.

**Comment by sebersole** [comment]
What exactly does this scan recipe do?  Have an example somewhere?

**Comment by rhart** [comment]
This particular recipe will add a `Sources` link in the summary to the commit that triggered the build scan https://scans.gradle.com/s/3r2nficswe7qu#summary. Although the link doesn't work in my example because the base url is wrong.

It also adds the commit id as meta data https://scans.gradle.com/s/3r2nficswe7qu#custom-values

There are some other recipes detailed on the plugin's github page https://github.com/melix/gradle-buildscan-recipes.

**Comment by dreab8** [comment]
Thanks @rhart 
rebased and applied upstream

**Pull request closed without merging**
