### PR TITLE
HHH-11288: get artifacts from project, not executionProject

### PR DESCRIPTION
**Pull request by candrews**
https://hibernate.atlassian.net/browse/HHH-11288

### CODE REVIEW

**Comment by vladmihalcea** [comment]
I tried this change proposal and it was not working in my case. [Check out the comment](https://hibernate.atlassian.net/browse/HHH-11288?focusedCommentId=86616&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-86616) that I wrote on the Jira issue. There's also a new proposal there to accomodate both ways of getting the artefacts.

**Comment by candrews** [comment]
@vladmihalcea I suspect you need to test using 5.2.6-SNAPSHOT (currently master) because you need to have the fix for https://hibernate.atlassian.net/browse/HHH-11287 as well. That should remove the need to check executionProject making the change in this PR work correctly for you.

**Comment by vladmihalcea** [comment]
You're right. After using the previous fix, it works now.

**Comment by vladmihalcea** [comment]
Applied upstream. Thanks.

**Pull request closed without merging**
