### PR TITLE
prevent InsertOrderingWithJoinedTableMultiLevelInheritance from freezing

### PR DESCRIPTION
**Pull request by jmartisk**
this is for EAP 7.1 https://issues.jboss.org/browse/JBEAP-10045

### CODE REVIEW

**Comment by Naros** [comment]
@jmartisk This targets 5.1.  I would think this type of fix would be useful for master too, right?

**Comment by jmartisk** [comment]
@Naros on master this test uses the doInHibernate block so I think master is not affected. Also HHH-11262 is fixed on master (which is the root cause why the test throws an exception in the first place) - this is just a workaround, the test will still fail (at least it does with Sybase 15.7), but will not freeze.

**Comment by jmartisk** [comment]
@gbadner  please review :)

**Comment by Naros** [comment]
@jmartisk Awesome, I didn't check master specifically, so that's good to know.  Carry on :).

**Comment by gbadner** [comment]
I created HHH-11611, amended the commit to refer to HHH-11611, and pushed to 5.1.

**Pull request closed without merging**
