### PR TITLE
HHH-16840 Allow serialization of ScanResultImpl

### PR DESCRIPTION
**Pull request by boutss**
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16840

### CODE REVIEW

**Comment by sebersole** [comment]
Please create a Jira discussing why you think this is a worthwhile feature and amend the commit message to include that Jira key.

**Comment by boutss** [comment]
I had already created it as expected, is that what it's about?
I will complete it.
https://hibernate.atlassian.net/jira/software/c/projects/HHH/issues/HHH-16840

**Comment by sebersole** [comment]
I'm inclined to reject this.  These are all internal contracts.  Making them `Serializable` for user use is kind of the antithesis of that

**Comment by boutss** [comment]
Yes, I completely understand about inner classes. I had the same thought.

Sounds perfect to me, the idea of the snapshot API. I was actually thinking about how I could go about extracting the information and serializing it into another concept.

For the implementation of this, I'll let you propose something, or would you like me to take a look myself?

**Comment by boutss** [comment]
Alright, I will propose something.
Of course, testing is important.
Perhaps I will use Zulip to discuss it further, so as not to clutter this discussion.

Thank you for taking the time in any case.

**Comment by sebersole** [comment]
Actually, I changed my mind on this.  Given that `File` and `URL` (and `byte[]` ofc) are actually `Serializable`, there is no need for custom Serialization hooks for the `InputStreamAccess`.

For testing though, the test should ensure the `ScanResult` can be serialized as well as deserialized and that the deserialized form is correct.  Take a look at `org.hibernate.orm.test.bootstrap.scanning.ScannerTest`.  (1) These test should be added to that class.  (2) Look at how it leverages `org.hibernate.orm.test.bootstrap.scanning.PackagingTestCase` to build actual archives to scan rather than building "fake" descriptors and archives.

**Comment by boutss** [comment]
Sorry for the delay.
Thank you for your help with the design!
I'm not sure if the test is enough for you or if we need to go further with validation.

**Comment by boutss** [comment]
@sebersole Okay with you?
Just to let you know, I'll be present for 15 days, then on leave for 15 days ^^

**Comment by boutss** [comment]
I have completed the changes. Are you in agreement to integrate them?

**Comment by boutss** [comment]
Strange, i have a :
java.lang.OutOfMemoryError: Java heap space

I rebase branch

**Pull request merged**
