### PR TITLE
HHH-13504 : Upgrade ByteBuddy to 1.9.11

### PR DESCRIPTION
**Pull request by gbadner**
https://hibernate.atlassian.net/browse/HHH-13504

### CODE REVIEW

**Comment by gbadner** [comment]
@Sanne, this upgrade is necessary to fix jdk13 issues. The upgrade for 5.3 needs to wait until 5.3.12. Can this be upgraded in 5.4.4?

**Comment by Sanne** [comment]
hi @gbadner , sure this can be updated in 5.4. I also see no problems in backporting (assuming all tests pass as I couldn't test it myself)

**Comment by Sanne** [comment]
merged

**Comment by Sanne** [comment]
@gbadner you need this backported?  As I wasn't sure I didn't push it to 5.3, but enaled the "consider for backporting " flag.

**Pull request merged**
