### PR TITLE
Metamodel: Changed to keep generated classes in Context

### PR DESCRIPTION
**Pull request by Janario**
Issue HHH-9892

### CODE REVIEW

**Comment by sebersole** [comment]
Janario, I thought we had a CLA for you but I cannot find it.  I cannot accept this PR with a signed CLA.  Can you sign one?

https://cla.jboss.org/

Thanks.

I'll be cutting 5.0.0.CR2 tomorrow (Tuesday July 6th).  If you can get this done today, I will get this fix in to that release.

**Comment by Janario** [comment]
@sebersole Thanks.
I signed it right now

It is in status "Awaiting approval by project lead"

**Comment by sebersole** [comment]
Yep, I just approved it.  I will apply this now

**Comment by sebersole** [comment]
Applied to master for 5.0.0.CR2.  Thanks!

**Comment by Janario** [comment]
Thanks :)

**Pull request closed without merging**
