### PR TITLE
HHH-2187 - Throw QueryException rather than IllegalArgumentException when query parsing fails.

### PR DESCRIPTION
**Pull request by Naros**
https://hibernate.atlassian.net/browse/HHH-2187

### CODE REVIEW

**Comment by beikov** [comment]
Not sure this is the right thing to do. JPA demands an `IllegalArgumentException`. Also see http://docs.oracle.com/javaee/6/api/javax/persistence/EntityManager.html#createQuery(java.lang.String)

**Comment by dreab8** [comment]
@beikov @Naros  AbstractSharedSessionContract#createquery() catches the exception and uses ExceptionConverterImpl to convert it into an IllegalArgumentException 
So  also with @Naros changes both 
Session#createQuery("bogus") and EntityManager#createQuery("bogus") are going to throw an IllegalArgumentException

**Comment by Naros** [comment]
@dreab8 Is correct.  

If the environment is bootstrapped as a JPA environment, then users will receive the expected JPA exception, `IllegalArgumentException`; however when bootstrapped in non-JPA, then users would get the expected `QueryException` rather than `IllegalArgumentException`.

So the fix is to address the native bootstrapping scenario while JPA remains as-is and unaffected.

**Comment by dreab8** [comment]
@Naros but I think it does not solve the issue related with Session#createQuery(), it still throws an IllegalArgumentException

**Comment by Naros** [comment]
@dreab8 OK, I'll take a look, thanks.

**Comment by Naros** [comment]
@dreab8, looking at existing tests it seems we decided to stick to the notion that `#createQuery()` would still throw an `IllegalArgumentException` however we would use the `#getCause()` method on that exception to get the _real underlying cause_ .

So in this type of situation, users should be able to do this now:
<pre>
catch ( IllegalArgumentException e ) {
  if ( QueryException.class.isInstance( e.getCause() ) ) {
    // handle problem
  }
}
</pre>

Previously, there was no root-cause.

**Comment by dreab8** [comment]
@Naros you are right

**Pull request closed without merging**
