### PR TITLE
HHH-10384 Fix thread safety issues in thread local optimiser

### PR DESCRIPTION
**Pull request by stuartwdouglas**
The current implementation is not thread safe for multi tenant situations, and assigns the same object to the thread local, which results in a racy assignment.

I have changed this to be based on my original working implementation.

### CODE REVIEW

**Comment by sebersole** [comment]
Hey Stuart, can you go ahead and start using the Hibernate code styles when contributing?  Thanks.  I am applying this one upstream and will fix the code styles as I have done with your other PRs; but would save some time to not have to do that each time.  Thanks!

**Comment by scottmarlow** [comment]
https://github.com/scottmarlow/hibernate-orm/tree/fix-optimiser has a few more changes to consider.

**Comment by scottmarlow** [comment]
I think the change to stop using the shared noTenantState is important

**Comment by sebersole** [comment]
Ok, I'll rollback my local work until these details get worked out between y'all.  Any input you need from me?

**Comment by stuartwdouglas** [comment]
Closing, I think Scotts patch looks ok

**Pull request closed without merging**
