### PR TITLE
HHH-14707 Upgrade to Byte Buddy 1.11.8

### PR DESCRIPTION
**Pull request by yrodiere**
https://hibernate.atlassian.net/browse/HHH-14707

Build against JDK18: https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-yoann-jdk18/1/

### CODE REVIEW

**Comment by Sanne** [comment]
It seems the JDK11 tests failed:

```

org.hibernate.orm.integrationtest.java.module.test.JavaModulePathIT > integrator FAILED
    java.lang.NoClassDefFoundError at JavaModulePathIT.java:58
        Caused by: java.lang.ClassNotFoundException at JavaModulePathIT.java:58

org.hibernate.orm.integrationtest.java.module.test.JavaModulePathIT > core FAILED
    java.lang.NoClassDefFoundError at JavaModulePathIT.java:34

```

**Comment by yrodiere** [comment]
The failure is really strange, I don't understand what is going on... It's definitely related to the bytebuddy upgrade, though.

To be fair, we're relying on an outdated method to test Java modules. I will have a look at what Steve mentioned [on Zulip](https://hibernate.zulipchat.com/#narrow/stream/132094-hibernate-orm-dev/topic/hibernate-integrationtest-java-modules); maybe it will fix the failures?

**Comment by yrodiere** [comment]
It looks like a problem in Byte-Buddy's `module-info` definition. I opened https://github.com/raphw/byte-buddy/pull/1079.

For future reference, the exact stack trace was this:

```
java.lang.NoClassDefFoundError: net/bytebuddy/utility/dispatcher/JavaDispatcher
	at net.bytebuddy/net.bytebuddy.description.type.TypeDescription$ForLoadedType.<clinit>(TypeDescription.java:8378)
	at net.bytebuddy/net.bytebuddy.description.type.TypeDescription.<clinit>(TypeDescription.java:65)
	at net.bytebuddy/net.bytebuddy.matcher.ElementMatchers.isFinalizer(ElementMatchers.java:1626)
	at net.bytebuddy/net.bytebuddy.matcher.ElementMatchers.isDefaultFinalizer(ElementMatchers.java:1616)
	at net.bytebuddy/net.bytebuddy.ByteBuddy.<init>(ByteBuddy.java:207)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.bytecode.internal.bytebuddy.ByteBuddyState.<init>(ByteBuddyState.java:79)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:67)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.bytecode.internal.bytebuddy.BytecodeProviderImpl.<init>(BytecodeProviderImpl.java:58)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.cfg.Environment.buildBytecodeProvider(Environment.java:345)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.cfg.Environment.buildBytecodeProvider(Environment.java:337)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.cfg.Environment.<clinit>(Environment.java:230)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$MergedSettings.<init>(EntityManagerFactoryBuilderImpl.java:1514)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$MergedSettings.<init>(EntityManagerFactoryBuilderImpl.java:1504)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.mergeSettings(EntityManagerFactoryBuilderImpl.java:496)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:229)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:187)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.boot.spi.Bootstrap.getEntityManagerFactoryBuilder(Bootstrap.java:75)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilder(HibernatePersistenceProvider.java:171)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:119)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.HibernatePersistenceProvider.getEntityManagerFactoryBuilderOrNull(HibernatePersistenceProvider.java:61)
	at org.hibernate.orm.core@5.5.4-SNAPSHOT/org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:50)
	at java.persistence@2.2/javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:79)
	at java.persistence@2.2/javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:54)
	at org.hibernate.orm.integrationtest.java.module.test/org.hibernate.orm.integrationtest.java.module.test.service.AuthorService.createSessionFactory(AuthorService.java:28)
	at org.hibernate.orm.integrationtest.java.module.test/org.hibernate.orm.integrationtest.java.module.test.service.AuthorService.<init>(AuthorService.java:24)
	at org.hibernate.orm.integrationtest.java.module.test/org.hibernate.orm.integrationtest.java.module.test.JavaModulePathIT.integrator(JavaModulePathIT.java:58)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at junit@4.13.2/org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at junit@4.13.2/org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at junit@4.13.2/org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at junit@4.13.2/org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at junit@4.13.2/org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at junit@4.13.2/org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at junit@4.13.2/org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at junit@4.13.2/org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at junit@4.13.2/org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at junit@4.13.2/org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at junit@4.13.2/org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at junit@4.13.2/org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at junit@4.13.2/org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at junit@4.13.2/org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at junit@4.13.2/org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at junit@4.13.2/org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:110)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:38)
	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:62)
	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:51)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:94)
	at com.sun.proxy.$Proxy2.processTestClass(Unknown Source)
	at org.gradle.api.internal.tasks.testing.worker.TestWorker.processTestClass(TestWorker.java:119)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.ClassNotFoundException: net.bytebuddy.utility.dispatcher.JavaDispatcher
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:581)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 76 more
```

**Comment by yrodiere** [comment]
@raphw fixed the Java module problems in Byte Buddy 1.11.8 (see [here](https://github.com/raphw/byte-buddy/pull/1079#issuecomment-880982494), and running the ORM tests locally, they seem to pass now. Let's see what CI has to say about it.

**Comment by yrodiere** [comment]
New build against JDK18: https://ci.hibernate.org/view/Personal%20jobs/job/hibernate-orm-personal-yoann-jdk18/2/

**Pull request merged**
