### PR TITLE
HHH-12128 - If there are two getters (get and is) in an entity, Hibernate will not bootstrap

### PR DESCRIPTION
**Pull request by vladmihalcea**
https://hibernate.atlassian.net/browse/HHH-12128

### CODE REVIEW

**Comment by vladmihalcea** [comment]
@sebersole @Naros @dreab8 Can you review this PR and let me know if we can integrate it. Thanks.

**Comment by vladmihalcea** [comment]
I discovered that this might be a duplicate of [HHH-12096](https://hibernate.atlassian.net/browse/HHH-12096) which is fixed in 5.2. I wonder if we should close this issue, and simply decide whether to backport HHH-12096.

**Comment by mkurz** [comment]
@vladmihalcea 
> I discovered that this might be a duplicate of HHH-12096 which is fixed in 5.2.

This is not true. `HHH-12096` wasn't backported to the 5.2 branch. Can you do this?

**Comment by vladmihalcea** [comment]
@mkurz 5.3 will become the next release, so backporting will be done by @gbadner based on her considerations.

**Comment by gbadner** [comment]
@vladmihalcea, I'm confused about the status. Is this issue a duplicate of HHH-12096 (fixed in master)? If so, you don't need my permission to backport this issue to 5.2 branch. If that is the case, shouldn't this PR be closed?

**Comment by vladmihalcea** [comment]
@gbadner It is indeed a duplicate. I marked the Jira issue as such and will close this PR too.

Nevertheless, I could backport [HHH-12096](https://hibernate.atlassian.net/browse/HHH-12096) to 5.2 as well. When I wrote that comment, I didn't know we could backport to previous branches until we release the Final non-Beta version of the current branch.

**Comment by mkurz** [comment]
Yes, please backport HHH-12096. Thank you!

**Comment by vladmihalcea** [comment]
It's backported to 5.2.13 now.

**Pull request closed without merging**
